var h;h||=typeof Module != 'undefined' ? Module : {};var ba=document.getElementById("status"),ca=document.getElementById("progress"),da=document.getElementById("spinner"),ea=document.getElementById("canvas"),fa=document.getElementById("canvasContainer"),ha=document.getElementById("logToggle"),ia=document.getElementById("logToggleContainer"),ja=document.getElementById("logContainer"),ka=document.getElementById("output"),la=ba.innerText;ha.checked=!1;
window.toggleLog=function(){ja.hidden=!ha.checked;ka.scrollTop=ka.scrollHeight};var ma=ea.getContext("webgl2",{alpha:!1,antialias:!1,depth:!1,powerPreference:"high-performance",premultipliedAlpha:!0,preserveDrawingBuffer:!1,stencil:!1});if(!ma)throw"Could not create a WebGL 2 context";ma.getSupportedExtensions().forEach(function(a){ma.getExtension(a)});ea.addEventListener("webglcontextlost",function(a){alert("WebGL context lost. You will need to reload the page.");a.preventDefault()},!1);
ka.value="";
h={preRun:[function(){na.TAISEI_NOASYNC="1";na.TAISEI_NOUNLOAD="1";na.TAISEI_PREFER_SDL_VIDEODRIVERS="emscripten";na.TAISEI_RENDERER="gles30";k("/persistent");oa(n,"/persistent")}],postRun:[],onFirstFrame:function(){fa.hidden=!1;ia.style.display="inline-block";h.setStatus("",!0)},print:function(a){1<arguments.length&&(a=Array.prototype.slice.call(arguments).join(" "));console.log(a);ka.value+=a+"\n";ka.scrollTop=ka.scrollHeight},printErr:function(a){1<arguments.length&&(a=Array.prototype.slice.call(arguments).join(" "));console.error(a)},
canvas:ea,preinitializedWebGLContext:ma,setStatus:function(a,b){var c=h.setStatus;if(a||b)if(c.Ri||(c.Ri={time:Date.now(),text:""}),a!==c.Ri.text){b=a.match(/([^(]+)\((\d+(\.\d+)?)\/(\d+)\)/);var d=Date.now();b&&30>d-c.Ri.time||(c.Ri.time=d,c.Ri.text=a,b?(a=b[1],ca.value=100*parseInt(b[2]),ca.max=100*parseInt(b[4]),ca.hidden=!1,da.hidden=!ea.hidden):(ca.value=null,ca.max=null,ca.hidden=!0,a||(da.hidden=!0)),ba.innerText=a.replace(/^Downloading(?: data)?\.\.\./,la).replace("...","\u2026"),console.log("[STATUS] "+
ba.innerText))}},totalDependencies:0,monitorRunDependencies:function(a){h.totalDependencies=Math.max(h.totalDependencies,a);h.setStatus(a?"Preparing\u2026 ("+(h.totalDependencies-a)+"/"+h.totalDependencies+")":"All downloads complete.")}};window.onerror=function(a){h.setStatus("Error: "+a)};function qa(a,b){sa(a,function(c){h.ccall("vfs_sync_callback",null,["boolean","string","number"],[a,c,b],{async:!0})})}
(function(){function a(){var b=h.SDL2;"undefined"!==typeof b&&("suspended"==b.hi.state&&b.hi.resume(),"running"==b.hi.state&&(ea.removeEventListener("click",a),document.removeEventListener("keydown",a)))}ea.addEventListener("click",a);document.addEventListener("keydown",a)})();"undefined"===typeof dynCall&&(dynCall=window.dynCall=h.dynCall=function(a,b,c){return ta.get(b).apply(this,c)});var ua=Object.assign({},h),va=[],wa="./this.program",ya="",za;
"undefined"!=typeof document&&document.currentScript&&(ya=document.currentScript.src);ya=ya.startsWith("blob:")?"":ya.substr(0,ya.replace(/[?#].*/,"").lastIndexOf("/")+1);za=a=>fetch(a,{credentials:"same-origin"}).then(b=>b.ok?b.arrayBuffer():Promise.reject(Error(b.status+" : "+b.url)));var Aa=h.print||console.log.bind(console),Ba=h.printErr||console.error.bind(console);Object.assign(h,ua);ua=null;h.arguments&&(va=h.arguments);h.thisProgram&&(wa=h.thisProgram);
var Ca=h.wasmBinary,Da,Ea=!1,Fa,r,v,Ga,Ha,Ia,Ja,w,y,z;function Ka(){var a=Da.buffer;h.HEAP_DATA_VIEW=z=new DataView(a);h.HEAP8=r=new Int8Array(a);h.HEAP16=Ga=new Int16Array(a);h.HEAPU8=v=new Uint8Array(a);h.HEAPU16=Ha=new Uint16Array(a);h.HEAP32=Ia=new Int32Array(a);h.HEAPU32=Ja=new Uint32Array(a);h.HEAPF32=w=new Float32Array(a);h.HEAPF64=new Float64Array(a);h.HEAP64=y=new BigInt64Array(a);h.HEAPU64=new BigUint64Array(a)}var La=[],Ma=[],Na=[],Oa=[];
function Pa(){var a=h.preRun.shift();La.unshift(a)}var Qa=0,Ra=null,Sa=null;function Ta(){Qa++;h.monitorRunDependencies?.(Qa)}function Ua(){Qa--;h.monitorRunDependencies?.(Qa);if(0==Qa&&(null!==Ra&&(clearInterval(Ra),Ra=null),Sa)){var a=Sa;Sa=null;a()}}function Va(a){h.onAbort?.(a);a="Aborted("+a+")";Ba(a);Ea=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Wa=a=>a.startsWith("data:application/octet-stream;base64,"),Xa;
function Ya(a){if(a==Xa&&Ca)return new Uint8Array(Ca);throw"both async and sync fetching of the wasm failed";}function Za(a){return Ca?Promise.resolve().then(()=>Ya(a)):za(a).then(b=>new Uint8Array(b),()=>Ya(a))}function $a(a,b,c){return Za(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{Ba(`failed to asynchronously prepare wasm: ${d}`);Va(d)})}
function ab(a,b){var c=Xa;Ca||"function"!=typeof WebAssembly.instantiateStreaming||Wa(c)||"function"!=typeof fetch?$a(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){Ba(`wasm streaming compile failed: ${e}`);Ba("falling back to ArrayBuffer instantiation");return $a(c,a,b)}))}
var db={1136800:(a,b)=>{qa(a,b)},1136820:(a,b)=>{alert((a?A(v,a):"")+"\n\n"+(b?A(v,b):""))},1136877:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1137024:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1137258:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.hi||("undefined"!==typeof AudioContext?b.hi=new AudioContext:
"undefined"!==typeof webkitAudioContext&&(b.hi=new webkitAudioContext),b.hi&&bb(b.hi));return void 0===b.hi?-1:0},1137751:()=>h.SDL2.hi.sampleRate,1137819:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.Xi&&(clearTimeout(g.capture.Xi),g.capture.Xi=void 0);g.capture.ij=g.hi.createMediaStreamSource(l);g.capture.ni=g.hi.createScriptProcessor(b,a,1);g.capture.ni.onaudioprocess=function(m){void 0!==g&&void 0!==g.capture&&(m.outputBuffer.getChannelData(0).fill(0),g.capture.qj=m.inputBuffer,dynCall("vi",
c,[d]))};g.capture.ij.connect(g.capture.ni);g.capture.ni.connect(g.hi.destination);g.capture.stream=l}var g=h.SDL2;g.capture.oj=g.hi.createBuffer(a,b,g.hi.sampleRate);g.capture.oj.getChannelData(0).fill(0);g.capture.Xi=setTimeout(function(){g.capture.qj=g.capture.oj;dynCall("vi",c,[d])},b/g.hi.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},1139471:(a,b,c,d)=>{var e=h.SDL2;e.audio.ni=e.hi.createScriptProcessor(b,0,a);e.audio.ni.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Nj=f.outputBuffer,dynCall("vi",c,[d]))};e.audio.ni.connect(e.hi.destination)},1139881:(a,b)=>{for(var c=h.SDL2,d=c.capture.qj.numberOfChannels,e=0;e<d;++e){var f=c.capture.qj.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)cb(a+4*g,f[g]);else for(g=0;g<b;++g)cb(a+4*(g*d+e),f[g])}},1140486:(a,b)=>{for(var c=h.SDL2,d=c.audio.Nj.numberOfChannels,e=0;e<d;++e){var f=c.audio.Nj.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=z.getFloat32(4*(a+(g*d+e<<2)>>2),!0)}},1140966:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Xi&&clearTimeout(b.capture.Xi);if(void 0!==b.capture.stream){a=
b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.ni&&(b.capture.ni.onaudioprocess=function(){},b.capture.ni.disconnect(),b.capture.ni=void 0);void 0!==b.capture.ij&&(b.capture.ij.disconnect(),b.capture.ij=void 0);void 0!==b.capture.oj&&(b.capture.oj=void 0);b.capture=void 0}else void 0!=b.audio.ni&&(b.audio.ni.disconnect(),b.audio.ni=void 0),b.audio=void 0;void 0!==b.hi&&void 0===b.audio&&void 0===b.capture&&
(b.hi.close(),b.hi=void 0)},1142138:()=>window.innerWidth,1142168:()=>window.innerHeight,1142199:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.fk!==h.canvas&&(d.ui=h.createContext(h.canvas,!1,!0),d.fk=h.canvas);if(d.w!==a||d.h!==b||d.yk!==d.ui)d.image=d.ui.createImageData(a,b),d.w=a,d.h=b,d.yk=d.ui;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=z.getInt32(4*b,!0);a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;
b++;e+=4}else if(d.jk!==a&&(d.ik=new Int32Array(a.buffer),d.kk=new Uint8Array(a.buffer),d.jk=a),a=d.ik,c=a.length,a.set(Ia.subarray(b,b+c)),a=d.kk,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.ui.putImageData(d.image,0,0)},1143668:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,
b);b=a.data;e>>=2;var l=0,m;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(m=b.length;l<m;){var p=z.getInt32(4*e,!0);b[l]=p&255;b[l+1]=p>>8&255;b[l+2]=p>>16&255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),m=b.length,b.set(Ia.subarray(e,e+m));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=B(c.length+1);C(c,v,d,c.length+1);return d},1144657:a=>{h.canvas&&(h.canvas.style.cursor=a?A(v,a):"")},
1144740:()=>{h.canvas&&(h.canvas.style.cursor="none")},1144809:()=>{h.onFirstFrame()}};function eb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var fb=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},bb=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&fb(d,c,()=>{"suspended"===a.state&&a.resume()})})})},gb=a=>{for(;0<a.length;)a.shift()(h)},hb=h.noExitRuntime||!0;
function cb(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":r[a]=b;break;case "i8":r[a]=b;break;case "i16":z.setInt16(2*(a>>1),b,!0);break;case "i32":z.setInt32(4*(a>>2),b,!0);break;case "i64":y[a>>3]=BigInt(b);break;case "float":z.setFloat32(4*(a>>2),b,!0);break;case "double":z.setFloat64(8*(a>>3),b,!0);break;case "*":z.setUint32(4*(a>>2),b,!0);break;default:Va(`invalid type for setValue: ${c}`)}}function ib(){var a=z.getInt32(4*(+jb>>2),!0);jb+=4;return a}
var lb=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},mb=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=lb(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ob=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},pb=a=>{if("/"===
a)return"/";a=mb(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},qb=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);Va("initRandomDevice")},rb=a=>(rb=qb())(a),sb=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=lb(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},tb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,A=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&tb)return tb.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
ub=[],vb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},C=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&
63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},wb=[];function xb(a,b){wb[a]={input:[],li:[],yi:b};yb(a,zb)}
var zb={open(a){var b=wb[a.node.Vi];if(!b)throw new D(43);a.fi=b;a.seekable=!1},close(a){a.fi.yi.dj(a.fi)},dj(a){a.fi.yi.dj(a.fi)},read(a,b,c,d){if(!a.fi||!a.fi.yi.Qj)throw new D(60);for(var e=0,f=0;f<d;f++){try{var g=a.fi.yi.Qj(a.fi)}catch(l){throw new D(29);}if(void 0===g&&0===e)throw new D(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.fi||!a.fi.yi.Aj)throw new D(60);try{for(var e=0;e<d;e++)a.fi.yi.Aj(a.fi,b[c+e])}catch(f){throw new D(29);
}d&&(a.node.timestamp=Date.now());return e}},Ab={Qj(){a:{if(!ub.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(vb(a)+1);a=C(a,b,0,b.length);b.length=a;ub=b}b=ub.shift()}return b},Aj(a,b){null===b||10===b?(Aa(A(a.li,0)),a.li=[]):0!=b&&a.li.push(b)},dj(a){a.li&&0<a.li.length&&(Aa(A(a.li,0)),a.li=[])},Bk(){return{Zk:25856,al:5,Yk:191,$k:35387,Xk:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,
22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ck(){return 0},Dk(){return[24,80]}},Bb={Aj(a,b){null===b||10===b?(Ba(A(a.li,0)),a.li=[]):0!=b&&a.li.push(b)},dj(a){a.li&&0<a.li.length&&(Ba(A(a.li,0)),a.li=[])}},Db=a=>{a=65536*Math.ceil(a/65536);var b=Cb(65536,a);b?(v.fill(0,b,b+a),a=b):a=0;return a};function Eb(a,b){var c=a.ei?a.ei.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ei,a.ei=new Uint8Array(b),0<a.gi&&a.ei.set(c.subarray(0,a.gi),0))}
var E={xi:null,ji(){return E.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new D(63);E.xi||(E.xi={dir:{node:{wi:E.ci.wi,oi:E.ci.oi,Si:E.ci.Si,Ji:E.ci.Ji,nj:E.ci.nj,Pi:E.ci.Pi,Ni:E.ci.Ni,mj:E.ci.mj,Oi:E.ci.Oi},stream:{Hi:E.di.Hi}},file:{node:{wi:E.ci.wi,oi:E.ci.oi},stream:{Hi:E.di.Hi,read:E.di.read,write:E.di.write,$i:E.di.$i,Ti:E.di.Ti,kj:E.di.kj}},link:{node:{wi:E.ci.wi,oi:E.ci.oi,Wi:E.ci.Wi},stream:{}},Mj:{node:{wi:E.ci.wi,oi:E.ci.oi},stream:Fb}});
c=Gb(a,b,c,d);F(c.mode)?(c.ci=E.xi.dir.node,c.di=E.xi.dir.stream,c.ei={}):32768===(c.mode&61440)?(c.ci=E.xi.file.node,c.di=E.xi.file.stream,c.gi=0,c.ei=null):40960===(c.mode&61440)?(c.ci=E.xi.link.node,c.di=E.xi.link.stream):8192===(c.mode&61440)&&(c.ci=E.xi.Mj.node,c.di=E.xi.Mj.stream);c.timestamp=Date.now();a&&(a.ei[b]=c,a.timestamp=c.timestamp);return c},ci:{wi(a){var b={};b.mk=8192===(a.mode&61440)?a.id:1;b.zk=a.id;b.mode=a.mode;b.Ik=1;b.uid=0;b.vk=0;b.Vi=a.Vi;F(a.mode)?b.size=4096:32768===(a.mode&
61440)?b.size=a.gi:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.bk=new Date(a.timestamp);b.lj=new Date(a.timestamp);b.ek=new Date(a.timestamp);b.ck=4096;b.dk=Math.ceil(b.size/b.ck);return b},oi(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.gi!=b))if(0==b)a.ei=null,a.gi=0;else{var c=a.ei;a.ei=new Uint8Array(b);c&&a.ei.set(c.subarray(0,Math.min(b,a.gi)));a.gi=b}},Si(){throw Hb[44];},Ji(a,b,c,d){return E.createNode(a,b,
c,d)},nj(a,b,c){if(F(a.mode)){try{var d=Ib(b,c)}catch(f){}if(d)for(var e in d.ei)throw new D(55);}delete a.parent.ei[a.name];a.parent.timestamp=Date.now();a.name=c;b.ei[c]=a;b.timestamp=a.parent.timestamp},Pi(a,b){delete a.ei[b];a.timestamp=Date.now()},Ni(a,b){var c=Ib(a,b),d;for(d in c.ei)throw new D(55);delete a.ei[b];a.timestamp=Date.now()},mj(a){var b=[".",".."],c;for(c of Object.keys(a.ei))b.push(c);return b},Oi(a,b,c){a=E.createNode(a,b,41471,0);a.link=c;return a},Wi(a){if(40960!==(a.mode&61440))throw new D(28);
return a.link}},di:{read(a,b,c,d,e){var f=a.node.ei;if(e>=a.node.gi)return 0;a=Math.min(a.node.gi-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){b.buffer===r.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ei||a.ei.subarray)){if(f)return a.ei=b.subarray(c,c+d),a.gi=d;if(0===a.gi&&0===e)return a.ei=b.slice(c,c+d),a.gi=d;if(e+d<=a.gi)return a.ei.set(b.subarray(c,c+d),e),d}Eb(a,e+d);if(a.ei.subarray&&
b.subarray)a.ei.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ei[e+f]=b[c+f];a.gi=Math.max(a.gi,e+d);return d},Hi(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.gi);if(0>b)throw new D(28);return b},$i(a,b,c){Eb(a.node,b+c);a.node.gi=Math.max(a.node.gi,b+c)},Ti(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new D(43);a=a.node.ei;if(e&2||!a||a.buffer!==r.buffer){d=!0;e=Db(b);if(!e)throw new D(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,
c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{Yj:e,zi:d}},kj(a,b,c,d){E.di.write(a,b,0,d,c,!1);return 0}}},Jb=(a,b,c)=>{var d=`al ${a}`;za(a).then(e=>{b(new Uint8Array(e));d&&Ua(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&Ta(d)},Kb=h.preloadPlugins||[],Nb=(a,b,c,d)=>{"undefined"!=typeof Lb&&Mb();var e=!1;Kb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},Pb=(a,b,c,d,e,f,g,l,m,p)=>{function q(H){function Z(pa){p?.();l||Ob(a,b,pa,d,e,m);f?.();Ua(u)}
Nb(H,t,Z,()=>{g?.();Ua(u)})||Z(H)}var t=b?sb(mb(a+"/"+b)):a,u=`cp ${t}`;Ta(u);"string"==typeof c?Jb(c,q,g):q(c)},Qb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},n={cj:{},indexedDB:()=>{if("undefined"!=typeof indexedDB)return indexedDB;var a=null;"object"==typeof window&&(a=window.indexedDB||window.mozIndexedDB||window.webkitIndexedDB||window.msIndexedDB);return a},ak:21,Di:"FILE_DATA",Mi:a=>{function b(){"again"===a.Gi?c():a.Gi=0}function c(){a.Gi="idb";n.Yi(a,!1,b)}a.Gi?"idb"===a.Gi&&(a.Gi=
"again"):a.Gi=setTimeout(c,0)},ji:a=>{var b=E.ji(a);if(a?.Jk?.Vk){b.Gi=0;var c=b.ci;b.ci=Object.assign({},b.ci);b.ci.Ji=(d,e,f,g)=>{var l=c.Ji(d,e,f,g);l.ci=b.ci;l.xk=b.ji;l.yj=l.di;l.di=Object.assign({},l.di);l.di.write=(m,p,q,t,u,H)=>{m.node.Tj=!0;return l.yj.write(m,p,q,t,u,H)};l.di.close=m=>{var p=m.node;p.Tj&&(n.Mi(p.xk),p.Tj=!1);if(p.yj.close)return p.yj.close(m)};return l};b.ci.Hk=(...d)=>(n.Mi(b.ji),c.Hk(...d));b.ci.Ni=(...d)=>(n.Mi(b.ji),c.Ni(...d));b.ci.Oi=(...d)=>(n.Mi(b.ji),c.Oi(...d));
b.ci.Pi=(...d)=>(n.Mi(b.ji),c.Pi(...d));b.ci.nj=(...d)=>(n.Mi(b.ji),c.nj(...d))}return b},Yi:(a,b,c)=>{n.tk(a,(d,e)=>{if(d)return c(d);n.uk(a,(f,g)=>{if(f)return c(f);n.Lk(b?g:e,b?e:g,c)})})},nl:()=>{Object.values(n.cj).forEach(a=>a.close());n.cj={}},sk:(a,b)=>{var c=n.cj[a];if(c)return b(null,c);try{var d=n.indexedDB().open(a,n.ak)}catch(e){return b(e)}if(!d)return b("Unable to connect to IndexedDB");d.onupgradeneeded=e=>{var f=e.target.result;e=e.target.transaction;var g;f.objectStoreNames.contains(n.Di)?
g=e.objectStore(n.Di):g=f.createObjectStore(n.Di);g.indexNames.contains("timestamp")||g.createIndex("timestamp","timestamp",{unique:!1})};d.onsuccess=()=>{c=d.result;n.cj[a]=c;b(null,c)};d.onerror=e=>{b(e.target.error);e.preventDefault()}},tk:(a,b)=>{function c(l){return"."!==l&&".."!==l}function d(l){return m=>mb(l+"/"+m)}var e={};for(a=Rb(a.Ui).filter(c).map(d(a.Ui));a.length;){var f=a.pop();try{var g=Sb(f)}catch(l){return b(l)}F(g.mode)&&a.push(...Rb(f).filter(c).map(d(f)));e[f]={timestamp:g.lj}}return b(null,
{type:"local",entries:e})},uk:(a,b)=>{var c={};n.sk(a.Ui,(d,e)=>{if(d)return b(d);try{var f=e.transaction([n.Di],"readonly");f.onerror=g=>{b(g.target.error);g.preventDefault()};f.objectStore(n.Di).index("timestamp").openKeyCursor().onsuccess=g=>{g=g.target.result;if(!g)return b(null,{type:"remote",db:e,entries:c});c[g.primaryKey]={timestamp:g.key};g.continue()}}catch(g){return b(g)}})},Fk:(a,b)=>{try{var c=G(a).node;var d=Sb(a)}catch(f){return b(f)}if(F(d.mode))return b(null,{timestamp:d.lj,mode:d.mode});
if(32768===(d.mode&61440)){a=c;var e=c.ei?c.ei.subarray?c.ei.subarray(0,c.gi):new Uint8Array(c.ei):new Uint8Array(0);a.ei=e;return b(null,{timestamp:d.lj,mode:d.mode,contents:c.ei})}return b(Error("node type not supported"))},Qk:(a,b,c)=>{try{if(F(b.mode))for(var d=b.mode,e=a.split("/"),f="",g=0;g<e.length;++g){if(e[g]){f+="/"+e[g];try{k(f,d)}catch(u){if(20!=u.ii)throw u;}}}else if(32768===(b.mode&61440)){f=b.contents;d={Kj:!0};d.flags=d.flags||577;g=Tb(a,d.flags,d.mode);if("string"==typeof f){var l=
new Uint8Array(vb(f)+1),m=C(f,l,0,l.length);Vb(g,l,0,m,void 0,d.Kj)}else if(ArrayBuffer.isView(f))Vb(g,f,0,f.byteLength,void 0,d.Kj);else throw Error("Unsupported data type");Wb(g)}else return c(Error("node type not supported"));Xb(a,b.mode);var p=b.timestamp,q=b.timestamp,t=G(a,{Ii:!0}).node;t.ci.oi(t,{timestamp:Math.max(p,q)})}catch(u){return c(u)}c(null)},Nk:(a,b)=>{try{var c=Sb(a);F(c.mode)?Yb(a):32768===(c.mode&61440)&&Zb(a)}catch(d){return b(d)}b(null)},Gk:(a,b,c)=>{a=a.get(b);a.onsuccess=d=>
c(null,d.target.result);a.onerror=d=>{c(d.target.error);d.preventDefault()}},Rk:(a,b,c,d)=>{try{var e=a.put(c,b)}catch(f){d(f);return}e.onsuccess=()=>d();e.onerror=f=>{d(f.target.error);f.preventDefault()}},Ok:(a,b,c)=>{a=a.delete(b);a.onsuccess=()=>c();a.onerror=d=>{c(d.target.error);d.preventDefault()}},Lk:(a,b,c)=>{function d(q){if(q&&!l)return l=!0,c(q)}var e=0,f=[];Object.keys(a.entries).forEach(q=>{var t=a.entries[q],u=b.entries[q];u&&t.timestamp.getTime()==u.timestamp.getTime()||(f.push(q),
e++)});var g=[];Object.keys(b.entries).forEach(q=>{a.entries[q]||(g.push(q),e++)});if(!e)return c(null);var l=!1,m=("remote"===a.type?a.db:b.db).transaction([n.Di],"readwrite"),p=m.objectStore(n.Di);m.onerror=m.onabort=q=>{d(q.target.error);q.preventDefault()};m.oncomplete=()=>{l||c(null)};f.sort().forEach(q=>{"local"===b.type?n.Gk(p,q,(t,u)=>{if(t)return d(t);n.Qk(q,u,d)}):n.Fk(q,(t,u)=>{if(t)return d(t);n.Rk(p,q,u,d)})});g.sort().reverse().forEach(q=>{"local"===b.type?n.Nk(q,d):n.Ok(p,q,d)})}},
$b=null,ac={},bc=[],cc=1,dc=null,ec=!1,fc=!0,D=class{constructor(a){this.name="ErrnoError";this.ii=a}},Hb={},gc=0,hc={},ic=class{constructor(){this.mi={};this.node=null}get flags(){return this.mi.flags}set flags(a){this.mi.flags=a}get position(){return this.mi.position}set position(a){this.mi.position=a}},jc=class{constructor(a,b,c,d){a||=this;this.parent=a;this.ji=a.ji;this.Ki=null;this.id=cc++;this.name=b;this.mode=c;this.ci={};this.di={};this.Vi=d}get read(){return 365===(this.mode&365)}set read(a){a?
this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Ek(){return F(this.mode)}get Sj(){return 8192===(this.mode&61440)}};
function G(a,b={}){a=sb(a);if(!a)return{path:"",node:null};b=Object.assign({Pj:!0,Bj:0},b);if(8<b.Bj)throw new D(32);a=a.split("/").filter(g=>!!g);for(var c=$b,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=Ib(c,a[e]);d=mb(d+"/"+a[e]);c.Ki&&(!f||f&&b.Pj)&&(c=c.Ki.root);if(!f||b.Ii)for(f=0;40960===(c.mode&61440);)if(c=kc(d),d=sb(ob(d),c),c=G(d,{Bj:b.Bj+1}).node,40<f++)throw new D(32);}return{path:d,node:c}}
function lc(a){for(var b;;){if(a===a.parent)return a=a.ji.Ui,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%dc.length}function nc(a){var b=mc(a.parent.id,a.name);if(dc[b]===a)dc[b]=a.Li;else for(b=dc[b];b;){if(b.Li===a){b.Li=a.Li;break}b=b.Li}}
function Ib(a,b){var c=F(a.mode)?(c=oc(a,"x"))?c:a.ci.Si?0:2:54;if(c)throw new D(c);for(c=dc[mc(a.id,b)];c;c=c.Li){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.ci.Si(a,b)}function Gb(a,b,c,d){a=new jc(a,b,c,d);b=mc(a.parent.id,a.name);a.Li=dc[b];return dc[b]=a}function F(a){return 16384===(a&61440)}function pc(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function oc(a,b){if(fc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function qc(a,b){try{return Ib(a,b),20}catch(c){}return oc(a,"wx")}function rc(a,b,c){try{var d=Ib(a,b)}catch(e){return e.ii}if(a=oc(a,"wx"))return a;if(c){if(!F(d.mode))return 54;if(d===d.parent||"/"===lc(d))return 10}else if(F(d.mode))return 31;return 0}function J(a){a=bc[a];if(!a)throw new D(8);return a}
function sc(a,b=-1){a=Object.assign(new ic,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!bc[b])break a;throw new D(33);}a.fd=b;return bc[b]=a}function tc(a,b=-1){a=sc(a,b);a.di?.fl?.(a);return a}var Fb={open(a){a.di=ac[a.node.Vi].di;a.di.open?.(a)},Hi(){throw new D(70);}};function yb(a,b){ac[a]={di:b}}function uc(){for(var a=[],b=[$b.ji];b.length;){var c=b.pop();a.push(c);b.push(...c.Vj)}return a}
function sa(a,b){function c(g){gc--;return b(g)}function d(g){if(g){if(!d.qk)return d.qk=!0,c(g)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);gc++;1<gc&&Ba(`warning: ${gc} FS.syncfs operations in flight at once, probably just doing extra work`);var e=uc(),f=0;e.forEach(g=>{if(!g.type.Yi)return d(null);g.type.Yi(g,a,d)})}
function oa(a,b){var c="/"===b;if(c&&$b)throw new D(10);if(!c&&b){var d=G(b,{Pj:!1});b=d.path;d=d.node;if(d.Ki)throw new D(10);if(!F(d.mode))throw new D(54);}b={type:a,Jk:{},Ui:b,Vj:[]};a=a.ji(b);a.ji=b;b.root=a;c?$b=a:d&&(d.Ki=b,d.ji&&d.ji.Vj.push(b))}function vc(a,b,c){var d=G(a,{parent:!0}).node;a=pb(a);if(!a||"."===a||".."===a)throw new D(28);var e=qc(d,a);if(e)throw new D(e);if(!d.ci.Ji)throw new D(63);return d.ci.Ji(d,a,b,c)}function k(a,b){return vc(a,(void 0!==b?b:511)&1023|16384,0)}
function wc(a,b,c){"undefined"==typeof c&&(c=b,b=438);return vc(a,b|8192,c)}function xc(a,b){if(!sb(a))throw new D(44);var c=G(b,{parent:!0}).node;if(!c)throw new D(44);b=pb(b);var d=qc(c,b);if(d)throw new D(d);if(!c.ci.Oi)throw new D(63);c.ci.Oi(c,b,a)}function Yb(a){var b=G(a,{parent:!0}).node;a=pb(a);var c=Ib(b,a),d=rc(b,a,!0);if(d)throw new D(d);if(!b.ci.Ni)throw new D(63);if(c.Ki)throw new D(10);b.ci.Ni(b,a);nc(c)}
function Rb(a){a=G(a,{Ii:!0}).node;if(!a.ci.mj)throw new D(54);return a.ci.mj(a)}function Zb(a){var b=G(a,{parent:!0}).node;if(!b)throw new D(44);a=pb(a);var c=Ib(b,a),d=rc(b,a,!1);if(d)throw new D(d);if(!b.ci.Pi)throw new D(63);if(c.Ki)throw new D(10);b.ci.Pi(b,a);nc(c)}function kc(a){a=G(a).node;if(!a)throw new D(44);if(!a.ci.Wi)throw new D(28);return sb(lc(a.parent),a.ci.Wi(a))}function Sb(a,b){a=G(a,{Ii:!b}).node;if(!a)throw new D(44);if(!a.ci.wi)throw new D(63);return a.ci.wi(a)}
function yc(a){return Sb(a,!0)}function Xb(a,b){a="string"==typeof a?G(a,{Ii:!0}).node:a;if(!a.ci.oi)throw new D(63);a.ci.oi(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Tb(a,b,c){if(""===a)throw new D(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=mb(a);try{e=G(a,{Ii:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new D(20);}else e=vc(a,c,0),d=!0;if(!e)throw new D(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!F(e.mode))throw new D(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:F(e.mode)&&("r"!==pc(b)||b&512)?31:oc(e,pc(b)):44))throw new D(c);if(b&512&&!d){c=e;c="string"==typeof c?G(c,{Ii:!0}).node:c;if(!c.ci.oi)throw new D(63);if(F(c.mode))throw new D(31);if(32768!==(c.mode&61440))throw new D(28);if(d=oc(c,"w"))throw new D(d);c.ci.oi(c,{size:0,timestamp:Date.now()})}b&=-131713;e=sc({node:e,path:lc(e),flags:b,seekable:!0,position:0,di:e.di,Sk:[],error:!1});e.di.open&&e.di.open(e);!h.logReadFiles||b&1||a in hc||(hc[a]=1);return e}
function Wb(a){if(null===a.fd)throw new D(8);a.Fi&&(a.Fi=null);try{a.di.close&&a.di.close(a)}catch(b){throw b;}finally{bc[a.fd]=null}a.fd=null}function zc(a,b,c){if(null===a.fd)throw new D(8);if(!a.seekable||!a.di.Hi)throw new D(70);if(0!=c&&1!=c&&2!=c)throw new D(28);a.position=a.di.Hi(a,b,c);a.Sk=[];return a.position}
function Vb(a,b,c,d,e,f){if(0>d||0>e)throw new D(28);if(null===a.fd)throw new D(8);if(0===(a.flags&2097155))throw new D(8);if(F(a.node.mode))throw new D(31);if(!a.di.write)throw new D(28);a.seekable&&a.flags&1024&&zc(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new D(70);b=a.di.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Ac(a,b){a="string"==typeof a?a:lc(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=mb(a+"/"+c);try{k(d)}catch(e){}a=d}}return d}function Bc(a,b,c,d){a=mb(("string"==typeof a?a:lc(a))+"/"+b);c=Qb(c,d);return vc(a,(void 0!==c?c:438)&4095|32768,0)}
function Ob(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:lc(a),g=b?mb(a+"/"+b):a);a=Qb(d,e);g=vc(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Xb(g,a|146);b=Tb(g,577);Vb(b,c,0,c.length,0,f);Wb(b);Xb(g,a)}}
function Cc(a,b,c,d){a=mb(("string"==typeof a?a:lc(a))+"/"+b);b=Qb(!!c,!!d);Cc.Uj??(Cc.Uj=64);var e=Cc.Uj++<<8|0;yb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,m){for(var p=0,q=0;q<m;q++){try{var t=c()}catch(u){throw new D(29);}if(void 0===t&&0===p)throw new D(6);if(null===t||void 0===t)break;p++;g[l+q]=t}p&&(f.node.timestamp=Date.now());return p},write(f,g,l,m){for(var p=0;p<m;p++)try{d(g[l+p])}catch(q){throw new D(29);}m&&(f.node.timestamp=Date.now());return p}});return wc(a,
b,e)}function Dc(a){if(!(a.Sj||a.Ek||a.link||a.ei)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.ei=(void 0)(a.url),a.gi=a.ei.length}catch(b){throw new D(29);}}}
function Ec(a,b,c,d,e){function f(m,p,q,t,u){m=m.node.ei;if(u>=m.length)return 0;t=Math.min(m.length-u,t);if(m.slice)for(var H=0;H<t;H++)p[q+H]=m[u+H];else for(H=0;H<t;H++)p[q+H]=m.get(u+H);return t}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Sj:!1,url:c};var g=Bc(a,b,d,e);c.ei?g.ei=c.ei:c.url&&(g.ei=null,g.url=c.url);Object.defineProperties(g,{gi:{get:function(){return this.ei.length}}});
var l={};Object.keys(g.di).forEach(m=>{var p=g.di[m];l[m]=(...q)=>{Dc(g);return p(...q)}});l.read=(m,p,q,t,u)=>{Dc(g);return f(m,p,q,t,u)};l.Ti=(m,p,q)=>{Dc(g);var t=Db(p);if(!t)throw new D(48);f(m,r,t,p,q);return{Yj:t,zi:!0}};g.di=l;return g}var K={},Fc=(a,b)=>a?A(v,a,b):"";function Gc(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":J(a).path;if(0==b.length){if(!c)throw new D(44);return a}return mb(a+"/"+b)}
function Hc(a,b,c){a=a(b);z.setInt32(4*(c>>2),a.mk,!0);z.setInt32(4*(c+4>>2),a.mode,!0);z.setUint32(4*(c+8>>2),a.Ik,!0);z.setInt32(4*(c+12>>2),a.uid,!0);z.setInt32(4*(c+16>>2),a.vk,!0);z.setInt32(4*(c+20>>2),a.Vi,!0);y[c+24>>3]=BigInt(a.size);z.setInt32(4*(c+32>>2),4096,!0);z.setInt32(4*(c+36>>2),a.dk,!0);b=a.bk.getTime();var d=a.lj.getTime(),e=a.ek.getTime();y[c+40>>3]=BigInt(Math.floor(b/1E3));z.setUint32(4*(c+48>>2),b%1E3*1E6,!0);y[c+56>>3]=BigInt(Math.floor(d/1E3));z.setUint32(4*(c+64>>2),d%1E3*
1E6,!0);y[c+72>>3]=BigInt(Math.floor(e/1E3));z.setUint32(4*(c+80>>2),e%1E3*1E6,!0);y[c+88>>3]=BigInt(a.zk);return 0}
var jb=void 0,Ic=[0,31,60,91,121,152,182,213,244,274,305,335],Jc=[0,31,59,90,120,151,181,212,243,273,304,334],Kc=a=>{if(!(a instanceof eb||"unwind"==a))throw a;},Lc=0,Mc=a=>{Fa=a;hb||0<Lc||(h.onExit?.(a),Ea=!0);throw new eb(a);},Nc=a=>{Fa=a;Mc(a)},Oc=()=>{if(!(hb||0<Lc))try{var a=Fa;Fa=a;Mc(a)}catch(b){Kc(b)}},Pc=a=>{if(!Ea)try{a(),Oc()}catch(b){Kc(b)}},Qc=(a,b)=>setTimeout(()=>{Pc(a)},b),Rc=!1,Sc=!1,Tc=[];
function Mb(){function a(){Sc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Uc){Uc=!0;Kb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Vc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Vc(d)}));var l=URL.createObjectURL(g),m=new Image;m.onload=()=>{var p=
document.createElement("canvas");p.width=m.width;p.height=m.height;p.getContext("2d").drawImage(m,0,0);URL.revokeObjectURL(l);e?.(c)};m.onerror=()=>{Ba(`Image ${l} could not be decoded`);f?.()};m.src=l}});Kb.push({canHandle:function(c){return!h.noAudioDecoding&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Vc(d)})),m=new Audio;m.addEventListener("canplaythrough",()=>f(m),!1);m.onerror=function(){if(!g){Ba(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",q=0,t=0,u=0;u<c.length;u++)for(q=q<<8|c[u],t+=8;6<=t;){var H=q>>t-6&63;t-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[H]}2==t?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&3)<<4],p+="=="):4==t&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(q&15)<<2],p+="=");m.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(m)}};m.src=l;Qc(()=>{f(m)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Sc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Wc=!1,Xc=void 0,Yc=void 0;function Zc(){if(!Rc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}
function Vc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var $c=[];function ad(){var a=h.canvas;$c.forEach(b=>b(a.width,a.height))}
function bd(a,b,c){b&&c?(a.Tk=b,a.wk=c):(b=a.Tk,c=a.wk);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Yc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var Lb={},Uc,L=12288,cd=!1,dd=0,ed=0,fd=0,M={alpha:!1,depth:!1,stencil:!1,antialias:!1},gd={},hd,N,jd=1,kd=[],O=[],ld=[],md=[],nd=[],P=[],od=[],pd=[],Q=[],qd=[],rd=[],sd=[],td={},ud={},vd=4,wd=0,xd=a=>{for(var b=jd++,c=a.length;c<b;c++)a[c]=null;return b},yd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=N[c](),g=f&&xd(d);f&&(f.name=g,d[g]=f);z.setInt32(4*(b+4*e>>2),g,!0)}},Ad=(a,b)=>{if(h.preinitializedWebGLContext){var c=h.preinitializedWebGLContext;b.xj=Number(c.getParameter(c.VERSION).match(/^WebGL (\d+).\d+/)[1])}else a.mi||
(a.mi=a.getContext,a.getContext=function(d,e){e=a.mi(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null}),c=a.getContext("webgl2",b);return c?zd(c,b):0},zd=(a,b)=>{var c=xd(pd);b={handle:c,attributes:b,version:b.xj,Ei:a};a.canvas&&(a.canvas.Qi=b);pd[c]=b;return c},Cd=a=>{Bd=pd[a];h.ui=N=Bd?.Ei},Dd={},Bd,Ed=a=>{var b=vb(a)+1,c=B(b);c&&C(a,v,c,b);return c},Vd=(a,b,c,d,e)=>{function f(){return g<Fd?(Oc(),!1):!0}Gd=a;Hd=d;var g=Fd;Id=!1;Jd=function(){if(!Ea)if(0<Kd.length){var l=Kd.shift();
l.jl(l.Uk);if(Ld){var m=Ld,p=0==m%1?m-1:Math.floor(m);Ld=l.cl?p:(8*m+(p+.5))/9}h.setStatus&&(l=h.statusMessage||"Please wait...",m=Ld??0,p=Md.gl??0,m?m<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(l):h.setStatus(""));f()&&setTimeout(Jd,0)}else if(f())if(Nd=Nd+1|0,1==Od&&1<Pd&&0!=Nd%Pd)Qd();else{0==Od&&(Rd=performance.now());a:if(!Ea){for(l of Sd)if(!1===l())break a;Pc(a);for(m of Td)m()}f()&&Qd()}};e||(b&&0<b?Ud(0,1E3/b):Ud(1,1),Qd());if(c)throw"unwind";},Id=!1,Qd=null,
Fd=0,Gd=null,Hd=0,Od=0,Pd=0,Nd=0,Kd=[],Sd=[],Td=[];function Wd(){Qd=null;Fd++}function Xd(){Fd++;var a=Od,b=Pd,c=Gd;Gd=null;Vd(c,0,!1,Hd,!0);Ud(a,b);Qd()}var Yd=0;function Zd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Yd)Yd=b+1E3/60;else for(;b+2>=Yd;)Yd+=1E3/60;setTimeout(a,Math.max(Yd-b,0))}}
var Md={},Jd,Ld,Rd,$d,Ud=(a,b)=>{Od=a;Pd=b;if(Gd)if(Id||=!0,0==a)Qd=function(){setTimeout(Jd,Math.max(0,Rd+b-performance.now())|0)};else if(1==a)Qd=function(){Zd(Jd)};else if(2==a){if("undefined"==typeof $d)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);$d=d=>{c.push(d);postMessage("setimmediate","*")}}else $d=setImmediate;Qd=function(){$d(Jd)}}},ae=[],be=(a,b)=>{ae.length=
0;for(var c;c=v[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;ae.push(112==c?z.getUint32(4*(b>>2),!0):106==c?y[b>>3]:105==c?z.getInt32(4*(b>>2),!0):z.getFloat64(8*(b>>3),!0));b+=d?8:4}return ae};function ce(a){var b=R.si[a];b.target.removeEventListener(b.ki,b.Oj,b.pi);R.si.splice(a,1)}function de(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var l in f)if(f[l]!=g[l])return!1;return!0}for(var e of R.Ai)if(e.Dj==a&&d(e.Jj,c))return;R.Ai.push({Dj:a,Xj:b,Jj:c});R.Ai.sort((f,g)=>f.Xj<g.Xj)}
function ee(a){R.Ai=R.Ai.filter(b=>b.Dj!=a)}function fe(){return navigator.userActivation?navigator.userActivation.isActive:R.vj&&R.gk.aj}function ge(){if(fe()){var a=R.Ai;R.Ai=[];for(var b of a)b.Dj(...b.Jj)}}function he(a){if(!a.target)return-4;if(a.ri)a.Oj=function(c){++R.vj;R.gk=a;ge();a.ti(c);ge();--R.vj},a.target.addEventListener(a.ki,a.Oj,a.pi),R.si.push(a);else for(var b=0;b<R.si.length;++b)R.si[b].target==a.target&&R.si[b].ki==a.ki&&ce(b--);return 0}
function ie(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={Wk:0,uj:0,wj:0,jj:0,Ij:0,Fj:0,sj:0,el:0,ml:0,dl:0,tj:0,zj:0,Hj:0,Ej:0,ol(){for(;R.si.length;)ce(R.si.length-1);R.Ai=[]},vj:0,Ai:[],si:[],Mk:(a,b)=>{for(var c=0;c<R.si.length;++c)R.si[c].target!=a||b&&b!=R.si[c].ki||ce(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},je={},ke=[0,document,window],S=a=>{a=2<a?a?A(v,a):"":a;return ke[a]||document.querySelector(a)},me=a=>{var b=vb(a)+1,c=le(b);C(a,v,c,b);return c},ne=a=>{var b=T(),c=le(8),d=c+4;a=me(a.id);
if(a=S(a))z.setInt32(4*(c>>2),a.width,!0),z.setInt32(4*(d>>2),a.height,!0);c=[z.getInt32(4*(c>>2),!0),z.getInt32(4*(d>>2),!0)];U(b);return c},oe=(a,b,c)=>{a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},pe=(a,b,c)=>{if(a.bl){var d=T();a=me(a.id);oe(a,b,c);U(d)}else a.width=b,a.height=c},qe=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),pe(a,d,e),a.style.width=
f,a.style.height=g,a.style.backgroundColor=l,m||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=m,a.style.paddingLeft=p,a.style.paddingRight=q,a.style.paddingTop=t,a.style.paddingBottom=u,a.style.marginLeft=H,a.style.marginRight=Z,a.style.marginTop=pa,a.style.marginBottom=aa,document.body.style.margin=kb,document.documentElement.style.overflow=Ub,document.body.scroll=x,a.style.Ci=xa,a.Qi&&a.Qi.Ei.viewport(0,0,d,e),je.bj&&V(je.bj,37,0,je.Lj))}var c=ne(a),d=c[0],e=
c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,m=document.body.style.backgroundColor,p=a.style.paddingLeft,q=a.style.paddingRight,t=a.style.paddingTop,u=a.style.paddingBottom,H=a.style.marginLeft,Z=a.style.marginRight,pa=a.style.marginTop,aa=a.style.marginBottom,kb=document.body.style.margin,Ub=document.documentElement.style.overflow,x=document.body.scroll,xa=a.style.Ci;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},re=(a,b,
c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},se=a=>0>ke.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},te=(a,b)=>{if(0!=b.Cj||0!=b.pj){qe(a);var c=b.Pk?innerWidth:screen.width,d=b.Pk?innerHeight:screen.height,e=se(a),f=e.width;e=e.height;var g=ne(a),l=g[0];g=g[1];3==b.Cj?(re(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Cj&&(c*g<l*d?(f=g*c/l,re(a,(d-f)/2,0),d=f):(f=l*d/g,re(a,0,(c-f)/2),c=f));var m;(m=a.style).backgroundColor||(m.backgroundColor="black");
let p;(p=document.body.style).backgroundColor||(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.rk&&(a.style.Ci="optimizeSpeed",a.style.Ci="-moz-crisp-edges",a.style.Ci="-o-crisp-edges",a.style.Ci="-webkit-optimize-contrast",a.style.Ci="optimize-contrast",a.style.Ci="crisp-edges",a.style.Ci="pixelated");m=2==b.pj?devicePixelRatio:1;0!=b.pj&&(c=c*m|0,d=d*m|0,pe(a,c,d),a.Qi&&a.Qi.Ei.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return R.fullscreenEnabled()?-3:-1;je=b;b.bj&&V(b.bj,37,0,b.Lj);return 0},ue=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},ve=a=>{try{a()}catch(b){Va(b)}};
function we(){var a=W,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{xe.push(c);try{return d(...e)}finally{if(!Ea&&(xe.pop(),X&&1===ye&&0===xe.length&&(ye=0,ve(ze),"undefined"!=typeof Ae&&!Be&&Ce))){Be=!0;do{e=Ce;Ce=0;var f=z.getUint32(4*(e>>2),!0),g=z.getUint32(4*(e+4>>2),!0);De(f,g);U(z.getUint32(4*(e+8>>2),!0));f=z.getUint32(4*(e+12>>2),!0);0!==f?(X=null,z.setUint32(4*(e+12>>2),0,!0),dynCall_vi(f,z.getUint32(4*(e+16>>2),!0))):(X=e+=20,ye=2,Ee(e),Fe(e))}while(Ce);Be=!1}}}:
d;return b}var ye=0,X=null,Ge=0,xe=[],He={},Ie={},Je=0,Ke=null,Le=[];function Me(){return new Promise((a,b)=>{Ke={resolve:a,reject:b}})}function Ne(){var a=B(4108),b=a+12;z.setUint32(4*(a>>2),b,!0);z.setUint32(4*(a+4>>2),b+4096,!0);Oe(a);return a}function Oe(a){var b=xe[0],c=He[b];void 0===c&&(c=Je++,He[b]=c,Ie[c]=b);z.setInt32(4*(a+8>>2),c,!0)}function Fe(a){a=z.getInt32(4*(a+8>>2),!0);return(0,W[Ie[a]])()}
function Pe(a){if(!Ea){if(0===ye){var b=!1,c=!1;a((d=0)=>{if(!Ea&&(Ge=d,b=!0,c)){ye=2;ve(()=>Ee(X));"undefined"!=typeof Md&&Gd&&Xd();d=!1;try{var e=Fe(X)}catch(l){e=l,d=!0}var f=!1;if(!X){var g=Ke;g&&(Ke=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(ye=1,X=Ne(),"undefined"!=typeof Md&&Gd&&Wd(),ve(()=>Qe(X)))}else 2===ye?(ye=0,ve(Re),Se(X),X=null,Le.forEach(Pc)):Va(`invalid state: ${ye}`);return Ge}}
var Ce=0,Be=!1,Ae={},Te=(a,b)=>{z.setFloat64(8*(a>>3),b.timestamp,!0);for(var c=0;c<b.axes.length;++c)z.setFloat64(8*(a+8*c+16>>3),b.axes[c],!0);for(c=0;c<b.buttons.length;++c)"object"==typeof b.buttons[c]?z.setFloat64(8*(a+8*c+528>>3),b.buttons[c].value,!0):z.setFloat64(8*(a+8*c+528>>3),b.buttons[c],!0);for(c=0;c<b.buttons.length;++c)r[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];r[a+1104]=b.connected;z.setInt32(4*(a+1108>>2),b.index,!0);z.setInt32(4*(a+8>>2),b.axes.length,
!0);z.setInt32(4*(a+12>>2),b.buttons.length,!0);C(b.id,v,a+1112,64);C(b.mapping,v,a+1176,64)},Ue=a=>N.activeTexture(a),Ve=(a,b)=>{N.attachShader(O[a],P[b])},We=(a,b,c)=>{N.bindAttribLocation(O[a],b,c?A(v,c):"")},Xe=(a,b)=>{35051==a?N.rj=b:35052==a&&(N.vi=b);N.bindBuffer(a,kd[b])},Ye=(a,b)=>{N.bindFramebuffer(a,ld[b])},Ze=(a,b)=>{N.bindTexture(a,nd[b])},$e=a=>{N.bindVertexArray(od[a])},af=(a,b)=>N.blendEquationSeparate(a,b),bf=(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),cf=(a,b,c,d,e,f,g,l,m,p)=>N.blitFramebuffer(a,
b,c,d,e,f,g,l,m,p),df=(a,b,c,d)=>{c&&b?N.bufferData(a,v,d,c,b):N.bufferData(a,b,d)},ef=(a,b,c,d)=>{c&&N.bufferSubData(a,b,v,d,c)},ff=a=>N.clear(a),gf=(a,b,c,d)=>N.clearColor(a,b,c,d),hf=a=>N.clearDepth(a),jf=a=>{N.compileShader(P[a])},kf=(a,b,c,d,e,f,g,l,m)=>{N.vi||!l?N.compressedTexSubImage2D(a,b,c,d,e,f,g,l,m):N.compressedTexSubImage2D(a,b,c,d,e,f,g,v,m,l)},lf=()=>{var a=xd(O),b=N.createProgram();b.name=a;b.hj=b.fj=b.gj=0;b.Gj=1;O[a]=b;return a},mf=a=>{var b=xd(P);P[b]=N.createShader(a);return b},
nf=a=>N.cullFace(a),of=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=kd[d];e&&(N.deleteBuffer(e),e.name=0,kd[d]=null,d==N.rj&&(N.rj=0),d==N.vi&&(N.vi=0))}},pf=(a,b)=>{for(var c=0;c<a;++c){var d=z.getInt32(4*(b+4*c>>2),!0),e=ld[d];e&&(N.deleteFramebuffer(e),e.name=0,ld[d]=null)}},qf=a=>{if(a){var b=O[a];b&&(N.deleteProgram(b),b.name=0,O[a]=null)}},rf=a=>{if(a){var b=P[a];b&&(N.deleteShader(b),P[a]=null)}},sf=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=nd[d];
e&&(N.deleteTexture(e),e.name=0,nd[d]=null)}},tf=(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0);N.deleteVertexArray(od[d]);od[d]=null}},uf=a=>N.depthFunc(a),vf=a=>{N.depthMask(!!a)},wf=a=>N.disable(a),xf=a=>{N.disableVertexAttribArray(a)},yf=(a,b,c)=>{N.drawArrays(a,b,c)},zf=(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},Af=[],Bf=(a,b)=>{for(var c=Af[a],d=0;d<a;d++)c[d]=z.getInt32(4*(b+4*d>>2),!0);N.drawBuffers(c)},Cf=(a,b,c,d)=>{N.drawElements(a,b,c,d)},Df=(a,b,c,d,e)=>{N.drawElementsInstanced(a,
b,c,d,e)},Ef=a=>N.enable(a),Ff=a=>{N.enableVertexAttribArray(a)},Gf=(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,nd[d],e)},Hf=a=>N.frontFace(a),If=(a,b)=>{yd(a,b,"createBuffer",kd)},Jf=(a,b)=>{yd(a,b,"createFramebuffer",ld)},Kf=(a,b)=>{yd(a,b,"createTexture",nd)},Lf=(a,b)=>{yd(a,b,"createVertexArray",od)},Mf=a=>N.generateMipmap(a),Nf=(a,b,c,d,e,f,g,l)=>{b=O[b];if(a=N[a](b,c))d=l&&C(a.name,v,l,d),e&&z.setInt32(4*(e>>2),d,!0),f&&z.setInt32(4*(f>>2),a.size,!0),g&&z.setInt32(4*(g>>2),a.type,!0)},Of=(a,
b,c,d,e,f,g)=>{Nf("getActiveUniform",a,b,c,d,e,f,g)},Pf=(a,b)=>{z.setUint32(4*(a>>2),b,!0);var c=z.getUint32(4*(a>>2),!0);z.setUint32(4*(a+4>>2),(b-c)/4294967296,!0)},Qf=()=>{var a="EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(N.getSupportedExtensions()||[]).filter(b=>a.includes(b))};function Rf(){var a=Qf();return a=a.concat(a.map(b=>"GL_"+b))}
var Sf=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:return;case 34814:case 36345:d=0;break;case 34466:var e=N.getParameter(34467);d=e?e.length:0;break;case 33309:d=Rf().length;break;case 33307:case 33308:d=33307==a?3:0}if(void 0===d)switch(e=N.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:d=
0;break;default:return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:z.setInt32(4*(b+4*a>>2),e[a],!0);break;case 2:z.setFloat32(4*(b+4*a>>2),e[a],!0);break;case 4:r[b+a]=e[a]?1:0}return}d=e.name|0}}switch(c){case 1:Pf(b,d);break;case 0:z.setInt32(4*(b>>2),d,!0);break;case 2:z.setFloat32(4*(b>>2),d,!0);break;case 4:r[b]=d?1:0}}},Tf=(a,b,c,d)=>{b=N.getIndexedParameter(a,b);switch(typeof b){case "boolean":a=
b?1:0;break;case "number":a=b;break;case "object":if(null===b)switch(a){case 35983:case 35368:a=0;break;default:return}else if(b instanceof WebGLBuffer)a=b.name|0;else return;break;default:return}switch(d){case 1:Pf(c,a);break;case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0);break;case 4:r[c]=a?1:0;break;default:throw"internal emscriptenWebGLGetIndexed() error, bad type: "+d;}},Uf=(a,b)=>Sf(a,b,0),Vf=(a,b,c,d)=>{a=N.getProgramInfoLog(O[a]);b=0<b&&d?C(a,v,d,b):0;c&&z.setInt32(4*
(c>>2),b,!0)},Wf=(a,b,c)=>{if(c&&!(a>=jd))if(a=O[a],35716==b)z.setInt32(4*(c>>2),N.getProgramInfoLog(a).length+1,!0);else if(35719==b){if(!a.hj){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.hj=Math.max(a.hj,N.getActiveUniform(a,b).name.length+1)}z.setInt32(4*(c>>2),a.hj,!0)}else if(35722==b){if(!a.fj)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.fj=Math.max(a.fj,N.getActiveAttrib(a,b).name.length+1);z.setInt32(4*(c>>2),a.fj,!0)}else if(35381==b){if(!a.gj)for(d=N.getProgramParameter(a,
35382),b=0;b<d;++b)a.gj=Math.max(a.gj,N.getActiveUniformBlockName(a,b).length+1);z.setInt32(4*(c>>2),a.gj,!0)}else z.setInt32(4*(c>>2),N.getProgramParameter(a,b),!0)},Xf=(a,b,c)=>{if(c){a=Q[a];b=2>Bd.version?N.Bi.getQueryObjectEXT(a,b):N.getQueryParameter(a,b);var d;"boolean"==typeof b?d=b?1:0:d=b;Pf(c,d)}},Yf=(a,b,c)=>{if(c){a=N.Bi.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*(c>>2),d,!0)}},Zf=(a,b,c,d)=>{a=N.getShaderInfoLog(P[a]);b=0<b&&d?C(a,v,d,b):0;c&&z.setInt32(4*
(c>>2),b,!0)},$f=(a,b,c)=>{c&&(35716==b?(a=N.getShaderInfoLog(P[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):35720==b?(a=N.getShaderSource(P[a]),z.setInt32(4*(c>>2),a?a.length+1:0,!0)):z.setInt32(4*(c>>2),N.getShaderParameter(P[a],b),!0))},ag=a=>{var b=td[a];if(!b){switch(a){case 7939:b=Ed(Rf().join(" "));break;case 7936:case 7937:case 37445:case 37446:b=(b=N.getParameter(a))?Ed(b):0;break;case 7938:b=Ed(`OpenGL ES 3.0 (${N.getParameter(7938)})`);break;case 35724:b=N.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);
null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=Ed(b)}td[a]=b}return b},bg=(a,b)=>{if(2>Bd.version)return 0;var c=ud[a];if(c)return 0>b||b>=c.length?0:c[b];switch(a){case 7939:return c=Rf().map(Ed),c=ud[a]=c,0>b||b>=c.length?0:c[b];default:return 0}},cg=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),dg=a=>{var b=a.Zi,c=a.$j,d;if(!b){a.Zi=b={};a.Zj={};var e=N.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=N.getActiveUniform(a,d);var g=f.name;f=f.size;var l=cg(g);l=0<l?
g.slice(0,l):g;var m=a.Gj;a.Gj+=f;c[l]=[f,m];for(g=0;g<f;++g)b[m]=g,a.Zj[m++]=l}}},eg=(a,b)=>{b=b?A(v,b):"";if(a=O[a]){dg(a);var c=a.Zi,d=0,e=b,f=cg(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.$j[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}return-1},Y=a=>{var b=N.hk,c=b.Zi[a];"number"==typeof c&&(b.Zi[a]=c=N.getUniformLocation(b,b.Zj[a]+(0<c?`[${c}]`:"")));return c},fg=(a,b,c,d)=>{if(c)if(a=O[a],dg(a),a=N.getUniform(a,Y(b)),"number"==typeof a||"boolean"==
typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*(c+4*b>>2),a[b],!0)}},gg=(a,b,c)=>{fg(a,b,c,2)},hg=(a,b,c)=>{fg(a,b,c,0)},ig=(a,b,c,d)=>{if(c)if(a=N.getVertexAttrib(a,b),34975==b)z.setInt32(4*(c>>2),a&&a.name,!0);else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:z.setInt32(4*(c>>2),a,!0);break;case 2:z.setFloat32(4*(c>>2),a,!0);break;
case 5:d=Math.fround(a),z.setInt32(4*(c>>2),d,!0)}else for(b=0;b<a.length;b++)switch(d){case 0:z.setInt32(4*(c+4*b>>2),a[b],!0);break;case 2:z.setFloat32(4*(c+4*b>>2),a[b],!0);break;case 5:var e=Math.fround(a[b]);z.setInt32(4*(c+4*b>>2),e,!0)}},jg=(a,b,c)=>{ig(a,b,c,0)},kg=a=>(a=od[a])?N.isVertexArray(a):0,lg=a=>{a=O[a];N.linkProgram(a);a.Zi=0;a.$j={}},mg=(a,b)=>{3317==a?vd=b:3314==a&&(wd=b);N.pixelStorei(a,b)},ng=a=>N.readBuffer(a),og=a=>{a-=5120;return 0==a?r:1==a?v:2==a?Ga:4==a?Ia:6==a?w:5==a||
28922==a||28520==a||30779==a||30782==a?Ja:Ha},pg=(a,b,c,d,e)=>{a=og(a);b=d*((wd||c)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+vd-1&-vd);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},qg=(a,b,c,d,e,f,g)=>{if(N.rj)N.readPixels(a,b,c,d,e,f,g);else{var l=og(f);g>>>=31-Math.clz32(l.BYTES_PER_ELEMENT);N.readPixels(a,b,c,d,e,f,l,g)}},rg=(a,b,c,d)=>N.scissor(a,b,c,d),sg=(a,b,c,d)=>{for(var e="",f=0;f<
b;++f){var g=d?z.getUint32(4*(d+4*f>>2),!0):void 0;e+=Fc(z.getUint32(4*(c+4*f>>2),!0),g)}N.shaderSource(P[a],e)},tg=(a,b,c,d,e,f,g,l,m)=>{if(N.vi)N.texImage2D(a,b,c,d,e,f,g,l,m);else if(m){var p=og(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);N.texImage2D(a,b,c,d,e,f,g,l,p,m)}else p=m?pg(l,g,d,e,m):null,N.texImage2D(a,b,c,d,e,f,g,l,p)},ug=(a,b,c)=>N.texParameteri(a,b,c),vg=(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),wg=(a,b,c,d,e,f,g,l,m)=>{if(N.vi)N.texSubImage2D(a,b,c,d,e,f,g,l,m);else if(m){var p=og(l);
N.texSubImage2D(a,b,c,d,e,f,g,l,p,m>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=m?pg(l,g,e,f,m):null,N.texSubImage2D(a,b,c,d,e,f,g,l,m)},xg=(a,b,c)=>{b&&N.uniform1fv(Y(a),w,c>>2,b)},yg=(a,b,c)=>{b&&N.uniform1iv(Y(a),Ia,c>>2,b)},zg=(a,b,c)=>{b&&N.uniform2fv(Y(a),w,c>>2,2*b)},Ag=(a,b,c)=>{b&&N.uniform2iv(Y(a),Ia,c>>2,2*b)},Bg=(a,b,c)=>{b&&N.uniform3fv(Y(a),w,c>>2,3*b)},Cg=(a,b,c)=>{b&&N.uniform3iv(Y(a),Ia,c>>2,3*b)},Dg=(a,b,c)=>{b&&N.uniform4fv(Y(a),w,c>>2,4*b)},Eg=(a,b,c)=>{b&&N.uniform4iv(Y(a),Ia,
c>>2,4*b)},Fg=(a,b,c,d)=>{b&&N.uniformMatrix3fv(Y(a),!!c,w,d>>2,9*b)},Gg=(a,b,c,d)=>{b&&N.uniformMatrix4fv(Y(a),!!c,w,d>>2,16*b)},Hg=a=>{a=O[a];N.useProgram(a);N.hk=a},Ig=(a,b)=>{N.vertexAttribDivisor(a,b)},Jg=(a,b,c,d,e)=>{N.vertexAttribIPointer(a,b,c,d,e)},Kg=(a,b,c,d,e,f)=>{N.vertexAttribPointer(a,b,c,!!d,e,f)},Lg=(a,b,c,d)=>N.viewport(a,b,c,d),Mg=(a,b)=>{if(!R.fullscreenEnabled())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?fe()?te(a,b):b.lk?(de(te,1,[a,b]),1):-2:-3:
-4},Ng=()=>{try{if(navigator.getGamepads)return(R.ej=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},Og=(a,b)=>{var c={target:S(2),ki:"beforeunload",ri:b,ti:(d=event)=>{var e=V(b,28,0,a);e&&=e?A(v,e):"";if(e)return d.preventDefault(),d.returnValue=e},pi:!0};return he(c)},Pg=(a,b,c,d,e,f)=>{R.sj||(R.sj=B(256));a={target:S(a),ki:f,ri:d,ti:(g=event)=>{var l=g.target.id?g.target.id:"",m=R.sj;C(ie(g.target),v,m+0,128);C(l,v,m+128,128);V(d,e,m,b)&&g.preventDefault()},pi:c};return he(a)},
Qg=(a,b,c,d,e)=>{R.tj||(R.tj=B(276));return he({target:a,ki:e,ri:d,ti:(f=event)=>{var g=R.tj,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,m=!!l;r[g]=m;r[g+1]=R.fullscreenEnabled();var p=m?l:R.Kk,q=p?.id||"";C(ie(p),v,g+2,128);C(q,v,g+130,128);z.setInt32(4*(g+260>>2),p?p.clientWidth:0,!0);z.setInt32(4*(g+264>>2),p?p.clientHeight:0,!0);z.setInt32(4*(g+268>>2),screen.width,!0);z.setInt32(4*(g+272>>2),screen.height,!0);m&&
(R.Kk=l);V(d,19,g,b)&&f.preventDefault()},pi:c})},Rg=(a,b,c,d,e)=>{R.uj||(R.uj=B(1240));b={target:S(2),aj:!0,ki:e,ri:c,ti:(f=event)=>{var g=R.uj;Te(g,f.gamepad);V(c,d,g,a)&&f.preventDefault()},pi:b};return he(b)},Sg=(a,b,c,d,e,f)=>{R.wj||(R.wj=B(160));a={target:S(a),ki:f,ri:d,ti:g=>{var l=R.wj;z.setFloat64(8*(l>>3),g.timeStamp,!0);var m=l>>2;z.setInt32(4*(m+2),g.location,!0);r[l+12]=g.ctrlKey;r[l+13]=g.shiftKey;r[l+14]=g.altKey;r[l+15]=g.metaKey;r[l+16]=g.repeat;z.setInt32(4*(m+5),g.charCode,!0);
z.setInt32(4*(m+6),g.keyCode,!0);z.setInt32(4*(m+7),g.which,!0);C(g.key||"",v,l+32,32);C(g.code||"",v,l+64,32);C(g.char||"",v,l+96,32);C(g.locale||"",v,l+128,32);V(d,e,l,b)&&g.preventDefault()},pi:c};return he(a)},Tg=(a,b,c)=>{z.setFloat64(8*(a>>3),b.timeStamp,!0);var d=a>>2;z.setInt32(4*(d+2),b.screenX,!0);z.setInt32(4*(d+3),b.screenY,!0);z.setInt32(4*(d+4),b.clientX,!0);z.setInt32(4*(d+5),b.clientY,!0);r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;z.setInt16(2*(2*d+14),
b.button,!0);z.setInt16(2*(2*d+15),b.buttons,!0);z.setInt32(4*(d+8),b.movementX,!0);z.setInt32(4*(d+9),b.movementY,!0);a=se(c);z.setInt32(4*(d+10),b.clientX-(a.left|0),!0);z.setInt32(4*(d+11),b.clientY-(a.top|0),!0)},Ug=(a,b,c,d,e,f)=>{R.jj||(R.jj=B(64));a=S(a);return he({target:a,aj:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ki:f,ri:d,ti:(g=event)=>{Tg(R.jj,g,a);V(d,e,R.jj,b)&&g.preventDefault()},pi:c})},Vg=(a,b,c,d,e)=>{R.zj||(R.zj=B(257));return he({target:a,ki:e,ri:d,ti:(f=event)=>{var g=
R.zj,l=document.pointerLockElement||document.mi||document.pk||document.nk;r[g]=!!l;var m=l?.id||"";C(ie(l),v,g+1,128);C(m,v,g+129,128);V(d,20,g,b)&&f.preventDefault()},pi:c})},Wg=(a,b,c,d)=>{R.Fj||(R.Fj=B(36));a=S(a);return he({target:a,ki:"resize",ri:d,ti:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=R.Fj;z.setInt32(4*(g>>2),0,!0);z.setInt32(4*(g+4>>2),f.clientWidth,!0);z.setInt32(4*(g+8>>2),f.clientHeight,!0);z.setInt32(4*(g+12>>2),innerWidth,!0);z.setInt32(4*(g+16>>2),innerHeight,
!0);z.setInt32(4*(g+20>>2),outerWidth,!0);z.setInt32(4*(g+24>>2),outerHeight,!0);z.setInt32(4*(g+28>>2),pageXOffset|0,!0);z.setInt32(4*(g+32>>2),pageYOffset|0,!0);V(d,10,g,b)&&e.preventDefault()}}},pi:c})},Xg=(a,b,c,d,e,f)=>{R.Ej||(R.Ej=B(1552));a=S(a);return he({target:a,aj:"touchstart"==f||"touchend"==f,ki:f,ri:d,ti:g=>{var l={},m=g.touches;for(var p of m)p.Rj=p.Wj=0,l[p.identifier]=p;for(var q of g.changedTouches)q.Rj=1,l[q.identifier]=q;for(var t of g.targetTouches)l[t.identifier].Wj=1;m=R.Ej;
z.setFloat64(8*(m>>3),g.timeStamp,!0);r[m+12]=g.ctrlKey;r[m+13]=g.shiftKey;r[m+14]=g.altKey;r[m+15]=g.metaKey;p=m+16;q=se(a);t=0;for(let u of Object.values(l))if(l=p>>2,z.setInt32(4*l,u.identifier,!0),z.setInt32(4*(l+1),u.screenX,!0),z.setInt32(4*(l+2),u.screenY,!0),z.setInt32(4*(l+3),u.clientX,!0),z.setInt32(4*(l+4),u.clientY,!0),z.setInt32(4*(l+5),u.pageX,!0),z.setInt32(4*(l+6),u.pageY,!0),r[p+28]=u.Rj,r[p+29]=u.Wj,z.setInt32(4*(l+8),u.clientX-(q.left|0),!0),z.setInt32(4*(l+9),u.clientY-(q.top|
0),!0),p+=48,31<++t)break;z.setInt32(4*(m+8>>2),t,!0);V(d,e,m,b)&&g.preventDefault()},pi:c})},Yg=(a,b,c)=>{var d=ke[1];R.Hj||(R.Hj=B(8));return he({target:d,ki:"visibilitychange",ri:c,ti:(e=event)=>{var f=R.Hj,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);r[f]=document.hidden;z.setInt32(4*(f+4>>2),g,!0);V(c,21,f,a)&&e.preventDefault()},pi:b})},Zg=(a,b,c,d)=>{R.Ij||(R.Ij=B(96));return he({target:a,aj:!0,ki:"wheel",ri:d,ti:(e=event)=>{var f=R.Ij;Tg(f,e,a);z.setFloat64(8*
(f+64>>3),e.deltaX,!0);z.setFloat64(8*(f+72>>3),e.deltaY,!0);z.setFloat64(8*(f+80>>3),e.deltaZ,!0);z.setInt32(4*(f+88>>2),e.deltaMode,!0);V(d,9,f,b)&&e.preventDefault()},pi:c})};class $g{constructor(){this.zi=[void 0];this.mi=[]}get(a){return this.zi[a]}has(a){return void 0!==this.zi[a]}$i(a){var b=this.mi.pop()||this.zi.length;this.zi[b]=a;return b}}var ah;
function bh(a,b,c,d,e){function f(){var I=0,ra=0;x.response&&kb&&0===z.getUint32(4*(a+12>>2),!0)&&(ra=x.response.byteLength);0<ra&&(I=B(ra),v.set(new Uint8Array(x.response),I));z.setUint32(4*(a+12>>2),I,!0);Pf(a+16,ra);Pf(a+24,0);(I=x.response?x.response.byteLength:0)&&Pf(a+32,I);z.setInt16(2*(a+40>>1),x.readyState,!0);z.setInt16(2*(a+42>>1),x.status,!0);x.statusText&&C(x.statusText,v,a+44,64)}var g=z.getUint32(4*(a+8>>2),!0);if(g){var l=g?A(v,g):"",m=a+108,p=Fc(m+0);p||="GET";var q=z.getUint32(4*
(m+56>>2),!0),t=z.getUint32(4*(m+68>>2),!0),u=z.getUint32(4*(m+72>>2),!0);g=z.getUint32(4*(m+76>>2),!0);var H=z.getUint32(4*(m+80>>2),!0),Z=z.getUint32(4*(m+84>>2),!0),pa=z.getUint32(4*(m+88>>2),!0),aa=z.getUint32(4*(m+52>>2),!0),kb=!!(aa&1),Ub=!!(aa&2);aa=!!(aa&64);t=t?t?A(v,t):"":void 0;u=u?u?A(v,u):"":void 0;var x=new XMLHttpRequest;x.withCredentials=!!v[m+60];x.open(p,l,!aa,t,u);aa||(x.timeout=q);x.mi=l;x.responseType="arraybuffer";H&&(l=H?A(v,H):"",x.overrideMimeType(l));if(g)for(;;){m=z.getUint32(4*
(g>>2),!0);if(!m)break;l=z.getUint32(4*(g+4>>2),!0);if(!l)break;g+=8;m=m?A(v,m):"";l=l?A(v,l):"";x.setRequestHeader(m,l)}var xa=ah.$i(x);z.setUint32(4*(a>>2),xa,!0);g=Z&&pa?v.slice(Z,Z+pa):null;x.onload=I=>{ah.has(xa)&&(f(),200<=x.status&&300>x.status?b?.(a,x,I):c?.(a,x,I))};x.onerror=I=>{ah.has(xa)&&(f(),c?.(a,x,I))};x.ontimeout=I=>{ah.has(xa)&&c?.(a,x,I)};x.onprogress=I=>{if(ah.has(xa)){var ra=kb&&Ub&&x.response?x.response.byteLength:0,nb=0;0<ra&&kb&&Ub&&(nb=B(ra),v.set(new Uint8Array(x.response),
nb));z.setUint32(4*(a+12>>2),nb,!0);Pf(a+16,ra);Pf(a+24,I.loaded-ra);Pf(a+32,I.total);z.setInt16(2*(a+40>>1),x.readyState,!0);3<=x.readyState&&0===x.status&&0<I.loaded&&(x.status=200);z.setInt16(2*(a+42>>1),x.status,!0);x.statusText&&C(x.statusText,v,a+44,64);d?.(a,x,I);nb&&Se(nb)}};x.onreadystatechange=I=>{ah.has(xa)&&(z.setInt16(2*(a+40>>1),x.readyState,!0),2<=x.readyState&&z.setInt16(2*(a+42>>1),x.status,!0),e?.(a,x,I))};try{x.send(g)}catch(I){c?.(a,x,I)}}else c(a,0,"no url specified!")}
var na={},dh=()=>{if(!ch){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:wa||"./this.program"},b;for(b in na)void 0===na[b]?delete a[b]:a[b]=na[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);ch=c}return ch},ch,ta;[44].forEach(a=>{Hb[a]=new D(a);Hb[a].stack="<generic error, no stack>"});dc=Array(4096);oa(E,"/");k("/tmp");k("/home");k("/home/web_user");
(function(){k("/dev");yb(259,{read:()=>0,write:(d,e,f,g)=>g});wc("/dev/null",259);xb(1280,Ab);xb(1536,Bb);wc("/dev/tty",1280);wc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=rb(a).byteLength);return a[--b]};Cc("/dev","random",c);Cc("/dev","urandom",c);k("/dev/shm");k("/dev/shm/tmp")})();
(function(){k("/proc");var a=k("/proc/self");k("/proc/self/fd");oa({ji(){var b=Gb(a,"fd",16895,73);b.ci={Si(c,d){var e=J(+d);c={parent:null,ji:{Ui:"fake"},ci:{Wi:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=Ac;h.FS_createDataFile=Ob;h.FS_createPreloadedFile=Pb;h.FS_unlink=Zb;h.FS_createLazyFile=Ec;h.FS_createDevice=Cc;
h.requestFullscreen=function(a,b){function c(){Rc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Zc,Xc&&d.requestPointerLock(),Rc=!0,Yc?("undefined"!=typeof SDL&&(f=z.getUint32(4*(SDL.screen>>2),!0),z.setInt32(4*(SDL.screen>>2),f|8388608,!0)),bd(h.canvas),ad()):bd(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Yc?("undefined"!=
typeof SDL&&(f=z.getUint32(4*(SDL.screen>>2),!0),z.setInt32(4*(SDL.screen>>2),f&-8388609,!0)),bd(h.canvas),ad()):bd(d));h.onFullScreen?.(Rc);h.onFullscreen?.(Rc)}Xc=a;Yc=b;"undefined"==typeof Xc&&(Xc=!0);"undefined"==typeof Yc&&(Yc=!1);var d=h.canvas;Wc||(Wc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");
d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){bd(h.canvas,a,b);c||ad()};
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.ui&&a==h.canvas)return h.ui;var e;if(b){var f={antialias:!1,alpha:!1,xj:2};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Dd&&(e=Ad(a,f)))var l=pd[e].Ei}else l=a.getContext("2d");if(!l)return null;c&&(h.ui=l,b&&Cd(e),Tc.forEach(m=>m()),Mb());return l};h.requestAnimationFrame=Zd;h.pauseMainLoop=Wd;
h.resumeMainLoop=Xd;h.preMainLoop&&Sd.push(h.preMainLoop);h.postMainLoop&&Td.push(h.postMainLoop);for(var eh=0;32>eh;++eh)Af.push(Array(eh));ah=new $g;
var qh={H:function(a,b,c){jb=c;try{var d=J(a);switch(b){case 0:var e=ib();if(0>e)break;for(;bc[e];)e++;return tc(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=ib(),d.flags|=e,0;case 12:return e=ib(),z.setInt16(2*(e+0>>1),2,!0),0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.ii}},fe:function(a,b){try{var c=J(a);return Hc(Sb,c.path,b)}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.ii}},pd:function(a,
b,c){try{var d=J(a);d.Fi||(d.Fi=Rb(d.path));a=0;for(var e=zc(d,0,1),f=Math.floor(e/280);f<d.Fi.length&&a+280<=c;){var g=d.Fi[f];if("."===g){var l=d.node.id;var m=4}else if(".."===g)l=G(d.path,{parent:!0}).node.id,m=4;else{var p=Ib(d.node,g);l=p.id;m=8192===(p.mode&61440)?2:F(p.mode)?4:40960===(p.mode&61440)?10:8}y[b+a>>3]=BigInt(l);y[b+a+8>>3]=BigInt(280*(f+1));z.setInt16(2*(b+a+16>>1),280,!0);r[b+a+18]=m;C(g,v,b+a+19,256);a+=280;f+=1}zc(d,280*f,0);return a}catch(q){if("undefined"==typeof K||"ErrnoError"!==
q.name)throw q;return-q.ii}},Wf:function(a,b,c){jb=c;try{var d=J(a);switch(b){case 21509:return d.fi?0:-59;case 21505:if(!d.fi)return-59;if(d.fi.yi.Bk){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=ib();z.setInt32(4*(e>>2),25856,!0);z.setInt32(4*(e+4>>2),5,!0);z.setInt32(4*(e+8>>2),191,!0);z.setInt32(4*(e+12>>2),35387,!0);for(var f=0;32>f;f++)r[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.fi?0:-59;case 21506:case 21507:case 21508:if(!d.fi)return-59;
if(d.fi.yi.Ck)for(e=ib(),z.getInt32(4*(e>>2),!0),z.getInt32(4*(e+4>>2),!0),z.getInt32(4*(e+8>>2),!0),z.getInt32(4*(e+12>>2),!0),a=[],f=0;32>f;f++)a.push(r[e+f+17]);return 0;case 21519:if(!d.fi)return-59;e=ib();z.setInt32(4*(e>>2),0,!0);return 0;case 21520:return d.fi?-28:-59;case 21531:e=ib();if(!d.di.Ak)throw new D(59);return d.di.Ak(d,b,e);case 21523:if(!d.fi)return-59;d.fi.yi.Dk&&(f=[24,80],e=ib(),z.setInt16(2*(e>>1),f[0],!0),z.setInt16(2*(e+2>>1),f[1],!0));return 0;case 21524:return d.fi?0:-59;
case 21515:return d.fi?0:-59;default:return-28}}catch(g){if("undefined"==typeof K||"ErrnoError"!==g.name)throw g;return-g.ii}},Ad:function(a,b){try{return a=a?A(v,a):"",Hc(yc,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.ii}},ed:function(a,b,c){try{return b=b?A(v,b):"",b=Gc(a,b),b=mb(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),k(b,c),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.ii}},Ld:function(a,b,c,d){try{b=b?A(v,b):"";var e=
d&256;b=Gc(a,b,d&4096);return Hc(e?yc:Sb,b,c)}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.ii}},wa:function(a,b,c,d){jb=d;try{b=b?A(v,b):"";b=Gc(a,b);var e=d?ib():0;return Tb(b,c,e).fd}catch(f){if("undefined"==typeof K||"ErrnoError"!==f.name)throw f;return-f.ii}},Wd:function(a,b){try{return a=a?A(v,a):"",Hc(Sb,a,b)}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return-c.ii}},Kc:function(a,b,c){try{return b=b?A(v,b):"",b=Gc(a,b),0===c?Zb(b):512===c?Yb(b):
Va("Invalid flags passed to unlinkat"),0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return-d.ii}},Vg:()=>{Va("")},Db:function(a){if(ah.has(a)){var b=ah.get(a),c=ah;c.zi[a]=void 0;c.mi.push(a);0<b.readyState&&4>b.readyState&&b.abort()}},Bf:()=>1,Cb:()=>{throw Infinity;},zg:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);z.setInt32(4*(b>>2),a.getSeconds(),!0);z.setInt32(4*(b+4>>2),a.getMinutes(),!0);z.setInt32(4*(b+8>>2),a.getHours(),!0);
z.setInt32(4*(b+12>>2),a.getDate(),!0);z.setInt32(4*(b+16>>2),a.getMonth(),!0);z.setInt32(4*(b+20>>2),a.getFullYear()-1900,!0);z.setInt32(4*(b+24>>2),a.getDay(),!0);var c=a.getFullYear();z.setInt32(4*(b+28>>2),(0!==c%4||0===c%100&&0!==c%400?Jc:Ic)[a.getMonth()]+a.getDate()-1|0,!0);z.setInt32(4*(b+36>>2),-(60*a.getTimezoneOffset()),!0);c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();z.setInt32(4*(b+32>>2),(c!=d&&a.getTimezoneOffset()==
Math.min(d,c))|0,!0)},df:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{if(isNaN(e))return 61;var l=J(d);if(0!==(b&2)&&0===(c&2)&&2!==(l.flags&2097155))throw new D(2);if(1===(l.flags&2097155))throw new D(2);if(!l.di.Ti)throw new D(43);if(!a)throw new D(28);var m=l.di.Ti(l,a,e,b,c);var p=m.Yj;z.setInt32(4*(f>>2),m.zi,!0);z.setUint32(4*(g>>2),p,!0);return 0}catch(q){if("undefined"==typeof K||"ErrnoError"!==q.name)throw q;return-q.ii}},pf:function(a,b,c,d,e,f){f=
-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=J(e);if(c&2){if(32768!==(g.node.mode&61440))throw new D(43);d&2||g.di.kj&&g.di.kj(g,v.slice(a,a+b),f,b,d)}}catch(l){if("undefined"==typeof K||"ErrnoError"!==l.name)throw l;return-l.ii}},Kg:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();z.setUint32(4*(a>>2),60*Math.max(f,e),!0);z.setInt32(4*(b>>2),Number(f!=e),!0);b=g=>{var l=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(l/
60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(C(a,v,c,17),C(b,v,d,17)):(C(a,v,d,17),C(b,v,c,17))},Uc:a=>{if(12448==a)return L=12288,1;L=12300;return 0},fd:(a,b,c,d,e)=>{if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=z.getInt32(4*(b>>2),!0);if(12321==a)a=z.getInt32(4*(b+4>>2),!0),M.alpha=0<a;else if(12325==a)a=z.getInt32(4*(b+4>>2),!0),M.depth=0<a;else if(12326==a)a=z.getInt32(4*(b+4>>2),!0),M.stencil=0<a;else if(12337==a)a=z.getInt32(4*(b+4>>2),!0),M.antialias=0<a;else if(12338==
a)a=z.getInt32(4*(b+4>>2),!0),M.antialias=1==a;else if(12544==a)a=z.getInt32(4*(b+4>>2),!0),M.kl=12547!=a;else if(12344==a)break;b+=8}c&&d||e?(e&&z.setInt32(4*(e>>2),1,!0),c&&0<d&&z.setUint32(4*(c>>2),62002,!0),L=12288,c=1):(L=12300,c=0)}return c},cd:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;for(a=1;;){b=z.getInt32(4*(d>>2),!0);if(12440==b)a=z.getInt32(4*(d+4>>2),!0);else if(12344==b)break;else return L=12292,0;d+=8}if(2>a||3<a)return L=12293,0;M.xj=a-1;M.ll=0;hd=Ad(h.canvas,M);if(0!=hd)return L=12288,
Cd(hd),Tc.forEach(e=>e()),Cd(null),62004;L=12297;return 0},ad:(a,b)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},bd:(a,b)=>{if(62E3!=a)return L=12296,0;if(62004!=b)return L=12294,0;a=hd;Bd===pd[a]&&(Bd=null);"object"==typeof R&&R.Mk(pd[a].Ei.canvas);pd[a]&&pd[a].Ei.canvas&&(pd[a].Ei.canvas.Qi=void 0);pd[a]=null;L=12288;dd==b&&(dd=0);return 1},$c:(a,b)=>{if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;ed==b&&(ed=0);fd==b&&(fd=0);L=12288;return 1},dd:(a,
b,c,d)=>{if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return z.setInt32(4*(d>>2),M.alpha?32:24,!0),1;case 12321:return z.setInt32(4*(d>>2),M.alpha?8:0,!0),1;case 12322:return z.setInt32(4*(d>>2),8,!0),1;case 12323:return z.setInt32(4*(d>>2),8,!0),1;case 12324:return z.setInt32(4*(d>>2),8,!0),1;case 12325:return z.setInt32(4*(d>>2),M.depth?24:0,!0),1;case 12326:return z.setInt32(4*(d>>2),M.stencil?8:0,!0),1;case 12327:return z.setInt32(4*
(d>>2),12344,!0),1;case 12328:return z.setInt32(4*(d>>2),62002,!0),1;case 12329:return z.setInt32(4*(d>>2),0,!0),1;case 12330:return z.setInt32(4*(d>>2),4096,!0),1;case 12331:return z.setInt32(4*(d>>2),16777216,!0),1;case 12332:return z.setInt32(4*(d>>2),4096,!0),1;case 12333:return z.setInt32(4*(d>>2),0,!0),1;case 12334:return z.setInt32(4*(d>>2),0,!0),1;case 12335:return z.setInt32(4*(d>>2),12344,!0),1;case 12337:return z.setInt32(4*(d>>2),M.antialias?4:0,!0),1;case 12338:return z.setInt32(4*(d>>
2),M.antialias?1:0,!0),1;case 12339:return z.setInt32(4*(d>>2),4,!0),1;case 12340:return z.setInt32(4*(d>>2),12344,!0),1;case 12341:case 12342:case 12343:return z.setInt32(4*(d>>2),-1,!0),1;case 12345:case 12346:return z.setInt32(4*(d>>2),0,!0),1;case 12347:return z.setInt32(4*(d>>2),0,!0),1;case 12348:return z.setInt32(4*(d>>2),1,!0),1;case 12349:case 12350:return z.setInt32(4*(d>>2),0,!0),1;case 12351:return z.setInt32(4*(d>>2),12430,!0),1;case 12352:return z.setInt32(4*(d>>2),4,!0),1;case 12354:return z.setInt32(4*
(d>>2),0,!0),1;default:return L=12292,0}},id:a=>{L=12288;return 0!=a&&1!=a?0:62E3},Sc:()=>L,hd:(a,b,c)=>{if(62E3!=a)return L=12296,0;b&&z.setInt32(4*(b>>2),1,!0);c&&z.setInt32(4*(c>>2),4,!0);cd=!0;L=12288;return 1},_c:(a,b,c,d)=>{if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;Cd(d?hd:null);dd=d;fd=b;ed=c;L=12288;return 1},Tc:(a,b)=>{if(62E3!=a)return L=12296,0;L=12288;if(gd[b])return gd[b];switch(b){case 12371:a=Ed("Emscripten");break;
case 12372:a=Ed("1.4 Emscripten EGL");break;case 12373:a=Ed("");break;case 12429:a=Ed("OpenGL_ES");break;default:return L=12300,0}return gd[b]=a},Zc:()=>{if(cd)if(h.ui)if(h.ui.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Yc:(a,b)=>{if(62E3!=a)return L=12296,0;0==b?Ud(0,0):Ud(1,b);L=12288;return 1},gd:a=>{if(62E3!=a)return L=12296,0;fd=ed=dd=0;cd=!1;L=12288;return 1},Wc:()=>{L=12288;return 1},Xc:()=>{L=12288;return 1},w:(a,b,c)=>{b=be(b,c);return db[a](...b)},d:(a,
b,c)=>{b=be(b,c);return db[a](...b)},ta:()=>{Wd();Gd=null},I:()=>Date.now(),Mc:()=>{if(!R.fullscreenEnabled())return-1;ee(te);var a=ke[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Qc:()=>{ee(ue);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Af:(a,b)=>{if(!Ea)if(0===ye){ye=1;var c=a+20;Oe(c);X=c;Qe(c);c=T();z.setUint32(4*(a+8>>2),c,!0);Ce=b}else ye=
0,Re(),X=null},r:()=>devicePixelRatio,j:(a,b,c)=>{a=S(a);if(!a)return-4;a=se(a);z.setFloat64(8*(b>>3),a.width,!0);z.setFloat64(8*(c>>3),a.height,!0);return 0},Y:(a,b)=>{if(0>a||a>=R.ej.length)return-5;if(!R.ej[a])return-7;Te(b,R.ej[a]);return 0},Ue:()=>2147483648,F:()=>performance.now(),Pc:()=>R.ej.length,Rc:(a,b)=>{z.setInt32(4*(a>>2),screen.width,!0);z.setInt32(4*(b>>2),screen.height,!0)},jb:Ue,ib:Ve,cf:(a,b)=>{N.beginQuery(a,Q[b])},Bb:(a,b)=>{N.Bi.beginQueryEXT(a,Q[b])},Ke:a=>N.beginTransformFeedback(a),
hb:We,gb:Xe,He:(a,b,c)=>{N.bindBufferBase(a,b,kd[c])},Ie:(a,b,c,d,e)=>{N.bindBufferRange(a,b,kd[c],d,e)},fb:Ye,eb:(a,b)=>{N.bindRenderbuffer(a,md[b])},Nd:(a,b)=>{N.bindSampler(a,qd[b])},db:Ze,Ed:(a,b)=>{N.bindTransformFeedback(a,rd[b])},Pe:$e,sb:$e,cb:(a,b,c,d)=>N.blendColor(a,b,c,d),bb:a=>N.blendEquation(a),$a:af,_a:(a,b)=>N.blendFunc(a,b),Za:bf,Se:cf,Ya:df,Xa:ef,Wa:a=>N.checkFramebufferStatus(a),Va:ff,ke:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),le:(a,b,c)=>{N.clearBufferfv(a,b,w,c>>2)},ne:(a,b,c)=>{N.clearBufferiv(a,
b,Ia,c>>2)},me:(a,b,c)=>{N.clearBufferuiv(a,b,Ja,c>>2)},Ua:gf,Ta:hf,Sa:a=>N.clearStencil(a),Xd:(a,b,c)=>{c=Number(c);return N.clientWaitSync(sd[a],b,c)},vf:(a,b)=>{N.hl.clipControlEXT(a,b)},Ra:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},Qa:jf,Pa:(a,b,c,d,e,f,g,l)=>{N.vi||!g?N.compressedTexImage2D(a,b,c,d,e,f,g,l):N.compressedTexImage2D(a,b,c,d,e,f,v,l,g)},jf:(a,b,c,d,e,f,g,l,m)=>{N.vi?N.compressedTexImage3D(a,b,c,d,e,f,g,l,m):N.compressedTexImage3D(a,b,c,d,e,f,g,v,m,l)},Oa:kf,hf:(a,b,c,d,e,f,g,l,m,
p,q)=>{N.vi?N.compressedTexSubImage3D(a,b,c,d,e,f,g,l,m,p,q):N.compressedTexSubImage3D(a,b,c,d,e,f,g,l,m,v,q,p)},ie:(a,b,c,d,e)=>N.copyBufferSubData(a,b,c,d,e),Na:(a,b,c,d,e,f,g,l)=>N.copyTexImage2D(a,b,c,d,e,f,g,l),Ma:(a,b,c,d,e,f,g,l)=>N.copyTexSubImage2D(a,b,c,d,e,f,g,l),kf:(a,b,c,d,e,f,g,l,m)=>N.copyTexSubImage3D(a,b,c,d,e,f,g,l,m),La:lf,Ka:mf,Ja:nf,Ia:of,Ha:pf,Ga:qf,ff:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Q[d];e&&(N.deleteQuery(e),Q[d]=null)}},Rb:(a,b)=>{for(var c=
0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=Q[d];e&&(N.Bi.deleteQueryEXT(e),Q[d]=null)}},Fa:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=md[d];e&&(N.deleteRenderbuffer(e),e.name=0,md[d]=null)}},Pd:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=qd[d];e&&(N.deleteSampler(e),e.name=0,qd[d]=null)}},Ea:rf,Yd:a=>{if(a){var b=sd[a];b&&(N.deleteSync(b),b.name=0,sd[a]=null)}},Da:sf,Dd:(a,b)=>{for(var c=0;c<a;c++){var d=z.getInt32(4*(b+4*c>>2),!0),e=rd[d];e&&(N.deleteTransformFeedback(e),
e.name=0,rd[d]=null)}},Oe:tf,rb:tf,Ca:uf,Ba:vf,Aa:(a,b)=>N.depthRange(a,b),za:(a,b)=>{N.detachShader(O[a],P[b])},ya:wf,yh:xf,xh:yf,ae:zf,nb:zf,ld:zf,sf:zf,md:zf,_e:Bf,qf:Bf,ob:Bf,wh:Cf,$d:Df,mb:Df,jd:Df,kd:Df,rf:Df,nf:(a,b,c,d,e,f)=>{N.drawElements(a,d,e,f)},vh:Ef,uh:Ff,bf:a=>N.endQuery(a),zb:a=>{N.Bi.endQueryEXT(a)},Je:()=>N.endTransformFeedback(),_d:(a,b)=>(a=N.fenceSync(a,b))?(b=xd(sd),a.name=b,sd[b]=a,b):0,th:()=>N.finish(),sh:()=>N.flush(),rh:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,md[d])},
qh:Gf,Qe:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,nd[c],d,e)},ph:Hf,oh:If,mh:Jf,gf:(a,b)=>{yd(a,b,"createQuery",Q)},_b:(a,b)=>{for(var c=0;c<a;c++){var d=N.Bi.createQueryEXT();if(!d){for(;c<a;)d=4*(b+4*c++>>2),z.setInt32(d,0,!0);break}var e=xd(Q);d.name=e;Q[e]=d;z.setInt32(4*(b+4*c>>2),e,!0)}},lh:(a,b)=>{yd(a,b,"createRenderbuffer",md)},Qd:(a,b)=>{yd(a,b,"createSampler",qd)},kh:Kf,Cd:(a,b)=>{yd(a,b,"createTransformFeedback",rd)},Ne:Lf,qb:Lf,nh:Mf,jh:(a,b,c,d,e,f,g)=>{Nf("getActiveAttrib",a,b,c,
d,e,f,g)},ih:Of,ce:(a,b,c,d,e)=>{a=O[a];if(a=N.getActiveUniformBlockName(a,b))e&&0<c?(c=C(a,v,e,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&z.setInt32(4*(d>>2),0,!0)},de:(a,b,c,d)=>{a=O[a];if(35393==c)z.setInt32(4*(d>>2),N.getActiveUniformBlockName(a,b).length+1,!0);else if(a=N.getActiveUniformBlockParameter(a,b,c),null!==a)if(35395==c)for(c=0;c<a.length;c++)z.setInt32(4*(d+4*c>>2),a[c],!0);else z.setInt32(4*(d>>2),a,!0)},ge:(a,b,c,d,e)=>{a=O[a];for(var f=[],g=0;g<b;g++)f.push(z.getInt32(4*(c+4*g>>2),!0));
if(a=N.getActiveUniforms(a,f,d))for(b=a.length,g=0;g<b;g++)z.setInt32(4*(e+4*g>>2),a[g],!0)},hh:(a,b,c,d)=>{a=N.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);z.setInt32(4*(c>>2),e,!0);for(b=0;b<e;++b)z.setInt32(4*(d+4*b>>2),P.indexOf(a[b]),!0)},gh:(a,b)=>N.getAttribLocation(O[a],b?A(v,b):""),fh:(a,b)=>Sf(a,b,4),Rd:(a,b,c)=>{Pf(c,N.getBufferParameter(a,b))},dh:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getBufferParameter(a,b),!0)},ch:()=>N.getError(),bh:(a,b)=>Sf(a,b,2),we:(a,b)=>N.getFragDataLocation(O[a],
b?A(v,b):""),ah:(a,b,c,d)=>{a=N.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;z.setInt32(4*(d>>2),a,!0)},Sd:(a,b,c)=>Tf(a,b,c,1),Ud:(a,b)=>{Sf(a,b,1)},Le:(a,b,c)=>Tf(a,b,c,0),$g:Uf,qd:(a,b,c,d,e)=>{a=N.getInternalformatParameter(a,b,c);if(null!==a)for(b=0;b<a.length&&b<d;++b)z.setInt32(4*(e+4*b>>2),a[b],!0)},xd:()=>{},Zg:Vf,_g:Wf,ub:Xf,wb:Yf,tb:Xf,$e:(a,b,c)=>{a=N.getQueryParameter(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;z.setInt32(4*
(c>>2),d,!0)},vb:Yf,af:(a,b,c)=>{z.setInt32(4*(c>>2),N.getQuery(a,b),!0)},xb:(a,b,c)=>{c&&(a=N.Bi.getQueryEXT(a,b),z.setInt32(4*(c>>2),a,!0))},Yg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getRenderbufferParameter(a,b),!0)},Gd:(a,b,c)=>{z.setFloat32(4*(c>>2),N.getSamplerParameter(qd[a],b),!0)},Hd:(a,b,c)=>{z.setInt32(4*(c>>2),N.getSamplerParameter(qd[a],b),!0)},Wg:Zf,Ug:(a,b,c,d)=>{a=N.getShaderPrecisionFormat(a,b);z.setInt32(4*(c>>2),a.rangeMin,!0);z.setInt32(4*(c+4>>2),a.rangeMax,!0);z.setInt32(4*(d>>2),
a.precision,!0)},Tg:(a,b,c,d)=>{if(a=N.getShaderSource(P[a]))b=0<b&&d?C(a,v,d,b):0,c&&z.setInt32(4*(c>>2),b,!0)},Xg:$f,Sg:ag,je:bg,Td:(a,b,c,d,e)=>{a=N.getSyncParameter(sd[a],b);null!==a&&(z.setInt32(4*(e>>2),a,!0),d&&z.setInt32(4*(d>>2),1,!0))},Rg:(a,b,c)=>{c&&z.setFloat32(4*(c>>2),N.getTexParameter(a,b),!0)},Qg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getTexParameter(a,b),!0)},Fe:(a,b,c,d,e,f,g)=>{a=O[a];if(a=N.getTransformFeedbackVarying(a,b))g&&0<c?(c=C(a.name,v,g,c),d&&z.setInt32(4*(d>>2),c,!0)):d&&
z.setInt32(4*(d>>2),0,!0),e&&z.setInt32(4*(e>>2),a.size,!0),f&&z.setInt32(4*(f>>2),a.type,!0)},ee:(a,b)=>N.getUniformBlockIndex(O[a],b?A(v,b):""),he:(a,b,c,d)=>{a=O[a];for(var e=[],f=0;f<b;f++)e.push(Fc(z.getInt32(4*(c+4*f>>2),!0)));if(a=N.getUniformIndices(a,e))for(b=a.length,f=0;f<b;f++)z.setInt32(4*(d+4*f>>2),a[f],!0)},Ng:eg,Pg:gg,Og:hg,xe:(a,b,c)=>fg(a,b,c,0),De:jg,Ce:jg,Jg:(a,b,c)=>{c&&z.setInt32(4*(c>>2),N.getVertexAttribOffset(a,b),!0)},Mg:(a,b,c)=>{ig(a,b,c,2)},Lg:(a,b,c)=>{ig(a,b,c,5)},Ig:(a,
b)=>N.hint(a,b),ud:(a,b,c)=>{for(var d=Af[b],e=0;e<b;e++)d[e]=z.getInt32(4*(c+4*e>>2),!0);N.invalidateFramebuffer(a,d)},td:(a,b,c,d,e,f,g)=>{for(var l=Af[b],m=0;m<b;m++)l[m]=z.getInt32(4*(c+4*m>>2),!0);N.invalidateSubFramebuffer(a,l,d,e,f,g)},Hg:a=>(a=kd[a])?N.isBuffer(a):0,Gg:a=>N.isEnabled(a),Fg:a=>(a=ld[a])?N.isFramebuffer(a):0,Eg:a=>(a=O[a])?N.isProgram(a):0,ef:a=>(a=Q[a])?N.isQuery(a):0,Ib:a=>(a=Q[a])?N.Bi.isQueryEXT(a):0,Dg:a=>(a=md[a])?N.isRenderbuffer(a):0,Od:a=>(a=qd[a])?N.isSampler(a):0,
Cg:a=>(a=P[a])?N.isShader(a):0,Zd:a=>N.isSync(sd[a]),Bg:a=>(a=nd[a])?N.isTexture(a):0,Bd:a=>N.isTransformFeedback(rd[a]),Me:kg,pb:kg,Ag:a=>N.lineWidth(a),yg:lg,zd:()=>N.pauseTransformFeedback(),xg:mg,uf:(a,b)=>{N.pl.polygonModeWEBGL(a,b)},wg:(a,b)=>N.polygonOffset(a,b),wf:(a,b,c)=>{N.il.polygonOffsetClampEXT(a,b,c)},wd:()=>{},vd:()=>{},yb:(a,b)=>{N.Bi.queryCounterEXT(Q[a],b)},of:ng,vg:qg,ug:()=>{},tg:(a,b,c,d)=>N.renderbufferStorage(a,b,c,d),Re:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,b,c,
d,e),yd:()=>N.resumeTransformFeedback(),sg:(a,b)=>{N.sampleCoverage(a,!!b)},Jd:(a,b,c)=>{N.samplerParameterf(qd[a],b,c)},Id:(a,b,c)=>{c=z.getFloat32(4*(c>>2),!0);N.samplerParameterf(qd[a],b,c)},Md:(a,b,c)=>{N.samplerParameteri(qd[a],b,c)},Kd:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);N.samplerParameteri(qd[a],b,c)},rg,qg:()=>{},pg:sg,og:(a,b,c)=>N.stencilFunc(a,b,c),ng:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),mg:a=>N.stencilMask(a),lg:(a,b)=>N.stencilMaskSeparate(a,b),kg:(a,b,c)=>N.stencilOp(a,b,c),jg:(a,
b,c,d)=>N.stencilOpSeparate(a,b,c,d),ig:tg,mf:(a,b,c,d,e,f,g,l,m,p)=>{if(N.vi)N.texImage3D(a,b,c,d,e,f,g,l,m,p);else if(p){var q=og(m);N.texImage3D(a,b,c,d,e,f,g,l,m,q,p>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else N.texImage3D(a,b,c,d,e,f,g,l,m,null)},hg:(a,b,c)=>N.texParameterf(a,b,c),gg:(a,b,c)=>{c=z.getFloat32(4*(c>>2),!0);N.texParameterf(a,b,c)},fg:ug,eg:(a,b,c)=>{c=z.getInt32(4*(c>>2),!0);N.texParameteri(a,b,c)},sd:vg,rd:(a,b,c,d,e,f)=>N.texStorage3D(a,b,c,d,e,f),dg:wg,lf:(a,b,c,d,e,f,g,l,m,p,
q)=>{if(N.vi)N.texSubImage3D(a,b,c,d,e,f,g,l,m,p,q);else if(q){var t=og(p);N.texSubImage3D(a,b,c,d,e,f,g,l,m,p,t,q>>>31-Math.clz32(t.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,f,g,l,m,p,null)},Ge:(a,b,c,d)=>{a=O[a];for(var e=[],f=0;f<b;f++)e.push(Fc(z.getInt32(4*(c+4*f>>2),!0)));N.transformFeedbackVaryings(a,e,d)},cg:(a,b)=>{N.uniform1f(Y(a),b)},bg:xg,ag:(a,b)=>{N.uniform1i(Y(a),b)},$f:yg,ve:(a,b)=>{N.uniform1ui(Y(a),b)},re:(a,b,c)=>{b&&N.uniform1uiv(Y(a),Ja,c>>2,b)},_f:(a,b,c)=>{N.uniform2f(Y(a),
b,c)},Zf:zg,Yf:(a,b,c)=>{N.uniform2i(Y(a),b,c)},Xf:Ag,ue:(a,b,c)=>{N.uniform2ui(Y(a),b,c)},qe:(a,b,c)=>{b&&N.uniform2uiv(Y(a),Ja,c>>2,2*b)},Vf:(a,b,c,d)=>{N.uniform3f(Y(a),b,c,d)},Uf:Bg,Tf:(a,b,c,d)=>{N.uniform3i(Y(a),b,c,d)},Sf:Cg,te:(a,b,c,d)=>{N.uniform3ui(Y(a),b,c,d)},pe:(a,b,c)=>{b&&N.uniform3uiv(Y(a),Ja,c>>2,3*b)},Rf:(a,b,c,d,e)=>{N.uniform4f(Y(a),b,c,d,e)},Qf:Dg,Pf:(a,b,c,d,e)=>{N.uniform4i(Y(a),b,c,d,e)},Of:Eg,se:(a,b,c,d,e)=>{N.uniform4ui(Y(a),b,c,d,e)},oe:(a,b,c)=>{b&&N.uniform4uiv(Y(a),
Ja,c>>2,4*b)},be:(a,b,c)=>{a=O[a];N.uniformBlockBinding(a,b,c)},Nf:(a,b,c,d)=>{b&&N.uniformMatrix2fv(Y(a),!!c,w,d>>2,4*b)},Ze:(a,b,c,d)=>{b&&N.uniformMatrix2x3fv(Y(a),!!c,w,d>>2,6*b)},Xe:(a,b,c,d)=>{b&&N.uniformMatrix2x4fv(Y(a),!!c,w,d>>2,8*b)},Mf:Fg,Ye:(a,b,c,d)=>{b&&N.uniformMatrix3x2fv(Y(a),!!c,w,d>>2,6*b)},Ve:(a,b,c,d)=>{b&&N.uniformMatrix3x4fv(Y(a),!!c,w,d>>2,12*b)},Lf:Gg,We:(a,b,c,d)=>{b&&N.uniformMatrix4x2fv(Y(a),!!c,w,d>>2,8*b)},Te:(a,b,c,d)=>{b&&N.uniformMatrix4x3fv(Y(a),!!c,w,d>>2,12*b)},
Kf:Hg,Jf:a=>{N.validateProgram(O[a])},If:(a,b)=>N.vertexAttrib1f(a,b),Hf:(a,b)=>{N.vertexAttrib1f(a,z.getFloat32(4*(b>>2),!0))},Gf:(a,b,c)=>N.vertexAttrib2f(a,b,c),Ff:(a,b)=>{N.vertexAttrib2f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0))},Ef:(a,b,c,d)=>N.vertexAttrib3f(a,b,c,d),Df:(a,b)=>{N.vertexAttrib3f(a,z.getFloat32(4*(b>>2),!0),z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0))},Cf:(a,b,c,d,e)=>N.vertexAttrib4f(a,b,c,d,e),zf:(a,b)=>{N.vertexAttrib4f(a,z.getFloat32(4*(b>>2),!0),
z.getFloat32(4*(b+4>>2),!0),z.getFloat32(4*(b+8>>2),!0),z.getFloat32(4*(b+12>>2),!0))},Fd:Ig,kb:Ig,nd:Ig,tf:Ig,od:Ig,Be:(a,b,c,d,e)=>N.vertexAttribI4i(a,b,c,d,e),ze:(a,b)=>{N.vertexAttribI4i(a,z.getInt32(4*(b>>2),!0),z.getInt32(4*(b+4>>2),!0),z.getInt32(4*(b+8>>2),!0),z.getInt32(4*(b+12>>2),!0))},Ae:(a,b,c,d,e)=>N.vertexAttribI4ui(a,b,c,d,e),ye:(a,b)=>{N.vertexAttribI4ui(a,z.getUint32(4*(b>>2),!0),z.getUint32(4*(b+4>>2),!0),z.getUint32(4*(b+8>>2),!0),z.getUint32(4*(b+12>>2),!0))},Ee:Jg,yf:Kg,xf:Lg,
Vd:(a,b,c)=>{c=Number(c);N.waitSync(sd[a],b,c)},C:()=>1,Fb:()=>!0,Nc:(a,b,c)=>{b={Cj:z.getInt32(4*(c>>2),!0),pj:z.getInt32(4*(c+4>>2),!0),rk:z.getInt32(4*(c+8>>2),!0),lk:b,bj:z.getInt32(4*(c+12>>2),!0),Lj:z.getInt32(4*(c+16>>2),!0)};return Mg(a,b)},ua:(a,b)=>{a=S(a);return a?a.requestPointerLock?fe()?ue(a):b?(de(ue,2,[a]),1):-2:-1:-4},Ah:a=>{var b=v.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,
d)/65536))-Da.buffer.byteLength+65535)/65536;try{Da.grow(d);Ka();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},ia:Ng,_:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Og(a,b),la:(a,b,c,d)=>Pg(a,b,c,d,12,"blur"),q:oe,E:(a,b,c)=>{a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},ma:(a,b,c,d)=>Pg(a,b,c,d,13,"focus"),ba:(a,b,c,d)=>{if(!R.fullscreenEnabled())return-1;a=S(a);if(!a)return-4;Qg(a,b,c,d,"webkitfullscreenchange");return Qg(a,b,c,d,"fullscreenchange")},
T:(a,b,c)=>Ng()?-1:Rg(a,b,c,26,"gamepadconnected"),R:(a,b,c)=>Ng()?-1:Rg(a,b,c,27,"gamepaddisconnected"),ea:(a,b,c,d)=>Sg(a,b,c,d,2,"keydown"),ca:(a,b,c,d)=>Sg(a,b,c,d,1,"keypress"),da:(a,b,c,d)=>Sg(a,b,c,d,3,"keyup"),L:(a,b,c)=>{Vd(()=>dynCall_v(a),b,c)},ra:(a,b,c,d)=>Ug(a,b,c,d,5,"mousedown"),pa:(a,b,c,d)=>Ug(a,b,c,d,33,"mouseenter"),oa:(a,b,c,d)=>Ug(a,b,c,d,34,"mouseleave"),sa:(a,b,c,d)=>Ug(a,b,c,d,8,"mousemove"),qa:(a,b,c,d)=>Ug(a,b,c,d,6,"mouseup"),fa:(a,b,c,d)=>{if(!document||!document.body||
!(document.body.requestPointerLock||document.body.mi||document.body.pk||document.body.nk))return-1;a=S(a);if(!a)return-4;Vg(a,b,c,d,"mozpointerlockchange");Vg(a,b,c,d,"webkitpointerlockchange");Vg(a,b,c,d,"mspointerlockchange");return Vg(a,b,c,d,"pointerlockchange")},aa:(a,b,c,d)=>Wg(a,b,c,d),ga:(a,b,c,d)=>Xg(a,b,c,d,25,"touchcancel"),ja:(a,b,c,d)=>Xg(a,b,c,d,23,"touchend"),ha:(a,b,c,d)=>Xg(a,b,c,d,24,"touchmove"),ka:(a,b,c,d)=>Xg(a,b,c,d,22,"touchstart"),$:(a,b,c)=>Yg(a,b,c),na:(a,b,c,d)=>(a=S(a))?
"undefined"!=typeof a.onwheel?Zg(a,b,c,d):-1:-4,Oc:a=>document.title=a?A(v,a):"",t:a=>Pe(b=>Qc(b,a)),Eb:function(a,b,c,d,e){function f(u){t?u():Pc(u)}var g=a+108,l=z.getUint32(4*(g+36>>2),!0),m=z.getUint32(4*(g+40>>2),!0),p=z.getUint32(4*(g+44>>2),!0),q=z.getUint32(4*(g+48>>2),!0),t=!!(z.getUint32(4*(g+52>>2),!0)&64);bh(a,u=>{f(()=>{l?dynCall_vi(l,u):b?.(u)})},u=>{f(()=>{m?dynCall_vi(m,u):c?.(u)})},u=>{f(()=>{p?dynCall_vi(p,u):d?.(u)})},u=>{f(()=>{q?dynCall_vi(q,u):e?.(u)})});return a},ab:(a,b)=>
{var c=0;dh().forEach((d,e)=>{var f=b+c;z.setUint32(4*(a+4*e>>2),f,!0);e=f;for(f=0;f<d.length;++f)r[e++]=d.charCodeAt(f);r[e]=0;c+=d.length+1});return 0},lb:(a,b)=>{var c=dh();z.setUint32(4*(a>>2),c.length,!0);var d=0;c.forEach(e=>d+=e.length+1);z.setUint32(4*(b>>2),d,!0);return 0},m:Nc,s:function(a){try{var b=J(a);Wb(b);return 0}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.ii}},zh:function(a,b){try{var c=J(a);r[b]=c.fi?2:F(c.mode)?3:40960===(c.mode&61440)?7:4;z.setInt16(2*
(b+2>>1),0,!0);y[b+8>>3]=BigInt(0);y[b+16>>3]=BigInt(0);return 0}catch(d){if("undefined"==typeof K||"ErrnoError"!==d.name)throw d;return d.ii}},va:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var l=z.getUint32(4*(a>>2),!0),m=z.getUint32(4*(a+4>>2),!0);a+=8;var p=e,q=f,t=r;if(0>m||0>q)throw new D(28);if(null===p.fd)throw new D(8);if(1===(p.flags&2097155))throw new D(8);if(F(p.node.mode))throw new D(31);if(!p.di.read)throw new D(28);var u="undefined"!=typeof q;if(!u)q=p.position;
else if(!p.seekable)throw new D(70);var H=p.di.read(p,t,l,m,q);u||(p.position+=H);var Z=H;if(0>Z){var pa=-1;break a}b+=Z;if(Z<m)break;"undefined"!=typeof f&&(f+=Z)}pa=b}z.setUint32(4*(d>>2),pa,!0);return 0}catch(aa){if("undefined"==typeof K||"ErrnoError"!==aa.name)throw aa;return aa.ii}},eh:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;var e=J(a);zc(e,b,c);y[d>>3]=BigInt(e.position);e.Fi&&0===b&&0===c&&(e.Fi=null);return 0}catch(f){if("undefined"==
typeof K||"ErrnoError"!==f.name)throw f;return f.ii}},Vc:function(a){try{var b=J(a);return Pe(c=>{var d=b.node.ji;d.type.Yi?d.type.Yi(d,!1,e=>{e?c(29):c(0)}):c(0)})}catch(c){if("undefined"==typeof K||"ErrnoError"!==c.name)throw c;return c.ii}},xa:function(a,b,c,d){try{a:{var e=J(a);a=b;for(var f,g=b=0;g<c;g++){var l=z.getUint32(4*(a>>2),!0),m=z.getUint32(4*(a+4>>2),!0);a+=8;var p=Vb(e,r,l,m,f);if(0>p){var q=-1;break a}b+=p;if(p<m)break;"undefined"!=typeof f&&(f+=p)}q=b}z.setUint32(4*(d>>2),q,!0);
return 0}catch(t){if("undefined"==typeof K||"ErrnoError"!==t.name)throw t;return t.ii}},Ob:Ue,tc:Ve,sc:We,D:Xe,z:Ye,N:Ze,Gc:$e,wc:af,vc:bf,yc:cf,A:df,P:ef,zc:ff,Xb:gf,Wb:hf,Tb:jf,X:kf,uc:lf,Vb:mf,Fc:nf,U:of,Bc:pf,Q:qf,B:rf,V:sf,cc:tf,Ec:uf,Pb:vf,p:wf,Yb:xf,Mb:yf,Nb:zf,Ac:Bf,Kb:Cf,Lb:Df,o:Ef,bc:Ff,Cc:Gf,Jb:Hf,Z:If,Dc:Jf,Jc:Kf,dc:Lf,Hc:Mf,fc:Of,k:Uf,gc:Vf,y:Wf,Sb:Zf,O:$f,i:ag,G:bg,ec:eg,l:gg,x:hg,rc:lg,M:mg,S:ng,Qb:qg,Lc:rg,Ub:sg,e:tg,g:ug,Ic:vg,W:wg,qc:xg,mc:yg,pc:zg,lc:Ag,oc:Bg,kc:Cg,nc:Dg,jc:Eg,
ic:Fg,hc:Gg,xc:Hg,Zb:Ig,$b:Jg,ac:Kg,Hb:Lg,J:fh,f:gh,v:hh,u:ih,K:jh,h:kh,a:lh,b:mh,c:nh,n:oh,Ab:ph,Gb:function(a,b){h.setStatus(a>=b?"":"Prefetching resources\u2026 ("+a+"/"+b+")",!0)}},W=function(){function a(c){W=c.exports;W=we();Da=W.Bh;Ka();ta=W.Nh;Ma.unshift(W.Ch);Ua("wasm-instantiate");return W}var b={a:qh};Ta("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return Ba(`Module.instantiateWasm callback failed with error: ${c}`),!1}Xa??=Wa("taisei.wasm")?"taisei.wasm":
h.locateFile?h.locateFile("taisei.wasm",ya):ya+"taisei.wasm";ab(b,function(c){a(c.instance)});return{}}();h._vfs_sync_callback=(a,b,c)=>(h._vfs_sync_callback=W.Dh)(a,b,c);
var rh=h._main=(a,b)=>(rh=h._main=W.Eh)(a,b),Cb=(a,b)=>(Cb=W.Fh)(a,b),B=a=>(B=W.Gh)(a),Se=a=>(Se=W.Hh)(a),sh=(a,b)=>(sh=W.Ih)(a,b),De=(a,b)=>(De=W.Jh)(a,b),U=a=>(U=W.Kh)(a),le=a=>(le=W.Lh)(a),T=()=>(T=W.Mh)(),V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=W.Oh)(a,b,c,d),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=W.Ph)(a,b,c),th=h.dynCall_ii=(a,b)=>(th=h.dynCall_ii=W.Qh)(a,b),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=W.Rh)(a,b),uh=h.dynCall_viii=(a,b,c,d)=>(uh=h.dynCall_viii=
W.Sh)(a,b,c,d),vh=h.dynCall_viiii=(a,b,c,d,e)=>(vh=h.dynCall_viiii=W.Th)(a,b,c,d,e),wh=h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,l,m,p)=>(wh=h.dynCall_viiiiiiiii=W.Uh)(a,b,c,d,e,f,g,l,m,p),xh=h.dynCall_i=a=>(xh=h.dynCall_i=W.Vh)(a),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=W.Wh)(a),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=W.Xh)(a,b,c),yh=h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(yh=h.dynCall_viiiiii=W.Yh)(a,b,c,d,e,f,g),zh=h.dynCall_iiiii=(a,b,c,d,e)=>(zh=h.dynCall_iiiii=W.Zh)(a,b,
c,d,e),Qe=a=>(Qe=W._h)(a),ze=()=>(ze=W.$h)(),Ee=a=>(Ee=W.ai)(a),Re=()=>(Re=W.bi)();function hh(a,b,c){var d=T();try{return dynCall_iii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;sh(1,0)}}function jh(a,b,c,d,e){var f=T();try{return zh(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;sh(1,0)}}function ih(a,b,c,d){var e=T();try{return V(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;sh(1,0)}}function fh(a){var b=T();try{return xh(a)}catch(c){U(b);if(c!==c+0)throw c;sh(1,0)}}
function mh(a,b,c,d){var e=T();try{uh(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;sh(1,0)}}function gh(a,b){var c=T();try{return th(a,b)}catch(d){U(c);if(d!==d+0)throw d;sh(1,0)}}function oh(a,b,c,d,e,f,g){var l=T();try{yh(a,b,c,d,e,f,g)}catch(m){U(l);if(m!==m+0)throw m;sh(1,0)}}function lh(a,b,c){var d=T();try{dynCall_vii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;sh(1,0)}}function kh(a,b){var c=T();try{dynCall_vi(a,b)}catch(d){U(c);if(d!==d+0)throw d;sh(1,0)}}
function nh(a,b,c,d,e){var f=T();try{vh(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;sh(1,0)}}function ph(a,b,c,d,e,f,g,l,m,p){var q=T();try{wh(a,b,c,d,e,f,g,l,m,p)}catch(t){U(q);if(t!==t+0)throw t;sh(1,0)}}h.addRunDependency=Ta;h.removeRunDependency=Ua;
h.ccall=(a,b,c,d,e)=>{function f(t){--Lc;0!==m&&U(m);return"string"===b?t?A(v,t):"":"boolean"===b?!!t:t}var g={string:t=>{var u=0;null!==t&&void 0!==t&&0!==t&&(u=me(t));return u},array:t=>{var u=le(t.length);r.set(t,u);return u}};a=h["_"+a];var l=[],m=0;if(d)for(var p=0;p<d.length;p++){var q=g[c[p]];q?(0===m&&(m=T()),l[p]=q(d[p])):l[p]=d[p]}c=X;d=a(...l);e=e?.async;Lc+=1;if(X!=c)return Me().then(f);d=f(d);return e?Promise.resolve(d):d};h.FS_createPreloadedFile=Pb;h.FS_unlink=a=>Zb(a);
h.FS_createPath=Ac;h.FS_createDevice=Cc;h.FS_createDataFile=(a,b,c,d,e,f)=>{Ob(a,b,c,d,e,f)};h.FS_createLazyFile=Ec;var Ah;Sa=function Bh(){Ah||Ch();Ah||(Sa=Bh)};function Dh(a=[]){var b=rh;a.unshift(wa);var c=a.length,d=le(4*(c+1)),e=d;a.forEach(g=>{g=me(g);z.setUint32(4*(e>>2),g,!0);e+=4});z.setUint32(4*(e>>2),0,!0);try{var f=b(c,d);Nc(f,!0)}catch(g){Kc(g)}}
function Ch(){var a=va;function b(){if(!Ah&&(Ah=!0,h.calledRun=!0,!Ea)){if(!h.noFSInit&&!ec){var c,d;ec=!0;e??=h.stdin;c??=h.stdout;d??=h.stderr;e?Cc("/dev","stdin",e):xc("/dev/tty","/dev/stdin");c?Cc("/dev","stdout",null,c):xc("/dev/tty","/dev/stdout");d?Cc("/dev","stderr",null,d):xc("/dev/tty1","/dev/stderr");Tb("/dev/stdin",0);Tb("/dev/stdout",1);Tb("/dev/stderr",1)}fc=!1;gb(Ma);gb(Na);h.onRuntimeInitialized?.();Eh&&Dh(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Oa.unshift(e)}gb(Oa)}}if(!(0<Qa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Pa();gb(La);0<Qa||(h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var Eh=!0;h.noInitialRun&&(Eh=!1);Ch();
