var h;h||=typeof Module != 'undefined' ? Module : {};let aa;(aa=h).expectedDataFileDownloads??(aa.expectedDataFileDownloads=0);h.expectedDataFileDownloads++;
(()=>{var a="undefined"!=typeof ENVIRONMENT_IS_WASM_WORKER&&ENVIRONMENT_IS_WASM_WORKER;"undefined"!=typeof ENVIRONMENT_IS_PTHREAD&&ENVIRONMENT_IS_PTHREAD||a||function(b){function c(p,u,v){let y;(y=h).dataFileDownloads??(y.dataFileDownloads={});fetch(p).catch(B=>Promise.reject(Error(`Network Error: ${p}`,{cause:B}))).then(B=>{if(!B.ok)return Promise.reject(Error(`${B.status}: ${B.url}`));if(!B.body&&B.arrayBuffer)return B.arrayBuffer().then(v);const F=B.body.getReader(),H=()=>F.read().then(Fb).catch(V=>
Promise.reject(Error(`Unexpected error while handling : ${B.url} ${V}`,{cause:V}))),W=[],xa=Number(B.headers.get("Content-Length")??u);let ka=0;const Fb=({done:V,value:yc})=>{if(V){var Ea=new Uint8Array(W.map(Gb=>Gb.length).reduce((Gb,se)=>Gb+se,0));V=0;for(var Fa of W)Ea.set(Fa,V),V+=Fa.length;v(Ea.buffer)}else{W.push(yc);ka+=yc.length;h.dataFileDownloads[p]={loaded:ka,total:xa};V=Fa=0;for(Ea of Object.values(h.dataFileDownloads))Fa+=Ea.loaded,V+=Ea.total;h.setStatus?.(`Downloading data... (${Fa}/${V})`);
return H()}};h.setStatus?.("Downloading data...");return H()})}function d(p){console.error("package error:",p)}function e(p){function u(F,H,W){this.start=F;this.end=H;this.audio=W}function v(F){if(!F)throw"Loading data file failed."+Error().stack;if(F.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;F=new Uint8Array(F);u.prototype.$f=F;F=b.files;for(var H=0;H<F.length;++H)u.prototype.gf[F[H].filename].onload();p.removeRunDependency("datafile_index.data")}p.FS_createPath("/",
"media",!0,!0);p.FS_createPath("/media","stateMainMenu",!0,!0);u.prototype={gf:{},open:function(F,H){this.name=H;this.gf[H]=this;p.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.$f.subarray(this.start,this.end))},finish:function(F){p.FS_createDataFile(this.name,null,F,!0,!0,!0);p.removeRunDependency(`fp ${this.name}`);this.gf[this.name]=null}};for(var y=b.files,B=0;B<y.length;++B)(new u(y[B].start,y[B].end,y[B].audio||0)).open("GET",y[B].filename);p.addRunDependency("datafile_index.data");
p.preloadResults??(p.preloadResults={});p.preloadResults["index.data"]={Jh:!1};n?(v(n),n=null):k=v}"object"===typeof window?window.encodeURIComponent(window.location.pathname.substring(0,window.location.pathname.lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.substring(0,location.pathname.lastIndexOf("/"))+"/");var f=h.locateFile?h.locateFile("index.data",""):"index.data",g=b.remote_package_size,k=null,n=h.getPreloadedPackage?
h.getPreloadedPackage(f,g):null;n||c(f,g,p=>{k?(k(p),k=null):n=p},d);if(h.calledRun)e(h);else{let p;((p=h).preRun??(p.preRun=[])).push(e)}}({files:[{filename:"/media/board.png",start:0,end:182027},{filename:"/media/buttonBackground.png",start:182027,end:184173},{filename:"/media/fall.ogg",start:184173,end:190117,audio:1},{filename:"/media/fuenteMenu.ttf",start:190117,end:235637},{filename:"/media/fuenteNormal.ttf",start:235637,end:294965},{filename:"/media/fuentelcd.ttf",start:294965,end:308249},
{filename:"/media/gemBlue.png",start:308249,end:312854},{filename:"/media/gemGreen.png",start:312854,end:317798},{filename:"/media/gemOrange.png",start:317798,end:323346},{filename:"/media/gemPurple.png",start:323346,end:327988},{filename:"/media/gemRed.png",start:327988,end:333371},{filename:"/media/gemWhite.png",start:333371,end:339184},{filename:"/media/gemYellow.png",start:339184,end:343475},{filename:"/media/handCursor.png",start:343475,end:344761},{filename:"/media/howtoScreen.png",start:344761,
end:585759},{filename:"/media/iconExit.png",start:585759,end:589145},{filename:"/media/iconHint.png",start:589145,end:591792},{filename:"/media/iconRestart.png",start:591792,end:595636},{filename:"/media/match1.ogg",start:595636,end:614819,audio:1},{filename:"/media/match2.ogg",start:614819,end:633486,audio:1},{filename:"/media/match3.ogg",start:633486,end:652315,audio:1},{filename:"/media/music.ogg",start:652315,end:3018664,audio:1},{filename:"/media/partc1.png",start:3018664,end:3023639},{filename:"/media/partc2.png",
start:3023639,end:3025638},{filename:"/media/scoreBackground.png",start:3025638,end:3027432},{filename:"/media/select.ogg",start:3027432,end:3034520,audio:1},{filename:"/media/selector.png",start:3034520,end:3036029},{filename:"/media/stateMainMenu/mainMenuBackground.png",start:3036029,end:3194918},{filename:"/media/stateMainMenu/mainMenuLogo.png",start:3194918,end:3368881},{filename:"/media/stateMainMenu/menuHighlight.png",start:3368881,end:3374433},{filename:"/media/timeBackground.png",start:3374433,
end:3376750}],remote_package_size:3376750})})();var ba=[],ca="./this.program",da="",ea;"undefined"!=typeof document&&document.currentScript&&(da=document.currentScript.src);da=da.startsWith("blob:")?"":da.slice(0,da.replace(/[?#].*/,"").lastIndexOf("/")+1);ea=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var fa=console.log.bind(console),l=console.error.bind(console),ha,ia,ja=!1,la,m,q,ma,na,r,t,w,oa,x,pa=0,qa=null;
function ra(){pa++;h.monitorRunDependencies?.(pa)}function sa(){pa--;h.monitorRunDependencies?.(pa);if(0==pa&&qa){var a=qa;qa=null;a()}}function ta(a){h.onAbort?.(a);a="Aborted("+a+")";l(a);ja=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ua;async function va(a){if(!ha)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==ua&&ha)a=new Uint8Array(ha);else throw"both async and sync fetching of the wasm failed";return a}
async function wa(a,b){try{var c=await va(a);return await WebAssembly.instantiate(c,b)}catch(d){l(`failed to asynchronously prepare wasm: ${d}`),ta(d)}}async function ya(a){var b=ua;if(!ha&&"function"==typeof WebAssembly.instantiateStreaming)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){l(`wasm streaming compile failed: ${d}`),l("falling back to ArrayBuffer instantiation")}return wa(b,a)}
class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var Aa=a=>{for(;0<a.length;)a.shift()(h)},Ba=[],Ca=[],Da=()=>{var a=h.preRun.shift();Ca.push(a)},Ga=!0;
function Ha(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":ma[a>>1]=b;break;case "i32":r[a>>2]=b;break;case "i64":oa[a>>3]=BigInt(b);break;case "float":w[a>>2]=b;break;case "double":x[a>>3]=b;break;case "*":t[a>>2]=b;break;default:ta(`invalid type for setValue: ${c}`)}}
var Ja=()=>{var a=r[+Ia>>2];Ia+=4;return a},Ka=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},La=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ma=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,
-1);return a+b},Na=()=>a=>crypto.getRandomValues(a),Oa=a=>{(Oa=Na())(a)},Pa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ka(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Qa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Qa)return Qa.decode(a.subarray(b,
c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ra=[],Sa=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},A=(a,b,c,d)=>{if(!(0<d))return 0;var e=
c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var k=a.charCodeAt(++f);g=65536+((g&1023)<<10)|k&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e},Ta=(a,b)=>{var c=Array(Sa(a)+1);a=A(a,c,0,c.length);b&&(c.length=a);return c},Ua=[];
function Va(a,b){Ua[a]={input:[],output:[],xf:b};Wa(a,Xa)}
var Xa={open(a){var b=Ua[a.node.If];if(!b)throw new C(43);a.bf=b;a.seekable=!1},close(a){a.bf.xf.Qf(a.bf)},Qf(a){a.bf.xf.Qf(a.bf)},read(a,b,c,d){if(!a.bf||!a.bf.xf.Ag)throw new C(60);for(var e=0,f=0;f<d;f++){try{var g=a.bf.xf.Ag(a.bf)}catch(k){throw new C(29);}if(void 0===g&&0===e)throw new C(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.zf=Date.now());return e},write(a,b,c,d){if(!a.bf||!a.bf.xf.lg)throw new C(60);try{for(var e=0;e<d;e++)a.bf.xf.lg(a.bf,b[c+e])}catch(f){throw new C(29);
}d&&(a.node.jf=a.node.hf=Date.now());return e}},Ya={Ag(){a:{if(!Ra.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ra=Ta(a,!0)}a=Ra.shift()}return a},lg(a,b){null===b||10===b?(fa(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},Qf(a){0<a.output?.length&&(fa(z(a.output)),a.output=[])},ih(){return{zh:25856,Bh:5,yh:191,Ah:35387,xh:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0]}},jh(){return 0},kh(){return[24,80]}},Za={lg(a,b){null===b||10===b?(l(z(a.output)),a.output=[]):0!=b&&a.output.push(b)},Qf(a){0<a.output?.length&&(l(z(a.output)),a.output=[])}},ab=a=>{a=65536*Math.ceil(a/65536);var b=$a(65536,a);b&&q.fill(0,b,b+a);return b},D={tf:null,wf(){return D.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new C(63);D.tf||(D.tf={dir:{node:{nf:D.af.nf,uf:D.af.uf,Ff:D.af.Ff,Vf:D.af.Vf,Jg:D.af.Jg,Zf:D.af.Zf,Kg:D.af.Kg,mg:D.af.mg,
Yf:D.af.Yf},stream:{sf:D.Zd.sf}},file:{node:{nf:D.af.nf,uf:D.af.uf},stream:{sf:D.Zd.sf,read:D.Zd.read,write:D.Zd.write,Gf:D.Zd.Gf,Xf:D.Zd.Xf}},link:{node:{nf:D.af.nf,uf:D.af.uf,Jf:D.af.Jf},stream:{}},xg:{node:{nf:D.af.nf,uf:D.af.uf},stream:bb}});c=cb(a,b,c,d);E(c.mode)?(c.af=D.tf.dir.node,c.Zd=D.tf.dir.stream,c.$e={}):32768===(c.mode&61440)?(c.af=D.tf.file.node,c.Zd=D.tf.file.stream,c.df=0,c.$e=null):40960===(c.mode&61440)?(c.af=D.tf.link.node,c.Zd=D.tf.link.stream):8192===(c.mode&61440)&&(c.af=D.tf.xg.node,
c.Zd=D.tf.xg.stream);c.zf=c.jf=c.hf=Date.now();a&&(a.$e[b]=c,a.zf=a.jf=a.hf=c.zf);return c},Lh(a){return a.$e?a.$e.subarray?a.$e.subarray(0,a.df):new Uint8Array(a.$e):new Uint8Array(0)},af:{nf(a){var b={};b.Xg=8192===(a.mode&61440)?a.id:1;b.gh=a.id;b.mode=a.mode;b.nh=1;b.uid=0;b.bh=0;b.If=a.If;E(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.df:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.zf=new Date(a.zf);b.jf=new Date(a.jf);b.hf=new Date(a.hf);b.Og=4096;b.Pg=Math.ceil(b.size/b.Og);
return b},uf(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.df!=b&&(0==b?(a.$e=null,a.df=0):(c=a.$e,a.$e=new Uint8Array(b),c&&a.$e.set(c.subarray(0,Math.min(b,a.df))),a.df=b)))},Ff(){throw D.yg;},Vf(a,b,c,d){return D.createNode(a,b,c,d)},Jg(a,b,c){try{var d=db(b,c)}catch(f){}if(d){if(E(a.mode))for(var e in d.$e)throw new C(55);eb(d)}delete a.parent.$e[a.name];b.$e[c]=a;a.name=c;b.hf=b.jf=a.parent.hf=a.parent.jf=Date.now()},Zf(a,b){delete a.$e[b];
a.hf=a.jf=Date.now()},Kg(a,b){var c=db(a,b),d;for(d in c.$e)throw new C(55);delete a.$e[b];a.hf=a.jf=Date.now()},mg(a){return[".","..",...Object.keys(a.$e)]},Yf(a,b,c){a=D.createNode(a,b,41471,0);a.link=c;return a},Jf(a){if(40960!==(a.mode&61440))throw new C(28);return a.link}},Zd:{read(a,b,c,d,e){var f=a.node.$e;if(e>=a.node.df)return 0;a=Math.min(a.node.df-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.jf=
a.hf=Date.now();if(b.subarray&&(!a.$e||a.$e.subarray)){if(f)return a.$e=b.subarray(c,c+d),a.df=d;if(0===a.df&&0===e)return a.$e=b.slice(c,c+d),a.df=d;if(e+d<=a.df)return a.$e.set(b.subarray(c,c+d),e),d}f=e+d;var g=a.$e?a.$e.length:0;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),0!=g&&(f=Math.max(f,256)),g=a.$e,a.$e=new Uint8Array(f),0<a.df&&a.$e.set(g.subarray(0,a.df),0));if(a.$e.subarray&&b.subarray)a.$e.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.$e[e+f]=b[c+f];a.df=Math.max(a.df,e+d);return d},
sf(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.df);if(0>b)throw new C(28);return b},Gf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new C(43);a=a.node.$e;if(e&2||!a||a.buffer!==m.buffer){d=!0;e=ab(b);if(!e)throw new C(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);m.set(a,e)}}else d=!1,e=a.byteOffset;return{Ig:e,ug:d}},Xf(a,b,c,d){D.Zd.write(a,b,0,d,c,!1);return 0}}},fb=async a=>{a=await ea(a);return new Uint8Array(a)},
gb=[],jb=(a,b,c,d)=>{"undefined"!=typeof hb&&ib();var e=!1;gb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},lb=(a,b,c,d,e,f,g,k,n,p)=>{function u(B){function F(H){p?.();k||kb(a,b,H,d,e,n);f?.();sa(y)}jb(B,v,F,()=>{g?.();sa(y)})||F(B)}var v=b?Pa(La(a+"/"+b)):a,y=`cp ${v}`;ra(y);"string"==typeof c?fb(c).then(u,g):u(c)},mb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},nb=null,ob={},pb=[],qb=1,rb=null,sb=!1,tb=!0,ub={},C=class{name="ErrnoError";constructor(a){this.ef=a}},vb=
class{gf={};node=null;get flags(){return this.gf.flags}set flags(a){this.gf.flags=a}get position(){return this.gf.position}set position(a){this.gf.position=a}},wb=class{af={};Zd={};Hf=null;constructor(a,b,c,d){a||=this;this.parent=a;this.wf=a.wf;this.id=qb++;this.name=b;this.mode=c;this.If=d;this.zf=this.jf=this.hf=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get lh(){return E(this.mode)}get Cg(){return 8192===
(this.mode&61440)}};
function xb(a,b={}){if(!a)throw new C(44);b.dg??(b.dg=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=nb,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=Ma(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");continue a}else d=d.parent;else{e=La(e+"/"+a[f]);try{d=db(d,a[f])}catch(k){if(44===k?.ef&&g&&b.oh)return{path:e};throw k;}!d.Hf||g&&!b.dg||(d=d.Hf.root);if(40960===(d.mode&61440)&&(!g||b.Pf)){if(!d.af.Jf)throw new C(52);
d=d.af.Jf(d);"/"===d.charAt(0)||(d=Ma(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new C(32);}function yb(a){for(var b;;){if(a===a.parent)return a=a.wf.Fg,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function zb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%rb.length}
function eb(a){var b=zb(a.parent.id,a.name);if(rb[b]===a)rb[b]=a.Df;else for(b=rb[b];b;){if(b.Df===a){b.Df=a.Df;break}b=b.Df}}function db(a,b){var c=E(a.mode)?(c=Ab(a,"x"))?c:a.af.Ff?0:2:54;if(c)throw new C(c);for(c=rb[zb(a.id,b)];c;c=c.Df){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.af.Ff(a,b)}function cb(a,b,c,d){a=new wb(a,b,c,d);b=zb(a.parent.id,a.name);a.Df=rb[b];return rb[b]=a}function E(a){return 16384===(a&61440)}
function Bb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Ab(a,b){if(tb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Cb(a,b){if(!E(a.mode))return 54;try{return db(a,b),20}catch(c){}return Ab(a,"wx")}function Db(a){if(!a)throw new C(63);return a}function G(a){a=pb[a];if(!a)throw new C(8);return a}
function Eb(a,b=-1){a=Object.assign(new vb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!pb[b])break a;throw new C(33);}a.fd=b;return pb[b]=a}function Hb(a,b=-1){a=Eb(a,b);a.Zd?.Hh?.(a);return a}function Ib(a,b){var c=null?.Zd.uf,d=c?null:a;c??=a.af.uf;Db(c);c(d,b)}var bb={open(a){a.Zd=ob[a.node.If].Zd;a.Zd.open?.(a)},sf(){throw new C(70);}};function Wa(a,b){ob[a]={Zd:b}}
function Jb(a,b){var c="/"===b;if(c&&nb)throw new C(10);if(!c&&b){var d=xb(b,{dg:!1});b=d.path;d=d.node;if(d.Hf)throw new C(10);if(!E(d.mode))throw new C(54);}b={type:a,Qh:{},Fg:b,mh:[]};a=a.wf(b);a.wf=b;b.root=a;c?nb=a:d&&(d.Hf=b,d.wf&&d.wf.mh.push(b))}function Kb(a,b,c){var d=xb(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new C(28);if("."===a||".."===a)throw new C(20);var e=Cb(d,a);if(e)throw new C(e);if(!d.af.Vf)throw new C(63);return d.af.Vf(d,a,b,c)}
function Lb(a,b=438){return Kb(a,b&4095|32768,0)}function I(a,b=511){return Kb(a,b&1023|16384,0)}function Mb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Kb(a,b|8192,c)}function Nb(a,b){if(!Pa(a))throw new C(44);var c=xb(b,{parent:!0}).node;if(!c)throw new C(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Cb(c,b);if(d)throw new C(d);if(!c.af.Yf)throw new C(63);c.af.Yf(c,b,a)}
function Ob(a){var b=xb(a,{parent:!0}).node;if(!b)throw new C(44);a=a&&a.match(/([^\/]+|\/)\/*$/)[1];var c=db(b,a);a:{try{var d=db(b,a)}catch(f){d=f.ef;break a}var e=Ab(b,"wx");d=e?e:E(d.mode)?31:0}if(d)throw new C(d);if(!b.af.Zf)throw new C(63);if(c.Hf)throw new C(10);b.af.Zf(b,a);eb(c)}function Pb(a,b){a=xb(a,{Pf:!b}).node;return Db(a.af.nf)(a)}function Qb(a,b){a="string"==typeof a?xb(a,{Pf:!0}).node:a;Ib(a,{mode:b&4095|a.mode&-4096,hf:Date.now(),Gh:void 0})}
function Rb(a,b,c=438){if(""===a)throw new C(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=xb(a,{Pf:!(b&131072),oh:!0});d=a.node;a=a.path}var f=!1;if(b&64)if(d){if(b&128)throw new C(20);}else{if(e)throw new C(31);d=Kb(a,c|511,0);f=!0}if(!d)throw new C(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&!E(d.mode))throw new C(54);
if(!f&&(e=d?40960===(d.mode&61440)?32:E(d.mode)&&("r"!==Bb(b)||b&576)?31:Ab(d,Bb(b)):44))throw new C(e);if(b&512&&!f){e=d;e="string"==typeof e?xb(e,{Pf:!0}).node:e;if(E(e.mode))throw new C(31);if(32768!==(e.mode&61440))throw new C(28);var g=Ab(e,"w");if(g)throw new C(g);Ib(e,{size:0,timestamp:Date.now()})}b&=-131713;e=Eb({node:d,path:yb(d),flags:b,seekable:!0,position:0,Zd:d.Zd,sh:[],error:!1});e.Zd.open&&e.Zd.open(e);f&&Qb(d,c&511);!h.logReadFiles||b&1||a in ub||(ub[a]=1);return e}
function Sb(a){if(null===a.fd)throw new C(8);a.gg&&(a.gg=null);try{a.Zd.close&&a.Zd.close(a)}catch(b){throw b;}finally{pb[a.fd]=null}a.fd=null}function Tb(a,b,c){if(null===a.fd)throw new C(8);if(!a.seekable||!a.Zd.sf)throw new C(70);if(0!=c&&1!=c&&2!=c)throw new C(28);a.position=a.Zd.sf(a,b,c);a.sh=[]}
function Ub(a,b,c,d,e,f){if(0>d||0>e)throw new C(28);if(null===a.fd)throw new C(8);if(0===(a.flags&2097155))throw new C(8);if(E(a.node.mode))throw new C(31);if(!a.Zd.write)throw new C(28);a.seekable&&a.flags&1024&&Tb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new C(70);b=a.Zd.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Vb(a,b){a="string"==typeof a?a:yb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=La(a+"/"+c);try{I(d)}catch(e){if(20!=e.ef)throw e;}a=d}}return d}function Wb(a,b,c,d){a=La(("string"==typeof a?a:yb(a))+"/"+b);return Lb(a,mb(c,d))}
function kb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:yb(a),g=b?La(a+"/"+b):a);a=mb(d,e);g=Lb(g,a);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Qb(g,a|146);b=Rb(g,577);Ub(b,c,0,c.length,0,f);Sb(b);Qb(g,a)}}
function Xb(a,b,c,d){a=La(("string"==typeof a?a:yb(a))+"/"+b);b=mb(!!c,!!d);Xb.Dg??(Xb.Dg=64);var e=Xb.Dg++<<8|0;Wa(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,n){for(var p=0,u=0;u<n;u++){try{var v=c()}catch(y){throw new C(29);}if(void 0===v&&0===p)throw new C(6);if(null===v||void 0===v)break;p++;g[k+u]=v}p&&(f.node.zf=Date.now());return p},write(f,g,k,n){for(var p=0;p<n;p++)try{d(g[k+p])}catch(u){throw new C(29);}n&&(f.node.jf=f.node.hf=Date.now());return p}});return Mb(a,
b,e)}function Yb(a){if(!(a.Cg||a.lh||a.link||a.$e)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");try{a.$e=(void 0)(a.url),a.df=a.$e.length}catch(b){throw new C(29);}}}
function Zb(a,b,c,d,e){function f(n,p,u,v,y){n=n.node.$e;if(y>=n.length)return 0;v=Math.min(n.length-y,v);if(n.slice)for(var B=0;B<v;B++)p[u+B]=n[y+B];else for(B=0;B<v;B++)p[u+B]=n.get(y+B);return v}if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Cg:!1,url:c};var g=Wb(a,b,d,e);c.$e?g.$e=c.$e:c.url&&(g.$e=null,g.url=c.url);Object.defineProperties(g,{df:{get:function(){return this.$e.length}}});
var k={};Object.keys(g.Zd).forEach(n=>{var p=g.Zd[n];k[n]=(...u)=>{Yb(g);return p(...u)}});k.read=(n,p,u,v,y)=>{Yb(g);return f(n,p,u,v,y)};k.Gf=(n,p,u)=>{Yb(g);var v=ab(p);if(!v)throw new C(48);f(n,m,v,p,u);return{Ig:v,ug:!0}};g.Zd=k;return g}var J={};function $b(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":G(a).path;if(0==b.length){if(!c)throw new C(44);return a}return a+"/"+b}
function ac(a,b){r[a>>2]=b.Xg;r[a+4>>2]=b.mode;t[a+8>>2]=b.nh;r[a+12>>2]=b.uid;r[a+16>>2]=b.bh;r[a+20>>2]=b.If;oa[a+24>>3]=BigInt(b.size);r[a+32>>2]=4096;r[a+36>>2]=b.Pg;var c=b.zf.getTime(),d=b.jf.getTime(),e=b.hf.getTime();oa[a+40>>3]=BigInt(Math.floor(c/1E3));t[a+48>>2]=c%1E3*1E6;oa[a+56>>3]=BigInt(Math.floor(d/1E3));t[a+64>>2]=d%1E3*1E6;oa[a+72>>3]=BigInt(Math.floor(e/1E3));t[a+80>>2]=e%1E3*1E6;oa[a+88>>3]=BigInt(b.gh);return 0}
var Ia=void 0,bc=0,cc={},dc=a=>{if(!(a instanceof za||"unwind"==a))throw a;},ec=a=>{la=a;Ga||0<bc||(h.onExit?.(a),ja=!0);throw new za(a);},fc=a=>{la=a;ec(a)},gc=()=>{if(!(Ga||0<bc))try{var a=la;la=a;ec(a)}catch(b){dc(b)}},hc=a=>{if(!ja)try{a(),gc()}catch(b){dc(b)}},ic=(a,b)=>setTimeout(()=>{hc(a)},b),jc=!1,kc=!1,lc=[],mc={};
function ib(){function a(){var c=h.canvas;kc=document.pointerLockElement===c||document.mozPointerLockElement===c||document.webkitPointerLockElement===c||document.msPointerLockElement===c}if(!nc){nc=!0;gb.push({canHandle:function(c){return!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:oc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:oc(d)}));var k=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=document.createElement("canvas");
p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);mc[d]=p;URL.revokeObjectURL(k);e?.(c)};n.onerror=()=>{l(`Image ${k} could not be decoded`);f?.()};n.src=k}});gb.push({canHandle:function(c){return!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,k=URL.createObjectURL(new Blob([c],{type:oc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){l(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",u=0,v=0,y=0;y<c.length;y++)for(u=u<<8|c[y],v+=8;6<=v;){var B=u>>v-6&63;v-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==v?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],p+="=="):4==v&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],p+="=");n.src="data:audio/x-"+d.slice(-3)+";base64,"+p;f(n)}};n.src=k;ic(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!kc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var pc=!1,qc=void 0,rc=void 0;function sc(){if(!jc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}
function oc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var tc=[];function uc(){var a=h.canvas;tc.forEach(b=>b(a.width,a.height))}
function vc(a,b,c){b&&c?(a.uh=b,a.dh=c):(b=a.uh,c=a.dh);var d=b,e=c;0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*f)}rc?(a.width!=d&&(a.width=
d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var hb={},nc,K=12288,wc=!1,xc=0,zc=0,Ac=0,L={alpha:!1,depth:!1,stencil:!1,antialias:!1},Bc={},Cc,M,Dc=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},Ec=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},Fc=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},Gc=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},Hc=1,Ic=[],N=[],Jc=[],Kc=[],Lc=[],O=[],Mc=[],Nc=[],Oc=[],Pc={},Qc=4,Rc=0,Sc=a=>{for(var b=Hc++,c=a.length;c<b;c++)a[c]=null;return b},Tc=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=M[c](),g=f&&Sc(d);f?(f.name=g,d[g]=f):P||=1282;r[b+4*e>>2]=g}},Vc=(a,b)=>{a.gf||(a.gf=a.getContext,a.getContext=function(d,e){e=a.gf(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Uc(c,b):0},Uc=(a,b)=>
{var c=Sc(Nc),d={handle:c,attributes:b,version:b.Eg,yf:a};a.canvas&&(a.canvas.Ef=d);Nc[c]=d;("undefined"==typeof b.Yg||b.Yg)&&Wc(d);return c},Yc=a=>{Xc=Nc[a];h.ctx=M=Xc?.yf},Wc=a=>{a||=Xc;if(!a.fh){a.fh=!0;var b=a.yf;b.Ph=b.getExtension("WEBGL_multi_draw");b.$g=b.getExtension("EXT_polygon_offset_clamp");b.Zg=b.getExtension("EXT_clip_control");b.th=b.getExtension("WEBGL_polygon_mode");Dc(b);Ec(b);Fc(b);b.vf=b.getExtension("EXT_disjoint_timer_query");Gc(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||
b.getExtension(c)})}},Zc={},P,Xc,$c=a=>{var b=Sa(a)+1,c=Q(b);c&&A(a,q,c,b);return c},rd=(a,b,c,d,e)=>{function f(){return g<ad?(gc(),!1):!0}bd=a;cd=d;var g=ad;dd=!1;ed=function(){if(!ja)if(0<fd.length){var k=fd.shift();k.Kh(k.vh);if(gd){var n=gd,p=0==n%1?n-1:Math.floor(n);gd=k.Dh?p:(8*n+(p+.5))/9}h.setStatus&&(k=h.statusMessage||"Please wait...",n=gd??0,p=hd.Ih??0,n?n<p?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(k):h.setStatus(""));f()&&setTimeout(ed,0)}else if(f())if(jd=
jd+1|0,1==kd&&1<ld&&0!=jd%ld)md();else{0==kd&&(nd=performance.now());a:if(!ja){for(k of od)if(!1===k())break a;hc(a);for(n of pd)n()}f()&&md()}};e||(0<b?qd(0,1E3/b):qd(1,1),md());if(c)throw"unwind";},dd=!1,md=null,ad=0,bd=null,cd=0,kd=0,ld=0,jd=0,fd=[],od=[],pd=[];function sd(){md=null;ad++}function td(){ad++;var a=kd,b=ld,c=bd;bd=null;rd(c,0,!1,cd,!0);qd(a,b);md()}var ud=0;
function vd(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ud)ud=b+1E3/60;else for(;b+2>=ud;)ud+=1E3/60;setTimeout(a,Math.max(ud-b,0))}}
var hd={},ed,gd,nd,wd,qd=(a,b)=>{kd=a;ld=b;if(bd)if(dd||=!0,0==a)md=function(){setTimeout(ed,Math.max(0,nd+b-performance.now())|0)};else if(1==a)md=function(){vd(ed)};else if(2==a){if("undefined"==typeof wd)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);wd=d=>{c.push(d);postMessage("setimmediate","*")}}else wd=setImmediate;md=function(){wd(ed)}}},xd=[],yd=(a,b)=>{xd.length=
0;for(var c;c=q[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;xd.push(112==c?t[b>>2]:106==c?oa[b>>3]:105==c?r[b>>2]:x[b>>3]);b+=d?8:4}return xd};function zd(a){var b=R.mf[a];b.target.removeEventListener(b.ff,b.zg,b.kf);R.mf.splice(a,1)}function Ad(a,b,c){function d(f,g){if(f.length!=g.length)return!1;for(var k in f)if(f[k]!=g[k])return!1;return!0}for(var e of R.Af)if(e.og==a&&d(e.vg,c))return;R.Af.push({og:a,Hg:b,vg:c});R.Af.sort((f,g)=>f.Hg<g.Hg)}function Bd(a){R.Af=R.Af.filter(b=>b.og!=a)}
function Cd(){return navigator.userActivation?navigator.userActivation.isActive:R.hg&&R.Rg.Lf}function Dd(){if(Cd()){var a=R.Af;R.Af=[];for(var b of a)b.og(...b.vg)}}function Ed(a){if(!a.target)return-4;if(a.lf)a.zg=function(c){++R.hg;R.Rg=a;Dd();a.pf(c);Dd();--R.hg},a.target.addEventListener(a.ff,a.zg,a.kf),R.mf.push(a);else for(var b=0;b<R.mf.length;++b)R.mf[b].target==a.target&&R.mf[b].ff==a.ff&&zd(b--);return 0}
function Fd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var R={wh:0,fg:0,ig:0,Wf:0,tg:0,qg:0,cg:0,Fh:0,Rh:0,Eh:0,eg:0,kg:0,sg:0,pg:0,Nh(a,b,c){m.set(m.subarray(b,b+c),a)},Sh(){for(;R.mf.length;)zd(R.mf.length-1);R.Af=[]},hg:0,Af:[],mf:[],qh:(a,b)=>{for(var c=0;c<R.mf.length;++c)R.mf[c].target!=a||b&&b!=R.mf[c].ff||zd(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},Gd=[0,document,window],S=a=>{a=2<a?a?z(q,a):"":a;return Gd[a]||document.querySelector(a)},Id=a=>{var b=Sa(a)+1,c=Hd(b);A(a,q,c,b);return c},Jd=
a=>{var b=T(),c=Hd(8),d=c+4;a=Id(a.id);if(a=S(a))r[c>>2]=a.width,r[d>>2]=a.height;c=[r[c>>2],r[d>>2]];U(b);return c},Kd=(a,b,c)=>{a=S(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ld=(a,b,c)=>{if(a.Ch){var d=T();a=Id(a.id);Kd(a,b,c);U(d)}else a.width=b,a.height=c},Md={},Nd=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Ld(a,d,e),a.style.width=f,a.style.height=
g,a.style.backgroundColor=k,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=u,a.style.paddingTop=v,a.style.paddingBottom=y,a.style.marginLeft=B,a.style.marginRight=F,a.style.marginTop=H,a.style.marginBottom=W,document.body.style.margin=xa,document.documentElement.style.overflow=ka,document.body.scroll=Fb,a.style.Bf=V,a.Ef&&a.Ef.yf.viewport(0,0,d,e),Md.Mf&&X(Md.Mf,37,0,Md.wg))}var c=Jd(a),d=c[0],e=c[1],f=a.style.width,
g=a.style.height,k=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,u=a.style.paddingRight,v=a.style.paddingTop,y=a.style.paddingBottom,B=a.style.marginLeft,F=a.style.marginRight,H=a.style.marginTop,W=a.style.marginBottom,xa=document.body.style.margin,ka=document.documentElement.style.overflow,Fb=document.body.scroll,V=a.style.Bf;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},Od=(a,b,c)=>{a.style.paddingLeft=
a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},Pd=a=>0>Gd.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},Qd=(a,b)=>{if(0!=b.ng||0!=b.ag){Nd(a);var c=b.rh?innerWidth:screen.width,d=b.rh?innerHeight:screen.height,e=Pd(a),f=e.width;e=e.height;var g=Jd(a),k=g[0];g=g[1];3==b.ng?(Od(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.ng&&(c*g<k*d?(f=g*c/k,Od(a,(d-f)/2,0),d=f):(f=k*d/g,Od(a,0,(c-f)/2),c=f));var n;(n=a.style).backgroundColor||(n.backgroundColor="black");let p;(p=document.body.style).backgroundColor||
(p.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.ah&&(a.style.Bf="optimizeSpeed",a.style.Bf="-moz-crisp-edges",a.style.Bf="-o-crisp-edges",a.style.Bf="-webkit-optimize-contrast",a.style.Bf="optimize-contrast",a.style.Bf="crisp-edges",a.style.Bf="pixelated");n=2==b.ag?devicePixelRatio:1;0!=b.ag&&(c=c*n|0,d=d*n|0,Ld(a,c,d),a.Ef&&a.Ef.yf.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);
else return R.fullscreenEnabled()?-3:-1;Md=b;b.Mf&&X(b.Mf,37,0,b.wg);return 0},Rd=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},Sd=(a,b)=>{x[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)x[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)x[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)m[a+c+1040]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];
m[a+1104]=b.connected;r[a+1108>>2]=b.index;r[a+8>>2]=b.axes.length;r[a+12>>2]=b.buttons.length;A(b.id,q,a+1112,64);A(b.mapping,q,a+1176,64)},Td=(a,b,c)=>{a=Pa(a);a=mc[a];if(!a)return 0;var d=a.getContext("2d").getImageData(0,0,a.width,a.height),e=Q(a.width*a.height*4);q.set(d.data,e);r[b>>2]=a.width;r[c>>2]=a.height;return e},Ud=[],Vd=(a,b,c,d,e,f,g,k)=>{b=N[b];if(a=M[a](b,c))d=k&&A(a.name,q,k,d),e&&(r[e>>2]=d),f&&(r[f>>2]=a.size),g&&(r[g>>2]=a.type)},Wd=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=
1;break;case 36344:0!=c&&1!=c&&(P||=1280);return;case 36345:d=0;break;case 34466:var e=M.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=M.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":P||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:P||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||
e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:r[b+4*a>>2]=e[a];break;case 2:w[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:P||=1280;l(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;t[b>>2]=c;t[b+4>>2]=(c-t[b>>2])/4294967296;break;
case 0:r[b>>2]=d;break;case 2:w[b>>2]=d;break;case 4:m[b]=d?1:0}}else P||=1281},Xd=(a,b,c)=>{if(c){a=M.vf.getQueryObjectEXT(Oc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;t[c>>2]=d;t[c+4>>2]=(d-t[c>>2])/4294967296}else P||=1281},Yd=(a,b,c)=>{if(c){a=M.vf.getQueryObjectEXT(Oc[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;r[c>>2]=d}else P||=1281},Zd=()=>{var a=Gc(M);return a=a.concat(a.map(b=>"GL_"+b))},$d=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ae=a=>{var b=a.Kf,c=a.Mg,d;if(!b){a.Kf=b={};a.Lg={};var e=
M.getProgramParameter(a,35718);for(d=0;d<e;++d){var f=M.getActiveUniform(a,d);var g=f.name;f=f.size;var k=$d(g);k=0<k?g.slice(0,k):g;var n=a.rg;a.rg+=f;c[k]=[f,n];for(g=0;g<f;++g)b[n]=g,a.Lg[n++]=k}}},Y=a=>{var b=M.Sg;if(b){var c=b.Kf[a];"number"==typeof c&&(b.Kf[a]=c=M.getUniformLocation(b,b.Lg[a]+(0<c?`[${c}]`:"")));return c}P||=1282},be=(a,b,c,d)=>{if(c)if(a=N[a],ae(a),a=M.getUniform(a,Y(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:w[c>>2]=a}else for(b=0;b<
a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b]}else P||=1281},ce=(a,b,c,d)=>{if(c)if(a=M.getVertexAttrib(a,b),34975==b)r[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:r[c>>2]=a;break;case 2:w[c>>2]=a;break;case 5:r[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:r[c+4*b>>2]=a[b];break;case 2:w[c+4*b>>2]=a[b];break;case 5:r[c+4*b>>2]=Math.fround(a[b])}else P||=1281},de=(a,b,c,d,e)=>{a-=5120;a=1==a?q:4==a?r:6==a?w:5==
a||28922==a?t:na;b=d*((Rc||c)*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+Qc-1&-Qc);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ee=[],fe=[],ge=(a,b)=>{if(!R.fullscreenEnabled())return-1;a=S(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Cd()?Qd(a,b):b.Wg?(Ad(Qd,1,[a,b]),1):-2:-3:-4},he=()=>{try{if(navigator.getGamepads)return(R.Rf=navigator.getGamepads())?0:-1}catch(a){navigator.getGamepads=null}return-1},ie=(a,
b)=>{var c={target:S(2),ff:"beforeunload",lf:b,pf:(d=event)=>{var e=X(b,28,0,a);e&&=e?z(q,e):"";if(e)return d.preventDefault(),d.returnValue=e},kf:!0};return Ed(c)},je=(a,b,c,d,e,f)=>{R.cg||(R.cg=Q(256));a={target:S(a),ff:f,lf:d,pf:(g=event)=>{var k=g.target.id?g.target.id:"",n=R.cg;A(Fd(g.target),q,n+0,128);A(k,q,n+128,128);X(d,e,n,b)&&g.preventDefault()},kf:c};return Ed(a)},ke=(a,b,c,d,e)=>{R.eg||(R.eg=Q(276));return Ed({target:a,ff:e,lf:d,pf:(f=event)=>{var g=R.eg,k=document.fullscreenElement||
document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!k;m[g]=n;m[g+1]=R.fullscreenEnabled();var p=n?k:R.ph,u=p?.id||"";A(Fd(p),q,g+2,128);A(u,q,g+130,128);r[g+260>>2]=p?p.clientWidth:0;r[g+264>>2]=p?p.clientHeight:0;r[g+268>>2]=screen.width;r[g+272>>2]=screen.height;n&&(R.ph=k);X(d,19,g,b)&&f.preventDefault()},kf:c})},le=(a,b,c,d,e)=>{R.fg||(R.fg=Q(1240));b={target:S(2),Lf:!0,ff:e,lf:c,pf:(f=event)=>{var g=R.fg;Sd(g,f.gamepad);X(c,d,g,a)&&f.preventDefault()},
kf:b};return Ed(b)},me=(a,b,c,d,e,f)=>{R.ig||(R.ig=Q(160));a={target:S(a),ff:f,lf:d,pf:g=>{var k=R.ig;x[k>>3]=g.timeStamp;var n=k>>2;r[n+2]=g.location;m[k+12]=g.ctrlKey;m[k+13]=g.shiftKey;m[k+14]=g.altKey;m[k+15]=g.metaKey;m[k+16]=g.repeat;r[n+5]=g.charCode;r[n+6]=g.keyCode;r[n+7]=g.which;A(g.key||"",q,k+32,32);A(g.code||"",q,k+64,32);A(g.char||"",q,k+96,32);A(g.locale||"",q,k+128,32);X(d,e,k,b)&&g.preventDefault()},kf:c};return Ed(a)},ne=(a,b,c)=>{x[a>>3]=b.timeStamp;var d=a>>2;r[d+2]=b.screenX;
r[d+3]=b.screenY;r[d+4]=b.clientX;r[d+5]=b.clientY;m[a+24]=b.ctrlKey;m[a+25]=b.shiftKey;m[a+26]=b.altKey;m[a+27]=b.metaKey;ma[2*d+14]=b.button;ma[2*d+15]=b.buttons;r[d+8]=b.movementX;r[d+9]=b.movementY;a=Pd(c);r[d+10]=b.clientX-(a.left|0);r[d+11]=b.clientY-(a.top|0)},oe=(a,b,c,d,e,f)=>{R.Wf||(R.Wf=Q(64));a=S(a);return Ed({target:a,Lf:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,ff:f,lf:d,pf:(g=event)=>{ne(R.Wf,g,a);X(d,e,R.Wf,b)&&g.preventDefault()},kf:c})},pe=(a,b,c,d,e)=>{R.kg||(R.kg=Q(257));
return Ed({target:a,ff:e,lf:d,pf:(f=event)=>{var g=R.kg,k=document.pointerLockElement||document.gf||document.Ng||document.$f;m[g]=!!k;var n=k?.id||"";A(Fd(k),q,g+1,128);A(n,q,g+129,128);X(d,20,g,b)&&f.preventDefault()},kf:c})},qe=(a,b,c,d)=>{R.qg||(R.qg=Q(36));a=S(a);return Ed({target:a,ff:"resize",lf:d,pf:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=R.qg;r[g>>2]=0;r[g+4>>2]=f.clientWidth;r[g+8>>2]=f.clientHeight;r[g+12>>2]=innerWidth;r[g+16>>2]=innerHeight;r[g+20>>2]=outerWidth;r[g+
24>>2]=outerHeight;r[g+28>>2]=pageXOffset|0;r[g+32>>2]=pageYOffset|0;X(d,10,g,b)&&e.preventDefault()}}},kf:c})},re=(a,b,c,d,e,f)=>{R.pg||(R.pg=Q(1552));a=S(a);return Ed({target:a,Lf:"touchstart"==f||"touchend"==f,ff:f,lf:d,pf:g=>{var k={},n=g.touches;for(var p of n)p.Bg=p.Gg=0,k[p.identifier]=p;for(var u of g.changedTouches)u.Bg=1,k[u.identifier]=u;for(var v of g.targetTouches)k[v.identifier].Gg=1;n=R.pg;x[n>>3]=g.timeStamp;m[n+12]=g.ctrlKey;m[n+13]=g.shiftKey;m[n+14]=g.altKey;m[n+15]=g.metaKey;p=
n+16;u=Pd(a);v=0;for(let y of Object.values(k))if(k=p>>2,r[k]=y.identifier,r[k+1]=y.screenX,r[k+2]=y.screenY,r[k+3]=y.clientX,r[k+4]=y.clientY,r[k+5]=y.pageX,r[k+6]=y.pageY,m[p+28]=y.Bg,m[p+29]=y.Gg,r[k+8]=y.clientX-(u.left|0),r[k+9]=y.clientY-(u.top|0),p+=48,31<++v)break;r[n+8>>2]=v;X(d,e,n,b)&&g.preventDefault()},kf:c})},te=(a,b,c)=>{var d=Gd[1];R.sg||(R.sg=Q(8));return Ed({target:d,ff:"visibilitychange",lf:c,pf:(e=event)=>{var f=R.sg,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);
m[f]=document.hidden;r[f+4>>2]=g;X(c,21,f,a)&&e.preventDefault()},kf:b})},ue=(a,b,c,d)=>{R.tg||(R.tg=Q(96));return Ed({target:a,Lf:!0,ff:"wheel",lf:d,pf:(e=event)=>{var f=R.tg;ne(f,e,a);x[f+64>>3]=e.deltaX;x[f+72>>3]=e.deltaY;x[f+80>>3]=e.deltaZ;r[f+88>>2]=e.deltaMode;X(d,9,f,b)&&e.preventDefault()},kf:c})},ve={},xe=()=>{if(!we){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-",
"_")+".UTF-8",_:ca||"./this.program"},b;for(b in ve)void 0===ve[b]?delete a[b]:a[b]=ve[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);we=c}return we},we,ye=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},ze=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&ye(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Ae=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},Be=a=>{try{a()}catch(b){ta(b)}};
function Ce(){var a=Z,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{De.push(c);try{return d(...e)}finally{ja||(De.pop(),Ee&&1===Fe&&0===De.length&&(Fe=0,Be(Ge),"undefined"!=typeof Fibers&&Fibers.Uh()))}}:d;return b}var Fe=0,Ee=null,He=0,De=[],Ie={},Je={},Ke=0,Le=null,Me=[];function Ne(){var a=Q(4108),b=a+12;t[a>>2]=b;t[a+4>>2]=b+4096;b=De[0];var c=Ie[b];void 0===c&&(c=Ke++,Ie[b]=c,Je[c]=b);r[a+8>>2]=c;return a}
function Oe(a){if(!ja){if(0===Fe){var b=!1,c=!1;a((d=0)=>{if(!ja&&(He=d,b=!0,c)){Fe=2;Be(()=>Pe(Ee));"undefined"!=typeof hd&&bd&&td();d=!1;try{var e=(0,Z[Je[r[Ee+8>>2]]])()}catch(k){e=k,d=!0}var f=!1;if(!Ee){var g=Le;g&&(Le=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Fe=1,Ee=Ne(),"undefined"!=typeof hd&&bd&&sd(),Be(()=>Qe(Ee)))}else 2===Fe?(Fe=0,Be(Re),Se(Ee),Ee=null,Me.forEach(hc)):ta(`invalid state: ${Fe}`);return He}}
var Te=(a,b)=>{b=1==b?Hd(a.length):Q(a.length);a.subarray||a.slice||(a=new Uint8Array(a));q.set(a,b);return b};rb=Array(4096);Jb(D,"/");I("/tmp");I("/home");I("/home/web_user");(function(){I("/dev");Wa(259,{read:()=>0,write:(d,e,f,g)=>g,sf:()=>0});Mb("/dev/null",259);Va(1280,Ya);Va(1536,Za);Mb("/dev/tty",1280);Mb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Oa(a),b=a.byteLength);return a[--b]};Xb("/dev","random",c);Xb("/dev","urandom",c);I("/dev/shm");I("/dev/shm/tmp")})();
(function(){I("/proc");var a=I("/proc/self");I("/proc/self/fd");Jb({wf(){var b=cb(a,"fd",16895,73);b.Zd={sf:D.Zd.sf};b.af={Ff(c,d){c=+d;var e=G(c);c={parent:null,wf:{Fg:"fake"},af:{Jf:()=>e.path},id:c+1};return c.parent=c},mg(){return Array.from(pb.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.FS_createPath=Vb;h.FS_createDataFile=kb;h.FS_createPreloadedFile=lb;h.FS_unlink=Ob;h.FS_createLazyFile=Zb;h.FS_createDevice=Xb;D.yg=new C(44);D.yg.stack="<generic error, no stack>";
h.requestFullscreen=function(a,b){function c(){jc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=sc,qc&&d.requestPointerLock(),jc=!0,rc?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=t[SDL.screen>>2]|8388608),vc(h.canvas),uc()):vc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),rc?("undefined"!=typeof SDL&&(r[SDL.screen>>2]=
t[SDL.screen>>2]&-8388609),vc(h.canvas),uc()):vc(d));h.onFullScreen?.(jc);h.onFullscreen?.(jc)}qc=a;rc=b;"undefined"==typeof qc&&(qc=!0);"undefined"==typeof rc&&(rc=!1);var d=h.canvas;pc||(pc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.setCanvasSize=function(a,b,c){vc(h.canvas,a,b);c||uc()};h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.ctx&&a==h.canvas)return h.ctx;var e;if(b){var f={antialias:!1,alpha:!1,Eg:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof Zc&&(e=Vc(a,f)))var k=Nc[e].yf}else k=a.getContext("2d");if(!k)return null;c&&(h.ctx=k,b&&Yc(e),lc.forEach(n=>n()),ib());return k};h.requestAnimationFrame=vd;h.pauseMainLoop=sd;h.resumeMainLoop=td;h.preMainLoop&&od.push(h.preMainLoop);h.postMainLoop&&pd.push(h.postMainLoop);for(let a=0;32>a;++a)Ud.push(Array(a));
for(var Ue=new Float32Array(288),Ve=0;288>=Ve;++Ve)ee[Ve]=Ue.subarray(0,Ve);var We=new Int32Array(288);for(Ve=0;288>=Ve;++Ve)fe[Ve]=We.subarray(0,Ve);h.noExitRuntime&&(Ga=h.noExitRuntime);h.preloadPlugins&&(gb=h.preloadPlugins);h.print&&(fa=h.print);h.printErr&&(l=h.printErr);h.wasmBinary&&(ha=h.wasmBinary);h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.addRunDependency=ra;h.removeRunDependency=sa;h.FS_createPreloadedFile=lb;h.FS_unlink=a=>Ob(a);h.FS_createPath=Vb;
h.FS_createDevice=Xb;h.FS_createDataFile=(a,b,c,d,e,f)=>{kb(a,b,c,d,e,f)};h.FS_createLazyFile=Zb;h.ALLOC_NORMAL=0;h.allocate=Te;
var Xe={535264:a=>{a=(a?z(q,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Te(Ta(a),"i8",0)},535489:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,535636:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,535870:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};
b.cf||("undefined"!==typeof AudioContext?b.cf=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.cf=new webkitAudioContext),b.cf&&"undefined"===typeof navigator.userActivation&&ze(b.cf));return void 0===b.cf?-1:0},536422:()=>h.SDL2.cf.sampleRate,536490:(a,b,c,d)=>{function e(){}function f(k){void 0!==g.capture.rf&&(clearInterval(g.capture.rf),g.capture.rf=void 0,g.capture.Cf=void 0);g.capture.jg=g.cf.createMediaStreamSource(k);g.capture.qf=g.cf.createScriptProcessor(b,a,1);g.capture.qf.onaudioprocess=
function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.bg=n.inputBuffer,Ae(c,[d]))};g.capture.jg.connect(g.capture.qf);g.capture.qf.connect(g.cf.destination);g.capture.stream=k}var g=h.SDL2;g.capture.Cf=g.cf.createBuffer(a,b,g.cf.sampleRate);g.capture.Cf.getChannelData(0).fill(0);g.capture.rf=setInterval(function(){g.capture.bg=g.capture.Cf;Ae(c,[d])},b/g.cf.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,
video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},538183:(a,b,c,d)=>{var e=h.SDL2;e.audio.qf=e.cf.createScriptProcessor(b,0,a);e.audio.qf.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(void 0!==e.audio.rf&&(clearInterval(e.audio.rf),e.audio.rf=void 0,e.audio.Cf=void 0),e.audio.Of=f.outputBuffer,Ae(c,[d]))};e.audio.qf.connect(e.cf.destination);"suspended"===e.cf.state&&(e.audio.Cf=e.cf.createBuffer(a,b,e.cf.sampleRate),
e.audio.Cf.getChannelData(0).fill(0),e.audio.rf=setInterval(function(){"undefined"!==typeof navigator.userActivation&&navigator.userActivation.hasBeenActive&&e.cf.resume();e.audio.Of=e.audio.Cf;Ae(c,[d]);e.audio.Of=void 0},b/e.cf.sampleRate*1E3))},539358:(a,b)=>{for(var c=h.SDL2,d=c.capture.bg.numberOfChannels,e=0;e<d;++e){var f=c.capture.bg.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=
0;g<b;++g)Ha(a+4*g,f[g]);else for(g=0;g<b;++g)Ha(a+4*(g*d+e),f[g])}},539963:(a,b)=>{var c=h.SDL2;a>>>=2;for(var d=c.audio.Of.numberOfChannels,e=0;e<d;++e){var f=c.audio.Of.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=w[a+(g*d+e)]}},540452:a=>{var b=h.SDL2;if(a){void 0!==b.capture.rf&&clearInterval(b.capture.rf);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c])}void 0!==b.capture.qf&&(b.capture.qf.onaudioprocess=function(){},b.capture.qf.disconnect());void 0!==b.capture.jg&&b.capture.jg.disconnect();b.capture=void 0}else void 0!=b.audio.qf&&b.audio.qf.disconnect(),void 0!==b.audio.rf&&clearInterval(b.audio.rf),b.audio=void 0;void 0!==b.cf&&void 0===b.audio&&void 0===b.capture&&(b.cf.close(),b.cf=void 0)},541458:()=>window.innerWidth,541488:()=>window.innerHeight,541519:(a,b,c)=>{h.SDL2||(h.SDL2=
{});var d=h.SDL2;d.Qg!==h.canvas&&(d.Nf=h.createContext(h.canvas,!1,!0),d.Qg=h.canvas);if(d.w!==a||d.h!==b||d.eh!==d.Nf)d.image=d.Nf.createImageData(a,b),d.w=a,d.h=b,d.eh=d.Nf;a=d.image.data;b=c/4;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=r[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Ug!==a&&(d.Tg=new Int32Array(a.buffer),d.Vg=new Uint8Array(a.buffer),d.Ug=a),a=d.Tg,c=a.length,a.set(r.subarray(b,b+c)),
a=d.Vg,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Nf.putImageData(d.image,0,0)},542987:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e/=4;var k=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;k<n;){var p=r[e];b[k]=p&
255;b[k+1]=p>>8&255;b[k+2]=p>>16&255;b[k+3]=p>>24&255;e++;k+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(r.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=Q(c.length+1);A(c,q,d,c.length+1);return d},543975:a=>{h.canvas&&(h.canvas.style.cursor=a?z(q,a):"")},544058:()=>{h.canvas&&(h.canvas.style.cursor="none")}},kf={Ya:(a,b)=>dynCall_vi(a,b),p:function(a,b,c){Ia=c;try{var d=G(a);switch(b){case 0:var e=Ja();if(0>
e)break;for(;pb[e];)e++;return Hb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Ja(),d.flags|=e,0;case 12:return e=Ja(),ma[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.ef}},nb:function(a,b){try{var c=G(a),d=c.node,e=c.Zd.nf;a=e?c:d;e??=d.af.nf;Db(e);var f=e(a);return ac(b,f)}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return-g.ef}},pb:function(a,b,c){Ia=c;try{var d=G(a);switch(b){case 21509:return d.bf?
0:-59;case 21505:if(!d.bf)return-59;if(d.bf.xf.ih){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Ja();r[e>>2]=25856;r[e+4>>2]=5;r[e+8>>2]=191;r[e+12>>2]=35387;for(var f=0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.bf?0:-59;case 21506:case 21507:case 21508:if(!d.bf)return-59;if(d.bf.xf.jh)for(e=Ja(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.bf)return-59;e=Ja();return r[e>>2]=0;case 21520:return d.bf?-28:-59;
case 21531:e=Ja();if(!d.Zd.hh)throw new C(59);return d.Zd.hh(d,b,e);case 21523:if(!d.bf)return-59;d.bf.xf.kh&&(f=[24,80],e=Ja(),ma[e>>1]=f[0],ma[e+2>>1]=f[1]);return 0;case 21524:return d.bf?0:-59;case 21515:return d.bf?0:-59;default:return-28}}catch(g){if("undefined"==typeof J||"ErrnoError"!==g.name)throw g;return-g.ef}},lb:function(a,b){try{return a=a?z(q,a):"",ac(b,Pb(a,!0))}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return-c.ef}},fb:function(a,b,c){try{return b=b?z(q,b):
"",b=$b(a,b),I(b,c),0}catch(d){if("undefined"==typeof J||"ErrnoError"!==d.name)throw d;return-d.ef}},kb:function(a,b,c,d){try{b=b?z(q,b):"";var e=d&256;b=$b(a,b,d&4096);return ac(c,e?Pb(b,!0):Pb(b))}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.ef}},o:function(a,b,c,d){Ia=d;try{b=b?z(q,b):"";b=$b(a,b);var e=d?Ja():0;return Rb(b,c,e).fd}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return-f.ef}},mb:function(a,b){try{return a=a?z(q,a):"",ac(b,Pb(a))}catch(c){if("undefined"==
typeof J||"ErrnoError"!==c.name)throw c;return-c.ef}},rb:()=>ta(""),$a:()=>{Ga=!1;bc=0},Xa:()=>{throw Infinity;},cb:function(a,b,c,d,e,f,g){e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{if(isNaN(e))return 61;var k=G(d);if(0!==(b&2)&&0===(c&2)&&2!==(k.flags&2097155))throw new C(2);if(1===(k.flags&2097155))throw new C(2);if(!k.Zd.Gf)throw new C(43);if(!a)throw new C(28);var n=k.Zd.Gf(k,a,e,b,c);var p=n.Ig;r[f>>2]=n.ug;t[g>>2]=p;return 0}catch(u){if("undefined"==typeof J||"ErrnoError"!==
u.name)throw u;return-u.ef}},db:function(a,b,c,d,e,f){f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=G(e);if(c&2){if(32768!==(g.node.mode&61440))throw new C(43);d&2||g.Zd.Xf&&g.Zd.Xf(g,q.slice(a,a+b),f,b,d)}}catch(k){if("undefined"==typeof J||"ErrnoError"!==k.name)throw k;return-k.ef}},ab:(a,b)=>{cc[a]&&(clearTimeout(cc[a].id),delete cc[a]);if(!b)return 0;var c=setTimeout(()=>{delete cc[a];hc(()=>Ye(a,performance.now()))},b);cc[a]={id:c,Th:b};return 0},eb:(a,b,c,d)=>{var e=(new Date).getFullYear(),
f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();t[a>>2]=60*Math.max(f,e);r[b>>2]=Number(f!=e);b=g=>{var k=Math.abs(g);return`UTC${0<=g?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(A(a,q,c,17),A(b,q,d,17)):(A(a,q,d,17),A(b,q,c,17))},Sa:a=>{if(12448==a)return K=12288,1;K=12300;return 0},pc:(a,b,c,d,e)=>{if(62E3!=a)K=12296,c=0;else{if(b)for(;;){a=r[b>>2];if(12321==a)L.alpha=0<r[b+4>>2];else if(12325==a)L.depth=
0<r[b+4>>2];else if(12326==a)L.stencil=0<r[b+4>>2];else if(12337==a)a=r[b+4>>2],L.antialias=0<a;else if(12338==a)a=r[b+4>>2],L.antialias=1==a;else if(12544==a)L.Mh=12547!=r[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(r[e>>2]=1),c&&0<d&&(t[c>>2]=62002),K=12288,c=1):(K=12300,c=0)}return c},Ub:(a,b,c,d)=>{if(62E3!=a)return K=12296,0;for(a=1;;){b=r[d>>2];if(12440==b)a=r[d+4>>2];else if(12344==b)break;else return K=12292,0;d+=8}if(2!=a)return K=12293,0;L.Eg=a-1;L.Oh=0;Cc=Vc(h.canvas,L);if(0!=Cc)return K=
12288,Yc(Cc),lc.forEach(e=>e()),Yc(null),62004;K=12297;return 0},yb:(a,b)=>{if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;K=12288;return 62006},Jb:(a,b)=>{if(62E3!=a)return K=12296,0;if(62004!=b)return K=12294,0;a=Cc;Xc===Nc[a]&&(Xc=null);"object"==typeof R&&R.qh(Nc[a].yf.canvas);Nc[a]?.yf.canvas&&(Nc[a].yf.canvas.Ef=void 0);Nc[a]=null;K=12288;xc==b&&(xc=0);return 1},qb:(a,b)=>{if(62E3!=a)return K=12296,0;if(62006!=b)return K=12301,1;zc==b&&(zc=0);Ac==b&&(Ac=0);K=12288;return 1},ec:(a,
b,c,d)=>{if(62E3!=a)return K=12296,0;if(62002!=b)return K=12293,0;if(!d)return K=12300,0;K=12288;switch(c){case 12320:return r[d>>2]=L.alpha?32:24,1;case 12321:return r[d>>2]=L.alpha?8:0,1;case 12322:return r[d>>2]=8,1;case 12323:return r[d>>2]=8,1;case 12324:return r[d>>2]=8,1;case 12325:return r[d>>2]=L.depth?24:0,1;case 12326:return r[d>>2]=L.stencil?8:0,1;case 12327:return r[d>>2]=12344,1;case 12328:return r[d>>2]=62002,1;case 12329:return r[d>>2]=0,1;case 12330:return r[d>>2]=4096,1;case 12331:return r[d>>
2]=16777216,1;case 12332:return r[d>>2]=4096,1;case 12333:return r[d>>2]=0,1;case 12334:return r[d>>2]=0,1;case 12335:return r[d>>2]=12344,1;case 12337:return r[d>>2]=L.antialias?4:0,1;case 12338:return r[d>>2]=L.antialias?1:0,1;case 12339:return r[d>>2]=4,1;case 12340:return r[d>>2]=12344,1;case 12341:case 12342:case 12343:return r[d>>2]=-1,1;case 12345:case 12346:return r[d>>2]=0,1;case 12347:return r[d>>2]=0,1;case 12348:return r[d>>2]=1;case 12349:case 12350:return r[d>>2]=0,1;case 12351:return r[d>>
2]=12430,1;case 12352:return r[d>>2]=4,1;case 12354:return r[d>>2]=0,1;default:return K=12292,0}},V:a=>{K=12288;return 0!=a&&1!=a?0:62E3},Pa:()=>K,Lc:(a,b,c)=>{if(62E3!=a)return K=12296,0;b&&(r[b>>2]=1);c&&(r[c>>2]=4);wc=!0;K=12288;return 1},hb:(a,b,c,d)=>{if(62E3!=a)return K=12296,0;if(0!=d&&62004!=d)return K=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return K=12301,0;Yc(d?Cc:null);xc=d;Ac=b;zc=c;K=12288;return 1},Qa:(a,b)=>{if(62E3!=a)return K=12296,0;K=12288;if(Bc[b])return Bc[b];switch(b){case 12371:a=
$c("Emscripten");break;case 12372:a=$c("1.4 Emscripten EGL");break;case 12373:a=$c("");break;case 12429:a=$c("OpenGL_ES");break;default:return K=12300,0}return Bc[b]=a},Za:()=>{if(wc)if(M)if(M.isContextLost())K=12302;else return K=12288,1;else K=12290;else K=12289;return 0},Wa:(a,b)=>{if(62E3!=a)return K=12296,0;0==b?qd(0,0):qd(1,b);K=12288;return 1},Ac:a=>{if(62E3!=a)return K=12296,0;Ac=zc=xc=0;wc=!1;K=12288;return 1},Ta:()=>{K=12288;return 1},Ua:()=>{K=12288;return 1},Aa:(a,b,c)=>{b=yd(b,c);return Xe[a](...b)},
a:(a,b,c)=>{b=yd(b,c);return Xe[a](...b)},C:(a,b,c)=>{b=yd(b,c);return Xe[a](...b)},Ra:()=>{sd();bd=null},U:()=>Date.now(),Ja:()=>{if(!R.fullscreenEnabled())return-1;Bd(Qd);var a=Gd[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Na:()=>{Bd(Rd);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Ma:a=>{Ga=!1;bc=0;la=a;ec(a)},f:()=>devicePixelRatio,b:(a,
b,c)=>{a=S(a);if(!a)return-4;a=Pd(a);x[b>>3]=a.width;x[c>>3]=a.height;return 0},W:(a,b)=>{if(0>a||a>=R.Rf.length)return-5;if(!R.Rf[a])return-7;Sd(b,R.Rf[a]);return 0},n:()=>performance.now(),fa:()=>R.Rf.length,Sd:(a,b,c)=>Td(a?z(q,a):"",b,c),Vb:(a,b,c)=>{a=Ze(a);return(a=pb[a])?Td(a.path,b,c):0},Oa:(a,b)=>{r[a>>2]=screen.width;r[b>>2]=screen.height},oa:a=>M.activeTexture(a),na:(a,b)=>{M.attachShader(N[a],O[b])},Fa:(a,b)=>{M.vf.beginQueryEXT(a,Oc[b])},ma:(a,b,c)=>{M.bindAttribLocation(N[a],b,c?z(q,
c):"")},la:(a,b)=>{M.bindBuffer(a,Ic[b])},ka:(a,b)=>{M.bindFramebuffer(a,Jc[b])},ja:(a,b)=>{M.bindRenderbuffer(a,Kc[b])},ia:(a,b)=>{M.bindTexture(a,Lc[b])},wa:a=>{M.bindVertexArray(Mc[a])},ha:(a,b,c,d)=>M.blendColor(a,b,c,d),ga:a=>M.blendEquation(a),ea:(a,b)=>M.blendEquationSeparate(a,b),da:(a,b)=>M.blendFunc(a,b),ca:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),ba:(a,b,c,d)=>{M.bufferData(a,c?q.subarray(c,c+b):b,d)},aa:(a,b,c,d)=>{M.bufferSubData(a,b,q.subarray(d,d+c))},$:a=>M.checkFramebufferStatus(a),
_:a=>M.clear(a),Z:(a,b,c,d)=>M.clearColor(a,b,c,d),Y:a=>M.clearDepth(a),X:a=>M.clearStencil(a),tb:(a,b)=>{M.Zg.clipControlEXT(a,b)},Rd:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},Qd:a=>{M.compileShader(O[a])},Pd:(a,b,c,d,e,f,g,k)=>{M.compressedTexImage2D(a,b,c,d,e,f,q.subarray(k,k+g))},Od:(a,b,c,d,e,f,g,k,n)=>{M.compressedTexSubImage2D(a,b,c,d,e,f,g,q.subarray(n,n+k))},Nd:(a,b,c,d,e,f,g,k)=>M.copyTexImage2D(a,b,c,d,e,f,g,k),Md:(a,b,c,d,e,f,g,k)=>M.copyTexSubImage2D(a,b,c,d,e,f,g,k),Ld:()=>{var a=Sc(N),
b=M.createProgram();b.name=a;b.Uf=b.Sf=b.Tf=0;b.rg=1;N[a]=b;return a},Kd:a=>{var b=Sc(O);O[b]=M.createShader(a);return b},Jd:a=>M.cullFace(a),Id:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Ic[d];e&&(M.deleteBuffer(e),e.name=0,Ic[d]=null)}},Hd:(a,b)=>{for(var c=0;c<a;++c){var d=r[b+4*c>>2],e=Jc[d];e&&(M.deleteFramebuffer(e),e.name=0,Jc[d]=null)}},Gd:a=>{if(a){var b=N[a];b?(M.deleteProgram(b),b.name=0,N[a]=null):P||=1281}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Oc[d];e&&(M.vf.deleteQueryEXT(e),
Oc[d]=null)}},Fd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Kc[d];e&&(M.deleteRenderbuffer(e),e.name=0,Kc[d]=null)}},Ed:a=>{if(a){var b=O[a];b?(M.deleteShader(b),O[a]=null):P||=1281}},Dd:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2],e=Lc[d];e&&(M.deleteTexture(e),e.name=0,Lc[d]=null)}},va:(a,b)=>{for(var c=0;c<a;c++){var d=r[b+4*c>>2];M.deleteVertexArray(Mc[d]);Mc[d]=null}},Cd:a=>M.depthFunc(a),Bd:a=>{M.depthMask(!!a)},Ad:(a,b)=>M.depthRange(a,b),zd:(a,b)=>{M.detachShader(N[a],O[b])},yd:a=>
M.disable(a),xd:a=>{M.disableVertexAttribArray(a)},wd:(a,b,c)=>{M.drawArrays(a,b,c)},ra:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=Ud[a],d=0;d<a;d++)c[d]=r[b+4*d>>2];M.drawBuffers(c)},vd:(a,b,c,d)=>{M.drawElements(a,b,c,d)},qa:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},ud:a=>M.enable(a),td:a=>{M.enableVertexAttribArray(a)},Ea:a=>{M.vf.endQueryEXT(a)},sd:()=>M.finish(),rd:()=>M.flush(),qd:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,Kc[d])},pd:(a,b,c,d,e)=>{M.framebufferTexture2D(a,
b,c,Lc[d],e)},od:a=>M.frontFace(a),nd:(a,b)=>{Tc(a,b,"createBuffer",Ic)},ld:(a,b)=>{Tc(a,b,"createFramebuffer",Jc)},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=M.vf.createQueryEXT();if(!d){for(P||=1282;c<a;)r[b+4*c++>>2]=0;break}var e=Sc(Oc);d.name=e;Oc[e]=d;r[b+4*c>>2]=e}},kd:(a,b)=>{Tc(a,b,"createRenderbuffer",Kc)},jd:(a,b)=>{Tc(a,b,"createTexture",Lc)},ua:(a,b)=>{Tc(a,b,"createVertexArray",Mc)},md:a=>M.generateMipmap(a),id:(a,b,c,d,e,f,g)=>Vd("getActiveAttrib",a,b,c,d,e,f,g),hd:(a,b,c,d,e,f,g)=>Vd("getActiveUniform",
a,b,c,d,e,f,g),gd:(a,b,c,d)=>{a=M.getAttachedShaders(N[a]);var e=a.length;e>b&&(e=b);r[c>>2]=e;for(b=0;b<e;++b)r[d+4*b>>2]=O.indexOf(a[b])},fd:(a,b)=>M.getAttribLocation(N[a],b?z(q,b):""),ed:(a,b)=>Wd(a,b,4),dd:(a,b,c)=>{c?r[c>>2]=M.getBufferParameter(a,b):P||=1281},cd:()=>{var a=M.getError()||P;P=0;return a},bd:(a,b)=>Wd(a,b,2),ad:(a,b,c,d)=>{a=M.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;r[d>>2]=a},$c:(a,b)=>Wd(a,b,0),Zc:(a,b,
c,d)=>{a=M.getProgramInfoLog(N[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,q,d,b):0;c&&(r[c>>2]=b)},_c:(a,b,c)=>{if(c)if(a>=Hc)P||=1281;else if(a=N[a],35716==b)a=M.getProgramInfoLog(a),null===a&&(a="(unknown error)"),r[c>>2]=a.length+1;else if(35719==b){if(!a.Uf){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Uf=Math.max(a.Uf,M.getActiveUniform(a,b).name.length+1)}r[c>>2]=a.Uf}else if(35722==b){if(!a.Sf)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.Sf=Math.max(a.Sf,M.getActiveAttrib(a,
b).name.length+1);r[c>>2]=a.Sf}else if(35381==b){if(!a.Tf)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.Tf=Math.max(a.Tf,M.getActiveUniformBlockName(a,b).length+1);r[c>>2]=a.Tf}else r[c>>2]=M.getProgramParameter(a,b);else P||=1281},ya:Xd,Ba:Yd,xa:Xd,za:Yd,Ca:(a,b,c)=>{c?r[c>>2]=M.vf.getQueryEXT(a,b):P||=1281},Yc:(a,b,c)=>{c?r[c>>2]=M.getRenderbufferParameter(a,b):P||=1281},Wc:(a,b,c,d)=>{a=M.getShaderInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?A(a,q,d,b):0;c&&(r[c>>2]=b)},Vc:(a,b,
c,d)=>{a=M.getShaderPrecisionFormat(a,b);r[c>>2]=a.rangeMin;r[c+4>>2]=a.rangeMax;r[d>>2]=a.precision},Uc:(a,b,c,d)=>{if(a=M.getShaderSource(O[a]))b=0<b&&d?A(a,q,d,b):0,c&&(r[c>>2]=b)},Xc:(a,b,c)=>{c?35716==b?(a=M.getShaderInfoLog(O[a]),null===a&&(a="(unknown error)"),r[c>>2]=a?a.length+1:0):35720==b?(a=M.getShaderSource(O[a]),r[c>>2]=a?a.length+1:0):r[c>>2]=M.getShaderParameter(O[a],b):P||=1281},Tc:a=>{var b=Pc[a];if(!b){switch(a){case 7939:b=$c(Zd().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=
M.getParameter(a))||(P||=1280);b=b?$c(b):0;break;case 7938:b=$c(`OpenGL ES 2.0 (${M.getParameter(7938)})`);break;case 35724:b=M.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=$c(b);break;default:P||=1280}Pc[a]=b}return b},Sc:(a,b,c)=>{c?w[c>>2]=M.getTexParameter(a,b):P||=1281},Rc:(a,b,c)=>{c?r[c>>2]=M.getTexParameter(a,b):P||=1281},Oc:(a,b)=>{b=b?z(q,b):"";if(a=N[a]){ae(a);var c=a.Kf,
d=0,e=b,f=$d(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Mg[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else P||=1281;return-1},Qc:(a,b,c)=>{be(a,b,c,2)},Pc:(a,b,c)=>{be(a,b,c,0)},Kc:(a,b,c)=>{c?r[c>>2]=M.getVertexAttribOffset(a,b):P||=1281},Nc:(a,b,c)=>{ce(a,b,c,2)},Mc:(a,b,c)=>{ce(a,b,c,5)},Jc:(a,b)=>M.hint(a,b),Ic:a=>(a=Ic[a])?M.isBuffer(a):0,Hc:a=>M.isEnabled(a),Gc:a=>(a=Jc[a])?M.isFramebuffer(a):0,Fc:a=>(a=N[a])?M.isProgram(a):0,Ga:a=>(a=Oc[a])?M.vf.isQueryEXT(a):
0,Ec:a=>(a=Kc[a])?M.isRenderbuffer(a):0,Dc:a=>(a=O[a])?M.isShader(a):0,Cc:a=>(a=Lc[a])?M.isTexture(a):0,ta:a=>(a=Mc[a])?M.isVertexArray(a):0,Bc:a=>M.lineWidth(a),zc:a=>{a=N[a];M.linkProgram(a);a.Kf=0;a.Mg={}},yc:(a,b)=>{3317==a?Qc=b:3314==a&&(Rc=b);M.pixelStorei(a,b)},sb:(a,b)=>{M.th.polygonModeWEBGL(a,b)},xc:(a,b)=>M.polygonOffset(a,b),ub:(a,b,c)=>{M.$g.polygonOffsetClampEXT(a,b,c)},Da:(a,b)=>{M.vf.queryCounterEXT(Oc[a],b)},wc:(a,b,c,d,e,f,g)=>{(g=de(f,e,c,d,g))?M.readPixels(a,b,c,d,e,f,g):P||=1280},
vc:()=>{},uc:(a,b,c,d)=>M.renderbufferStorage(a,b,c,d),tc:(a,b)=>{M.sampleCoverage(a,!!b)},sc:(a,b,c,d)=>M.scissor(a,b,c,d),rc:()=>{P||=1280},qc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=t[c+4*f>>2])?z(q,g,d?t[d+4*f>>2]:void 0):"";e+=g}M.shaderSource(O[a],e)},oc:(a,b,c)=>M.stencilFunc(a,b,c),nc:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),mc:a=>M.stencilMask(a),lc:(a,b)=>M.stencilMaskSeparate(a,b),kc:(a,b,c)=>M.stencilOp(a,b,c),jc:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),ic:(a,b,c,d,e,f,g,k,n)=>
{n=n?de(k,g,d,e,n):null;M.texImage2D(a,b,c,d,e,f,g,k,n)},hc:(a,b,c)=>M.texParameterf(a,b,c),gc:(a,b,c)=>{M.texParameterf(a,b,w[c>>2])},fc:(a,b,c)=>M.texParameteri(a,b,c),dc:(a,b,c)=>{M.texParameteri(a,b,r[c>>2])},cc:(a,b,c,d,e,f,g,k,n)=>{n=n?de(k,g,e,f,n):null;M.texSubImage2D(a,b,c,d,e,f,g,k,n)},bc:(a,b)=>{M.uniform1f(Y(a),b)},ac:(a,b,c)=>{if(288>=b)for(var d=ee[b],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);M.uniform1fv(Y(a),d)},$b:(a,b)=>{M.uniform1i(Y(a),b)},_b:(a,b,c)=>{if(288>=
b)for(var d=fe[b],e=0;e<b;++e)d[e]=r[c+4*e>>2];else d=r.subarray(c>>2,c+4*b>>2);M.uniform1iv(Y(a),d)},Zb:(a,b,c)=>{M.uniform2f(Y(a),b,c)},Yb:(a,b,c)=>{if(144>=b){b*=2;for(var d=ee[b],e=0;e<b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2]}else d=w.subarray(c>>2,c+8*b>>2);M.uniform2fv(Y(a),d)},Xb:(a,b,c)=>{M.uniform2i(Y(a),b,c)},Wb:(a,b,c)=>{if(144>=b){b*=2;for(var d=fe[b],e=0;e<b;e+=2)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2]}else d=r.subarray(c>>2,c+8*b>>2);M.uniform2iv(Y(a),d)},Tb:(a,b,c,d)=>{M.uniform3f(Y(a),
b,c,d)},Sb:(a,b,c)=>{if(96>=b){b*=3;for(var d=ee[b],e=0;e<b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2]}else d=w.subarray(c>>2,c+12*b>>2);M.uniform3fv(Y(a),d)},Rb:(a,b,c,d)=>{M.uniform3i(Y(a),b,c,d)},Qb:(a,b,c)=>{if(96>=b){b*=3;for(var d=fe[b],e=0;e<b;e+=3)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2]}else d=r.subarray(c>>2,c+12*b>>2);M.uniform3iv(Y(a),d)},Pb:(a,b,c,d,e)=>{M.uniform4f(Y(a),b,c,d,e)},Ob:(a,b,c)=>{if(72>=b){var d=ee[4*b],e=w;c>>=2;b*=4;for(var f=
0;f<b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=w.subarray(c>>2,c+16*b>>2);M.uniform4fv(Y(a),d)},Nb:(a,b,c,d,e)=>{M.uniform4i(Y(a),b,c,d,e)},Mb:(a,b,c)=>{if(72>=b){b*=4;for(var d=fe[b],e=0;e<b;e+=4)d[e]=r[c+4*e>>2],d[e+1]=r[c+(4*e+4)>>2],d[e+2]=r[c+(4*e+8)>>2],d[e+3]=r[c+(4*e+12)>>2]}else d=r.subarray(c>>2,c+16*b>>2);M.uniform4iv(Y(a),d)},Lb:(a,b,c,d)=>{if(72>=b){b*=4;for(var e=ee[b],f=0;f<b;f+=4)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+
3]=w[d+(4*f+12)>>2]}else e=w.subarray(d>>2,d+16*b>>2);M.uniformMatrix2fv(Y(a),!!c,e)},Kb:(a,b,c,d)=>{if(32>=b){b*=9;for(var e=ee[b],f=0;f<b;f+=9)e[f]=w[d+4*f>>2],e[f+1]=w[d+(4*f+4)>>2],e[f+2]=w[d+(4*f+8)>>2],e[f+3]=w[d+(4*f+12)>>2],e[f+4]=w[d+(4*f+16)>>2],e[f+5]=w[d+(4*f+20)>>2],e[f+6]=w[d+(4*f+24)>>2],e[f+7]=w[d+(4*f+28)>>2],e[f+8]=w[d+(4*f+32)>>2]}else e=w.subarray(d>>2,d+36*b>>2);M.uniformMatrix3fv(Y(a),!!c,e)},Ib:(a,b,c,d)=>{if(18>=b){var e=ee[16*b],f=w;d>>=2;b*=16;for(var g=0;g<b;g+=16){var k=
d+g;e[g]=f[k];e[g+1]=f[k+1];e[g+2]=f[k+2];e[g+3]=f[k+3];e[g+4]=f[k+4];e[g+5]=f[k+5];e[g+6]=f[k+6];e[g+7]=f[k+7];e[g+8]=f[k+8];e[g+9]=f[k+9];e[g+10]=f[k+10];e[g+11]=f[k+11];e[g+12]=f[k+12];e[g+13]=f[k+13];e[g+14]=f[k+14];e[g+15]=f[k+15]}}else e=w.subarray(d>>2,d+64*b>>2);M.uniformMatrix4fv(Y(a),!!c,e)},Hb:a=>{a=N[a];M.useProgram(a);M.Sg=a},Gb:a=>{M.validateProgram(N[a])},Fb:(a,b)=>M.vertexAttrib1f(a,b),Eb:(a,b)=>{M.vertexAttrib1f(a,w[b>>2])},Db:(a,b,c)=>M.vertexAttrib2f(a,b,c),Cb:(a,b)=>{M.vertexAttrib2f(a,
w[b>>2],w[b+4>>2])},Bb:(a,b,c,d)=>M.vertexAttrib3f(a,b,c,d),Ab:(a,b)=>{M.vertexAttrib3f(a,w[b>>2],w[b+4>>2],w[b+8>>2])},zb:(a,b,c,d,e)=>M.vertexAttrib4f(a,b,c,d,e),xb:(a,b)=>{M.vertexAttrib4f(a,w[b>>2],w[b+4>>2],w[b+8>>2],w[b+12>>2])},pa:(a,b)=>{M.vertexAttribDivisor(a,b)},wb:(a,b,c,d,e,f)=>{M.vertexAttribPointer(a,b,c,!!d,e,f)},vb:(a,b,c,d)=>M.viewport(a,b,c,d),r:()=>1,Ka:(a,b,c)=>ge(a,{ng:r[c>>2],ag:r[c+4>>2],ah:r[c+8>>2],Wg:b,Mf:r[c+12>>2],wg:r[c+16>>2]}),O:(a,b)=>{a=S(a);return a?a.requestPointerLock?
Cd()?Rd(a):b?(Ad(Rd,2,[a]),1):-2:-1:-4},bb:()=>{ta("OOM")},s:he,t:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:ie(a,b),G:(a,b,c,d)=>je(a,b,c,d,12,"blur"),e:Kd,l:(a,b,c)=>{a=S(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},H:(a,b,c,d)=>je(a,b,c,d,13,"focus"),w:(a,b,c,d)=>{if(!R.fullscreenEnabled())return-1;a=S(a);if(!a)return-4;ke(a,b,c,d,"webkitfullscreenchange");return ke(a,b,c,d,"fullscreenchange")},k:(a,b,c)=>he()?-1:le(a,b,c,26,"gamepadconnected"),j:(a,b,c)=>
he()?-1:le(a,b,c,27,"gamepaddisconnected"),z:(a,b,c,d)=>me(a,b,c,d,2,"keydown"),x:(a,b,c,d)=>me(a,b,c,d,1,"keypress"),y:(a,b,c,d)=>me(a,b,c,d,3,"keyup"),Td:(a,b,c)=>{rd(()=>dynCall_v(a),b,c)},M:(a,b,c,d)=>oe(a,b,c,d,5,"mousedown"),K:(a,b,c,d)=>oe(a,b,c,d,33,"mouseenter"),J:(a,b,c,d)=>oe(a,b,c,d,34,"mouseleave"),N:(a,b,c,d)=>oe(a,b,c,d,8,"mousemove"),L:(a,b,c,d)=>oe(a,b,c,d,6,"mouseup"),A:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.gf||document.body.Ng||
document.body.$f))return-1;a=S(a);if(!a)return-4;pe(a,b,c,d,"mozpointerlockchange");pe(a,b,c,d,"webkitpointerlockchange");pe(a,b,c,d,"mspointerlockchange");return pe(a,b,c,d,"pointerlockchange")},v:(a,b,c,d)=>qe(a,b,c,d),B:(a,b,c,d)=>re(a,b,c,d,25,"touchcancel"),E:(a,b,c,d)=>re(a,b,c,d,23,"touchend"),D:(a,b,c,d)=>re(a,b,c,d,24,"touchmove"),F:(a,b,c,d)=>re(a,b,c,d,22,"touchstart"),u:(a,b,c)=>te(a,b,c),I:(a,b,c,d)=>(a=S(a))?"undefined"!=typeof a.onwheel?ue(a,b,c,d):-1:-4,La:a=>document.title=a?z(q,
a):"",q:a=>Oe(b=>ic(b,a)),ib:(a,b)=>{var c=0,d=0,e;for(e of xe()){var f=b+c;t[a+d>>2]=f;c+=A(e,q,f,Infinity)+1;d+=4}return 0},jb:(a,b)=>{var c=xe();t[a>>2]=c.length;a=0;for(var d of c)a+=Sa(d)+1;t[b>>2]=a;return 0},g:function(a){try{var b=G(a);Sb(b);return 0}catch(c){if("undefined"==typeof J||"ErrnoError"!==c.name)throw c;return c.ef}},T:function(a,b,c,d){try{a:{var e=G(a);a=b;for(var f,g=b=0;g<c;g++){var k=t[a>>2],n=t[a+4>>2];a+=8;var p=e,u=k,v=n,y=f,B=m;if(0>v||0>y)throw new C(28);if(null===p.fd)throw new C(8);
if(1===(p.flags&2097155))throw new C(8);if(E(p.node.mode))throw new C(31);if(!p.Zd.read)throw new C(28);var F="undefined"!=typeof y;if(!F)y=p.position;else if(!p.seekable)throw new C(70);var H=p.Zd.read(p,B,u,v,y);F||(p.position+=H);var W=H;if(0>W){var xa=-1;break a}b+=W;if(W<n)break;"undefined"!=typeof f&&(f+=W)}xa=b}t[d>>2]=xa;return 0}catch(ka){if("undefined"==typeof J||"ErrnoError"!==ka.name)throw ka;return ka.ef}},gb:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=G(a);Tb(e,b,c);oa[d>>3]=BigInt(e.position);e.gg&&0===b&&0===c&&(e.gg=null);return 0}catch(f){if("undefined"==typeof J||"ErrnoError"!==f.name)throw f;return f.ef}},ob:function(a,b,c,d){try{a:{var e=G(a);a=b;for(var f,g=b=0;g<c;g++){var k=t[a>>2],n=t[a+4>>2];a+=8;var p=Ub(e,m,k,n,f);if(0>p){var u=-1;break a}b+=p;if(p<n)break;"undefined"!=typeof f&&(f+=p)}u=b}t[d>>2]=u;return 0}catch(v){if("undefined"==typeof J||"ErrnoError"!==v.name)throw v;return v.ef}},m:$e,P:af,h:bf,i:cf,Va:df,Q:ef,S:ff,d:gf,
c:hf,R:jf,_a:ec},Z;
(async function(){function a(c){Z=c.exports;Z=Ce();ia=Z.Ud;c=ia.buffer;m=new Int8Array(c);ma=new Int16Array(c);q=new Uint8Array(c);na=new Uint16Array(c);r=new Int32Array(c);t=new Uint32Array(c);w=new Float32Array(c);x=new Float64Array(c);oa=new BigInt64Array(c);new BigUint64Array(c);sa("wasm-instantiate");return Z}ra("wasm-instantiate");var b={a:kf};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ua??=h.locateFile?h.locateFile("index.wasm",da):da+"index.wasm";
return a((await ya(b)).instance)})();
var lf=h._main=(a,b)=>(lf=h._main=Z.Wd)(a,b),Q=a=>(Q=Z.Xd)(a),Se=a=>(Se=Z.Yd)(a),Ze=a=>(Ze=Z._d)(a),$a=(a,b)=>($a=Z.$d)(a,b),Ye=(a,b)=>(Ye=Z.ae)(a,b),mf=(a,b)=>(mf=Z.be)(a,b),U=a=>(U=Z.ce)(a),Hd=a=>(Hd=Z.de)(a),T=()=>(T=Z.ee)(),nf=h.dynCall_iiiii=(a,b,c,d,e)=>(nf=h.dynCall_iiiii=Z.fe)(a,b,c,d,e),dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=Z.ge)(a,b,c),dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=Z.he)(a,b,c),X=h.dynCall_iiii=(a,b,c,d)=>(X=h.dynCall_iiii=Z.ie)(a,
b,c,d),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=Z.je)(a,b),of=h.dynCall_ii=(a,b)=>(of=h.dynCall_ii=Z.ke)(a,b),pf=h.dynCall_jiji=(a,b,c,d)=>(pf=h.dynCall_jiji=Z.le)(a,b,c,d);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Z.me)(a,b);var qf=h.dynCall_iiiiii=(a,b,c,d,e,f)=>(qf=h.dynCall_iiiiii=Z.ne)(a,b,c,d,e,f);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_iiiiiiiii=Z.oe)(a,b,c,d,e,f,g,k,n);h.dynCall_iiiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiiii=Z.pe)(a,b,c,d,e,f,g);
h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,k,n)=>(h.dynCall_viiiiiiii=Z.qe)(a,b,c,d,e,f,g,k,n);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_iiiiiiii=Z.re)(a,b,c,d,e,f,g,k);var rf=h.dynCall_viii=(a,b,c,d)=>(rf=h.dynCall_viii=Z.se)(a,b,c,d);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=Z.te)(a,b,c,d,e,f);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=Z.ue)(a,b,c,d,e);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,k,n,p)=>(h.dynCall_viiiiiiiii=Z.ve)(a,b,c,d,e,f,g,k,n,p);
var sf=h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,k,n,p)=>(sf=h.dynCall_iiiiiiiiii=Z.we)(a,b,c,d,e,f,g,k,n,p),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=Z.xe)(a);h.dynCall_iiji=(a,b,c,d)=>(h.dynCall_iiji=Z.ye)(a,b,c,d);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,k,n,p,u,v,y,B,F,H)=>(h.dynCall_iiiiiiiiiiiiiiff=Z.ze)(a,b,c,d,e,f,g,k,n,p,u,v,y,B,F,H);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,k)=>(h.dynCall_viiiiiii=Z.Ae)(a,b,c,d,e,f,g,k);
h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,k,n,p,u,v)=>(h.dynCall_viiiiiiiiiii=Z.Be)(a,b,c,d,e,f,g,k,n,p,u,v);h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,k,n,p,u)=>(h.dynCall_iiiiiidiiff=Z.Ce)(a,b,c,d,e,f,g,k,n,p,u);h.dynCall_i=a=>(h.dynCall_i=Z.De)(a);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=Z.Ee)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=Z.Fe)(a,b);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=Z.Ge)(a,b,c);h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=Z.He)(a,b,c);
h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=Z.Ie)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=Z.Je)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=Z.Ke)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=Z.Le)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=Z.Me)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=Z.Ne)(a,b,c,d,e,f,g);h.dynCall_vfff=(a,b,c,d)=>(h.dynCall_vfff=Z.Oe)(a,b,c,d);
h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=Z.Pe)(a,b,c,d,e,f,g);h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=Z.Qe)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=Z.Re)(a,b);h.dynCall_viijii=(a,b,c,d,e,f)=>(h.dynCall_viijii=Z.Se)(a,b,c,d,e,f);h.dynCall_iiiiij=(a,b,c,d,e,f)=>(h.dynCall_iiiiij=Z.Te)(a,b,c,d,e,f);h.dynCall_iiiiid=(a,b,c,d,e,f)=>(h.dynCall_iiiiid=Z.Ue)(a,b,c,d,e,f);h.dynCall_iiiiijj=(a,b,c,d,e,f,g)=>(h.dynCall_iiiiijj=Z.Ve)(a,b,c,d,e,f,g);
h.dynCall_iiiiiijj=(a,b,c,d,e,f,g,k)=>(h.dynCall_iiiiiijj=Z.We)(a,b,c,d,e,f,g,k);var Qe=a=>(Qe=Z.Xe)(a),Ge=()=>(Ge=Z.Ye)(),Pe=a=>(Pe=Z.Ze)(a),Re=()=>(Re=Z._e)();function ff(a,b,c,d){var e=T();try{return pf(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;mf(1,0);return 0n}}function cf(a,b,c,d,e){var f=T();try{return nf(a,b,c,d,e)}catch(g){U(f);if(g!==g+0)throw g;mf(1,0)}}function $e(a,b){var c=T();try{return of(a,b)}catch(d){U(c);if(d!==d+0)throw d;mf(1,0)}}
function bf(a,b,c,d){var e=T();try{return X(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;mf(1,0)}}function gf(a,b){var c=T();try{dynCall_vi(a,b)}catch(d){U(c);if(d!==d+0)throw d;mf(1,0)}}function hf(a,b,c){var d=T();try{dynCall_vii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;mf(1,0)}}function jf(a,b,c,d){var e=T();try{rf(a,b,c,d)}catch(f){U(e);if(f!==f+0)throw f;mf(1,0)}}function ef(a,b,c,d,e,f,g,k,n,p){var u=T();try{return sf(a,b,c,d,e,f,g,k,n,p)}catch(v){U(u);if(v!==v+0)throw v;mf(1,0)}}
function df(a,b,c,d,e,f){var g=T();try{return qf(a,b,c,d,e,f)}catch(k){U(g);if(k!==k+0)throw k;mf(1,0)}}function af(a,b,c){var d=T();try{return dynCall_iii(a,b,c)}catch(e){U(d);if(e!==e+0)throw e;mf(1,0)}}function tf(a=[]){var b=lf;a.unshift(ca);var c=a.length,d=Hd(4*(c+1)),e=d;a.forEach(g=>{t[e>>2]=Id(g);e+=4});t[e>>2]=0;try{var f=b(c,d);fc(f)}catch(g){dc(g)}}
function uf(a=ba){function b(){h.calledRun=!0;if(!ja){if(!h.noFSInit&&!sb){var c,d;sb=!0;c??=h.stdin;d??=h.stdout;e??=h.stderr;c?Xb("/dev","stdin",c):Nb("/dev/tty","/dev/stdin");d?Xb("/dev","stdout",null,d):Nb("/dev/tty","/dev/stdout");e?Xb("/dev","stderr",null,e):Nb("/dev/tty1","/dev/stderr");Rb("/dev/stdin",0);Rb("/dev/stdout",1);Rb("/dev/stderr",1)}Z.Vd();tb=!1;h.onRuntimeInitialized?.();h.noInitialRun||tf(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var e=
h.postRun.shift();Ba.push(e)}Aa(Ba)}}if(0<pa)qa=uf;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Da();Aa(Ca);0<pa?qa=uf:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);b()},1)):b()}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();uf();
