var h;h||=typeof Module != 'undefined' ? Module : {};h.xf||(h.xf=0);h.xf++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,t){var q=new XMLHttpRequest;q.open("GET",n,!0);q.responseType="arraybuffer";q.onprogress=function(u){var D=p;u.total&&(D=u.total);if(u.loaded){q.Fe?h.Xe[n].loaded=u.loaded:(q.Fe=!0,h.Xe||(h.Xe={}),h.Xe[n]={loaded:u.loaded,total:D});var J=D=u=0,W;for(W in h.Xe){var ja=h.Xe[W];u+=ja.total;D+=ja.loaded;J++}u=Math.ceil(u*h.xf/J);h.setStatus&&h.setStatus(`Downloading data... (${D}/${u})`)}else!h.Xe&&h.setStatus&&h.setStatus("Downloading data...")};
q.onerror=function(){throw Error("NetworkError for: "+n);};q.onload=function(){if(200==q.status||304==q.status||206==q.status||0==q.status&&q.response)t(q.response);else throw Error(q.statusText+" : "+q.responseURL);};q.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,D,J){this.start=u;this.end=D;this.audio=J}function p(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
u=new Uint8Array(u);n.prototype.Ef=u;u=a.files;for(var D=0;D<u.length;++D)n.prototype.Fe[u[D].filename].onload();h.removeRunDependency("datafile_index.data")}h.FS_createPath("/","dgguspat",!0,!0);n.prototype={Fe:{},open:function(u,D){this.name=D;this.Fe[D]=this;h.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.Ef.subarray(this.start,this.end))},finish:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency(`fp ${this.name}`);this.Fe[this.name]=null}};
for(var t=a.files,q=0;q<t.length;++q)(new n(t[q].start,t[q].end,t[q].audio||0)).open("GET",t[q].filename);h.addRunDependency("datafile_index.data");h.Wf||(h.Wf={});h.Wf["index.data"]={Og:!1};l?(p(l),l=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("index.data",""):"index.data",f=a.remote_package_size,g=null,l=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;l||b(e,f,function(n){g?(g(n),g=null):l=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/DUKE3D.GRP",
start:0,end:11035779},{filename:"/dgguspat/acbass.pat",start:11035779,end:11046608},{filename:"/dgguspat/accordn.pat",start:11046608,end:11066231},{filename:"/dgguspat/acguitar.pat",start:11066231,end:11118812},{filename:"/dgguspat/acpiano.pat",start:11118812,end:11184071},{filename:"/dgguspat/agogo.pat",start:11184071,end:11211798},{filename:"/dgguspat/agogohi.pat",start:11211798,end:11219081},{filename:"/dgguspat/agogolo.pat",start:11219081,end:11226364},{filename:"/dgguspat/altosax.pat",start:11226364,
end:11238075},{filename:"/dgguspat/applause.pat",start:11238075,end:11298524},{filename:"/dgguspat/atmosphr.pat",start:11298524,end:11361559},{filename:"/dgguspat/aurora.pat",start:11361559,end:11424062},{filename:"/dgguspat/bagpipes.pat",start:11424062,end:11440119},{filename:"/dgguspat/banjo.pat",start:11440119,end:11504642},{filename:"/dgguspat/barisax.pat",start:11504642,end:11526381},{filename:"/dgguspat/basslead.pat",start:11526381,end:11579770},{filename:"/dgguspat/bassoon.pat",start:11579770,
end:11596493},{filename:"/dgguspat/belltree.pat",start:11596493,end:11660596},{filename:"/dgguspat/blank.pat",start:11660596,end:11663963},{filename:"/dgguspat/bongohi.pat",start:11663963,end:11671196},{filename:"/dgguspat/bongolo.pat",start:11671196,end:11680397},{filename:"/dgguspat/bottle.pat",start:11680397,end:11705460},{filename:"/dgguspat/bowglass.pat",start:11705460,end:11755151},{filename:"/dgguspat/britepno.pat",start:11755151,end:11827890},{filename:"/dgguspat/c550kc_1.pat",start:11827890,
end:11839267},{filename:"/dgguspat/c550sn10.pat",start:11839267,end:11855235},{filename:"/dgguspat/c550sn_6.pat",start:11855235,end:11872557},{filename:"/dgguspat/c550vibs.pat",start:11872557,end:11903593},{filename:"/dgguspat/cabasa.pat",start:11903593,end:11920796},{filename:"/dgguspat/calliope.pat",start:11920796,end:11967099},{filename:"/dgguspat/carillon.pat",start:11967099,end:11979188},{filename:"/dgguspat/castinet.pat",start:11979188,end:11991537},{filename:"/dgguspat/celeste.pat",start:11991537,
end:12011744},{filename:"/dgguspat/cello.pat",start:12011744,end:12030485},{filename:"/dgguspat/charang.pat",start:12030485,end:12121146},{filename:"/dgguspat/chiflead.pat",start:12121146,end:12184527},{filename:"/dgguspat/choir.pat",start:12184527,end:12229880},{filename:"/dgguspat/church.pat",start:12229880,end:12234489},{filename:"/dgguspat/claps.pat",start:12234489,end:12246208},{filename:"/dgguspat/clarinet.pat",start:12246208,end:12265369},{filename:"/dgguspat/clave.pat",start:12265369,end:12270404},
{filename:"/dgguspat/clavinet.pat",start:12270404,end:12273847},{filename:"/dgguspat/cleangtr.pat",start:12273847,end:12319874},{filename:"/dgguspat/concrtna.pat",start:12319874,end:12337855},{filename:"/dgguspat/congahi1.pat",start:12337855,end:12346608},{filename:"/dgguspat/congahi2.pat",start:12346608,end:12356321},{filename:"/dgguspat/congalo.pat",start:12356321,end:12366034},{filename:"/dgguspat/contraba.pat",start:12366034,end:12375757},{filename:"/dgguspat/cowbell.pat",start:12375757,end:12382402},
{filename:"/dgguspat/crystal.pat",start:12382402,end:12443185},{filename:"/dgguspat/cuica1.pat",start:12443185,end:12462180},{filename:"/dgguspat/cuica2.pat",start:12462180,end:12488197},{filename:"/dgguspat/cymbell.pat",start:12488197,end:12523012},{filename:"/dgguspat/cymchina.pat",start:12523012,end:12571557},{filename:"/dgguspat/cymcrsh1.pat",start:12571557,end:12634910},{filename:"/dgguspat/cymcrsh2.pat",start:12634910,end:12697321},{filename:"/dgguspat/cymride1.pat",start:12697321,end:12732976},
{filename:"/dgguspat/cymride2.pat",start:12732976,end:12768631},{filename:"/dgguspat/cymsplsh.pat",start:12768631,end:12831984},{filename:"/dgguspat/dgguspat.txt",start:12831984,end:12835089},{filename:"/dgguspat/distgtr.pat",start:12835089,end:12873338},{filename:"/dgguspat/dmx2timid.py",start:12873338,end:12874196},{filename:"/dgguspat/doo.pat",start:12874196,end:12891529},{filename:"/dgguspat/echovox.pat",start:12891529,end:12921816},{filename:"/dgguspat/englhorn.pat",start:12921816,end:12946491},
{filename:"/dgguspat/epiano1.pat",start:12946491,end:12961496},{filename:"/dgguspat/epiano2.pat",start:12961496,end:13005687},{filename:"/dgguspat/fantasia.pat",start:13005687,end:13052916},{filename:"/dgguspat/fiddle.pat",start:13052916,end:13065225},{filename:"/dgguspat/flute.pat",start:13065225,end:13077608},{filename:"/dgguspat/fngrbass.pat",start:13077608,end:13097405},{filename:"/dgguspat/frenchrn.pat",start:13097405,end:13126040},{filename:"/dgguspat/freshair.pat",start:13126040,end:13184347},
{filename:"/dgguspat/fretless.pat",start:13184347,end:13189952},{filename:"/dgguspat/fx-blow.pat",start:13189952,end:13247645},{filename:"/dgguspat/fx-fret.pat",start:13247645,end:13275276},{filename:"/dgguspat/ghostie.pat",start:13275276,end:13338577},{filename:"/dgguspat/glocken.pat",start:13338577,end:13349272},{filename:"/dgguspat/gtrharm.pat",start:13349272,end:13359445},{filename:"/dgguspat/guiro1.pat",start:13359445,end:13368006},{filename:"/dgguspat/guiro2.pat",start:13368006,end:13386827},
{filename:"/dgguspat/halopad.pat",start:13386827,end:13447118},{filename:"/dgguspat/harmonca.pat",start:13447118,end:13462419},{filename:"/dgguspat/harp.pat",start:13462419,end:13486346},{filename:"/dgguspat/helicptr.pat",start:13486346,end:13536673},{filename:"/dgguspat/highq.pat",start:13536673,end:13540618},{filename:"/dgguspat/hihatcl.pat",start:13540618,end:13550071},{filename:"/dgguspat/hihatop.pat",start:13550071,end:13590488},{filename:"/dgguspat/hihatpd.pat",start:13590488,end:13594413},
{filename:"/dgguspat/hitbrass.pat",start:13594413,end:13657782},{filename:"/dgguspat/homeorg.pat",start:13657782,end:13660083},{filename:"/dgguspat/honky.pat",start:13660083,end:13791988},{filename:"/dgguspat/hrpschrd.pat",start:13791988,end:13799697},{filename:"/dgguspat/jazzgtr.pat",start:13799697,end:13855620},{filename:"/dgguspat/jingles.pat",start:13855620,end:13889839},{filename:"/dgguspat/jungle.pat",start:13889839,end:13917380},{filename:"/dgguspat/kalimba.pat",start:13917380,end:13922119},
{filename:"/dgguspat/kick1.pat",start:13922119,end:13931530},{filename:"/dgguspat/kick2.pat",start:13931530,end:13941907},{filename:"/dgguspat/koto.pat",start:13941907,end:13983986},{filename:"/dgguspat/lead5th.pat",start:13983986,end:13997219},{filename:"/dgguspat/maracas.pat",start:13997219,end:14006652},{filename:"/dgguspat/marcato.pat",start:14006652,end:14129533},{filename:"/dgguspat/marimba.pat",start:14129533,end:14133980},{filename:"/dgguspat/metalpad.pat",start:14133980,end:14194885},{filename:"/dgguspat/metbell.pat",
start:14194885,end:14195424},{filename:"/dgguspat/metclick.pat",start:14195424,end:14195963},{filename:"/dgguspat/musicbox.pat",start:14195963,end:14226910},{filename:"/dgguspat/mutegtr.pat",start:14226910,end:14261487},{filename:"/dgguspat/mutetrum.pat",start:14261487,end:14280506},{filename:"/dgguspat/nyguitar.pat",start:14280506,end:14319717},{filename:"/dgguspat/oboe.pat",start:14319717,end:14328986},{filename:"/dgguspat/ocarina.pat",start:14328986,end:14332523},{filename:"/dgguspat/odguitar.pat",
start:14332523,end:14358368},{filename:"/dgguspat/orchhit.pat",start:14358368,end:14387119},{filename:"/dgguspat/percorg.pat",start:14387119,end:14402554},{filename:"/dgguspat/piccolo.pat",start:14402554,end:14411499},{filename:"/dgguspat/pickbass.pat",start:14411499,end:14444712},{filename:"/dgguspat/pistol.pat",start:14444712,end:14481307},{filename:"/dgguspat/pizzcato.pat",start:14481307,end:14521480},{filename:"/dgguspat/polysyn.pat",start:14521480,end:14582239},{filename:"/dgguspat/recorder.pat",
start:14582239,end:14587886},{filename:"/dgguspat/reedorg.pat",start:14587886,end:14591357},{filename:"/dgguspat/revcym.pat",start:14591357,end:14618748},{filename:"/dgguspat/ringwhsl.pat",start:14618748,end:14677239},{filename:"/dgguspat/rockorg.pat",start:14677239,end:14738126},{filename:"/dgguspat/santur.pat",start:14738126,end:14781959},{filename:"/dgguspat/sawwave.pat",start:14781959,end:14836444},{filename:"/dgguspat/scratch1.pat",start:14836444,end:14845535},{filename:"/dgguspat/scratch2.pat",
start:14845535,end:14850418},{filename:"/dgguspat/seashore.pat",start:14850418,end:14912825},{filename:"/dgguspat/shakazul.pat",start:14912825,end:14975414},{filename:"/dgguspat/shaker.pat",start:14975414,end:14981941},{filename:"/dgguspat/shamisen.pat",start:14981941,end:15008608},{filename:"/dgguspat/shannai.pat",start:15008608,end:15028759},{filename:"/dgguspat/sitar.pat",start:15028759,end:15065738},{filename:"/dgguspat/slap.pat",start:15065738,end:15077769},{filename:"/dgguspat/slapbas1.pat",
start:15077769,end:15133902},{filename:"/dgguspat/slapbas2.pat",start:15133902,end:15175483},{filename:"/dgguspat/slowstr.pat",start:15175483,end:15212200},{filename:"/dgguspat/snare1.pat",start:15212200,end:15229617},{filename:"/dgguspat/snare2.pat",start:15229617,end:15238120},{filename:"/dgguspat/soundtrk.pat",start:15238120,end:15278211},{filename:"/dgguspat/sprnosax.pat",start:15278211,end:15292924},{filename:"/dgguspat/sqrclick.pat",start:15292924,end:15293463},{filename:"/dgguspat/sqrwave.pat",
start:15293463,end:15323902},{filename:"/dgguspat/startrak.pat",start:15323902,end:15378987},{filename:"/dgguspat/steeldrm.pat",start:15378987,end:15403216},{filename:"/dgguspat/stickrim.pat",start:15403216,end:15409221},{filename:"/dgguspat/sticks.pat",start:15409221,end:15417978},{filename:"/dgguspat/surdo1.pat",start:15417978,end:15437505},{filename:"/dgguspat/surdo2.pat",start:15437505,end:15457032},{filename:"/dgguspat/sweeper.pat",start:15457032,end:15519777},{filename:"/dgguspat/synbass1.pat",
start:15519777,end:15532404},{filename:"/dgguspat/synbass2.pat",start:15532404,end:15538595},{filename:"/dgguspat/synbras1.pat",start:15538595,end:15600330},{filename:"/dgguspat/synbras2.pat",start:15600330,end:15660971},{filename:"/dgguspat/synpiano.pat",start:15660971,end:15672514},{filename:"/dgguspat/synstr1.pat",start:15672514,end:15735277},{filename:"/dgguspat/synstr2.pat",start:15735277,end:15768442},{filename:"/dgguspat/syntom.pat",start:15768442,end:15829773},{filename:"/dgguspat/taiko.pat",
start:15829773,end:15867444},{filename:"/dgguspat/tamborin.pat",start:15867444,end:15885663},{filename:"/dgguspat/telephon.pat",start:15885663,end:15894820},{filename:"/dgguspat/tenorsax.pat",start:15894820,end:15912187},{filename:"/dgguspat/timbaleh.pat",start:15912187,end:15923026},{filename:"/dgguspat/timbalel.pat",start:15923026,end:15942813},{filename:"/dgguspat/timpani.pat",start:15942813,end:15957286},{filename:"/dgguspat/tomhi1.pat",start:15957286,end:15970753},{filename:"/dgguspat/tomhi2.pat",
start:15970753,end:15984208},{filename:"/dgguspat/tomlo1.pat",start:15984208,end:15997663},{filename:"/dgguspat/tomlo2.pat",start:15997663,end:16017190},{filename:"/dgguspat/tommid1.pat",start:16017190,end:16030645},{filename:"/dgguspat/tommid2.pat",start:16030645,end:16044100},{filename:"/dgguspat/toms.pat",start:16044100,end:16057567},{filename:"/dgguspat/tremstr.pat",start:16057567,end:16180448},{filename:"/dgguspat/triangl1.pat",start:16180448,end:16185229},{filename:"/dgguspat/triangl2.pat",
start:16185229,end:16217130},{filename:"/dgguspat/trombone.pat",start:16217130,end:16243317},{filename:"/dgguspat/trumpet.pat",start:16243317,end:16256938},{filename:"/dgguspat/tuba.pat",start:16256938,end:16268785},{filename:"/dgguspat/tubebell.pat",start:16268785,end:16287422},{filename:"/dgguspat/ultramid.ini",start:16287422,end:16293731},{filename:"/dgguspat/unicorn.pat",start:16293731,end:16354236},{filename:"/dgguspat/vibes.pat",start:16354236,end:16375833},{filename:"/dgguspat/vibslap.pat",
start:16375833,end:16395080},{filename:"/dgguspat/viola.pat",start:16395080,end:16451545},{filename:"/dgguspat/violin.pat",start:16451545,end:16476606},{filename:"/dgguspat/voices.pat",start:16476606,end:16506893},{filename:"/dgguspat/voxlead.pat",start:16506893,end:16537182},{filename:"/dgguspat/warmpad.pat",start:16537182,end:16573673},{filename:"/dgguspat/whistle.pat",start:16573673,end:16585726},{filename:"/dgguspat/whistle1.pat",start:16585726,end:16590041},{filename:"/dgguspat/whistle2.pat",
start:16590041,end:16592214},{filename:"/dgguspat/woodblk.pat",start:16592214,end:16599899},{filename:"/dgguspat/woodblk1.pat",start:16599899,end:16604934},{filename:"/dgguspat/woodblk2.pat",start:16604934,end:16612619},{filename:"/dgguspat/woodflut.pat",start:16612619,end:16616810},{filename:"/dgguspat/xylophon.pat",start:16616810,end:16635895},{filename:"/duke3d.cfg",start:16635895,end:16638699},{filename:"/timidity.cfg",start:16638699,end:16641245}],remote_package_size:16641245});
var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",fa,ha;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=ea.startsWith("blob:")?"":ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1);fa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ha=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ia=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ka;h.wasmBinary&&(ka=h.wasmBinary);var la,ma=!1,na,m,r,oa,pa,v,w,x,y,qa=[],ra=[],sa=[],ta=[];
function ua(){var a=h.preRun.shift();qa.unshift(a)}var va=0,wa=null,xa=null;function ya(){va++;h.monitorRunDependencies?.(va)}function za(){va--;h.monitorRunDependencies?.(va);if(0==va&&(null!==wa&&(clearInterval(wa),wa=null),xa)){var a=xa;xa=null;a()}}function z(a){h.onAbort?.(a);a="Aborted("+a+")";k(a);ma=!0;na=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Aa=a=>a.startsWith("data:application/octet-stream;base64,"),Ba;Ba="index.wasm";
if(!Aa(Ba)){var Ca=Ba;Ba=h.locateFile?h.locateFile(Ca,ea):ea+Ca}function Da(a){if(a==Ba&&ka)return new Uint8Array(ka);throw"both async and sync fetching of the wasm failed";}function Ea(a){return ka||"function"!=typeof fetch?Promise.resolve().then(()=>Da(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw`failed to load wasm binary file at '${a}'`;return b.arrayBuffer()}).catch(()=>Da(a))}
function Fa(a,b,c){return Ea(a).then(d=>WebAssembly.instantiate(d,b)).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);z(d)})}function Ga(a,b){var c=Ba;ka||"function"!=typeof WebAssembly.instantiateStreaming||Aa(c)||"function"!=typeof fetch?Fa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Fa(c,a,b)}))}
var A,B,Na={266920:a=>{a=(a?C(r,a):"")+"\n\nAbort/Retry/Ignore/AlwaysIgnore? [ariA] :";a=window.prompt(a,"i");null===a&&(a="i");return Ha(Ia(a),"i8",Ja)},267145:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,267292:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,267526:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio=
{};b.De||("undefined"!==typeof AudioContext?b.De=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.De=new webkitAudioContext),b.De&&Ka(b.De));return void 0===b.De?-1:0},268019:()=>h.SDL2.De.sampleRate,268087:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.ef&&(clearTimeout(g.capture.ef),g.capture.ef=void 0);g.capture.nf=g.De.createMediaStreamSource(l);g.capture.Ie=g.De.createScriptProcessor(b,a,1);g.capture.Ie.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),
g.capture.wf=n.inputBuffer,La(c,[d]))};g.capture.nf.connect(g.capture.Ie);g.capture.Ie.connect(g.De.destination);g.capture.stream=l}var g=h.SDL2;g.capture.sf=g.De.createBuffer(a,b,g.De.sampleRate);g.capture.sf.getChannelData(0).fill(0);g.capture.ef=setTimeout(function(){g.capture.wf=g.capture.sf;La(c,[d])},b/g.De.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&
navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},269739:(a,b,c,d)=>{var e=h.SDL2;e.audio.Ie=e.De.createScriptProcessor(b,0,a);e.audio.Ie.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.Jf=f.outputBuffer,La(c,[d]))};e.audio.Ie.connect(e.De.destination)},270149:(a,b)=>{for(var c=h.SDL2,d=c.capture.wf.numberOfChannels,e=0;e<d;++e){var f=c.capture.wf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+
b+" samples!";if(1==d)for(var g=0;g<b;++g)Ma(a+4*g,f[g]);else for(g=0;g<b;++g)Ma(a+4*(g*d+e),f[g])}},270754:(a,b)=>{for(var c=h.SDL2,d=c.audio.Jf.numberOfChannels,e=0;e<d;++e){var f=c.audio.Jf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=x[a+(g*d+e<<2)>>2]}},271234:a=>{var b=h.SDL2;if(a){void 0!==b.capture.ef&&clearTimeout(b.capture.ef);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();
for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);b.capture.stream=void 0}void 0!==b.capture.Ie&&(b.capture.Ie.onaudioprocess=function(){},b.capture.Ie.disconnect(),b.capture.Ie=void 0);void 0!==b.capture.nf&&(b.capture.nf.disconnect(),b.capture.nf=void 0);void 0!==b.capture.sf&&(b.capture.sf=void 0);b.capture=void 0}else void 0!=b.audio.Ie&&(b.audio.Ie.disconnect(),b.audio.Ie=void 0),b.audio=void 0;void 0!==b.De&&void 0===b.audio&&void 0===b.capture&&(b.De.close(),b.De=void 0)},272406:()=>
window.innerWidth,272436:()=>window.innerHeight,272467:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.eg!==h.canvas&&(d.Ne=h.createContext(h.canvas,!1,!0),d.eg=h.canvas);if(d.w!==a||d.h!==b||d.pg!==d.Ne)d.image=d.Ne.createImageData(a,b),d.w=a,d.h=b,d.pg=d.Ne;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=v[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.hg!==a&&(d.gg=new Int32Array(a.buffer),
d.ig=new Uint8Array(a.buffer),d.hg=a),a=d.gg,c=a.length,a.set(v.subarray(b,b+c)),a=d.ig,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Ne.putImageData(d.image,0,0)},273936:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&
b instanceof CanvasPixelArray)for(n=b.length;l<n;){var p=v[e];b[l]=p&255;b[l+1]=p>>8&255;b[l+2]=p>>16&255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(v.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=E(c.length+1);F(c,r,d,c.length+1);return d},274925:a=>{h.canvas&&(h.canvas.style.cursor=a?C(r,a):"")},275008:()=>{h.canvas&&(h.canvas.style.cursor="none")}};
function Oa(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Pa=a=>{for(;0<a.length;)a.shift()(h)},Qa=h.noExitRuntime||!0;
function Ma(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":m[a]=b;break;case "i8":m[a]=b;break;case "i16":oa[a>>1]=b;break;case "i32":v[a>>2]=b;break;case "i64":z("to do setValue(i64) use WASM_BIGINT");case "float":x[a>>2]=b;break;case "double":y[a>>3]=b;break;case "*":w[a>>2]=b;break;default:z(`invalid type for setValue: ${c}`)}}
var Ra="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,C=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ra)return Ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Sa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Ta=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Sa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Ua=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Va=a=>{if("/"===
a)return"/";a=Ta(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Wa=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);z("initRandomDevice")},Xa=a=>(Xa=Wa())(a),Ya=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Sa(b.split("/").filter(e=>!!e),!c).join("/");
return(c?"/":"")+b||"."},Za=[],$a=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},F=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|
g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Ia(a,b){var c=Array($a(a)+1);a=F(a,c,0,c.length);b&&(c.length=a);return c}var ab=[];function bb(a,b){ab[a]={input:[],He:[],Se:b};cb(a,db)}
var db={open(a){var b=ab[a.node.cf];if(!b)throw new G(43);a.Be=b;a.seekable=!1},close(a){a.Be.Se.jf(a.Be)},jf(a){a.Be.Se.jf(a.Be)},read(a,b,c,d){if(!a.Be||!a.Be.Se.Mf)throw new G(60);for(var e=0,f=0;f<d;f++){try{var g=a.Be.Se.Mf(a.Be)}catch(l){throw new G(29);}if(void 0===g&&0===e)throw new G(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.Be||!a.Be.Se.zf)throw new G(60);try{for(var e=0;e<d;e++)a.Be.Se.zf(a.Be,b[c+e])}catch(f){throw new G(29);
}d&&(a.node.timestamp=Date.now());return e}},eb={Mf(){a:{if(!Za.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Za=Ia(a,!0)}a=Za.shift()}return a},zf(a,b){null===b||10===b?(ia(C(a.He,0)),a.He=[]):0!=b&&a.He.push(b)},jf(a){a.He&&0<a.He.length&&(ia(C(a.He,0)),a.He=[])},sg(){return{Hg:25856,Jg:5,Gg:191,Ig:35387,Fg:[3,28,127,21,4,0,1,0,
17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},tg(){return 0},ug(){return[24,80]}},fb={zf(a,b){null===b||10===b?(k(C(a.He,0)),a.He=[]):0!=b&&a.He.push(b)},jf(a){a.He&&0<a.He.length&&(k(C(a.He,0)),a.He=[])}};function gb(a,b){var c=a.ze?a.ze.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ze,a.ze=new Uint8Array(b),0<a.Ce&&a.ze.set(c.subarray(0,a.Ce),0))}
var H={Pe:null,Re(){return H.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new G(63);H.Pe||(H.Pe={dir:{node:{Oe:H.Jd.Oe,Je:H.Jd.Je,bf:H.Jd.bf,pf:H.Jd.pf,Xf:H.Jd.Xf,uf:H.Jd.uf,rf:H.Jd.rf,qf:H.Jd.qf,tf:H.Jd.tf},stream:{We:H.Ae.We}},file:{node:{Oe:H.Jd.Oe,Je:H.Jd.Je},stream:{We:H.Ae.We,read:H.Ae.read,write:H.Ae.write,Ff:H.Ae.Ff,yf:H.Ae.yf,Tf:H.Ae.Tf}},link:{node:{Oe:H.Jd.Oe,Je:H.Jd.Je,df:H.Jd.df},stream:{}},If:{node:{Oe:H.Jd.Oe,Je:H.Jd.Je},stream:hb}});
c=ib(a,b,c,d);I(c.mode)?(c.Jd=H.Pe.dir.node,c.Ae=H.Pe.dir.stream,c.ze={}):32768===(c.mode&61440)?(c.Jd=H.Pe.file.node,c.Ae=H.Pe.file.stream,c.Ce=0,c.ze=null):40960===(c.mode&61440)?(c.Jd=H.Pe.link.node,c.Ae=H.Pe.link.stream):8192===(c.mode&61440)&&(c.Jd=H.Pe.If.node,c.Ae=H.Pe.If.stream);c.timestamp=Date.now();a&&(a.ze[b]=c,a.timestamp=c.timestamp);return c},Qg(a){return a.ze?a.ze.subarray?a.ze.subarray(0,a.Ce):new Uint8Array(a.ze):new Uint8Array(0)},Jd:{Oe(a){var b={};b.kg=8192===(a.mode&61440)?a.id:
1;b.Nf=a.id;b.mode=a.mode;b.yg=1;b.uid=0;b.ng=0;b.cf=a.cf;I(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ce:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.ag=new Date(a.timestamp);b.xg=new Date(a.timestamp);b.dg=new Date(a.timestamp);b.bg=4096;b.cg=Math.ceil(b.size/b.bg);return b},Je(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.Ce!=b))if(0==b)a.ze=null,a.Ce=0;else{var c=a.ze;a.ze=new Uint8Array(b);c&&a.ze.set(c.subarray(0,
Math.min(b,a.Ce)));a.Ce=b}},bf(){throw jb[44];},pf(a,b,c,d){return H.createNode(a,b,c,d)},Xf(a,b,c){if(I(a.mode)){try{var d=kb(b,c)}catch(f){}if(d)for(var e in d.ze)throw new G(55);}delete a.parent.ze[a.name];a.parent.timestamp=Date.now();a.name=c;b.ze[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},uf(a,b){delete a.ze[b];a.timestamp=Date.now()},rf(a,b){var c=kb(a,b),d;for(d in c.ze)throw new G(55);delete a.ze[b];a.timestamp=Date.now()},qf(a){var b=[".",".."],c;for(c of Object.keys(a.ze))b.push(c);
return b},tf(a,b,c){a=H.createNode(a,b,41471,0);a.link=c;return a},df(a){if(40960!==(a.mode&61440))throw new G(28);return a.link}},Ae:{read(a,b,c,d,e){var f=a.node.ze;if(e>=a.node.Ce)return 0;a=Math.min(a.node.Ce-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ze||a.ze.subarray)){if(f)return a.ze=b.subarray(c,c+d),a.Ce=d;if(0===a.Ce&&0===e)return a.ze=b.slice(c,c+d),
a.Ce=d;if(e+d<=a.Ce)return a.ze.set(b.subarray(c,c+d),e),d}gb(a,e+d);if(a.ze.subarray&&b.subarray)a.ze.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ze[e+f]=b[c+f];a.Ce=Math.max(a.Ce,e+d);return d},We(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ce);if(0>b)throw new G(28);return b},Ff(a,b,c){gb(a.node,b+c);a.node.Ce=Math.max(a.node.Ce,b+c)},yf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new G(43);a=a.node.ze;if(e&2||a.buffer!==m.buffer){if(0<c||c+b<a.length)a.subarray?
a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;z();b=void 0;if(!b)throw new G(48);m.set(a,b)}else c=!1,b=a.byteOffset;return{Xg:b,Dg:c}},Tf(a,b,c,d){H.Ae.write(a,b,0,d,c,!1);return 0}}},lb=(a,b,c)=>{var d=`al ${a}`;ha(a,e=>{b(new Uint8Array(e));d&&za(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&ya(d)},mb=h.preloadPlugins||[],pb=(a,b,c,d)=>{"undefined"!=typeof nb&&ob();var e=!1;mb.forEach(f=>{!e&&f.canHandle(b)&&(f.handle(a,b,c,d),e=!0)});return e},rb=(a,b,c,
d,e,f,g,l,n,p)=>{function t(D){function J(W){p?.();l||qb(a,b,W,d,e,n);f?.();za(u)}pb(D,q,J,()=>{g?.();za(u)})||J(D)}var q=b?Ya(Ta(a+"/"+b)):a,u=`cp ${q}`;ya(u);"string"==typeof c?lb(c,t,g):t(c)},sb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},tb=null,ub={},vb=[],wb=1,xb=null,yb=!0,G=class{constructor(a){this.name="ErrnoError";this.Ee=a}},jb={},zb=class{constructor(){this.Fe={};this.node=null}get flags(){return this.Fe.flags}set flags(a){this.Fe.flags=a}get position(){return this.Fe.position}set position(a){this.Fe.position=
a}},Ab=class{constructor(a,b,c,d){a||=this;this.parent=a;this.Re=a.Re;this.Ze=null;this.id=wb++;this.name=b;this.mode=c;this.Jd={};this.Ae={};this.cf=d}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get vg(){return I(this.mode)}get Pf(){return 8192===(this.mode&61440)}};
function K(a,b={}){a=Ya(a);if(!a)return{path:"",node:null};b=Object.assign({Lf:!0,Af:0},b);if(8<b.Af)throw new G(32);a=a.split("/").filter(g=>!!g);for(var c=tb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=kb(c,a[e]);d=Ta(d+"/"+a[e]);c.Ze&&(!f||f&&b.Lf)&&(c=c.Ze.root);if(!f||b.Ye)for(f=0;40960===(c.mode&61440);)if(c=Bb(d),d=Ya(Ua(d),c),c=K(d,{Af:b.Af+1}).node,40<f++)throw new G(32);}return{path:d,node:c}}
function Cb(a){for(var b;;){if(a===a.parent)return a=a.Re.Sf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Db(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%xb.length}function Eb(a){var b=Db(a.parent.id,a.name);if(xb[b]===a)xb[b]=a.$e;else for(b=xb[b];b;){if(b.$e===a){b.$e=a.$e;break}b=b.$e}}
function kb(a,b){var c=I(a.mode)?(c=Fb(a,"x"))?c:a.Jd.bf?0:2:54;if(c)throw new G(c);for(c=xb[Db(a.id,b)];c;c=c.$e){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Jd.bf(a,b)}function ib(a,b,c,d){a=new Ab(a,b,c,d);b=Db(a.parent.id,a.name);a.$e=xb[b];return xb[b]=a}function I(a){return 16384===(a&61440)}function Gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Fb(a,b){if(yb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Hb(a,b){try{return kb(a,b),20}catch(c){}return Fb(a,"wx")}function Ib(a,b,c){try{var d=kb(a,b)}catch(e){return e.Ee}if(a=Fb(a,"wx"))return a;if(c){if(!I(d.mode))return 54;if(d===d.parent||"/"===Cb(d))return 10}else if(I(d.mode))return 31;return 0}function Jb(a){a=vb[a];if(!a)throw new G(8);return a}
function Kb(a,b=-1){a=Object.assign(new zb,a);if(-1==b)a:{for(b=0;4096>=b;b++)if(!vb[b])break a;throw new G(33);}a.fd=b;return vb[b]=a}function Lb(a,b=-1){a=Kb(a,b);a.Ae?.Mg?.(a);return a}var hb={open(a){a.Ae=ub[a.node.cf].Ae;a.Ae.open?.(a)},We(){throw new G(70);}};function cb(a,b){ub[a]={Ae:b}}
function Mb(a,b){var c="/"===b;if(c&&tb)throw new G(10);if(!c&&b){var d=K(b,{Lf:!1});b=d.path;d=d.node;if(d.Ze)throw new G(10);if(!I(d.mode))throw new G(54);}b={type:a,Wg:{},Sf:b,wg:[]};a=a.Re(b);a.Re=b;b.root=a;c?tb=a:d&&(d.Ze=b,d.Re&&d.Re.wg.push(b))}function Nb(a,b,c){var d=K(a,{parent:!0}).node;a=Va(a);if(!a||"."===a||".."===a)throw new G(28);var e=Hb(d,a);if(e)throw new G(e);if(!d.Jd.pf)throw new G(63);return d.Jd.pf(d,a,b,c)}function L(a,b){return Nb(a,(void 0!==b?b:511)&1023|16384,0)}
function Ob(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Nb(a,b|8192,c)}function Pb(a,b){if(!Ya(a))throw new G(44);var c=K(b,{parent:!0}).node;if(!c)throw new G(44);b=Va(b);var d=Hb(c,b);if(d)throw new G(d);if(!c.Jd.tf)throw new G(63);c.Jd.tf(c,b,a)}function Qb(a){var b=K(a,{parent:!0}).node;if(!b)throw new G(44);a=Va(a);var c=kb(b,a),d=Ib(b,a,!1);if(d)throw new G(d);if(!b.Jd.uf)throw new G(63);if(c.Ze)throw new G(10);b.Jd.uf(b,a);Eb(c)}
function Bb(a){a=K(a).node;if(!a)throw new G(44);if(!a.Jd.df)throw new G(28);return Ya(Cb(a.parent),a.Jd.df(a))}function Rb(a,b){a=K(a,{Ye:!b}).node;if(!a)throw new G(44);if(!a.Jd.Oe)throw new G(63);return a.Jd.Oe(a)}function Sb(a){return Rb(a,!0)}function Tb(a,b){a="string"==typeof a?K(a,{Ye:!0}).node:a;if(!a.Jd.Je)throw new G(63);a.Jd.Je(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Ub(a,b,c){if(""===a)throw new G(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=Ta(a);try{e=K(a,{Ye:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new G(20);}else e=Nb(a,c,0),d=!0;if(!e)throw new G(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!I(e.mode))throw new G(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:I(e.mode)&&("r"!==Gb(b)||b&512)?31:Fb(e,Gb(b)):44))throw new G(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Ye:!0}).node:c;if(!c.Jd.Je)throw new G(63);if(I(c.mode))throw new G(31);if(32768!==(c.mode&61440))throw new G(28);if(d=Fb(c,"w"))throw new G(d);c.Jd.Je(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Kb({node:e,path:Cb(e),flags:b,seekable:!0,position:0,Ae:e.Ae,Ag:[],error:!1});e.Ae.open&&e.Ae.open(e);!h.logReadFiles||b&1||(Vb||={},a in Vb||(Vb[a]=1));return e}
function Wb(a){if(null===a.fd)throw new G(8);a.Ve&&(a.Ve=null);try{a.Ae.close&&a.Ae.close(a)}catch(b){throw b;}finally{vb[a.fd]=null}a.fd=null}function Xb(a,b,c){if(null===a.fd)throw new G(8);if(!a.seekable||!a.Ae.We)throw new G(70);if(0!=c&&1!=c&&2!=c)throw new G(28);a.position=a.Ae.We(a,b,c);a.Ag=[];return a.position}
function Yb(a,b,c,d,e,f){if(0>d||0>e)throw new G(28);if(null===a.fd)throw new G(8);if(0===(a.flags&2097155))throw new G(8);if(I(a.node.mode))throw new G(31);if(!a.Ae.write)throw new G(28);a.seekable&&a.flags&1024&&Xb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new G(70);b=a.Ae.write(a,b,c,d,e,f);g||(a.position+=b);return b}var Zb;
function $b(a,b){a="string"==typeof a?a:Cb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Ta(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}function ac(a,b,c,d){a=Ta(("string"==typeof a?a:Cb(a))+"/"+b);c=sb(c,d);return Nb(a,(void 0!==c?c:438)&4095|32768,0)}
function qb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Cb(a),g=b?Ta(a+"/"+b):a);a=sb(d,e);g=Nb(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Tb(g,a|146);b=Ub(g,577);Yb(b,c,0,c.length,0,f);Wb(b);Tb(g,a)}}
function bc(a,b,c,d){a=Ta(("string"==typeof a?a:Cb(a))+"/"+b);b=sb(!!c,!!d);bc.Qf||(bc.Qf=64);var e=bc.Qf++<<8|0;cb(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,l,n){for(var p=0,t=0;t<n;t++){try{var q=c()}catch(u){throw new G(29);}if(void 0===q&&0===p)throw new G(6);if(null===q||void 0===q)break;p++;g[l+t]=q}p&&(f.node.timestamp=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{d(g[l+p])}catch(t){throw new G(29);}n&&(f.node.timestamp=Date.now());return p}});return Ob(a,
b,e)}function cc(a){if(!(a.Pf||a.vg||a.link||a.ze)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(fa)try{a.ze=Ia(fa(a.url),!0),a.Ce=a.ze.length}catch(b){throw new G(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function dc(a,b,c,d,e){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Pf:!1,url:c};var f=ac(a,b,d,e);c.ze?f.ze=c.ze:c.url&&(f.ze=null,f.url=c.url);Object.defineProperties(f,{Ce:{get:function(){return this.ze.length}}});var g={};Object.keys(f.Ae).forEach(l=>{var n=f.Ae[l];g[l]=(...p)=>{cc(f);return n(...p)}});g.read=(l,n,p,t,q)=>{cc(f);l=l.node.ze;if(q>=l.length)n=0;else{t=Math.min(l.length-
q,t);if(l.slice)for(var u=0;u<t;u++)n[p+u]=l[q+u];else for(u=0;u<t;u++)n[p+u]=l.get(q+u);n=t}return n};g.yf=()=>{cc(f);z();throw new G(48);};f.Ae=g;return f}var M={},Vb;function ec(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?"/":Jb(a).path;if(0==b.length){if(!c)throw new G(44);return a}return Ta(a+"/"+b)}
function fc(a,b,c){a=a(b);v[c>>2]=a.kg;v[c+4>>2]=a.mode;w[c+8>>2]=a.yg;v[c+12>>2]=a.uid;v[c+16>>2]=a.ng;v[c+20>>2]=a.cf;B=[a.size>>>0,(A=a.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+24>>2]=B[0];v[c+28>>2]=B[1];v[c+32>>2]=4096;v[c+36>>2]=a.cg;b=a.ag.getTime();var d=a.xg.getTime(),e=a.dg.getTime();B=[Math.floor(b/1E3)>>>0,(A=Math.floor(b/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:
0)];v[c+40>>2]=B[0];v[c+44>>2]=B[1];w[c+48>>2]=b%1E3*1E3;B=[Math.floor(d/1E3)>>>0,(A=Math.floor(d/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+56>>2]=B[0];v[c+60>>2]=B[1];w[c+64>>2]=d%1E3*1E3;B=[Math.floor(e/1E3)>>>0,(A=Math.floor(e/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+72>>2]=B[0];v[c+76>>2]=B[1];w[c+80>>2]=e%1E3*1E3;B=[a.Nf>>>0,(A=a.Nf,1<=+Math.abs(A)?0<A?+Math.floor(A/
4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[c+88>>2]=B[0];v[c+92>>2]=B[1];return 0}var gc=void 0;function hc(){var a=v[+gc>>2];gc+=4;return a}
var ic=[0,31,60,91,121,152,182,213,244,274,305,335],jc=[0,31,59,90,120,151,181,212,243,273,304,334],uc=(a,b)=>{kc=a;lc=b;if(mc)if(nc||=!0,0==a)oc=function(){var d=Math.max(0,pc+b-qc())|0;setTimeout(rc,d)};else if(1==a)oc=function(){sc(rc)};else if(2==a){if("undefined"==typeof tc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);tc=function(d){c.push(d);postMessage("setimmediate",
"*")}}else tc=setImmediate;oc=function(){tc(rc)}}},qc;qc=()=>performance.now();
var Bc=a=>{mc=a;var b=vc;nc=!1;rc=function(){if(!ma)if(0<wc.length){var c=wc.shift();c.Pg(c.Eg);if(xc){var d=xc,e=0==d%1?d-1:Math.floor(d);xc=c.Lg?e:(8*d+(e+.5))/9}h.setStatus&&(c=h.statusMessage||"Please wait...",d=xc,e=yc.Ng,d?d<e?h.setStatus("{message} ({expected - remaining}/{expected})"):h.setStatus(c):h.setStatus(""));b<vc||setTimeout(rc,0)}else b<vc||(zc=zc+1|0,1==kc&&1<lc&&0!=zc%lc?oc():(0==kc&&(pc=qc()),ma||h.preMainLoop&&!1===h.preMainLoop()||(Ac(a),h.postMainLoop?.()),b<vc||("object"==
typeof SDL&&SDL.audio?.Yg?.(),oc())))}},Cc=a=>{a instanceof Oa||"unwind"==a||da(1,a)},Dc=0,Ec=a=>{na=a;Qa||0<Dc||(h.onExit?.(a),ma=!0);da(a,new Oa(a))},Fc=a=>{na=a;Ec(a)},Ac=a=>{if(!ma)try{if(a(),!(Qa||0<Dc))try{na=a=na,Ec(a)}catch(b){Cc(b)}}catch(b){Cc(b)}},Gc=(a,b)=>setTimeout(()=>{Ac(a)},b),nc=!1,oc=null,vc=0,mc=null,kc=0,lc=0,zc=0,wc=[];function Hc(){oc=null;vc++}function Ic(){vc++;var a=kc,b=lc,c=mc;mc=null;Bc(c);uc(a,b);oc()}var yc={},pc,rc,xc,Jc=!1,Kc=!1,Lc=[];
function ob(){function a(){Kc=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Mc){Mc=!0;mb.push({canHandle:function(c){return!h.Vg&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Nc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Nc(d)}));var l=URL.createObjectURL(g),n=new Image;n.onload=()=>{var p=document.createElement("canvas");
p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(l);e?.(c)};n.onerror=()=>{k(`Image ${l} could not be decoded`);f?.()};n.src=l}});mb.push({canHandle:function(c){return!h.Ug&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e?.(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Nc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",t=0,q=0,u=0;u<c.length;u++)for(t=t<<8|c[u],q+=8;6<=q;){var D=t>>q-6&63;q-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[D]}2==q?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==q&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=l;Gc(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Kc&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Oc=!1,Pc=void 0,Qc=void 0;function Rc(){if(!Jc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Sc=0;
function sc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Sc)Sc=b+1E3/60;else for(;b+2>=Sc;)Sc+=1E3/60;setTimeout(a,Math.max(Sc-b,0))}}function Nc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Tc=[];function Uc(){var a=h.canvas;Tc.forEach(b=>b(a.width,a.height))}
function Vc(a,b,c){b&&c?(a.Cg=b,a.og=c):(b=a.Cg,c=a.og);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Qc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var nb={},tc,Mc,N=12288,Wc=!1,Xc=0,Yc=0,Zc=0,O={alpha:!1,depth:!1,stencil:!1,antialias:!1},$c={},ad,bd=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},cd=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},dd=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},ed=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},fd=1,gd=[],P=[],hd=[],jd=[],kd=[],Q=[],ld=[],md=[],nd=[],od={},pd=4,qd=a=>{for(var b=fd++,c=a.length;c<b;c++)a[c]=null;return b},rd=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=R[c](),g=f&&qd(d);f?(f.name=g,d[g]=f):S||=1282;v[b+4*e>>2]=g}},td=(a,b)=>{a.Fe||(a.Fe=a.getContext,a.getContext=function(d,e){e=a.Fe(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?sd(c,b):0},sd=(a,b)=>{var c=
qd(md),d={handle:c,attributes:b,version:b.Rf,Te:a};a.canvas&&(a.canvas.af=d);md[c]=d;("undefined"==typeof b.lg||b.lg)&&ud(d);return c},wd=a=>{vd=md[a];h.Ne=R=vd?.Te},ud=a=>{a||=vd;if(!a.qg){a.qg=!0;var b=a.Te;bd(b);cd(b);dd(b);b.Qe=b.getExtension("EXT_disjoint_timer_query");b.Tg=b.getExtension("WEBGL_multi_draw");ed(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},xd={},S,vd,yd=a=>{var b=$a(a)+1,c=E(b);c&&F(a,r,c,b);return c},zd=[],Ad=(a,b)=>{zd.length=0;for(var c;c=
r[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;zd.push(112==c?w[b>>2]:105==c?v[b>>2]:y[b>>3]);b+=d?8:4}return zd},Dd=a=>{var b=Bd();a=a();Cd(b);return a},Ed=0,Fd=[];function Gd(a,b,c){function d(g,l){if(g.length!=l.length)return!1;for(var n in g)if(g[n]!=l[n])return!1;return!0}for(var e in Fd){var f=Fd[e];if(f.Cf==a&&d(f.Gf,c))return}Fd.push({Cf:a,Vf:b,Gf:c});Fd.sort((g,l)=>g.Vf<l.Vf)}function Hd(a){for(var b=0;b<Fd.length;++b)Fd[b].Cf==a&&(Fd.splice(b,1),--b)}
function Id(){return navigator.userActivation?navigator.userActivation.isActive:Ed&&Jd.gf}function Kd(){if(Id())for(var a=0;a<Fd.length;++a){var b=Fd[a];Fd.splice(a,1);--a;b.Cf(...b.Gf)}}var Ld=[];function Md(a){var b=Ld[a];b.target.removeEventListener(b.Ge,b.Kf,b.Ke);Ld.splice(a,1)}
function T(a){if(!a.target)return-4;if(a.Le)a.Kf=function(c){++Ed;Jd=a;Kd();a.Me(c);Kd();--Ed},a.target.addEventListener(a.Ge,a.Kf,a.Ke),Ld.push(a);else for(var b=0;b<Ld.length;++b)Ld[b].target==a.target&&Ld[b].Ge==a.Ge&&Md(b--);return 0}function Nd(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}function Od(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Pd={},Jd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be={},ce=[0,document,window],U=a=>{a=2<a?a?C(r,a):"":a;return ce[a]||document.querySelector(a)},ee=a=>{var b=$a(a)+1,c=de(b);F(a,r,c,b);return c},fe=a=>Dd(()=>{var b=de(8),c=b+4,d=ee(a.id);if(d=U(d))v[b>>2]=d.width,v[c>>2]=d.height;return[v[b>>2],v[c>>2]]}),ge=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},he=(a,b,c)=>{a.Kg?Dd(()=>{var d=ee(a.id);ge(d,b,c)}):(a.width=b,a.height=c)},ie=a=>{function b(){document.fullscreenElement||document.webkitFullscreenElement||
(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),he(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=t,a.style.paddingTop=q,a.style.paddingBottom=u,a.style.marginLeft=D,a.style.marginRight=J,a.style.marginTop=W,a.style.marginBottom=ja,document.body.style.margin=bf,document.documentElement.style.overflow=
cf,document.body.scroll=df,a.style.Ue=ef,a.af&&a.af.Te.viewport(0,0,d,e),be.hf&&V(be.hf,37,0,be.Hf))}var c=fe(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,q=a.style.paddingTop,u=a.style.paddingBottom,D=a.style.marginLeft,J=a.style.marginRight,W=a.style.marginTop,ja=a.style.marginBottom,bf=document.body.style.margin,cf=document.documentElement.style.overflow,df=document.body.scroll,ef=
a.style.Ue;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},je=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ke=a=>0>ce.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},le=(a,b)=>{if(0!=b.Bf||0!=b.vf){ie(a);var c=b.zg?innerWidth:screen.width,d=b.zg?innerHeight:screen.height,e=ke(a),f=e.width;e=e.height;var g=fe(a),l=g[0];g=g[1];3==b.Bf?(je(a,(d-e)/2,(c-f)/2),c=f,d=e):2==b.Bf&&(c*g<
l*d?(f=g*c/l,je(a,(d-f)/2,0),d=f):(f=l*d/g,je(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.mg&&(a.style.Ue="optimizeSpeed",a.style.Ue="-moz-crisp-edges",a.style.Ue="-o-crisp-edges",a.style.Ue="-webkit-optimize-contrast",a.style.Ue="optimize-contrast",a.style.Ue="crisp-edges",a.style.Ue="pixelated");f=2==b.vf?devicePixelRatio:1;0!=b.vf&&
(c=c*f|0,d=d*f|0,he(a,c,d),a.af&&a.af.Te.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Od()?-3:-1;be=b;b.hf&&V(b.hf,37,0,b.Hf);return 0},me=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},ne=(a,b)=>{y[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)y[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)y[a+8*c+528>>
3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)v[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];v[a+1296>>2]=b.connected;v[a+1300>>2]=b.index;v[a+8>>2]=b.axes.length;v[a+12>>2]=b.buttons.length;F(b.id,r,a+1304,64);F(b.mapping,r,a+1368,64)},oe=[],pe=(a,b,c,d,e,f,g,l)=>{b=P[b];if(a=R[a](b,c))d=l&&F(a.name,r,l,d),e&&(v[e>>2]=d),f&&(v[f>>2]=a.size),g&&(v[g>>2]=a.type)},qe=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=
1;break;case 36344:0!=c&&1!=c&&(S||=1280);return;case 36345:d=0;break;case 34466:var e=R.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=R.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":S||=1280;return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:S||=1280;return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||
e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:v[b+4*a>>2]=e[a];break;case 2:x[b+4*a>>2]=e[a];break;case 4:m[b+a]=e[a]?1:0}return}try{d=e.name|0}catch(f){S||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:S||=1280;k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);return}switch(c){case 1:c=d;w[b>>2]=c;w[b+4>>2]=(c-w[b>>2])/4294967296;break;
case 0:v[b>>2]=d;break;case 2:x[b>>2]=d;break;case 4:m[b]=d?1:0}}else S||=1281},re=(a,b,c)=>{if(c){a=R.Qe.getQueryObjectEXT(nd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d;w[c+4>>2]=(d-w[c>>2])/4294967296}else S||=1281},se=(a,b,c)=>{if(c){a=R.Qe.getQueryObjectEXT(nd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;v[c>>2]=d}else S||=1281};function te(){var a=ed(R);return a=a.concat(a.map(b=>"GL_"+b))}
var ue=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ve=a=>{var b=a.ff,c=a.Zf,d;if(!b)for(a.ff=b={},a.Yf={},d=0;d<R.getProgramParameter(a,35718);++d){var e=R.getActiveUniform(a,d);var f=e.name;e=e.size;var g=ue(f);g=0<g?f.slice(0,g):f;var l=a.Df;a.Df+=e;c[g]=[e,l];for(f=0;f<e;++f)b[l]=f,a.Yf[l++]=g}},X=a=>{var b=R.fg;if(b){var c=b.ff[a];"number"==typeof c&&(b.ff[a]=c=R.getUniformLocation(b,b.Yf[a]+(0<c?`[${c}]`:"")));return c}S||=1282},we=(a,b,c,d)=>{if(c)if(a=P[a],ve(a),a=R.getUniform(a,X(b)),"number"==
typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:x[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b]}else S||=1281},xe=(a,b,c,d)=>{if(c)if(a=R.getVertexAttrib(a,b),34975==b)v[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:v[c>>2]=a;break;case 2:x[c>>2]=a;break;case 5:v[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:v[c+4*b>>2]=a[b];break;case 2:x[c+4*b>>2]=a[b];break;case 5:v[c+
4*b>>2]=Math.fround(a[b])}else S||=1281},ye=(a,b,c,d,e)=>{a-=5120;a=1==a?r:4==a?v:6==a?x:5==a||28922==a?w:pa;var f=pd;b=d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*a.BYTES_PER_ELEMENT+f-1&-f);return a.subarray(e>>>31-Math.clz32(a.BYTES_PER_ELEMENT),e+b>>>31-Math.clz32(a.BYTES_PER_ELEMENT))},ze=[],Ae=[],Be=(a,b)=>{if(!Od())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Id()?le(a,b):b.jg?(Gd(le,1,[a,b]),1):-2:-3:-4},Ce=()=>{try{if(navigator.getGamepads)return(Qd=navigator.getGamepads())?
0:-1}catch(a){navigator.getGamepads=null}return-1},De=(a,b)=>{var c={target:U(2),Ge:"beforeunload",Le:b,Me:(d=event)=>{var e=V(b,28,0,a);e&&=e?C(r,e):"";if(e)return d.preventDefault(),d.returnValue=e},Ke:!0};return T(c)},Ee=(a,b,c,d,e,f)=>{Rd||=E(256);a={target:U(a),Ge:f,Le:d,Me:(g=event)=>{var l=g.target.id?g.target.id:"",n=Rd;F(Nd(g.target),r,n+0,128);F(l,r,n+128,128);V(d,e,n,b)&&g.preventDefault()},Ke:c};return T(a)},Fe=(a,b,c,d,e)=>{Td||=E(280);return T({target:a,Ge:e,Le:d,Me:(f=event)=>{var g=
Td,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;v[g>>2]=n;v[g+4>>2]=Od();var p=n?l:Sd,t=p?.id||"";F(Nd(p),r,g+8,128);F(t,r,g+136,128);v[g+264>>2]=p?p.clientWidth:0;v[g+268>>2]=p?p.clientHeight:0;v[g+272>>2]=screen.width;v[g+276>>2]=screen.height;n&&(Sd=l);V(d,19,g,b)&&f.preventDefault()},Ke:c})},Ge=(a,b,c,d,e)=>{Ud||=E(1432);b={target:U(2),gf:!0,Ge:e,Le:c,Me:(f=event)=>{var g=Ud;ne(g,f.gamepad);V(c,d,g,a)&&f.preventDefault()},
Ke:b};return T(b)},He=(a,b,c,d,e,f)=>{Vd||=E(176);a={target:U(a),Ge:f,Le:d,Me:g=>{var l=Vd;y[l>>3]=g.timeStamp;var n=l>>2;v[n+2]=g.location;v[n+3]=g.ctrlKey;v[n+4]=g.shiftKey;v[n+5]=g.altKey;v[n+6]=g.metaKey;v[n+7]=g.repeat;v[n+8]=g.charCode;v[n+9]=g.keyCode;v[n+10]=g.which;F(g.key||"",r,l+44,32);F(g.code||"",r,l+76,32);F(g.char||"",r,l+108,32);F(g.locale||"",r,l+140,32);V(d,e,l,b)&&g.preventDefault()},Ke:c};return T(a)},Ie=(a,b,c)=>{y[a>>3]=b.timeStamp;a>>=2;v[a+2]=b.screenX;v[a+3]=b.screenY;v[a+
4]=b.clientX;v[a+5]=b.clientY;v[a+6]=b.ctrlKey;v[a+7]=b.shiftKey;v[a+8]=b.altKey;v[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;v[a+11]=b.movementX;v[a+12]=b.movementY;c=ke(c);v[a+13]=b.clientX-(c.left|0);v[a+14]=b.clientY-(c.top|0)},Je=(a,b,c,d,e,f)=>{Wd||=E(72);a=U(a);return T({target:a,gf:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,Ge:f,Le:d,Me:(g=event)=>{Ie(Wd,g,a);V(d,e,Wd,b)&&g.preventDefault()},Ke:c})},Ke=(a,b,c,d,e)=>{Xd||=E(260);return T({target:a,Ge:e,Le:d,Me:(f=event)=>
{var g=Xd,l=document.pointerLockElement||document.Fe||document.$f||document.Ef;v[g>>2]=!!l;var n=l?.id||"";F(Nd(l),r,g+4,128);F(n,r,g+132,128);V(d,20,g,b)&&f.preventDefault()},Ke:c})},Le=(a,b,c,d)=>{Yd||=E(36);a=U(a);return T({target:a,Ge:"resize",Le:d,Me:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=Yd;v[g>>2]=0;v[g+4>>2]=f.clientWidth;v[g+8>>2]=f.clientHeight;v[g+12>>2]=innerWidth;v[g+16>>2]=innerHeight;v[g+20>>2]=outerWidth;v[g+24>>2]=outerHeight;v[g+28>>2]=pageXOffset|0;v[g+32>>
2]=pageYOffset|0;V(d,10,g,b)&&e.preventDefault()}}},Ke:c})},Me=(a,b,c,d,e,f)=>{Zd||=E(1696);a=U(a);return T({target:a,gf:"touchstart"==f||"touchend"==f,Ge:f,Le:d,Me:g=>{for(var l,n={},p=g.touches,t=0;t<p.length;++t)l=p[t],l.Of=l.Uf=0,n[l.identifier]=l;for(t=0;t<g.changedTouches.length;++t)l=g.changedTouches[t],l.Of=1,n[l.identifier]=l;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Uf=1;p=Zd;y[p>>3]=g.timeStamp;var q=p>>2;v[q+3]=g.ctrlKey;v[q+4]=g.shiftKey;v[q+5]=g.altKey;v[q+
6]=g.metaKey;q+=7;var u=ke(a),D=0;for(t in n)if(l=n[t],v[q]=l.identifier,v[q+1]=l.screenX,v[q+2]=l.screenY,v[q+3]=l.clientX,v[q+4]=l.clientY,v[q+5]=l.pageX,v[q+6]=l.pageY,v[q+7]=l.Of,v[q+8]=l.Uf,v[q+9]=l.clientX-(u.left|0),v[q+10]=l.clientY-(u.top|0),q+=13,31<++D)break;v[p+8>>2]=D;V(d,e,p,b)&&g.preventDefault()},Ke:c})},Ne=(a,b,c)=>{var d=ce[1];$d||=E(8);return T({target:d,Ge:"visibilitychange",Le:c,Me:(e=event)=>{var f=$d,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);
v[f>>2]=document.hidden;v[f+4>>2]=g;V(c,21,f,a)&&e.preventDefault()},Ke:b})},Oe=(a,b,c,d)=>{ae||=E(104);return T({target:a,gf:!0,Ge:"wheel",Le:d,Me:(e=event)=>{var f=ae;Ie(f,e,a);y[f+72>>3]=e.deltaX;y[f+80>>3]=e.deltaY;y[f+88>>3]=e.deltaZ;v[f+96>>2]=e.deltaMode;V(d,9,f,b)&&e.preventDefault()},Ke:c})},Pe={},Re=()=>{if(!Qe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-",
"_")+".UTF-8",_:ca||"./this.program"},b;for(b in Pe)void 0===Pe[b]?delete a[b]:a[b]=Pe[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);Qe=c}return Qe},Qe,Se=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ka=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Se(d,c,()=>{"suspended"===a.state&&a.resume()})})})},La=(a,b=[])=>{var c="vi".replace(/p/g,"i");(0,h["dynCall_"+c])(a,...b)},Te=a=>{try{a()}catch(b){z(b)}};
function Ue(){var a=Y,b={};for(let [c,d]of Object.entries(a))b[c]="function"==typeof d?(...e)=>{Ve.push(c);try{return d(...e)}finally{ma||(Ve.pop(),We&&1===Xe&&0===Ve.length&&(Xe=0,Te(Ye),"undefined"!=typeof Fibers&&Fibers.Zg()))}}:d;return b}var Xe=0,We=null,Ze=0,Ve=[],$e={},af={},ff=0,gf=null,hf=[];function jf(){var a=E(4108),b=a+12;w[a>>2]=b;w[a+4>>2]=b+4096;b=Ve[0];var c=$e[b];void 0===c&&(c=ff++,$e[b]=c,af[c]=b);v[a+8>>2]=c;return a}
function kf(a){if(!ma){if(0===Xe){var b=!1,c=!1;a((d=0)=>{if(!ma&&(Ze=d,b=!0,c)){Xe=2;Te(()=>lf(We));"undefined"!=typeof nb&&mc&&Ic();d=!1;try{var e=(0,Y[af[v[We+8>>2]]])()}catch(l){e=l,d=!0}var f=!1;if(!We){var g=gf;g&&(gf=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Xe=1,We=jf(),"undefined"!=typeof nb&&mc&&Hc(),Te(()=>mf(We)))}else 2===Xe?(Xe=0,Te(nf),of(We),We=null,hf.forEach(Ac)):z(`invalid state: ${Xe}`);return Ze}}
var Ja=0,Ha=(a,b)=>{b=1==b?de(a.length):E(a.length);a.subarray||a.slice||(a=new Uint8Array(a));r.set(a,b);return b};[44].forEach(a=>{jb[a]=new G(a);jb[a].stack="<generic error, no stack>"});xb=Array(4096);Mb(H,"/");L("/tmp");L("/home");L("/home/web_user");
(function(){L("/dev");cb(259,{read:()=>0,write:(d,e,f,g)=>g});Ob("/dev/null",259);bb(1280,eb);bb(1536,fb);Ob("/dev/tty",1280);Ob("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Xa(a).byteLength);return a[--b]};bc("/dev","random",c);bc("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Mb({Re(){var b=ib(a,"fd",16895,73);b.Jd={bf(c,d){var e=Jb(+d);c={parent:null,Re:{Sf:"fake"},Jd:{df:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=$b;h.FS_createDataFile=qb;h.FS_createPreloadedFile=rb;h.FS_unlink=Qb;h.FS_createLazyFile=dc;h.FS_createDevice=bc;
h.requestFullscreen=function(a,b){function c(){Jc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Rc,Pc&&d.requestPointerLock(),Jc=!0,Qc?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=w[SDL.screen>>2]|8388608),Vc(h.canvas),Uc()):Vc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Qc?("undefined"!=typeof SDL&&(v[SDL.screen>>2]=
w[SDL.screen>>2]&-8388609),Vc(h.canvas),Uc()):Vc(d));h.onFullScreen?.(Jc);h.onFullscreen?.(Jc)}Pc=a;Qc=b;"undefined"==typeof Pc&&(Pc=!0);"undefined"==typeof Qc&&(Qc=!1);var d=h.canvas;Oc||(Oc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);e.requestFullscreen=
e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=sc;h.setCanvasSize=function(a,b,c){Vc(h.canvas,a,b);c||Uc()};h.pauseMainLoop=Hc;h.resumeMainLoop=Ic;
h.getUserMedia=function(a){let b;(b=window).getUserMedia||(b.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};h.createContext=function(a,b,c,d){if(b&&h.Ne&&a==h.canvas)return h.Ne;var e;if(b){var f={antialias:!1,alpha:!1,Rf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof xd&&(e=td(a,f)))var l=md[e].Te}else l=a.getContext("2d");if(!l)return null;c&&(h.Ne=l,b&&wd(e),h.Bg=b,Lc.forEach(n=>n()),ob());return l};for(var R,Z=0;32>Z;++Z)oe.push(Array(Z));
var pf=new Float32Array(288);for(Z=0;288>Z;++Z)ze[Z]=pf.subarray(0,Z);var qf=new Int32Array(288);for(Z=0;288>Z;++Z)Ae[Z]=qf.subarray(0,Z);
var rf={a:(a,b,c,d)=>{z(`Assertion failed: ${a?C(r,a):""}, at: `+[b?b?C(r,b):"":"unknown filename",c,d?d?C(r,d):"":"unknown function"])},gb:function(a,b,c){try{b=b?C(r,b):"";b=ec(a,b);if(c&-8)return-28;var d=K(b,{Ye:!0}).node;if(!d)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&Fb(d,a)?-2:0}catch(e){if("undefined"==typeof M||"ErrnoError"!==e.name)throw e;return-e.Ee}},P:function(a,b,c){gc=c;try{var d=Jb(a);switch(b){case 0:var e=hc();if(0>e)break;for(;vb[e];)e++;return Lb(d,e).fd;
case 1:case 2:return 0;case 3:return d.flags;case 4:return e=hc(),d.flags|=e,0;case 12:return e=hc(),oa[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Ee}},bb:function(a,b){try{var c=Jb(a);return fc(Rb,c.path,b)}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.Ee}},Va:function(a,b,c){try{var d=Jb(a);if(!d.Ve){var e=K(d.path,{Ye:!0}).node;if(!e.Jd.qf)throw new G(54);var f=e.Jd.qf(e);d.Ve=f}a=0;for(var g=
Xb(d,0,1),l=Math.floor(g/280);l<d.Ve.length&&a+280<=c;){var n=d.Ve[l];if("."===n){var p=d.node.id;var t=4}else if(".."===n)p=K(d.path,{parent:!0}).node.id,t=4;else{var q=kb(d.node,n);p=q.id;t=8192===(q.mode&61440)?2:I(q.mode)?4:40960===(q.mode&61440)?10:8}B=[p>>>0,(A=p,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[b+a>>2]=B[0];v[b+a+4>>2]=B[1];B=[280*(l+1)>>>0,(A=280*(l+1),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>
0))/4294967296)>>>0:0)];v[b+a+8>>2]=B[0];v[b+a+12>>2]=B[1];oa[b+a+16>>1]=280;m[b+a+18]=t;F(n,r,b+a+19,256);a+=280;l+=1}Xb(d,280*l,0);return a}catch(u){if("undefined"==typeof M||"ErrnoError"!==u.name)throw u;return-u.Ee}},cb:function(a,b,c){gc=c;try{var d=Jb(a);switch(b){case 21509:return d.Be?0:-59;case 21505:if(!d.Be)return-59;if(d.Be.Se.sg){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=hc();v[e>>2]=25856;v[e+4>>2]=5;v[e+8>>2]=191;v[e+12>>2]=35387;for(var f=
0;32>f;f++)m[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.Be?0:-59;case 21506:case 21507:case 21508:if(!d.Be)return-59;if(d.Be.Se.tg)for(e=hc(),a=[],f=0;32>f;f++)a.push(m[e+f+17]);return 0;case 21519:if(!d.Be)return-59;e=hc();return v[e>>2]=0;case 21520:return d.Be?-28:-59;case 21531:e=hc();if(!d.Ae.rg)throw new G(59);return d.Ae.rg(d,b,e);case 21523:if(!d.Be)return-59;d.Be.Se.ug&&(f=[24,80],e=hc(),oa[e>>1]=f[0],oa[e+2>>1]=f[1]);return 0;case 21524:return d.Be?0:-59;case 21515:return d.Be?
0:-59;default:return-28}}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return-g.Ee}},$a:function(a,b){try{return a=a?C(r,a):"",fc(Sb,a,b)}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.Ee}},Xa:function(a,b,c){try{return b=b?C(r,b):"",b=ec(a,b),b=Ta(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),L(b,c),0}catch(d){if("undefined"==typeof M||"ErrnoError"!==d.name)throw d;return-d.Ee}},_a:function(a,b,c,d){try{b=b?C(r,b):"";var e=d&256;b=ec(a,b,d&4096);
return fc(e?Sb:Rb,b,c)}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Ee}},O:function(a,b,c,d){gc=d;try{b=b?C(r,b):"";b=ec(a,b);var e=d?hc():0;return Ub(b,c,e).fd}catch(f){if("undefined"==typeof M||"ErrnoError"!==f.name)throw f;return-f.Ee}},ab:function(a,b){try{return a=a?C(r,a):"",fc(Rb,a,b)}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return-c.Ee}},Ta:function(a,b,c){try{b=b?C(r,b):"";b=ec(a,b);if(0===c)Qb(b);else if(512===c){a=b;var d=K(a,{parent:!0}).node,
e=Va(a),f=kb(d,e),g=Ib(d,e,!0);if(g)throw new G(g);if(!d.Jd.rf)throw new G(63);if(f.Ze)throw new G(10);d.Jd.rf(d,e);Eb(f)}else z("Invalid flags passed to unlinkat");return 0}catch(l){if("undefined"==typeof M||"ErrnoError"!==l.name)throw l;return-l.Ee}},fb:()=>1,eb:(a,b,c)=>r.copyWithin(a,b,b+c),Qa:function(a,b,c){a=new Date(1E3*(b+2097152>>>0<4194305-!!a?(a>>>0)+4294967296*b:NaN));v[c>>2]=a.getSeconds();v[c+4>>2]=a.getMinutes();v[c+8>>2]=a.getHours();v[c+12>>2]=a.getDate();v[c+16>>2]=a.getMonth();
v[c+20>>2]=a.getFullYear()-1900;v[c+24>>2]=a.getDay();b=a.getFullYear();v[c+28>>2]=(0!==b%4||0===b%100&&0!==b%400?jc:ic)[a.getMonth()]+a.getDate()-1|0;v[c+36>>2]=-(60*a.getTimezoneOffset());b=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();v[c+32>>2]=(b!=d&&a.getTimezoneOffset()==Math.min(d,b))|0},Ua:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=new Date(e,0,1),g=new Date(e,6,1);e=f.getTimezoneOffset();var l=g.getTimezoneOffset();w[a>>2]=
60*Math.max(e,l);v[b>>2]=Number(e!=l);a=n=>n.toLocaleTimeString(void 0,{hour12:!1,timeZoneName:"short"}).split(" ")[1];f=a(f);g=a(g);l<e?(F(f,r,c,17),F(g,r,d,17)):(F(f,r,d,17),F(g,r,c,17))},Ma:a=>{if(12448==a)return N=12288,1;N=12300;return 0},lc:(a,b,c,d,e)=>{if(62E3!=a)N=12296,c=0;else{if(b)for(;;){a=v[b>>2];if(12321==a)O.alpha=0<v[b+4>>2];else if(12325==a)O.depth=0<v[b+4>>2];else if(12326==a)O.stencil=0<v[b+4>>2];else if(12337==a)a=v[b+4>>2],O.antialias=0<a;else if(12338==a)a=v[b+4>>2],O.antialias=
1==a;else if(12544==a)O.Rg=12547!=v[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(v[e>>2]=1),c&&0<d&&(w[c>>2]=62002),N=12288,c=1):(N=12300,c=0)}return c},Rb:(a,b,c,d)=>{if(62E3!=a)return N=12296,0;for(a=1;;){b=v[d>>2];if(12440==b)a=v[d+4>>2];else if(12344==b)break;else return N=12292,0;d+=8}if(2!=a)return N=12293,0;O.Rf=a-1;O.Sg=0;ad=td(h.canvas,O);if(0!=ad)return N=12288,wd(ad),h.Bg=!0,Lc.forEach(function(e){e()}),wd(null),62004;N=12297;return 0},ub:(a,b)=>{if(62E3!=a)return N=12296,0;if(62002!=
b)return N=12293,0;N=12288;return 62006},Fb:(a,b)=>{if(62E3!=a)return N=12296,0;if(62004!=b)return N=12294,0;a=ad;vd===md[a]&&(vd=null);if("object"==typeof Pd)for(var c=md[a].Te.canvas,d=0;d<Ld.length;++d)Ld[d].target!=c||Md(d--);md[a]&&md[a].Te.canvas&&(md[a].Te.canvas.af=void 0);md[a]=null;N=12288;Xc==b&&(Xc=0);return 1},jb:(a,b)=>{if(62E3!=a)return N=12296,0;if(62006!=b)return N=12301,1;Yc==b&&(Yc=0);Zc==b&&(Zc=0);N=12288;return 1},ac:(a,b,c,d)=>{if(62E3!=a)return N=12296,0;if(62002!=b)return N=
12293,0;if(!d)return N=12300,0;N=12288;switch(c){case 12320:return v[d>>2]=O.alpha?32:24,1;case 12321:return v[d>>2]=O.alpha?8:0,1;case 12322:return v[d>>2]=8,1;case 12323:return v[d>>2]=8,1;case 12324:return v[d>>2]=8,1;case 12325:return v[d>>2]=O.depth?24:0,1;case 12326:return v[d>>2]=O.stencil?8:0,1;case 12327:return v[d>>2]=12344,1;case 12328:return v[d>>2]=62002,1;case 12329:return v[d>>2]=0,1;case 12330:return v[d>>2]=4096,1;case 12331:return v[d>>2]=16777216,1;case 12332:return v[d>>2]=4096,
1;case 12333:return v[d>>2]=0,1;case 12334:return v[d>>2]=0,1;case 12335:return v[d>>2]=12344,1;case 12337:return v[d>>2]=O.antialias?4:0,1;case 12338:return v[d>>2]=O.antialias?1:0,1;case 12339:return v[d>>2]=4,1;case 12340:return v[d>>2]=12344,1;case 12341:case 12342:case 12343:return v[d>>2]=-1,1;case 12345:case 12346:return v[d>>2]=0,1;case 12347:return v[d>>2]=0,1;case 12348:return v[d>>2]=1;case 12349:case 12350:return v[d>>2]=0,1;case 12351:return v[d>>2]=12430,1;case 12352:return v[d>>2]=
4,1;case 12354:return v[d>>2]=0,1;default:return N=12292,0}},Q:a=>{N=12288;return 0!=a&&1!=a?0:62E3},Ja:()=>N,Hc:(a,b,c)=>{if(62E3!=a)return N=12296,0;b&&(v[b>>2]=1);c&&(v[c>>2]=4);Wc=!0;N=12288;return 1},db:(a,b,c,d)=>{if(62E3!=a)return N=12296,0;if(0!=d&&62004!=d)return N=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return N=12301,0;wd(d?ad:null);Xc=d;Zc=b;Yc=c;N=12288;return 1},La:(a,b)=>{if(62E3!=a)return N=12296,0;N=12288;if($c[b])return $c[b];switch(b){case 12371:a=yd("Emscripten");break;case 12372:a=
yd("1.4 Emscripten EGL");break;case 12373:a=yd("");break;case 12429:a=yd("OpenGL_ES");break;default:return N=12300,0}return $c[b]=a},Wa:()=>{if(Wc)if(h.Ne)if(h.Ne.isContextLost())N=12302;else return N=12288,1;else N=12290;else N=12289;return 0},Pa:(a,b)=>{if(62E3!=a)return N=12296,0;0==b?uc(0,0):uc(1,b);N=12288;return 1},wc:a=>{if(62E3!=a)return N=12296,0;Zc=Yc=Xc=0;Wc=!1;N=12288;return 1},Na:()=>{N=12288;return 1},Oa:()=>{N=12288;return 1},Ea:(a,b,c)=>{b=Ad(b,c);return Na[a](...b)},b:(a,b,c)=>{b=
Ad(b,c);return Na[a](...b)},I:(a,b,c)=>{b=Ad(b,c);return Na[a](...b)},Gb:()=>{Hc();mc=null},g:()=>Date.now(),Da:()=>{if(!Od())return-1;Hd(le);var a=ce[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ha:()=>{Hd(me);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},Ka:a=>{Qa=!1;Dc=0;na=a;Ec(a)},f:()=>devicePixelRatio,d:(a,b,c)=>{a=U(a);if(!a)return-4;
a=ke(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},o:(a,b)=>{if(0>a||a>=Qd.length)return-5;if(!Qd[a])return-7;ne(b,Qd[a]);return 0},l:qc,ja:()=>Qd.length,Ia:(a,b)=>{v[a>>2]=screen.width;v[b>>2]=screen.height},ia:a=>R.activeTexture(a),ha:(a,b)=>{R.attachShader(P[a],Q[b])},za:(a,b)=>{R.Qe.beginQueryEXT(a,nd[b])},ga:(a,b,c)=>{R.bindAttribLocation(P[a],b,c?C(r,c):"")},fa:(a,b)=>{R.bindBuffer(a,gd[b])},ea:(a,b)=>{R.bindFramebuffer(a,hd[b])},da:(a,b)=>{R.bindRenderbuffer(a,jd[b])},ca:(a,b)=>{R.bindTexture(a,
kd[b])},ra:a=>{R.bindVertexArray(ld[a])},ba:(a,b,c,d)=>R.blendColor(a,b,c,d),aa:a=>R.blendEquation(a),$:(a,b)=>R.blendEquationSeparate(a,b),_:(a,b)=>R.blendFunc(a,b),Z:(a,b,c,d)=>R.blendFuncSeparate(a,b,c,d),Y:(a,b,c,d)=>{R.bufferData(a,c?r.subarray(c,c+b):b,d)},X:(a,b,c,d)=>{R.bufferSubData(a,b,r.subarray(d,d+c))},W:a=>R.checkFramebufferStatus(a),V:a=>R.clear(a),U:(a,b,c,d)=>R.clearColor(a,b,c,d),T:a=>R.clearDepth(a),S:a=>R.clearStencil(a),R:(a,b,c,d)=>{R.colorMask(!!a,!!b,!!c,!!d)},Dd:a=>{R.compileShader(Q[a])},
Cd:(a,b,c,d,e,f,g,l)=>{R.compressedTexImage2D(a,b,c,d,e,f,l?r.subarray(l,l+g):null)},Bd:(a,b,c,d,e,f,g,l,n)=>{R.compressedTexSubImage2D(a,b,c,d,e,f,g,n?r.subarray(n,n+l):null)},Ad:(a,b,c,d,e,f,g,l)=>R.copyTexImage2D(a,b,c,d,e,f,g,l),zd:(a,b,c,d,e,f,g,l)=>R.copyTexSubImage2D(a,b,c,d,e,f,g,l),yd:()=>{var a=qd(P),b=R.createProgram();b.name=a;b.mf=b.kf=b.lf=0;b.Df=1;P[a]=b;return a},xd:a=>{var b=qd(Q);Q[b]=R.createShader(a);return b},wd:a=>R.cullFace(a),vd:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>
2],e=gd[d];e&&(R.deleteBuffer(e),e.name=0,gd[d]=null)}},ud:(a,b)=>{for(var c=0;c<a;++c){var d=v[b+4*c>>2],e=hd[d];e&&(R.deleteFramebuffer(e),e.name=0,hd[d]=null)}},td:a=>{if(a){var b=P[a];b?(R.deleteProgram(b),b.name=0,P[a]=null):S||=1281}},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=nd[d];e&&(R.Qe.deleteQueryEXT(e),nd[d]=null)}},sd:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=jd[d];e&&(R.deleteRenderbuffer(e),e.name=0,jd[d]=null)}},rd:a=>{if(a){var b=Q[a];b?(R.deleteShader(b),Q[a]=null):
S||=1281}},qd:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=kd[d];e&&(R.deleteTexture(e),e.name=0,kd[d]=null)}},qa:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];R.deleteVertexArray(ld[d]);ld[d]=null}},pd:a=>R.depthFunc(a),od:a=>{R.depthMask(!!a)},nd:(a,b)=>R.depthRange(a,b),md:(a,b)=>{R.detachShader(P[a],Q[b])},ld:a=>R.disable(a),kd:a=>{R.disableVertexAttribArray(a)},jd:(a,b,c)=>{R.drawArrays(a,b,c)},ma:(a,b,c,d)=>{R.drawArraysInstanced(a,b,c,d)},na:(a,b)=>{for(var c=oe[a],d=0;d<a;d++)c[d]=v[b+
4*d>>2];R.drawBuffers(c)},id:(a,b,c,d)=>{R.drawElements(a,b,c,d)},la:(a,b,c,d,e)=>{R.drawElementsInstanced(a,b,c,d,e)},hd:a=>R.enable(a),gd:a=>{R.enableVertexAttribArray(a)},ya:a=>{R.Qe.endQueryEXT(a)},fd:()=>R.finish(),ed:()=>R.flush(),dd:(a,b,c,d)=>{R.framebufferRenderbuffer(a,b,c,jd[d])},cd:(a,b,c,d,e)=>{R.framebufferTexture2D(a,b,c,kd[d],e)},bd:a=>R.frontFace(a),ad:(a,b)=>{rd(a,b,"createBuffer",gd)},_c:(a,b)=>{rd(a,b,"createFramebuffer",hd)},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=R.Qe.createQueryEXT();
if(!d){for(S||=1282;c<a;)v[b+4*c++>>2]=0;break}var e=qd(nd);d.name=e;nd[e]=d;v[b+4*c>>2]=e}},Zc:(a,b)=>{rd(a,b,"createRenderbuffer",jd)},Yc:(a,b)=>{rd(a,b,"createTexture",kd)},pa:(a,b)=>{rd(a,b,"createVertexArray",ld)},$c:a=>R.generateMipmap(a),Xc:(a,b,c,d,e,f,g)=>{pe("getActiveAttrib",a,b,c,d,e,f,g)},Wc:(a,b,c,d,e,f,g)=>{pe("getActiveUniform",a,b,c,d,e,f,g)},Vc:(a,b,c,d)=>{a=R.getAttachedShaders(P[a]);var e=a.length;e>b&&(e=b);v[c>>2]=e;for(b=0;b<e;++b)v[d+4*b>>2]=Q.indexOf(a[b])},Uc:(a,b)=>R.getAttribLocation(P[a],
b?C(r,b):""),Tc:(a,b)=>qe(a,b,4),Sc:(a,b,c)=>{c?v[c>>2]=R.getBufferParameter(a,b):S||=1281},Rc:()=>{var a=R.getError()||S;S=0;return a},Qc:(a,b)=>qe(a,b,2),Pc:(a,b,c,d)=>{a=R.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;v[d>>2]=a},Oc:(a,b)=>qe(a,b,0),Mc:(a,b,c,d)=>{a=R.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,r,d,b):0;c&&(v[c>>2]=b)},Nc:(a,b,c)=>{if(c)if(a>=fd)S||=1281;else if(a=P[a],35716==b)a=R.getProgramInfoLog(a),
null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.mf)for(b=0;b<R.getProgramParameter(a,35718);++b)a.mf=Math.max(a.mf,R.getActiveUniform(a,b).name.length+1);v[c>>2]=a.mf}else if(35722==b){if(!a.kf)for(b=0;b<R.getProgramParameter(a,35721);++b)a.kf=Math.max(a.kf,R.getActiveAttrib(a,b).name.length+1);v[c>>2]=a.kf}else if(35381==b){if(!a.lf)for(b=0;b<R.getProgramParameter(a,35382);++b)a.lf=Math.max(a.lf,R.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.lf}else v[c>>2]=R.getProgramParameter(a,
b);else S||=1281},ta:re,va:se,sa:re,ua:se,wa:(a,b,c)=>{c?v[c>>2]=R.Qe.getQueryEXT(a,b):S||=1281},Lc:(a,b,c)=>{c?v[c>>2]=R.getRenderbufferParameter(a,b):S||=1281},Jc:(a,b,c,d)=>{a=R.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?F(a,r,d,b):0;c&&(v[c>>2]=b)},Ic:(a,b,c,d)=>{a=R.getShaderPrecisionFormat(a,b);v[c>>2]=a.rangeMin;v[c+4>>2]=a.rangeMax;v[d>>2]=a.precision},Gc:(a,b,c,d)=>{if(a=R.getShaderSource(Q[a]))b=0<b&&d?F(a,r,d,b):0,c&&(v[c>>2]=b)},Kc:(a,b,c)=>{c?35716==b?(a=R.getShaderInfoLog(Q[a]),
null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=R.getShaderSource(Q[a]),v[c>>2]=a?a.length+1:0):v[c>>2]=R.getShaderParameter(Q[a],b):S||=1281},Fc:a=>{var b=od[a];if(!b){switch(a){case 7939:b=yd(te().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=R.getParameter(a))||(S||=1280);b=b?yd(b):0;break;case 7938:b=yd(`OpenGL ES 2.0 (${R.getParameter(7938)})`);break;case 35724:b=R.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&
(3==c[1].length&&(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=yd(b);break;default:S||=1280}od[a]=b}return b},Ec:(a,b,c)=>{c?x[c>>2]=R.getTexParameter(a,b):S||=1281},Dc:(a,b,c)=>{c?v[c>>2]=R.getTexParameter(a,b):S||=1281},Ac:(a,b)=>{b=b?C(r,b):"";if(a=P[a]){ve(a);var c=a.ff,d=0,e=b,f=ue(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Zf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||R.getUniformLocation(a,b)))return d}else S||=1281;return-1},Cc:(a,b,c)=>{we(a,b,c,2)},Bc:(a,b,c)=>{we(a,b,c,0)},
xc:(a,b,c)=>{c?v[c>>2]=R.getVertexAttribOffset(a,b):S||=1281},zc:(a,b,c)=>{xe(a,b,c,2)},yc:(a,b,c)=>{xe(a,b,c,5)},vc:(a,b)=>R.hint(a,b),uc:a=>(a=gd[a])?R.isBuffer(a):0,tc:a=>R.isEnabled(a),sc:a=>(a=hd[a])?R.isFramebuffer(a):0,rc:a=>(a=P[a])?R.isProgram(a):0,Aa:a=>(a=nd[a])?R.Qe.isQueryEXT(a):0,qc:a=>(a=jd[a])?R.isRenderbuffer(a):0,pc:a=>(a=Q[a])?R.isShader(a):0,oc:a=>(a=kd[a])?R.isTexture(a):0,oa:a=>(a=ld[a])?R.isVertexArray(a):0,nc:a=>R.lineWidth(a),mc:a=>{a=P[a];R.linkProgram(a);a.ff=0;a.Zf={}},
kc:(a,b)=>{3317==a&&(pd=b);R.pixelStorei(a,b)},jc:(a,b)=>R.polygonOffset(a,b),xa:(a,b)=>{R.Qe.queryCounterEXT(nd[a],b)},ic:(a,b,c,d,e,f,g)=>{(g=ye(f,e,c,d,g))?R.readPixels(a,b,c,d,e,f,g):S||=1280},hc:()=>{},gc:(a,b,c,d)=>R.renderbufferStorage(a,b,c,d),fc:(a,b)=>{R.sampleCoverage(a,!!b)},ec:(a,b,c,d)=>R.scissor(a,b,c,d),dc:()=>{S||=1280},cc:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=(g=w[c+4*f>>2])?C(r,g,d?w[d+4*f>>2]:void 0):"";e+=g}R.shaderSource(Q[a],e)},bc:(a,b,c)=>R.stencilFunc(a,b,c),$b:(a,
b,c,d)=>R.stencilFuncSeparate(a,b,c,d),_b:a=>R.stencilMask(a),Zb:(a,b)=>R.stencilMaskSeparate(a,b),Yb:(a,b,c)=>R.stencilOp(a,b,c),Xb:(a,b,c,d)=>R.stencilOpSeparate(a,b,c,d),Wb:(a,b,c,d,e,f,g,l,n)=>{n=n?ye(l,g,d,e,n):null;R.texImage2D(a,b,c,d,e,f,g,l,n)},Vb:(a,b,c)=>R.texParameterf(a,b,c),Ub:(a,b,c)=>{R.texParameterf(a,b,x[c>>2])},Tb:(a,b,c)=>R.texParameteri(a,b,c),Sb:(a,b,c)=>{R.texParameteri(a,b,v[c>>2])},Qb:(a,b,c,d,e,f,g,l,n)=>{n=n?ye(l,g,e,f,n):null;R.texSubImage2D(a,b,c,d,e,f,g,l,n)},Pb:(a,b)=>
{R.uniform1f(X(a),b)},Ob:(a,b,c)=>{if(288>=b)for(var d=ze[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);R.uniform1fv(X(a),d)},Nb:(a,b)=>{R.uniform1i(X(a),b)},Mb:(a,b,c)=>{if(288>=b)for(var d=Ae[b],e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);R.uniform1iv(X(a),d)},Lb:(a,b,c)=>{R.uniform2f(X(a),b,c)},Kb:(a,b,c)=>{if(144>=b)for(var d=ze[2*b],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);R.uniform2fv(X(a),d)},Jb:(a,b,c)=>{R.uniform2i(X(a),
b,c)},Ib:(a,b,c)=>{if(144>=b)for(var d=Ae[2*b],e=0;e<2*b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2];else d=v.subarray(c>>2,c+8*b>>2);R.uniform2iv(X(a),d)},Hb:(a,b,c,d)=>{R.uniform3f(X(a),b,c,d)},Eb:(a,b,c)=>{if(96>=b)for(var d=ze[3*b],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);R.uniform3fv(X(a),d)},Db:(a,b,c,d)=>{R.uniform3i(X(a),b,c,d)},Cb:(a,b,c)=>{if(96>=b)for(var d=Ae[3*b],e=0;e<3*b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>
2],d[e+2]=v[c+(4*e+8)>>2];else d=v.subarray(c>>2,c+12*b>>2);R.uniform3iv(X(a),d)},Bb:(a,b,c,d,e)=>{R.uniform4f(X(a),b,c,d,e)},Ab:(a,b,c)=>{if(72>=b){var d=ze[4*b],e=x;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=x.subarray(c>>2,c+16*b>>2);R.uniform4fv(X(a),d)},zb:(a,b,c,d,e)=>{R.uniform4i(X(a),b,c,d,e)},yb:(a,b,c)=>{if(72>=b)for(var d=Ae[4*b],e=0;e<4*b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2];
else d=v.subarray(c>>2,c+16*b>>2);R.uniform4iv(X(a),d)},xb:(a,b,c,d)=>{if(72>=b)for(var e=ze[4*b],f=0;f<4*b;f+=4)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2];else e=x.subarray(d>>2,d+16*b>>2);R.uniformMatrix2fv(X(a),!!c,e)},wb:(a,b,c,d)=>{if(32>=b)for(var e=ze[9*b],f=0;f<9*b;f+=9)e[f]=x[d+4*f>>2],e[f+1]=x[d+(4*f+4)>>2],e[f+2]=x[d+(4*f+8)>>2],e[f+3]=x[d+(4*f+12)>>2],e[f+4]=x[d+(4*f+16)>>2],e[f+5]=x[d+(4*f+20)>>2],e[f+6]=x[d+(4*f+24)>>2],e[f+7]=x[d+(4*f+28)>>
2],e[f+8]=x[d+(4*f+32)>>2];else e=x.subarray(d>>2,d+36*b>>2);R.uniformMatrix3fv(X(a),!!c,e)},vb:(a,b,c,d)=>{if(18>=b){var e=ze[16*b],f=x;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);R.uniformMatrix4fv(X(a),!!c,e)},tb:a=>{a=P[a];R.useProgram(a);
R.fg=a},sb:a=>{R.validateProgram(P[a])},rb:(a,b)=>R.vertexAttrib1f(a,b),qb:(a,b)=>{R.vertexAttrib1f(a,x[b>>2])},pb:(a,b,c)=>R.vertexAttrib2f(a,b,c),ob:(a,b)=>{R.vertexAttrib2f(a,x[b>>2],x[b+4>>2])},nb:(a,b,c,d)=>R.vertexAttrib3f(a,b,c,d),mb:(a,b)=>{R.vertexAttrib3f(a,x[b>>2],x[b+4>>2],x[b+8>>2])},lb:(a,b,c,d,e)=>R.vertexAttrib4f(a,b,c,d,e),kb:(a,b)=>{R.vertexAttrib4f(a,x[b>>2],x[b+4>>2],x[b+8>>2],x[b+12>>2])},ka:(a,b)=>{R.vertexAttribDivisor(a,b)},ib:(a,b,c,d,e,f)=>{R.vertexAttribPointer(a,b,c,!!d,
e,f)},hb:(a,b,c,d)=>R.viewport(a,b,c,d),n:()=>1,Fa:(a,b,c)=>Be(a,{Bf:v[c>>2],vf:v[c+4>>2],mg:v[c+8>>2],jg:b,hf:v[c+12>>2],Hf:v[c+16>>2]}),L:(a,b)=>{a=U(a);return a?a.requestPointerLock?Id()?me(a):b?(Gd(me,2,[a]),1):-2:-1:-4},Sa:()=>{z("OOM")},p:Ce,q:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:De(a,b),C:(a,b,c,d)=>Ee(a,b,c,d,12,"blur"),e:ge,k:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},D:(a,b,c,d)=>Ee(a,b,c,d,13,"focus"),t:(a,b,c,d)=>{if(!Od())return-1;
a=U(a);if(!a)return-4;Fe(a,b,c,d,"webkitfullscreenchange");return Fe(a,b,c,d,"fullscreenchange")},j:(a,b,c)=>Ce()?-1:Ge(a,b,c,26,"gamepadconnected"),i:(a,b,c)=>Ce()?-1:Ge(a,b,c,27,"gamepaddisconnected"),w:(a,b,c,d)=>He(a,b,c,d,2,"keydown"),u:(a,b,c,d)=>He(a,b,c,d,1,"keypress"),v:(a,b,c,d)=>He(a,b,c,d,3,"keyup"),J:(a,b,c,d)=>Je(a,b,c,d,5,"mousedown"),G:(a,b,c,d)=>Je(a,b,c,d,33,"mouseenter"),F:(a,b,c,d)=>Je(a,b,c,d,34,"mouseleave"),K:(a,b,c,d)=>Je(a,b,c,d,8,"mousemove"),H:(a,b,c,d)=>Je(a,b,c,d,6,"mouseup"),
x:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Fe||document.body.$f||document.body.Ef))return-1;a=U(a);if(!a)return-4;Ke(a,b,c,d,"mozpointerlockchange");Ke(a,b,c,d,"webkitpointerlockchange");Ke(a,b,c,d,"mspointerlockchange");return Ke(a,b,c,d,"pointerlockchange")},s:(a,b,c,d)=>Le(a,b,c,d),y:(a,b,c,d)=>Me(a,b,c,d,25,"touchcancel"),A:(a,b,c,d)=>Me(a,b,c,d,23,"touchend"),z:(a,b,c,d)=>Me(a,b,c,d,24,"touchmove"),B:(a,b,c,d)=>Me(a,b,c,d,22,"touchstart"),r:(a,
b,c)=>Ne(a,b,c),E:(a,b,c,d)=>(a=U(a))?"undefined"!=typeof a.onwheel?Oe(a,b,c,d):-1:-4,Ga:a=>document.title=a?C(r,a):"",m:a=>kf(b=>Gc(b,a)),Ya:(a,b)=>{var c=0;Re().forEach((d,e)=>{var f=b+c;e=w[a+4*e>>2]=f;for(f=0;f<d.length;++f)m[e++]=d.charCodeAt(f);m[e]=0;c+=d.length+1});return 0},Za:(a,b)=>{var c=Re();w[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);w[b>>2]=d;return 0},c:Fc,h:function(a){try{var b=Jb(a);Wb(b);return 0}catch(c){if("undefined"==typeof M||"ErrnoError"!==c.name)throw c;return c.Ee}},
N:function(a,b,c,d){try{a:{var e=Jb(a);a=b;for(var f,g=b=0;g<c;g++){var l=w[a>>2],n=w[a+4>>2];a+=8;var p=e,t=f,q=m;if(0>n||0>t)throw new G(28);if(null===p.fd)throw new G(8);if(1===(p.flags&2097155))throw new G(8);if(I(p.node.mode))throw new G(31);if(!p.Ae.read)throw new G(28);var u="undefined"!=typeof t;if(!u)t=p.position;else if(!p.seekable)throw new G(70);var D=p.Ae.read(p,q,l,n,t);u||(p.position+=D);var J=D;if(0>J){var W=-1;break a}b+=J;if(J<n)break;"undefined"!=typeof f&&(f+=J)}W=b}w[d>>2]=W;
return 0}catch(ja){if("undefined"==typeof M||"ErrnoError"!==ja.name)throw ja;return ja.Ee}},Ra:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Jb(a);Xb(f,b,d);B=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];v[e>>2]=B[0];v[e+4>>2]=B[1];f.Ve&&0===b&&0===d&&(f.Ve=null);return 0}catch(g){if("undefined"==typeof M||"ErrnoError"!==g.name)throw g;return g.Ee}},M:function(a,
b,c,d){try{a:{var e=Jb(a);a=b;for(var f,g=b=0;g<c;g++){var l=w[a>>2],n=w[a+4>>2];a+=8;var p=Yb(e,m,l,n,f);if(0>p){var t=-1;break a}b+=p;"undefined"!=typeof f&&(f+=p)}t=b}w[d>>2]=t;return 0}catch(q){if("undefined"==typeof M||"ErrnoError"!==q.name)throw q;return q.Ee}}},Y=function(){function a(c){Y=c.exports;Y=Ue();la=Y.Ed;c=la.buffer;h.HEAP8=m=new Int8Array(c);h.HEAP16=oa=new Int16Array(c);h.HEAPU8=r=new Uint8Array(c);h.HEAPU16=pa=new Uint16Array(c);h.HEAP32=v=new Int32Array(c);h.HEAPU32=w=new Uint32Array(c);
h.HEAPF32=x=new Float32Array(c);h.HEAPF64=y=new Float64Array(c);ra.unshift(Y.Fd);za("wasm-instantiate");return Y}var b={a:rf};ya("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ga(b,function(c){a(c.instance)});return{}}(),E=a=>(E=Y.Gd)(a),of=a=>(of=Y.Hd)(a),sf=h._main=(a,b)=>(sf=h._main=Y.Id)(a,b),Cd=a=>(Cd=Y.Kd)(a),de=a=>(de=Y.Ld)(a),Bd=()=>(Bd=Y.Md)(),dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=
h.dynCall_vi=Y.Nd)(a,b);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=Y.Od)(a,b,c,d,e);var dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=Y.Pd)(a,b,c),dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=Y.Qd)(a);h.dynCall_ii=(a,b)=>(h.dynCall_ii=Y.Rd)(a,b);var V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=Y.Sd)(a,b,c,d);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=Y.Td)(a,b,c,d,e);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Y.Ud)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Y.Vd)(a,b);
h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=Y.Wd)(a,b,c,d);var dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=Y.Xd)(a,b,c);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=Y.Yd)(a,b,c,d,e,f);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiiiiii=Y.Zd)(a,b,c,d,e,f,g,l);h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,l,n,p)=>(h.dynCall_iiiiiiiiii=Y._d)(a,b,c,d,e,f,g,l,n,p);
h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,l,n,p,t,q,u,D,J,W)=>(h.dynCall_iiiiiiiiiiiiiiff=Y.$d)(a,b,c,d,e,f,g,l,n,p,t,q,u,D,J,W);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=Y.ae)(a,b,c,d,e,f);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_iiiiiiiii=Y.be)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_viiiiiii=Y.ce)(a,b,c,d,e,f,g,l);h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,l,n,p,t,q)=>(h.dynCall_viiiiiiiiiii=Y.de)(a,b,c,d,e,f,g,l,n,p,t,q);
h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,l,n,p,t)=>(h.dynCall_iiiiiidiiff=Y.ee)(a,b,c,d,e,f,g,l,n,p,t);h.dynCall_i=a=>(h.dynCall_i=Y.fe)(a);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=Y.ge)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=Y.he)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_viiiiiiii=Y.ie)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,l,n,p)=>(h.dynCall_viiiiiiiii=Y.je)(a,b,c,d,e,f,g,l,n,p);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=Y.ke)(a,b,c);
h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=Y.le)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=Y.me)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=Y.ne)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=Y.oe)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=Y.pe)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=Y.qe)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=Y.re)(a,b,c,d,e,f,g);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=Y.se)(a,b,c,d,e,f,g);
h.dynCall_iid=(a,b,c)=>(h.dynCall_iid=Y.te)(a,b,c);h.dynCall_di=(a,b)=>(h.dynCall_di=Y.ue)(a,b);var mf=a=>(mf=Y.ve)(a),Ye=()=>(Ye=Y.we)(),lf=a=>(lf=Y.xe)(a),nf=()=>(nf=Y.ye)();h.addRunDependency=ya;h.removeRunDependency=za;h.FS_createPath=$b;h.FS_createLazyFile=dc;h.FS_createDevice=bc;h.FS_createPreloadedFile=rb;h.FS_createDataFile=qb;h.FS_unlink=Qb;h.allocate=Ha;var tf;xa=function uf(){tf||vf();tf||(xa=uf)};
function wf(a=[]){var b=sf;a.unshift(ca);var c=a.length,d=de(4*(c+1)),e=d;a.forEach(g=>{w[e>>2]=ee(g);e+=4});w[e>>2]=0;try{var f=b(c,d);Fc(f,!0)}catch(g){Cc(g)}}
function vf(){var a=ba;function b(){if(!tf&&(tf=!0,h.calledRun=!0,!ma)){h.noFSInit||Zb||(Zb=!0,h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?bc("/dev","stdin",h.stdin):Pb("/dev/tty","/dev/stdin"),h.stdout?bc("/dev","stdout",null,h.stdout):Pb("/dev/tty","/dev/stdout"),h.stderr?bc("/dev","stderr",null,h.stderr):Pb("/dev/tty1","/dev/stderr"),Ub("/dev/stdin",0),Ub("/dev/stdout",1),Ub("/dev/stderr",1));yb=!1;Pa(ra);Pa(sa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();xf&&wf(a);if(h.postRun)for("function"==
typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ta.unshift(c)}Pa(ta)}}if(!(0<va)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ua();Pa(qa);0<va||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var xf=!0;h.noInitialRun&&(xf=!1);vf();
