var h;h||=typeof Module !== 'undefined' ? Module : {};h.lf||(h.lf=0);h.lf++;
h.ENVIRONMENT_IS_PTHREAD||h.$ww||function(a){function b(n,p,t){var r=new XMLHttpRequest;r.open("GET",n,!0);r.responseType="arraybuffer";r.onprogress=function(u){var B=p;u.total&&(B=u.total);if(u.loaded){r.ve?h.Ne[n].loaded=u.loaded:(r.ve=!0,h.Ne||(h.Ne={}),h.Ne[n]={loaded:u.loaded,total:B});var N=B=u=0,W;for(W in h.Ne){var fa=h.Ne[W];u+=fa.total;B+=fa.loaded;N++}u=Math.ceil(u*h.lf/N);h.setStatus&&h.setStatus(`Downloading data... (${B}/${u})`)}else!h.Ne&&h.setStatus&&h.setStatus("Downloading data...")};
r.onerror=function(){throw Error("NetworkError for: "+n);};r.onload=function(){if(200==r.status||304==r.status||206==r.status||0==r.status&&r.response)t(r.response);else throw Error(r.statusText+" : "+r.responseURL);};r.send(null)}function c(n){console.error("package error:",n)}function d(){function n(u,B,N){this.start=u;this.end=B;this.audio=N}function p(u){if(!u)throw"Loading data file failed."+Error().stack;if(u.constructor.name!==ArrayBuffer.name)throw"bad input to processPackageData"+Error().stack;
u=new Uint8Array(u);n.prototype.qf=u;u=a.files;for(var B=0;B<u.length;++B)n.prototype.ve[u[B].filename].onload();h.removeRunDependency("datafile_index.data")}h.FS_createPath("/","data",!0,!0);n.prototype={ve:{},open:function(u,B){this.name=B;this.ve[B]=this;h.addRunDependency(`fp ${this.name}`)},onload:function(){this.finish(this.qf.subarray(this.start,this.end))},finish:function(u){h.FS_createDataFile(this.name,null,u,!0,!0,!0);h.removeRunDependency(`fp ${this.name}`);this.ve[this.name]=null}};for(var t=
a.files,r=0;r<t.length;++r)(new n(t[r].start,t[r].end,t[r].audio||0)).open("GET",t[r].filename);h.addRunDependency("datafile_index.data");h.Lf||(h.Lf={});h.Lf["index.data"]={Gg:!1};l?(p(l),l=null):g=p}"object"===typeof window?window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/"):"undefined"===typeof process&&"undefined"!==typeof location&&encodeURIComponent(location.pathname.toString().substring(0,location.pathname.toString().lastIndexOf("/"))+
"/");"function"!==typeof h.locateFilePackage||h.locateFile||(h.locateFile=h.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var e=h.locateFile?h.locateFile("index.data",""):"index.data",f=a.remote_package_size,g=null,l=h.getPreloadedPackage?h.getPreloadedPackage(e,f):null;l||b(e,f,function(n){g?(g(n),g=null):l=n},c);h.calledRun?d():(h.preRun||(h.preRun=[]),h.preRun.push(d))}({files:[{filename:"/data/audiohed.wl1",
start:0,end:1156},{filename:"/data/audiot.wl1",start:1156,end:133769},{filename:"/data/gamemaps.wl1",start:133769,end:161194},{filename:"/data/maphead.wl1",start:161194,end:161596},{filename:"/data/vgadict.wl1",start:161596,end:162620},{filename:"/data/vgagraph.wl1",start:162620,end:489188},{filename:"/data/vgahead.wl1",start:489188,end:489659},{filename:"/data/vswap.wl1",start:489659,end:1232571}],remote_package_size:1232571});
var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},ea="",ha,ia;"undefined"!=typeof document&&document.currentScript&&(ea=document.currentScript.src);ea=0!==ea.indexOf("blob:")?ea.substr(0,ea.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText};
ia=(a,b,c)=>{var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=()=>{200==d.status||0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)};var ja=h.print||console.log.bind(console),k=h.printErr||console.error.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ka;h.wasmBinary&&(ka=h.wasmBinary);"object"!=typeof WebAssembly&&m("no native wasm support detected");
var la,ma=!1,na,q,v,oa,pa,w,x,y,z,qa=[],ra=[],sa=[],ta=[],ua=[];function va(){var a=h.preRun.shift();qa.unshift(a)}var wa=0,xa=null,ya=null;function za(){wa++;h.monitorRunDependencies&&h.monitorRunDependencies(wa)}function Aa(){wa--;h.monitorRunDependencies&&h.monitorRunDependencies(wa);if(0==wa&&(null!==xa&&(clearInterval(xa),xa=null),ya)){var a=ya;ya=null;a()}}
function m(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";k(a);ma=!0;na=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ba=a=>a.startsWith("data:application/octet-stream;base64,"),Ca;Ca="index.wasm";if(!Ba(Ca)){var Da=Ca;Ca=h.locateFile?h.locateFile(Da,ea):ea+Da}function Ea(a){if(a==Ca&&ka)return new Uint8Array(ka);throw"both async and sync fetching of the wasm failed";}
function Fa(a){return ka||"function"!=typeof fetch?Promise.resolve().then(()=>Ea(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Ea(a))}function Ga(a,b,c){return Fa(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{k(`failed to asynchronously prepare wasm: ${d}`);m(d)})}
function Ha(a,b){var c=Ca;ka||"function"!=typeof WebAssembly.instantiateStreaming||Ba(c)||"function"!=typeof fetch?Ga(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){k(`wasm streaming compile failed: ${e}`);k("falling back to ArrayBuffer instantiation");return Ga(c,a,b)}))}
var A,C,La={173860:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,174007:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,174241:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.ue||("undefined"!==typeof AudioContext?b.ue=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.ue=new webkitAudioContext),b.ue&&
Ia(b.ue));return void 0===b.ue?-1:0},174734:()=>h.SDL2.ue.sampleRate,174802:(a,b,c,d)=>{function e(){}function f(l){void 0!==g.capture.Ve&&(clearTimeout(g.capture.Ve),g.capture.Ve=void 0);g.capture.cf=g.ue.createMediaStreamSource(l);g.capture.ye=g.ue.createScriptProcessor(b,a,1);g.capture.ye.onaudioprocess=function(n){void 0!==g&&void 0!==g.capture&&(n.outputBuffer.getChannelData(0).fill(0),g.capture.kf=n.inputBuffer,Ja(c,[d]))};g.capture.cf.connect(g.capture.ye);g.capture.ye.connect(g.ue.destination);
g.capture.stream=l}var g=h.SDL2;g.capture.ff=g.ue.createBuffer(a,b,g.ue.sampleRate);g.capture.ff.getChannelData(0).fill(0);g.capture.Ve=setTimeout(function(){g.capture.kf=g.capture.ff;Ja(c,[d])},b/g.ue.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(f).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},f,e)},176454:(a,b,c,d)=>{var e=h.SDL2;e.audio.ye=
e.ue.createScriptProcessor(b,0,a);e.audio.ye.onaudioprocess=function(f){void 0!==e&&void 0!==e.audio&&(e.audio.zf=f.outputBuffer,Ja(c,[d]))};e.audio.ye.connect(e.ue.destination)},176864:(a,b)=>{for(var c=h.SDL2,d=c.capture.kf.numberOfChannels,e=0;e<d;++e){var f=c.capture.kf.getChannelData(e);if(f.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";if(1==d)for(var g=0;g<b;++g)Ka(a+4*g,f[g]);else for(g=0;g<b;++g)Ka(a+4*(g*d+e),
f[g])}},177469:(a,b)=>{for(var c=h.SDL2,d=c.audio.zf.numberOfChannels,e=0;e<d;++e){var f=c.audio.zf.getChannelData(e);if(f.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+f.length+" samples vs expected "+b+" samples!";for(var g=0;g<b;++g)f[g]=y[a+(g*d+e<<2)>>2]}},177949:a=>{var b=h.SDL2;if(a){void 0!==b.capture.Ve&&clearTimeout(b.capture.Ve);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.ye&&(b.capture.ye.onaudioprocess=function(){},b.capture.ye.disconnect(),b.capture.ye=void 0);void 0!==b.capture.cf&&(b.capture.cf.disconnect(),b.capture.cf=void 0);void 0!==b.capture.ff&&(b.capture.ff=void 0);b.capture=void 0}else void 0!=b.audio.ye&&(b.audio.ye.disconnect(),b.audio.ye=void 0),b.audio=void 0;void 0!==b.ue&&void 0===b.audio&&void 0===b.capture&&(b.ue.close(),b.ue=void 0)},179121:()=>window.innerWidth,179151:()=>window.innerHeight,179182:(a,
b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Uf!==h.canvas&&(d.Ee=h.createContext(h.canvas,!1,!0),d.Uf=h.canvas);if(d.w!==a||d.h!==b||d.fg!==d.Ee)d.image=d.Ee.createImageData(a,b),d.w=a,d.h=b,d.fg=d.Ee;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var f=w[b];a[e]=f&255;a[e+1]=f>>8&255;a[e+2]=f>>16&255;a[e+3]=255;b++;e+=4}else if(d.Xf!==a&&(d.Wf=new Int32Array(a.buffer),d.Yf=new Uint8Array(a.buffer),d.Xf=a),a=d.Wf,c=a.length,
a.set(w.subarray(b,b+c)),a=d.Yf,b=3,e=b+4*c,0==c%8)for(;b<e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.Ee.putImageData(d.image,0,0)},180651:(a,b,c,d,e)=>{var f=document.createElement("canvas");f.width=a;f.height=b;var g=f.getContext("2d");a=g.createImageData(a,b);b=a.data;e>>=2;var l=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;l<
n;){var p=w[e];b[l]=p&255;b[l+1]=p>>8&255;b[l+2]=p>>16&255;b[l+3]=p>>24&255;e++;l+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(w.subarray(e,e+n));g.putImageData(a,0,0);c=0===c&&0===d?"url("+f.toDataURL()+"), auto":"url("+f.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,v,d,c.length+1);return d},181640:a=>{h.canvas&&(h.canvas.style.cursor=a?F(v,a):"")},181723:()=>{h.canvas&&(h.canvas.style.cursor="none")}};
function Ma(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var Na=(a,b,c)=>{a.addEventListener(b,c,{once:!0})},Ia=a=>{var b;b||=[document,document.getElementById("canvas")];["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Na(d,c,()=>{"suspended"===a.state&&a.resume()})})})},Oa=a=>{for(;0<a.length;)a.shift()(h)},Ja=(a,b)=>{var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)},Pa=h.noExitRuntime||!0;
function Ka(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":q[a>>0]=b;break;case "i8":q[a>>0]=b;break;case "i16":oa[a>>1]=b;break;case "i32":w[a>>2]=b;break;case "i64":m("to do setValue(i64) use WASM_BIGINT");case "float":y[a>>2]=b;break;case "double":z[a>>3]=b;break;case "*":x[a>>2]=b;break;default:m(`invalid type for setValue: ${c}`)}}
var Qa="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,F=(a,b,c)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Qa)return Qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ra=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},G=a=>{var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Ra(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Sa=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.substr(0,b.length-1);return a+b},Ta=a=>{if("/"===
a)return"/";a=G(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)},Ua=()=>{if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues)return a=>crypto.getRandomValues(a);m("initRandomDevice")},Va=a=>(Va=Ua())(a);
function Wa(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!=typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Ra(a.split("/").filter(d=>!!d),!b).join("/");return(b?"/":"")+a||"."}
var Xa=[],Ya=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},E=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>
12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e};function Za(a){var b=Array(Ya(a)+1);a=E(a,b,0,b.length);b.length=a;return b}var ab=[];function bb(a,b){ab[a]={input:[],xe:[],Je:b};cb(a,db)}
var db={open(a){var b=ab[a.node.Te];if(!b)throw new H(43);a.se=b;a.seekable=!1},close(a){a.se.Je.Ze(a.se)},Ze(a){a.se.Je.Ze(a.se)},read(a,b,c,d){if(!a.se||!a.se.Je.Bf)throw new H(60);for(var e=0,f=0;f<d;f++){try{var g=a.se.Je.Bf(a.se)}catch(l){throw new H(29);}if(void 0===g&&0===e)throw new H(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write(a,b,c,d){if(!a.se||!a.se.Je.pf)throw new H(60);try{for(var e=0;e<d;e++)a.se.Je.pf(a.se,b[c+e])}catch(f){throw new H(29);
}d&&(a.node.timestamp=Date.now());return e}},eb={Bf(){a:{if(!Xa.length){var a=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(a=window.prompt("Input: "),null!==a&&(a+="\n")):"function"==typeof readline&&(a=readline(),null!==a&&(a+="\n"));if(!a){a=null;break a}Xa=Za(a)}a=Xa.shift()}return a},pf(a,b){null===b||10===b?(ja(F(a.xe,0)),a.xe=[]):0!=b&&a.xe.push(b)},Ze(a){a.xe&&0<a.xe.length&&(ja(F(a.xe,0)),a.xe=[])},ig(){return{Ag:25856,Cg:5,zg:191,Bg:35387,yg:[3,28,127,21,4,0,1,0,17,
19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},jg(){return 0},kg(){return[24,80]}},fb={pf(a,b){null===b||10===b?(k(F(a.xe,0)),a.xe=[]):0!=b&&a.xe.push(b)},Ze(a){a.xe&&0<a.xe.length&&(k(F(a.xe,0)),a.xe=[])}};function gb(a,b){var c=a.Cd?a.Cd.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Cd,a.Cd=new Uint8Array(b),0<a.te&&a.Cd.set(c.subarray(0,a.te),0))}
var I={Ge:null,Ie(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new H(63);I.Ge||(I.Ge={dir:{node:{Fe:I.qe.Fe,ze:I.qe.ze,Se:I.qe.Se,df:I.qe.df,Nf:I.qe.Nf,hf:I.qe.hf,ef:I.qe.ef,Mf:I.qe.Mf,gf:I.qe.gf},stream:{Me:I.re.Me}},file:{node:{Fe:I.qe.Fe,ze:I.qe.ze},stream:{Me:I.re.Me,read:I.re.read,write:I.re.write,vf:I.re.vf,nf:I.re.nf,If:I.re.If}},link:{node:{Fe:I.qe.Fe,ze:I.qe.ze,Ue:I.qe.Ue},stream:{}},yf:{node:{Fe:I.qe.Fe,ze:I.qe.ze},stream:hb}});
c=ib(a,b,c,d);J(c.mode)?(c.qe=I.Ge.dir.node,c.re=I.Ge.dir.stream,c.Cd={}):32768===(c.mode&61440)?(c.qe=I.Ge.file.node,c.re=I.Ge.file.stream,c.te=0,c.Cd=null):40960===(c.mode&61440)?(c.qe=I.Ge.link.node,c.re=I.Ge.link.stream):8192===(c.mode&61440)&&(c.qe=I.Ge.yf.node,c.re=I.Ge.yf.stream);c.timestamp=Date.now();a&&(a.Cd[b]=c,a.timestamp=c.timestamp);return c},Ig(a){return a.Cd?a.Cd.subarray?a.Cd.subarray(0,a.te):new Uint8Array(a.Cd):new Uint8Array(0)},qe:{Fe(a){var b={};b.$f=8192===(a.mode&61440)?a.id:
1;b.Cf=a.id;b.mode=a.mode;b.og=1;b.uid=0;b.dg=0;b.Te=a.Te;J(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.te:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.Qf=new Date(a.timestamp);b.ng=new Date(a.timestamp);b.Tf=new Date(a.timestamp);b.Rf=4096;b.Sf=Math.ceil(b.size/b.Rf);return b},ze(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);if(void 0!==b.size&&(b=b.size,a.te!=b))if(0==b)a.Cd=null,a.te=0;else{var c=a.Cd;a.Cd=new Uint8Array(b);c&&a.Cd.set(c.subarray(0,
Math.min(b,a.te)));a.te=b}},Se(){throw jb[44];},df(a,b,c,d){return I.createNode(a,b,c,d)},Nf(a,b,c){if(J(a.mode)){try{var d=kb(b,c)}catch(f){}if(d)for(var e in d.Cd)throw new H(55);}delete a.parent.Cd[a.name];a.parent.timestamp=Date.now();a.name=c;b.Cd[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},hf(a,b){delete a.Cd[b];a.timestamp=Date.now()},ef(a,b){var c=kb(a,b),d;for(d in c.Cd)throw new H(55);delete a.Cd[b];a.timestamp=Date.now()},Mf(a){var b=[".",".."],c;for(c in a.Cd)a.Cd.hasOwnProperty(c)&&
b.push(c);return b},gf(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},Ue(a){if(40960!==(a.mode&61440))throw new H(28);return a.link}},re:{read(a,b,c,d,e){var f=a.node.Cd;if(e>=a.node.te)return 0;a=Math.min(a.node.te-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write(a,b,c,d,e,f){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Cd||a.Cd.subarray)){if(f)return a.Cd=b.subarray(c,c+d),a.te=d;if(0===a.te&&0===e)return a.Cd=b.slice(c,
c+d),a.te=d;if(e+d<=a.te)return a.Cd.set(b.subarray(c,c+d),e),d}gb(a,e+d);if(a.Cd.subarray&&b.subarray)a.Cd.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Cd[e+f]=b[c+f];a.te=Math.max(a.te,e+d);return d},Me(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.te);if(0>b)throw new H(28);return b},vf(a,b,c){gb(a.node,b+c);a.node.te=Math.max(a.node.te,b+c)},nf(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new H(43);a=a.node.Cd;if(e&2||a.buffer!==q.buffer){if(0<c||c+b<a.length)a.subarray?
a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);c=!0;m();b=void 0;if(!b)throw new H(48);q.set(a,b)}else c=!1,b=a.byteOffset;return{Pg:b,wg:c}},If(a,b,c,d){I.re.write(a,b,0,d,c,!1);return 0}}},lb=(a,b,c)=>{var d=`al ${a}`;ia(a,e=>{e||m(`Loading data file "${a}" failed (no arrayBuffer).`);b(new Uint8Array(e));d&&Aa(d)},()=>{if(c)c();else throw`Loading data file "${a}" failed.`;});d&&za(d)},mb=h.preloadPlugins||[],pb=(a,b,c,d)=>{"undefined"!=typeof nb&&ob();var e=!1;mb.forEach(f=>{!e&&f.canHandle(b)&&
(f.handle(a,b,c,d),e=!0)});return e},rb=(a,b,c,d,e,f,g,l,n,p)=>{function t(B){function N(W){p&&p();l||qb(a,b,W,d,e,n);f&&f();Aa(u)}pb(B,r,N,()=>{g&&g();Aa(u)})||N(B)}var r=b?Wa(G(a+"/"+b)):a,u=`cp ${r}`;za(u);"string"==typeof c?lb(c,B=>t(B),g):t(c)},sb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},tb=null,vb={},wb=[],xb=1,yb=null,zb=!0,H=null,jb={};
function K(a,b={}){a=Wa(a);if(!a)return{path:"",node:null};b=Object.assign({Af:!0,rf:0},b);if(8<b.rf)throw new H(32);a=a.split("/").filter(g=>!!g);for(var c=tb,d="/",e=0;e<a.length;e++){var f=e===a.length-1;if(f&&b.parent)break;c=kb(c,a[e]);d=G(d+"/"+a[e]);c.Oe&&(!f||f&&b.Af)&&(c=c.Oe.root);if(!f||b.Ye)for(f=0;40960===(c.mode&61440);)if(c=Ab(d),d=Wa(Sa(d),c),c=K(d,{rf:b.rf+1}).node,40<f++)throw new H(32);}return{path:d,node:c}}
function Bb(a){for(var b;;){if(a===a.parent)return a=a.Ie.Hf,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function Cb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%yb.length}function Db(a){var b=Cb(a.parent.id,a.name);if(yb[b]===a)yb[b]=a.Pe;else for(b=yb[b];b;){if(b.Pe===a){b.Pe=a.Pe;break}b=b.Pe}}
function kb(a,b){var c;if(c=(c=Eb(a,"x"))?c:a.qe.Se?0:2)throw new H(c,a);for(c=yb[Cb(a.id,b)];c;c=c.Pe){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.qe.Se(a,b)}function ib(a,b,c,d){a=new Fb(a,b,c,d);b=Cb(a.parent.id,a.name);a.Pe=yb[b];return yb[b]=a}function J(a){return 16384===(a&61440)}function Gb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}
function Eb(a,b){if(zb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function Hb(a,b){try{return kb(a,b),20}catch(c){}return Eb(a,"wx")}function Ib(a,b,c){try{var d=kb(a,b)}catch(e){return e.Ce}if(a=Eb(a,"wx"))return a;if(c){if(!J(d.mode))return 54;if(d===d.parent||"/"===Bb(d))return 10}else if(J(d.mode))return 31;return 0}function Jb(){for(var a=0;4096>=a;a++)if(!wb[a])return a;throw new H(33);}
function Kb(a){a=wb[a];if(!a)throw new H(8);return a}function Lb(a,b=-1){Mb||(Mb=function(){this.ve={}},Mb.prototype={},Object.defineProperties(Mb.prototype,{object:{get(){return this.node},set(c){this.node=c}},flags:{get(){return this.ve.flags},set(c){this.ve.flags=c}},position:{get(){return this.ve.position},set(c){this.ve.position=c}}}));a=Object.assign(new Mb,a);-1==b&&(b=Jb());a.fd=b;return wb[b]=a}var hb={open(a){a.re=vb[a.node.Te].re;a.re.open&&a.re.open(a)},Me(){throw new H(70);}};
function cb(a,b){vb[a]={re:b}}function Nb(a,b){var c="/"===b,d=!b;if(c&&tb)throw new H(10);if(!c&&!d){var e=K(b,{Af:!1});b=e.path;e=e.node;if(e.Oe)throw new H(10);if(!J(e.mode))throw new H(54);}b={type:a,Og:{},Hf:b,mg:[]};a=a.Ie(b);a.Ie=b;b.root=a;c?tb=a:e&&(e.Oe=b,e.Ie&&e.Ie.mg.push(b))}function Ob(a,b,c){var d=K(a,{parent:!0}).node;a=Ta(a);if(!a||"."===a||".."===a)throw new H(28);var e=Hb(d,a);if(e)throw new H(e);if(!d.qe.df)throw new H(63);return d.qe.df(d,a,b,c)}
function L(a,b){return Ob(a,(void 0!==b?b:511)&1023|16384,0)}function Pb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return Ob(a,b|8192,c)}function Qb(a,b){if(!Wa(a))throw new H(44);var c=K(b,{parent:!0}).node;if(!c)throw new H(44);b=Ta(b);var d=Hb(c,b);if(d)throw new H(d);if(!c.qe.gf)throw new H(63);c.qe.gf(c,b,a)}
function Rb(a){var b=K(a,{parent:!0}).node;if(!b)throw new H(44);a=Ta(a);var c=kb(b,a),d=Ib(b,a,!1);if(d)throw new H(d);if(!b.qe.hf)throw new H(63);if(c.Oe)throw new H(10);b.qe.hf(b,a);Db(c)}function Ab(a){a=K(a).node;if(!a)throw new H(44);if(!a.qe.Ue)throw new H(28);return Wa(Bb(a.parent),a.qe.Ue(a))}function Sb(a,b){a="string"==typeof a?K(a,{Ye:!0}).node:a;if(!a.qe.ze)throw new H(63);a.qe.ze(a,{mode:b&4095|a.mode&-4096,timestamp:Date.now()})}
function Tb(a,b,c){if(""===a)throw new H(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?("undefined"==typeof c?438:c)&4095|32768:0;if("object"==typeof a)var e=a;else{a=G(a);try{e=K(a,{Ye:!(b&131072)}).node}catch(f){}}d=!1;if(b&64)if(e){if(b&128)throw new H(20);}else e=Ob(a,c,0),d=!0;if(!e)throw new H(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&!J(e.mode))throw new H(54);if(!d&&(c=
e?40960===(e.mode&61440)?32:J(e.mode)&&("r"!==Gb(b)||b&512)?31:Eb(e,Gb(b)):44))throw new H(c);if(b&512&&!d){c=e;c="string"==typeof c?K(c,{Ye:!0}).node:c;if(!c.qe.ze)throw new H(63);if(J(c.mode))throw new H(31);if(32768!==(c.mode&61440))throw new H(28);if(d=Eb(c,"w"))throw new H(d);c.qe.ze(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Lb({node:e,path:Bb(e),flags:b,seekable:!0,position:0,re:e.re,tg:[],error:!1});e.re.open&&e.re.open(e);!h.logReadFiles||b&1||(Ub||={},a in Ub||(Ub[a]=1));return e}
function Vb(a){if(null===a.fd)throw new H(8);a.mf&&(a.mf=null);try{a.re.close&&a.re.close(a)}catch(b){throw b;}finally{wb[a.fd]=null}a.fd=null}function Wb(a,b,c){if(null===a.fd)throw new H(8);if(!a.seekable||!a.re.Me)throw new H(70);if(0!=c&&1!=c&&2!=c)throw new H(28);a.position=a.re.Me(a,b,c);a.tg=[]}
function Xb(a,b,c,d,e,f){if(0>d||0>e)throw new H(28);if(null===a.fd)throw new H(8);if(0===(a.flags&2097155))throw new H(8);if(J(a.node.mode))throw new H(31);if(!a.re.write)throw new H(28);a.seekable&&a.flags&1024&&Wb(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new H(70);b=a.re.write(a,b,c,d,e,f);g||(a.position+=b);return b}
function Yb(){H||(H=function(a,b){this.name="ErrnoError";this.node=b;this.rg=function(c){this.Ce=c};this.rg(a);this.message="FS error"},H.prototype=Error(),H.prototype.constructor=H,[44].forEach(a=>{jb[a]=new H(a);jb[a].stack="<generic error, no stack>"}))}var Zb;function $b(a,b){a="string"==typeof a?a:Bb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=G(a+"/"+c);try{L(d)}catch(e){}a=d}}return d}
function ac(a,b,c,d){a=G(("string"==typeof a?a:Bb(a))+"/"+b);c=sb(c,d);return Ob(a,(void 0!==c?c:438)&4095|32768,0)}function qb(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:Bb(a),g=b?G(a+"/"+b):a);a=sb(d,e);g=Ob(g,(void 0!==a?a:438)&4095|32768,0);if(c){if("string"==typeof c){b=Array(c.length);d=0;for(e=c.length;d<e;++d)b[d]=c.charCodeAt(d);c=b}Sb(g,a|146);b=Tb(g,577);Xb(b,c,0,c.length,0,f);Vb(b);Sb(g,a)}}
function bc(a,b,c,d){a=G(("string"==typeof a?a:Bb(a))+"/"+b);b=sb(!!c,!!d);bc.Ff||(bc.Ff=64);var e=bc.Ff++<<8|0;cb(e,{open(f){f.seekable=!1},close(){d&&d.buffer&&d.buffer.length&&d(10)},read(f,g,l,n){for(var p=0,t=0;t<n;t++){try{var r=c()}catch(u){throw new H(29);}if(void 0===r&&0===p)throw new H(6);if(null===r||void 0===r)break;p++;g[l+t]=r}p&&(f.node.timestamp=Date.now());return p},write(f,g,l,n){for(var p=0;p<n;p++)try{d(g[l+p])}catch(t){throw new H(29);}n&&(f.node.timestamp=Date.now());return p}});
return Pb(a,b,e)}function cc(a){if(!(a.Ef||a.lg||a.link||a.Cd)){if("undefined"!=typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(ha)try{a.Cd=Za(ha(a.url)),a.te=a.Cd.length}catch(b){throw new H(29);}else throw Error("Cannot load without read() or XMLHttpRequest.");}}
function dc(a,b,c,d,e){if("undefined"!=typeof XMLHttpRequest)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";c={Ef:!1,url:c};var f=ac(a,b,d,e);c.Cd?f.Cd=c.Cd:c.url&&(f.Cd=null,f.url=c.url);Object.defineProperties(f,{te:{get:function(){return this.Cd.length}}});var g={};Object.keys(f.re).forEach(l=>{var n=f.re[l];g[l]=function(){cc(f);return n.apply(null,arguments)}});g.read=(l,n,p,t,r)=>{cc(f);l=l.node.Cd;if(r>=l.length)n=
0;else{t=Math.min(l.length-r,t);if(l.slice)for(var u=0;u<t;u++)n[p+u]=l[r+u];else for(u=0;u<t;u++)n[p+u]=l.get(r+u);n=t}return n};g.nf=()=>{cc(f);m();throw new H(48);};f.re=g;return f}var ec={},Mb,Ub;function fc(a,b){if("/"===b.charAt(0))return b;a=-100===a?"/":Kb(a).path;if(0==b.length)throw new H(44);return G(a+"/"+b)}var gc=void 0;function hc(){var a=w[+gc>>2];gc+=4;return a}
var sc=(a,b)=>{ic=a;jc=b;if(kc)if(lc||=!0,0==a)mc=function(){var d=Math.max(0,nc+b-oc())|0;setTimeout(pc,d)};else if(1==a)mc=function(){qc(pc)};else if(2==a){if("undefined"==typeof rc)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);rc=function(d){c.push(d);postMessage("setimmediate","*")}}else rc=setImmediate;mc=function(){rc(pc)}}},oc;oc=()=>performance.now();
var Ac=(a,b,c,d,e)=>{!kc||m("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");kc=a;tc=d;var f=uc;lc=!1;pc=function(){if(!ma)if(0<vc.length){var g=vc.shift();g.Hg(g.xg);if(wc){var l=wc,n=0==l%1?l-1:Math.floor(l);wc=g.Eg?n:(8*l+(n+.5))/9}h.setStatus&&(g=h.statusMessage||"Please wait...",l=wc,n=xc.Fg,l?l<n?h.setStatus(g+" ("+(n-l)+"/"+n+")"):h.setStatus(g):h.setStatus(""));
f<uc||setTimeout(pc,0)}else f<uc||(yc=yc+1|0,1==ic&&1<jc&&0!=yc%jc?mc():(0==ic&&(nc=oc()),ma||h.preMainLoop&&!1===h.preMainLoop()||(zc(a),h.postMainLoop&&h.postMainLoop()),f<uc||("object"==typeof SDL&&SDL.audio&&SDL.audio.pg&&SDL.audio.pg(),mc())))};e||(b&&0<b?sc(0,1E3/b):sc(1,1),mc());if(c)throw"unwind";},Bc=a=>{a instanceof Ma||"unwind"==a||da(1,a)},Cc=a=>{na=a;if(!Pa){if(h.onExit)h.onExit(a);ma=!0}da(a,new Ma(a))},Dc=a=>{na=a;Cc(a)},zc=a=>{if(!ma)try{if(a(),!Pa)try{na=a=na,Cc(a)}catch(b){Bc(b)}}catch(b){Bc(b)}},
Ec=(a,b)=>setTimeout(()=>{zc(a)},b),lc=!1,mc=null,uc=0,kc=null,tc=0,ic=0,jc=0,yc=0,vc=[];function Fc(){mc=null;uc++}function Gc(){uc++;var a=ic,b=jc,c=kc;kc=null;Ac(c,0,!1,tc,!0);sc(a,b);mc()}var xc={},nc,pc,wc,Hc=!1,Ic=!1,Jc=[];
function ob(){function a(){Ic=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}if(!Kc){Kc=!0;mb.push({canHandle:function(c){return!h.Ng&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var g=new Blob([c],{type:Lc(d)});g.size!==c.length&&(g=new Blob([(new Uint8Array(c)).buffer],{type:Lc(d)}));var l=URL.createObjectURL(g),n=new Image;n.onload=()=>{n.complete||m(`Image ${d} could not be decoded`);
var p=document.createElement("canvas");p.width=n.width;p.height=n.height;p.getContext("2d").drawImage(n,0,0);URL.revokeObjectURL(l);e&&e(c)};n.onerror=()=>{k(`Image ${l} could not be decoded`);f&&f()};n.src=l}});mb.push({canHandle:function(c){return!h.Mg&&c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e){function f(){g||(g=!0,e&&e(c))}var g=!1,l=URL.createObjectURL(new Blob([c],{type:Lc(d)})),n=new Audio;n.addEventListener("canplaythrough",()=>f(n),!1);n.onerror=function(){if(!g){k(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);
for(var p="",t=0,r=0,u=0;u<c.length;u++)for(t=t<<8|c[u],r+=8;6<=r;){var B=t>>r-6&63;r-=6;p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[B]}2==r?(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&3)<<4],p+="=="):4==r&&(p+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(t&15)<<2],p+="=");n.src="data:audio/x-"+d.substr(-3)+";base64,"+p;f(n)}};n.src=l;Ec(()=>{f(n)},1E4)}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||
b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!Ic&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}var Mc=!1,Nc=void 0,Oc=void 0;function Pc(){if(!Hc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Qc=0;
function qc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Qc)Qc=b+1E3/60;else for(;b+2>=Qc;)Qc+=1E3/60;setTimeout(a,Math.max(Qc-b,0))}}function Lc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Rc=[];function Sc(){var a=h.canvas;Rc.forEach(b=>b(a.width,a.height))}
function Tc(a,b,c){b&&c?(a.vg=b,a.eg=c):(b=a.vg,c=a.eg);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Oc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var nb={},rc,Kc,M=12288,Uc=!1,Vc=0,Wc=0,Xc=0,O={alpha:!1,depth:!1,stencil:!1,antialias:!1},Yc={},Zc,$c=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,f)=>b.drawArraysInstancedANGLE(c,d,e,f),a.drawElementsInstanced=(c,d,e,f,g)=>b.drawElementsInstancedANGLE(c,d,e,f,g))},ad=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},bd=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},cd=1,dd=[],P=[],ed=[],fd=[],gd=[],Q=[],hd=[],jd=[],kd=[],ld={},md=4;function R(a){nd||=a}
var od=a=>{for(var b=cd++,c=a.length;c<b;c++)a[c]=null;return b},qd=(a,b)=>{a.ve||(a.ve=a.getContext,a.getContext=function(d,e){e=a.ve(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?pd(c,b):0},pd=(a,b)=>{var c=od(jd),d={handle:c,attributes:b,version:b.Gf,Ke:a};a.canvas&&(a.canvas.Qe=d);jd[c]=d;("undefined"==typeof b.ag||b.ag)&&rd(d);return c},td=a=>{sd=jd[a];h.Ee=S=sd&&sd.Ke},rd=a=>{a||=sd;if(!a.gg){a.gg=!0;var b=a.Ke;$c(b);ad(b);bd(b);b.He=
b.getExtension("EXT_disjoint_timer_query");b.Lg=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}};function ud(){var a=S.getSupportedExtensions()||[];return a=a.concat(a.map(b=>"GL_"+b))}
var vd={},nd,sd,wd=a=>{var b=Ya(a)+1,c=D(b);c&&E(a,v,c,b);return c},xd=[],yd=(a,b)=>{xd.length=0;for(var c;c=v[a++];){var d=105!=c;d&=112!=c;b+=d&&b%8?4:0;xd.push(112==c?x[b>>2]:105==c?w[b>>2]:z[b>>3]);b+=d?8:4}return xd},Bd=a=>{var b=zd();a=a();Ad(b);return a},Cd=0;function Dd(){for(var a=Ed.length-1;0<=a;--a)Fd(a);Ed=[];T=[]}var T=[];
function Gd(a,b,c){function d(g,l){if(g.length!=l.length)return!1;for(var n in g)if(g[n]!=l[n])return!1;return!0}for(var e in T){var f=T[e];if(f.tf==a&&d(f.wf,c))return}T.push({tf:a,Kf:b,wf:c});T.sort((g,l)=>g.Kf<l.Kf)}function Hd(a){for(var b=0;b<T.length;++b)T[b].tf==a&&(T.splice(b,1),--b)}function Id(){return navigator.userActivation?navigator.userActivation.isActive:Cd&&Jd.Re}function Kd(){if(Id())for(var a=0;a<T.length;++a){var b=T[a];T.splice(a,1);--a;b.tf.apply(null,b.wf)}}var Ed=[];
function Fd(a){var b=Ed[a];b.target.removeEventListener(b.we,b.bg,b.Ae);Ed.splice(a,1)}function Ld(a){function b(d){++Cd;Jd=a;Kd();a.De(d);Kd();--Cd}if(!a.target)return-4;if(a.Be)a.bg=b,a.target.addEventListener(a.we,b,a.Ae),Ed.push(a),Md||(ta.push(Dd),Md=!0);else for(var c=0;c<Ed.length;++c)Ed[c].target==a.target&&Ed[c].we==a.we&&Fd(c--);return 0}function Nd(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}
function Od(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}
var Pd={},Md,Jd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be={},ce=[0,document,window],U=a=>{a=2<a?a?F(v,a):"":a;return ce[a]||document.querySelector(a)},ee=a=>{var b=Ya(a)+1,c=de(b);E(a,v,c,b);return c},fe=a=>Bd(()=>{var b=de(8),c=b+4,d=ee(a.id);if(d=U(d))w[b>>2]=d.width,w[c>>2]=d.height;return[w[b>>2],w[c>>2]]}),ge=(a,b,c)=>{a=U(a);if(!a)return-4;a.width=b;a.height=c;return 0},he=(a,b,c)=>{a.Dg?Bd(()=>{var d=ee(a.id);ge(d,b,c)}):(a.width=b,a.height=c)},ie=a=>{function b(){document.fullscreenElement||
document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),he(a,d,e),a.style.width=f,a.style.height=g,a.style.backgroundColor=l,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=p,a.style.paddingRight=t,a.style.paddingTop=r,a.style.paddingBottom=u,a.style.marginLeft=B,a.style.marginRight=N,a.style.marginTop=W,a.style.marginBottom=fa,document.body.style.margin=
ub,document.documentElement.style.overflow=$a,document.body.scroll=cf,a.style.Le=df,a.Qe&&a.Qe.Ke.viewport(0,0,d,e),be.Xe&&V.apply(null,[be.Xe,37,0,be.xf]))}var c=fe(a),d=c[0],e=c[1],f=a.style.width,g=a.style.height,l=a.style.backgroundColor,n=document.body.style.backgroundColor,p=a.style.paddingLeft,t=a.style.paddingRight,r=a.style.paddingTop,u=a.style.paddingBottom,B=a.style.marginLeft,N=a.style.marginRight,W=a.style.marginTop,fa=a.style.marginBottom,ub=document.body.style.margin,$a=document.documentElement.style.overflow,
cf=document.body.scroll,df=a.style.Le;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)},je=(a,b,c)=>{a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"},ke=a=>0>ce.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},le=(a,b)=>{if(0!=b.sf||0!=b.jf){ie(a);var c=b.sg?innerWidth:screen.width,d=b.sg?innerHeight:screen.height,e=ke(a),f=e.width;e=e.height;var g=fe(a),l=g[0];g=g[1];3==b.sf?(je(a,(d-e)/2,(c-f)/
2),c=f,d=e):2==b.sf&&(c*g<l*d?(f=g*c/l,je(a,(d-f)/2,0),d=f):(f=l*d/g,je(a,0,(c-f)/2),c=f));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.cg&&(a.style.Le="optimizeSpeed",a.style.Le="-moz-crisp-edges",a.style.Le="-o-crisp-edges",a.style.Le="-webkit-optimize-contrast",a.style.Le="optimize-contrast",a.style.Le="crisp-edges",a.style.Le="pixelated");f=2==b.jf?devicePixelRatio:
1;0!=b.jf&&(c=c*f|0,d=d*f|0,he(a,c,d),a.Qe&&a.Qe.Ke.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return Od()?-3:-1;be=b;b.Xe&&V.apply(null,[b.Xe,37,0,b.xf]);return 0},me=a=>{if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0},ne=(a,b)=>{z[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)z[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)z[a+
8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)w[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];w[a+1296>>2]=b.connected;w[a+1300>>2]=b.index;w[a+8>>2]=b.axes.length;w[a+12>>2]=b.buttons.length;E(b.id,v,a+1304,64);E(b.mapping,v,a+1368,64)},oe=[],pe=(a,b,c,d)=>{for(var e=0;e<a;e++){var f=S[c](),g=f&&od(d);f?(f.name=g,d[g]=f):R(1282);w[b+4*e>>2]=g}},qe=(a,b,c,d,e,f,g,l)=>{b=P[b];if(a=S[a](b,c))d=l&&E(a.name,
v,l,d),e&&(w[e>>2]=d),f&&(w[f>>2]=a.size),g&&(w[g>>2]=a.type)},re=(a,b,c)=>{if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=S.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=S.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;
default:R(1280);return}else{if(e instanceof Float32Array||e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:w[b+4*a>>2]=e[a];break;case 2:y[b+4*a>>2]=e[a];break;case 4:q[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(f){R(1280);k(`GL_INVALID_ENUM in glGet${c}v: Unknown object returned from WebGL getParameter(${a})! (error: ${f})`);return}}break;default:R(1280);k(`GL_INVALID_ENUM in glGet${c}v: Native code calling glGet${c}v(${a}) and it returns ${e} of type ${typeof e}!`);
return}switch(c){case 1:c=d;x[b>>2]=c;x[b+4>>2]=(c-x[b>>2])/4294967296;break;case 0:w[b>>2]=d;break;case 2:y[b>>2]=d;break;case 4:q[b>>0]=d?1:0}}else R(1281)},se=(a,b,c)=>{if(c){a=S.He.getQueryObjectEXT(kd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d;x[c+4>>2]=(d-x[c>>2])/4294967296}else R(1281)},te=(a,b,c)=>{if(c){a=S.He.getQueryObjectEXT(kd[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;w[c>>2]=d}else R(1281)},ue=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),ve=a=>{var b=a.We,c=a.Pf,d;if(!b)for(a.We=
b={},a.Of={},d=0;d<S.getProgramParameter(a,35718);++d){var e=S.getActiveUniform(a,d);var f=e.name;e=e.size;var g=ue(f);g=0<g?f.slice(0,g):f;var l=a.uf;a.uf+=e;c[g]=[e,l];for(f=0;f<e;++f)b[l]=f,a.Of[l++]=g}},X=a=>{var b=S.Vf;if(b){var c=b.We[a];"number"==typeof c&&(b.We[a]=c=S.getUniformLocation(b,b.Of[a]+(0<c?`[${c}]`:"")));return c}R(1282)},we=(a,b,c,d)=>{if(c)if(a=P[a],ve(a),a=S.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a}else for(b=
0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b]}else R(1281)},xe=(a,b,c,d)=>{if(c)if(a=S.getVertexAttrib(a,b),34975==b)w[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:w[c>>2]=a;break;case 2:y[c>>2]=a;break;case 5:w[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:w[c+4*b>>2]=a[b];break;case 2:y[c+4*b>>2]=a[b];break;case 5:w[c+4*b>>2]=Math.fround(a[b])}else R(1281)},ye=(a,b,c,d,e)=>{a-=5120;a=1==a?v:4==a?w:6==a?y:
5==a||28922==a?x:pa;var f=31-Math.clz32(a.BYTES_PER_ELEMENT),g=md;return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+g-1&-g)>>f)},ze=[],Ae=[],Be=(a,b)=>{if(!Od())return-1;a=U(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?Id()?le(a,b):b.Zf?(Gd(le,1,[a,b]),1):-2:-3:-4},Ce=(a,b)=>{var c={target:U(2),we:"beforeunload",Be:b,De:(d=event)=>{var e=V.apply(null,[b,28,0,a]);e&&=e?F(v,e):"";if(e)return d.preventDefault(),d.returnValue=e},Ae:!0};return Ld(c)},De=(a,b,
c,d,e,f)=>{Rd||=D(256);a={target:U(a),we:f,Be:d,De:(g=event)=>{var l=g.target.id?g.target.id:"",n=Rd;E(Nd(g.target),v,n+0,128);E(l,v,n+128,128);V.apply(null,[d,e,n,b])&&g.preventDefault()},Ae:c};return Ld(a)},Ee=(a,b,c,d,e)=>{Td||=D(280);return Ld({target:a,we:e,Be:d,De:(f=event)=>{var g=Td,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!l;w[g>>2]=n;w[g+4>>2]=Od();var p=n?l:Sd,t=p&&p.id?p.id:"";E(Nd(p),v,g+8,128);E(t,
v,g+136,128);w[g+264>>2]=p?p.clientWidth:0;w[g+268>>2]=p?p.clientHeight:0;w[g+272>>2]=screen.width;w[g+276>>2]=screen.height;n&&(Sd=l);V.apply(null,[d,19,g,b])&&f.preventDefault()},Ae:c})},Fe=(a,b,c,d,e)=>{Ud||=D(1432);b={target:U(2),Re:!0,we:e,Be:c,De:(f=event)=>{var g=Ud;ne(g,f.gamepad);V.apply(null,[c,d,g,a])&&f.preventDefault()},Ae:b};return Ld(b)},Ge=(a,b,c,d,e,f)=>{Vd||=D(176);a={target:U(a),Re:!0,we:f,Be:d,De:g=>{var l=Vd;z[l>>3]=g.timeStamp;var n=l>>2;w[n+2]=g.location;w[n+3]=g.ctrlKey;w[n+
4]=g.shiftKey;w[n+5]=g.altKey;w[n+6]=g.metaKey;w[n+7]=g.repeat;w[n+8]=g.charCode;w[n+9]=g.keyCode;w[n+10]=g.which;E(g.key||"",v,l+44,32);E(g.code||"",v,l+76,32);E(g.char||"",v,l+108,32);E(g.locale||"",v,l+140,32);V.apply(null,[d,e,l,b])&&g.preventDefault()},Ae:c};return Ld(a)},He=(a,b,c)=>{z[a>>3]=b.timeStamp;a>>=2;w[a+2]=b.screenX;w[a+3]=b.screenY;w[a+4]=b.clientX;w[a+5]=b.clientY;w[a+6]=b.ctrlKey;w[a+7]=b.shiftKey;w[a+8]=b.altKey;w[a+9]=b.metaKey;oa[2*a+20]=b.button;oa[2*a+21]=b.buttons;w[a+11]=
b.movementX;w[a+12]=b.movementY;c=ke(c);w[a+13]=b.clientX-c.left;w[a+14]=b.clientY-c.top},Ie=(a,b,c,d,e,f)=>{Wd||=D(72);a=U(a);return Ld({target:a,Re:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,we:f,Be:d,De:(g=event)=>{He(Wd,g,a);V.apply(null,[d,e,Wd,b])&&g.preventDefault()},Ae:c})},Je=(a,b,c,d,e)=>{Xd||=D(260);return Ld({target:a,we:e,Be:d,De:(f=event)=>{var g=Xd,l=document.pointerLockElement||document.ve||document.qg||document.qf;w[g>>2]=!!l;var n=l&&l.id?l.id:"";E(Nd(l),v,g+4,128);E(n,v,g+
132,128);V.apply(null,[d,20,g,b])&&f.preventDefault()},Ae:c})},Ke=(a,b,c,d)=>{Yd||=D(36);a=U(a);return Ld({target:a,we:"resize",Be:d,De:(e=event)=>{if(e.target==a){var f=document.body;if(f){var g=Yd;w[g>>2]=e.detail;w[g+4>>2]=f.clientWidth;w[g+8>>2]=f.clientHeight;w[g+12>>2]=innerWidth;w[g+16>>2]=innerHeight;w[g+20>>2]=outerWidth;w[g+24>>2]=outerHeight;w[g+28>>2]=pageXOffset;w[g+32>>2]=pageYOffset;V.apply(null,[d,10,g,b])&&e.preventDefault()}}},Ae:c})},Le=(a,b,c,d,e,f)=>{Zd||=D(1696);a=U(a);return Ld({target:a,
Re:"touchstart"==f||"touchend"==f,we:f,Be:d,De:g=>{for(var l,n={},p=g.touches,t=0;t<p.length;++t)l=p[t],l.Df=l.Jf=0,n[l.identifier]=l;for(t=0;t<g.changedTouches.length;++t)l=g.changedTouches[t],l.Df=1,n[l.identifier]=l;for(t=0;t<g.targetTouches.length;++t)n[g.targetTouches[t].identifier].Jf=1;p=Zd;z[p>>3]=g.timeStamp;var r=p>>2;w[r+3]=g.ctrlKey;w[r+4]=g.shiftKey;w[r+5]=g.altKey;w[r+6]=g.metaKey;r+=7;var u=ke(a),B=0;for(t in n)if(l=n[t],w[r]=l.identifier,w[r+1]=l.screenX,w[r+2]=l.screenY,w[r+3]=l.clientX,
w[r+4]=l.clientY,w[r+5]=l.pageX,w[r+6]=l.pageY,w[r+7]=l.Df,w[r+8]=l.Jf,w[r+9]=l.clientX-u.left,w[r+10]=l.clientY-u.top,r+=13,31<++B)break;w[p+8>>2]=B;V.apply(null,[d,e,p,b])&&g.preventDefault()},Ae:c})},Me=(a,b,c)=>{var d=ce[1];$d||=D(8);return Ld({target:d,we:"visibilitychange",Be:c,De:(e=event)=>{var f=$d,g=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);w[f>>2]=document.hidden;w[f+4>>2]=g;V.apply(null,[c,21,f,a])&&e.preventDefault()},Ae:b})},Ne=(a,b,c,d)=>{ae||=D(104);
return Ld({target:a,Re:!0,we:"wheel",Be:d,De:(e=event)=>{var f=ae;He(f,e,a);z[f+72>>3]=e.deltaX;z[f+80>>3]=e.deltaY;z[f+88>>3]=e.deltaZ;w[f+96>>2]=e.deltaMode;V.apply(null,[d,9,f,b])&&e.preventDefault()},Ae:c})},Oe={},Qe=()=>{if(!Pe){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Oe)void 0===Oe[b]?delete a[b]:a[b]=Oe[b];
var c=[];for(b in a)c.push(`${b}=${a[b]}`);Pe=c}return Pe},Pe,Re=a=>{try{a()}catch(b){m(b)}};function Se(){var a=Y,b={},c;for(c in a)(function(d){var e=a[d];b[d]="function"==typeof e?function(){Te.push(d);try{return e.apply(null,arguments)}finally{ma||(Te.pop(),Ue&&1===Ve&&0===Te.length&&(Ve=0,Re(We),"undefined"!=typeof Fibers&&Fibers.Qg()))}}:e})(c);return b}var Ve=0,Ue=null,Xe=0,Te=[],Ye={},Ze={},$e=0,af=null,bf=[];
function ef(){var a=D(4108),b=a+12;x[a>>2]=b;x[a+4>>2]=b+4096;b=Te[0];var c=Ye[b];void 0===c&&(c=$e++,Ye[b]=c,Ze[c]=b);w[a+8>>2]=c;return a}
function ff(a){if(!ma){if(0===Ve){var b=!1,c=!1;a((d=0)=>{if(!ma&&(Xe=d,b=!0,c)){Ve=2;Re(()=>gf(Ue));"undefined"!=typeof nb&&kc&&Gc();d=!1;try{var e=(0,Y[Ze[w[Ue+8>>2]]])()}catch(l){e=l,d=!0}var f=!1;if(!Ue){var g=af;g&&(af=null,(d?g.reject:g.resolve)(e),f=!0)}if(d&&!f)throw e;}});c=!0;b||(Ve=1,Ue=ef(),"undefined"!=typeof nb&&kc&&Fc(),Re(()=>hf(Ue)))}else 2===Ve?(Ve=0,Re(jf),kf(Ue),Ue=null,bf.forEach(d=>zc(d))):m(`invalid state: ${Ve}`);return Xe}}
function Fb(a,b,c,d){a||=this;this.parent=a;this.Ie=a.Ie;this.Oe=null;this.id=xb++;this.name=b;this.mode=c;this.qe={};this.re={};this.Te=d}Object.defineProperties(Fb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},lg:{get:function(){return J(this.mode)}},Ef:{get:function(){return 8192===(this.mode&61440)}}});Yb();yb=Array(4096);
Nb(I,"/");L("/tmp");L("/home");L("/home/web_user");(function(){L("/dev");cb(259,{read:()=>0,write:(d,e,f,g)=>g});Pb("/dev/null",259);bb(1280,eb);bb(1536,fb);Pb("/dev/tty",1280);Pb("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(b=Va(a).byteLength);return a[--b]};bc("/dev","random",c);bc("/dev","urandom",c);L("/dev/shm");L("/dev/shm/tmp")})();
(function(){L("/proc");var a=L("/proc/self");L("/proc/self/fd");Nb({Ie(){var b=ib(a,"fd",16895,73);b.qe={Se(c,d){var e=Kb(+d);c={parent:null,Ie:{Hf:"fake"},qe:{Ue:()=>e.path}};return c.parent=c}};return b}},"/proc/self/fd")})();h.FS_createPath=$b;h.FS_createDataFile=qb;h.FS_createPreloadedFile=rb;h.FS_unlink=Rb;h.FS_createLazyFile=dc;h.FS_createDevice=bc;
h.requestFullscreen=function(a,b){function c(){Hc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Pc,Nc&&d.requestPointerLock(),Hc=!0,Oc?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=x[SDL.screen>>2]|8388608),Tc(h.canvas),Sc()):Tc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Oc?("undefined"!=typeof SDL&&(w[SDL.screen>>2]=
x[SDL.screen>>2]&-8388609),Tc(h.canvas),Sc()):Tc(d));if(h.onFullScreen)h.onFullScreen(Hc);if(h.onFullscreen)h.onFullscreen(Hc)}Nc=a;Oc=b;"undefined"==typeof Nc&&(Nc=!0);"undefined"==typeof Oc&&(Oc=!1);var d=h.canvas;Mc||(Mc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,
d);e.appendChild(d);e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()};h.requestAnimationFrame=qc;h.setCanvasSize=function(a,b,c){Tc(h.canvas,a,b);c||Sc()};h.pauseMainLoop=Fc;h.resumeMainLoop=Gc;
h.getUserMedia=function(a){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(a)};
h.createContext=function(a,b,c,d){if(b&&h.Ee&&a==h.canvas)return h.Ee;var e;if(b){var f={antialias:!1,alpha:!1,Gf:1};if(d)for(var g in d)f[g]=d[g];if("undefined"!=typeof vd&&(e=qd(a,f)))var l=jd[e].Ke}else l=a.getContext("2d");if(!l)return null;c&&(b||"undefined"==typeof S||m("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.Ee=l,b&&td(e),h.ug=b,Jc.forEach(n=>n()),ob());return l};for(var S,Z=0;32>Z;++Z)oe.push(Array(Z));var lf=new Float32Array(288);
for(Z=0;288>Z;++Z)ze[Z]=lf.subarray(0,Z+1);var mf=new Int32Array(288);for(Z=0;288>Z;++Z)Ae[Z]=mf.subarray(0,Z+1);
var of={b:(a,b,c,d)=>{m(`Assertion failed: ${a?F(v,a):""}, at: `+[b?b?F(v,b):"":"unknown filename",c,d?d?F(v,d):"":"unknown function"])},M:function(a,b,c){gc=c;try{var d=Kb(a);switch(b){case 0:var e=hc();if(0>e)return-28;for(;wb[e];)e++;return Lb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=hc(),d.flags|=e,0;case 5:return e=hc(),oa[e+0>>1]=2,0;case 6:case 7:return 0;case 16:case 8:return-28;case 9:return w[nf()>>2]=28,-1;default:return-28}}catch(f){if("undefined"==typeof ec||
"ErrnoError"!==f.name)throw f;return-f.Ce}},Za:function(a,b,c){gc=c;try{var d=Kb(a);switch(b){case 21509:return d.se?0:-59;case 21505:if(!d.se)return-59;if(d.se.Je.ig){b=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=hc();w[e>>2]=25856;w[e+4>>2]=5;w[e+8>>2]=191;w[e+12>>2]=35387;for(var f=0;32>f;f++)q[e+f+17>>0]=b[f]||0}return 0;case 21510:case 21511:case 21512:return d.se?0:-59;case 21506:case 21507:case 21508:if(!d.se)return-59;if(d.se.Je.jg)for(e=hc(),b=[],f=
0;32>f;f++)b.push(q[e+f+17>>0]);return 0;case 21519:if(!d.se)return-59;e=hc();return w[e>>2]=0;case 21520:return d.se?-28:-59;case 21531:e=hc();if(!d.re.hg)throw new H(59);return d.re.hg(d,b,e);case 21523:if(!d.se)return-59;d.se.Je.kg&&(f=[24,80],e=hc(),oa[e>>1]=f[0],oa[e+2>>1]=f[1]);return 0;case 21524:return d.se?0:-59;case 21515:return d.se?0:-59;default:return-28}}catch(g){if("undefined"==typeof ec||"ErrnoError"!==g.name)throw g;return-g.Ce}},Ua:function(a,b,c){try{return b=b?F(v,b):"",b=fc(a,
b),b=G(b),"/"===b[b.length-1]&&(b=b.substr(0,b.length-1)),L(b,c),0}catch(d){if("undefined"==typeof ec||"ErrnoError"!==d.name)throw d;return-d.Ce}},N:function(a,b,c,d){gc=d;try{b=b?F(v,b):"";b=fc(a,b);var e=d?hc():0;return Tb(b,c,e).fd}catch(f){if("undefined"==typeof ec||"ErrnoError"!==f.name)throw f;return-f.Ce}},Ta:function(a,b){try{a=a?F(v,a):"";a:{try{var c=K(a,{Ye:!0}).node;if(!c)throw new H(44);if(!c.qe.Fe)throw new H(63);var d=c.qe.Fe(c)}catch(n){if(n&&n.node&&G(a)!==G(Bb(n.node))){var e=-54;
break a}throw n;}w[b>>2]=d.$f;w[b+4>>2]=d.mode;x[b+8>>2]=d.og;w[b+12>>2]=d.uid;w[b+16>>2]=d.dg;w[b+20>>2]=d.Te;C=[d.size>>>0,(A=d.size,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+24>>2]=C[0];w[b+28>>2]=C[1];w[b+32>>2]=4096;w[b+36>>2]=d.Sf;var f=d.Qf.getTime(),g=d.ng.getTime(),l=d.Tf.getTime();C=[Math.floor(f/1E3)>>>0,(A=Math.floor(f/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+40>>
2]=C[0];w[b+44>>2]=C[1];x[b+48>>2]=f%1E3*1E3;C=[Math.floor(g/1E3)>>>0,(A=Math.floor(g/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+56>>2]=C[0];w[b+60>>2]=C[1];x[b+64>>2]=g%1E3*1E3;C=[Math.floor(l/1E3)>>>0,(A=Math.floor(l/1E3),1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+72>>2]=C[0];w[b+76>>2]=C[1];x[b+80>>2]=l%1E3*1E3;C=[d.Cf>>>0,(A=d.Cf,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>
0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];w[b+88>>2]=C[0];w[b+92>>2]=C[1];e=0}return e}catch(n){if("undefined"==typeof ec||"ErrnoError"!==n.name)throw n;return-n.Ce}},Sa:function(a,b,c){try{b=b?F(v,b):"";b=fc(a,b);if(0===c)Rb(b);else if(512===c){a=b;var d=K(a,{parent:!0}).node,e=Ta(a),f=kb(d,e),g=Ib(d,e,!0);if(g)throw new H(g);if(!d.qe.ef)throw new H(63);if(f.Oe)throw new H(10);d.qe.ef(d,e);Db(f)}else m("Invalid flags passed to unlinkat");return 0}catch(l){if("undefined"==typeof ec||"ErrnoError"!==
l.name)throw l;return-l.Ce}},_a:()=>1,P:()=>{m("")},Ma:a=>{if(12448==a)return M=12288,1;M=12300;return 0},nc:(a,b,c,d,e)=>{if(62E3!=a)M=12296,c=0;else{if(b)for(;;){a=w[b>>2];if(12321==a)O.alpha=0<w[b+4>>2];else if(12325==a)O.depth=0<w[b+4>>2];else if(12326==a)O.stencil=0<w[b+4>>2];else if(12337==a)a=w[b+4>>2],O.antialias=0<a;else if(12338==a)a=w[b+4>>2],O.antialias=1==a;else if(12544==a)O.Jg=12547!=w[b+4>>2];else if(12344==a)break;b+=8}c&&d||e?(e&&(w[e>>2]=1),c&&0<d&&(x[c>>2]=62002),M=12288,c=1):
(M=12300,c=0)}return c},Tb:(a,b,c,d)=>{if(62E3!=a)return M=12296,0;for(a=1;;){b=w[d>>2];if(12440==b)a=w[d+4>>2];else if(12344==b)break;else return M=12292,0;d+=8}if(2!=a)return M=12293,0;O.Gf=a-1;O.Kg=0;Zc=qd(h.canvas,O);if(0!=Zc)return M=12288,td(Zc),h.ug=!0,Jc.forEach(function(e){e()}),td(null),62004;M=12297;return 0},xb:(a,b)=>{if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;M=12288;return 62006},Ib:(a,b)=>{if(62E3!=a)return M=12296,0;if(62004!=b)return M=12294,0;a=Zc;sd===jd[a]&&(sd=
null);if("object"==typeof Pd)for(var c=jd[a].Ke.canvas,d=0;d<Ed.length;++d)Ed[d].target!=c||Fd(d--);jd[a]&&jd[a].Ke.canvas&&(jd[a].Ke.canvas.Qe=void 0);jd[a]=null;M=12288;Vc==b&&(Vc=0);return 1},mb:(a,b)=>{if(62E3!=a)return M=12296,0;if(62006!=b)return M=12301,1;Wc==b&&(Wc=0);Xc==b&&(Xc=0);M=12288;return 1},cc:(a,b,c,d)=>{if(62E3!=a)return M=12296,0;if(62002!=b)return M=12293,0;if(!d)return M=12300,0;M=12288;switch(c){case 12320:return w[d>>2]=O.alpha?32:24,1;case 12321:return w[d>>2]=O.alpha?8:0,
1;case 12322:return w[d>>2]=8,1;case 12323:return w[d>>2]=8,1;case 12324:return w[d>>2]=8,1;case 12325:return w[d>>2]=O.depth?24:0,1;case 12326:return w[d>>2]=O.stencil?8:0,1;case 12327:return w[d>>2]=12344,1;case 12328:return w[d>>2]=62002,1;case 12329:return w[d>>2]=0,1;case 12330:return w[d>>2]=4096,1;case 12331:return w[d>>2]=16777216,1;case 12332:return w[d>>2]=4096,1;case 12333:return w[d>>2]=0,1;case 12334:return w[d>>2]=0,1;case 12335:return w[d>>2]=12344,1;case 12337:return w[d>>2]=O.antialias?
4:0,1;case 12338:return w[d>>2]=O.antialias?1:0,1;case 12339:return w[d>>2]=4,1;case 12340:return w[d>>2]=12344,1;case 12341:case 12342:case 12343:return w[d>>2]=-1,1;case 12345:case 12346:return w[d>>2]=0,1;case 12347:return w[d>>2]=0,1;case 12348:return w[d>>2]=1;case 12349:case 12350:return w[d>>2]=0,1;case 12351:return w[d>>2]=12430,1;case 12352:return w[d>>2]=4,1;case 12354:return w[d>>2]=0,1;default:return M=12292,0}},O:a=>{M=12288;return 0!=a&&1!=a?0:62E3},Ka:()=>M,Jc:(a,b,c)=>{if(62E3!=a)return M=
12296,0;b&&(w[b>>2]=1);c&&(w[c>>2]=4);Uc=!0;M=12288;return 1},bb:(a,b,c,d)=>{if(62E3!=a)return M=12296,0;if(0!=d&&62004!=d)return M=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return M=12301,0;td(d?Zc:null);Vc=d;Xc=b;Wc=c;M=12288;return 1},La:(a,b)=>{if(62E3!=a)return M=12296,0;M=12288;if(Yc[b])return Yc[b];switch(b){case 12371:a=wd("Emscripten");break;case 12372:a=wd("1.4 Emscripten EGL");break;case 12373:a=wd("");break;case 12429:a=wd("OpenGL_ES");break;default:return M=12300,0}return Yc[b]=a},Ya:()=>
{if(Uc)if(h.Ee)if(h.Ee.isContextLost())M=12302;else return M=12288,1;else M=12290;else M=12289;return 0},Pa:(a,b)=>{if(62E3!=a)return M=12296,0;0==b?sc(0,0):sc(1,b);M=12288;return 1},yc:a=>{if(62E3!=a)return M=12296,0;Xc=Wc=Vc=0;Uc=!1;M=12288;return 1},Na:()=>{M=12288;return 1},Oa:()=>{M=12288;return 1},Ga:(a,b,c)=>{b=yd(b,c);return La[a].apply(null,b)},a:(a,b,c)=>{b=yd(b,c);return La[a].apply(null,b)},$a:()=>Date.now(),Da:()=>{if(!Od())return-1;Hd(le);var a=ce[1];if(a.exitFullscreen)a.fullscreenElement&&
a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},Ha:()=>{Hd(me);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},e:()=>devicePixelRatio,c:(a,b,c)=>{a=U(a);if(!a)return-4;a=ke(a);z[b>>3]=a.width;z[c>>3]=a.height;return 0},n:(a,b)=>{if(0>a||a>=Qd.length)return-5;if(!Qd[a])return-7;ne(b,Qd[a]);return 0},j:oc,sa:()=>Qd.length,Ia:(a,b)=>{w[a>>2]=screen.width;w[b>>2]=screen.height},ia:function(a){S.activeTexture(a)},
ha:(a,b)=>{S.attachShader(P[a],Q[b])},za:(a,b)=>{S.He.beginQueryEXT(a,kd[b])},ga:(a,b,c)=>{S.bindAttribLocation(P[a],b,c?F(v,c):"")},fa:(a,b)=>{S.bindBuffer(a,dd[b])},ea:(a,b)=>{S.bindFramebuffer(a,ed[b])},da:(a,b)=>{S.bindRenderbuffer(a,fd[b])},ca:(a,b)=>{S.bindTexture(a,gd[b])},qa:a=>{S.bindVertexArray(hd[a])},ba:function(a,b,c,d){S.blendColor(a,b,c,d)},aa:function(a){S.blendEquation(a)},$:function(a,b){S.blendEquationSeparate(a,b)},_:function(a,b){S.blendFunc(a,b)},Z:function(a,b,c,d){S.blendFuncSeparate(a,
b,c,d)},Y:(a,b,c,d)=>{S.bufferData(a,c?v.subarray(c,c+b):b,d)},X:(a,b,c,d)=>{S.bufferSubData(a,b,v.subarray(d,d+c))},W:function(a){return S.checkFramebufferStatus(a)},V:function(a){S.clear(a)},U:function(a,b,c,d){S.clearColor(a,b,c,d)},T:function(a){S.clearDepth(a)},S:function(a){S.clearStencil(a)},R:(a,b,c,d)=>{S.colorMask(!!a,!!b,!!c,!!d)},Q:a=>{S.compileShader(Q[a])},vd:(a,b,c,d,e,f,g,l)=>{S.compressedTexImage2D(a,b,c,d,e,f,l?v.subarray(l,l+g):null)},ud:(a,b,c,d,e,f,g,l,n)=>{S.compressedTexSubImage2D(a,
b,c,d,e,f,g,n?v.subarray(n,n+l):null)},td:function(a,b,c,d,e,f,g,l){S.copyTexImage2D(a,b,c,d,e,f,g,l)},sd:function(a,b,c,d,e,f,g,l){S.copyTexSubImage2D(a,b,c,d,e,f,g,l)},rd:()=>{var a=od(P),b=S.createProgram();b.name=a;b.bf=b.$e=b.af=0;b.uf=1;P[a]=b;return a},qd:a=>{var b=od(Q);Q[b]=S.createShader(a);return b},pd:function(a){S.cullFace(a)},od:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=dd[d];e&&(S.deleteBuffer(e),e.name=0,dd[d]=null)}},nd:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=ed[d];
e&&(S.deleteFramebuffer(e),e.name=0,ed[d]=null)}},md:a=>{if(a){var b=P[a];b?(S.deleteProgram(b),b.name=0,P[a]=null):R(1281)}},Ba:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=kd[d];e&&(S.He.deleteQueryEXT(e),kd[d]=null)}},ld:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=fd[d];e&&(S.deleteRenderbuffer(e),e.name=0,fd[d]=null)}},kd:a=>{if(a){var b=Q[a];b?(S.deleteShader(b),Q[a]=null):R(1281)}},jd:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=gd[d];e&&(S.deleteTexture(e),e.name=0,gd[d]=null)}},
pa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];S.deleteVertexArray(hd[d]);hd[d]=null}},id:function(a){S.depthFunc(a)},hd:a=>{S.depthMask(!!a)},gd:function(a,b){S.depthRange(a,b)},fd:(a,b)=>{S.detachShader(P[a],Q[b])},ed:function(a){S.disable(a)},dd:a=>{S.disableVertexAttribArray(a)},cd:(a,b,c)=>{S.drawArrays(a,b,c)},la:(a,b,c,d)=>{S.drawArraysInstanced(a,b,c,d)},ma:(a,b)=>{for(var c=oe[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];S.drawBuffers(c)},bd:(a,b,c,d)=>{S.drawElements(a,b,c,d)},ka:(a,b,c,d,e)=>{S.drawElementsInstanced(a,
b,c,d,e)},ad:function(a){S.enable(a)},$c:a=>{S.enableVertexAttribArray(a)},ya:a=>{S.He.endQueryEXT(a)},_c:function(){S.finish()},Zc:function(){S.flush()},Yc:(a,b,c,d)=>{S.framebufferRenderbuffer(a,b,c,fd[d])},Xc:(a,b,c,d,e)=>{S.framebufferTexture2D(a,b,c,gd[d],e)},Wc:function(a){S.frontFace(a)},Vc:(a,b)=>{pe(a,b,"createBuffer",dd)},Tc:(a,b)=>{pe(a,b,"createFramebuffer",ed)},Ca:(a,b)=>{for(var c=0;c<a;c++){var d=S.He.createQueryEXT();if(!d){for(R(1282);c<a;)w[b+4*c++>>2]=0;break}var e=od(kd);d.name=
e;kd[e]=d;w[b+4*c>>2]=e}},Sc:(a,b)=>{pe(a,b,"createRenderbuffer",fd)},Rc:(a,b)=>{pe(a,b,"createTexture",gd)},oa:function(a,b){pe(a,b,"createVertexArray",hd)},Uc:function(a){S.generateMipmap(a)},Qc:(a,b,c,d,e,f,g)=>{qe("getActiveAttrib",a,b,c,d,e,f,g)},Pc:(a,b,c,d,e,f,g)=>{qe("getActiveUniform",a,b,c,d,e,f,g)},Oc:(a,b,c,d)=>{a=S.getAttachedShaders(P[a]);var e=a.length;e>b&&(e=b);w[c>>2]=e;for(b=0;b<e;++b)w[d+4*b>>2]=Q.indexOf(a[b])},Nc:(a,b)=>S.getAttribLocation(P[a],b?F(v,b):""),Mc:(a,b)=>re(a,b,
4),Lc:(a,b,c)=>{c?w[c>>2]=S.getBufferParameter(a,b):R(1281)},Kc:()=>{var a=S.getError()||nd;nd=0;return a},Ic:(a,b)=>re(a,b,2),Hc:(a,b,c,d)=>{a=S.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;w[d>>2]=a},Gc:(a,b)=>re(a,b,0),Ec:(a,b,c,d)=>{a=S.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,v,d,b):0;c&&(w[c>>2]=b)},Fc:(a,b,c)=>{if(c)if(a>=cd)R(1281);else if(a=P[a],35716==b)a=S.getProgramInfoLog(a),null===a&&(a="(unknown error)"),
w[c>>2]=a.length+1;else if(35719==b){if(!a.bf)for(b=0;b<S.getProgramParameter(a,35718);++b)a.bf=Math.max(a.bf,S.getActiveUniform(a,b).name.length+1);w[c>>2]=a.bf}else if(35722==b){if(!a.$e)for(b=0;b<S.getProgramParameter(a,35721);++b)a.$e=Math.max(a.$e,S.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.$e}else if(35381==b){if(!a.af)for(b=0;b<S.getProgramParameter(a,35382);++b)a.af=Math.max(a.af,S.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.af}else w[c>>2]=S.getProgramParameter(a,b);else R(1281)},
ta:se,va:te,ra:se,ua:te,wa:(a,b,c)=>{c?w[c>>2]=S.He.getQueryEXT(a,b):R(1281)},Dc:(a,b,c)=>{c?w[c>>2]=S.getRenderbufferParameter(a,b):R(1281)},Bc:(a,b,c,d)=>{a=S.getShaderInfoLog(Q[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,v,d,b):0;c&&(w[c>>2]=b)},Ac:(a,b,c,d)=>{a=S.getShaderPrecisionFormat(a,b);w[c>>2]=a.rangeMin;w[c+4>>2]=a.rangeMax;w[d>>2]=a.precision},zc:(a,b,c,d)=>{if(a=S.getShaderSource(Q[a]))b=0<b&&d?E(a,v,d,b):0,c&&(w[c>>2]=b)},Cc:(a,b,c)=>{c?35716==b?(a=S.getShaderInfoLog(Q[a]),null===
a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=S.getShaderSource(Q[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=S.getShaderParameter(Q[a],b):R(1281)},xc:a=>{var b=ld[a];if(!b){switch(a){case 7939:b=wd(ud().join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=S.getParameter(a))||R(1280);b=b?wd(b):0;break;case 7938:b=wd(`OpenGL ES 2.0 (${S.getParameter(7938)})`);break;case 35724:b=S.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&
(c[1]+="0"),b=`OpenGL ES GLSL ES ${c[1]} (${b})`);b=wd(b);break;default:R(1280)}ld[a]=b}return b},wc:(a,b,c)=>{c?y[c>>2]=S.getTexParameter(a,b):R(1281)},vc:(a,b,c)=>{c?w[c>>2]=S.getTexParameter(a,b):R(1281)},sc:(a,b)=>{b=b?F(v,b):"";if(a=P[a]){ve(a);var c=a.We,d=0,e=b,f=ue(b);0<f&&(d=parseInt(b.slice(f+1))>>>0,e=b.slice(0,f));if((e=a.Pf[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||S.getUniformLocation(a,b)))return d}else R(1281);return-1},uc:(a,b,c)=>{we(a,b,c,2)},tc:(a,b,c)=>{we(a,b,c,0)},pc:(a,b,c)=>{c?w[c>>
2]=S.getVertexAttribOffset(a,b):R(1281)},rc:(a,b,c)=>{xe(a,b,c,2)},qc:(a,b,c)=>{xe(a,b,c,5)},oc:function(a,b){S.hint(a,b)},mc:a=>(a=dd[a])?S.isBuffer(a):0,lc:function(a){return S.isEnabled(a)},kc:a=>(a=ed[a])?S.isFramebuffer(a):0,jc:a=>(a=P[a])?S.isProgram(a):0,Aa:a=>(a=kd[a])?S.He.isQueryEXT(a):0,ic:a=>(a=fd[a])?S.isRenderbuffer(a):0,hc:a=>(a=Q[a])?S.isShader(a):0,gc:a=>(a=gd[a])?S.isTexture(a):0,na:a=>(a=hd[a])?S.isVertexArray(a):0,fc:function(a){S.lineWidth(a)},ec:a=>{a=P[a];S.linkProgram(a);a.We=
0;a.Pf={}},dc:(a,b)=>{3317==a&&(md=b);S.pixelStorei(a,b)},bc:function(a,b){S.polygonOffset(a,b)},xa:(a,b)=>{S.He.queryCounterEXT(kd[a],b)},ac:(a,b,c,d,e,f,g)=>{(g=ye(f,e,c,d,g))?S.readPixels(a,b,c,d,e,f,g):R(1280)},$b:()=>{},_b:function(a,b,c,d){S.renderbufferStorage(a,b,c,d)},Zb:(a,b)=>{S.sampleCoverage(a,!!b)},Yb:function(a,b,c,d){S.scissor(a,b,c,d)},Xb:()=>{R(1280)},Wb:(a,b,c,d)=>{for(var e="",f=0;f<b;++f){var g=d?w[d+4*f>>2]:-1,l=w[c+4*f>>2];g=l?F(v,l,0>g?void 0:g):"";e+=g}S.shaderSource(Q[a],
e)},Vb:function(a,b,c){S.stencilFunc(a,b,c)},Ub:function(a,b,c,d){S.stencilFuncSeparate(a,b,c,d)},Sb:function(a){S.stencilMask(a)},Rb:function(a,b){S.stencilMaskSeparate(a,b)},Qb:function(a,b,c){S.stencilOp(a,b,c)},Pb:function(a,b,c,d){S.stencilOpSeparate(a,b,c,d)},Ob:(a,b,c,d,e,f,g,l,n)=>{S.texImage2D(a,b,c,d,e,f,g,l,n?ye(l,g,d,e,n):null)},Nb:function(a,b,c){S.texParameterf(a,b,c)},Mb:(a,b,c)=>{S.texParameterf(a,b,y[c>>2])},Lb:function(a,b,c){S.texParameteri(a,b,c)},Kb:(a,b,c)=>{S.texParameteri(a,
b,w[c>>2])},Jb:(a,b,c,d,e,f,g,l,n)=>{var p=null;n&&(p=ye(l,g,e,f,n));S.texSubImage2D(a,b,c,d,e,f,g,l,p)},Hb:(a,b)=>{S.uniform1f(X(a),b)},Gb:(a,b,c)=>{if(288>=b)for(var d=ze[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);S.uniform1fv(X(a),d)},Fb:(a,b)=>{S.uniform1i(X(a),b)},Eb:(a,b,c)=>{if(288>=b)for(var d=Ae[b-1],e=0;e<b;++e)d[e]=w[c+4*e>>2];else d=w.subarray(c>>2,c+4*b>>2);S.uniform1iv(X(a),d)},Db:(a,b,c)=>{S.uniform2f(X(a),b,c)},Cb:(a,b,c)=>{if(144>=b)for(var d=ze[2*b-1],e=0;e<
2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>2,c+8*b>>2);S.uniform2fv(X(a),d)},Bb:(a,b,c)=>{S.uniform2i(X(a),b,c)},Ab:(a,b,c)=>{if(144>=b)for(var d=Ae[2*b-1],e=0;e<2*b;e+=2)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2];else d=w.subarray(c>>2,c+8*b>>2);S.uniform2iv(X(a),d)},zb:(a,b,c,d)=>{S.uniform3f(X(a),b,c,d)},yb:(a,b,c)=>{if(96>=b)for(var d=ze[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);S.uniform3fv(X(a),
d)},wb:(a,b,c,d)=>{S.uniform3i(X(a),b,c,d)},vb:(a,b,c)=>{if(96>=b)for(var d=Ae[3*b-1],e=0;e<3*b;e+=3)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2];else d=w.subarray(c>>2,c+12*b>>2);S.uniform3iv(X(a),d)},ub:(a,b,c,d,e)=>{S.uniform4f(X(a),b,c,d,e)},tb:(a,b,c)=>{if(72>=b){var d=ze[4*b-1],e=y;c>>=2;for(var f=0;f<4*b;f+=4){var g=c+f;d[f]=e[g];d[f+1]=e[g+1];d[f+2]=e[g+2];d[f+3]=e[g+3]}}else d=y.subarray(c>>2,c+16*b>>2);S.uniform4fv(X(a),d)},sb:(a,b,c,d,e)=>{S.uniform4i(X(a),b,c,d,e)},rb:(a,
b,c)=>{if(72>=b)for(var d=Ae[4*b-1],e=0;e<4*b;e+=4)d[e]=w[c+4*e>>2],d[e+1]=w[c+(4*e+4)>>2],d[e+2]=w[c+(4*e+8)>>2],d[e+3]=w[c+(4*e+12)>>2];else d=w.subarray(c>>2,c+16*b>>2);S.uniform4iv(X(a),d)},qb:(a,b,c,d)=>{if(72>=b)for(var e=ze[4*b-1],f=0;f<4*b;f+=4)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2];else e=y.subarray(d>>2,d+16*b>>2);S.uniformMatrix2fv(X(a),!!c,e)},pb:(a,b,c,d)=>{if(32>=b)for(var e=ze[9*b-1],f=0;f<9*b;f+=9)e[f]=y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>
2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2];else e=y.subarray(d>>2,d+36*b>>2);S.uniformMatrix3fv(X(a),!!c,e)},ob:(a,b,c,d)=>{if(18>=b){var e=ze[16*b-1],f=y;d>>=2;for(var g=0;g<16*b;g+=16){var l=d+g;e[g]=f[l];e[g+1]=f[l+1];e[g+2]=f[l+2];e[g+3]=f[l+3];e[g+4]=f[l+4];e[g+5]=f[l+5];e[g+6]=f[l+6];e[g+7]=f[l+7];e[g+8]=f[l+8];e[g+9]=f[l+9];e[g+10]=f[l+10];e[g+11]=f[l+11];e[g+12]=f[l+
12];e[g+13]=f[l+13];e[g+14]=f[l+14];e[g+15]=f[l+15]}}else e=y.subarray(d>>2,d+64*b>>2);S.uniformMatrix4fv(X(a),!!c,e)},nb:a=>{a=P[a];S.useProgram(a);S.Vf=a},lb:a=>{S.validateProgram(P[a])},kb:function(a,b){S.vertexAttrib1f(a,b)},jb:(a,b)=>{S.vertexAttrib1f(a,y[b>>2])},ib:function(a,b,c){S.vertexAttrib2f(a,b,c)},hb:(a,b)=>{S.vertexAttrib2f(a,y[b>>2],y[b+4>>2])},gb:function(a,b,c,d){S.vertexAttrib3f(a,b,c,d)},fb:(a,b)=>{S.vertexAttrib3f(a,y[b>>2],y[b+4>>2],y[b+8>>2])},eb:function(a,b,c,d,e){S.vertexAttrib4f(a,
b,c,d,e)},db:(a,b)=>{S.vertexAttrib4f(a,y[b>>2],y[b+4>>2],y[b+8>>2],y[b+12>>2])},ja:(a,b)=>{S.vertexAttribDivisor(a,b)},cb:(a,b,c,d,e,f)=>{S.vertexAttribPointer(a,b,c,!!d,e,f)},ab:function(a,b,c,d){S.viewport(a,b,c,d)},m:()=>1,Xa:(a,b,c)=>v.copyWithin(a,b,b+c),Ea:(a,b,c)=>Be(a,{sf:w[c>>2],jf:w[c+4>>2],cg:w[c+8>>2],Zf:b,Xe:w[c+12>>2],xf:w[c+16>>2]}),J:(a,b)=>{a=U(a);return a?a.requestPointerLock?Id()?me(a):b?(Gd(me,2,[a]),1):-2:-1:-4},Ra:()=>{m("OOM")},o:()=>(Qd=navigator.getGamepads?navigator.getGamepads():
navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1,p:(a,b,c)=>"undefined"==typeof onbeforeunload?-1:1!==c?-5:Ce(a,b),B:(a,b,c,d)=>De(a,b,c,d,12,"blur"),d:ge,i:(a,b,c)=>{a=U(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},C:(a,b,c,d)=>De(a,b,c,d,13,"focus"),s:(a,b,c,d)=>{if(!Od())return-1;a=U(a);if(!a)return-4;Ee(a,b,c,d,"webkitfullscreenchange");return Ee(a,b,c,d,"fullscreenchange")},f:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Fe(a,b,c,26,
"gamepadconnected"):-1,h:(a,b,c)=>navigator.getGamepads||navigator.webkitGetGamepads?Fe(a,b,c,27,"gamepaddisconnected"):-1,v:(a,b,c,d)=>Ge(a,b,c,d,2,"keydown"),t:(a,b,c,d)=>Ge(a,b,c,d,1,"keypress"),u:(a,b,c,d)=>Ge(a,b,c,d,3,"keyup"),Ja:(a,b,c)=>{Ac(()=>dynCall_v.call(null,a),b,c)},H:(a,b,c,d)=>Ie(a,b,c,d,5,"mousedown"),F:(a,b,c,d)=>Ie(a,b,c,d,33,"mouseenter"),E:(a,b,c,d)=>Ie(a,b,c,d,34,"mouseleave"),I:(a,b,c,d)=>Ie(a,b,c,d,8,"mousemove"),G:(a,b,c,d)=>Ie(a,b,c,d,6,"mouseup"),w:(a,b,c,d)=>{if(!document||
!document.body||!(document.body.requestPointerLock||document.body.ve||document.body.qg||document.body.qf))return-1;a=U(a);if(!a)return-4;Je(a,b,c,d,"mozpointerlockchange");Je(a,b,c,d,"webkitpointerlockchange");Je(a,b,c,d,"mspointerlockchange");return Je(a,b,c,d,"pointerlockchange")},r:(a,b,c,d)=>Ke(a,b,c,d),x:(a,b,c,d)=>Le(a,b,c,d,25,"touchcancel"),z:(a,b,c,d)=>Le(a,b,c,d,23,"touchend"),y:(a,b,c,d)=>Le(a,b,c,d,24,"touchmove"),A:(a,b,c,d)=>Le(a,b,c,d,22,"touchstart"),q:(a,b,c)=>Me(a,b,c),D:(a,b,c,
d)=>(a=U(a))?"undefined"!=typeof a.onwheel?Ne(a,b,c,d):-1:-4,Fa:a=>document.title=a?F(v,a):"",l:a=>ff(b=>Ec(b,a)),Va:(a,b)=>{var c=0;Qe().forEach((d,e)=>{var f=b+c;e=x[a+4*e>>2]=f;for(f=0;f<d.length;++f)q[e++>>0]=d.charCodeAt(f);q[e>>0]=0;c+=d.length+1});return 0},Wa:(a,b)=>{var c=Qe();x[a>>2]=c.length;var d=0;c.forEach(e=>d+=e.length+1);x[b>>2]=d;return 0},g:Dc,k:function(a){try{var b=Kb(a);Vb(b);return 0}catch(c){if("undefined"==typeof ec||"ErrnoError"!==c.name)throw c;return c.Ce}},L:function(a,
b,c,d){try{a:{var e=Kb(a);a=b;for(var f,g=b=0;g<c;g++){var l=x[a>>2],n=x[a+4>>2];a+=8;var p=e,t=l,r=n,u=f,B=q;if(0>r||0>u)throw new H(28);if(null===p.fd)throw new H(8);if(1===(p.flags&2097155))throw new H(8);if(J(p.node.mode))throw new H(31);if(!p.re.read)throw new H(28);var N="undefined"!=typeof u;if(!N)u=p.position;else if(!p.seekable)throw new H(70);var W=p.re.read(p,B,t,r,u);N||(p.position+=W);var fa=W;if(0>fa){var ub=-1;break a}b+=fa;if(fa<n)break;"undefined"!==typeof f&&(f+=fa)}ub=b}x[d>>2]=
ub;return 0}catch($a){if("undefined"==typeof ec||"ErrnoError"!==$a.name)throw $a;return $a.Ce}},Qa:function(a,b,c,d,e){b=c+2097152>>>0<4194305-!!b?(b>>>0)+4294967296*c:NaN;try{if(isNaN(b))return 61;var f=Kb(a);Wb(f,b,d);C=[f.position>>>0,(A=f.position,1<=+Math.abs(A)?0<A?+Math.floor(A/4294967296)>>>0:~~+Math.ceil((A-+(~~A>>>0))/4294967296)>>>0:0)];w[e>>2]=C[0];w[e+4>>2]=C[1];f.mf&&0===b&&0===d&&(f.mf=null);return 0}catch(g){if("undefined"==typeof ec||"ErrnoError"!==g.name)throw g;return g.Ce}},K:function(a,
b,c,d){try{a:{var e=Kb(a);a=b;for(var f,g=b=0;g<c;g++){var l=x[a>>2],n=x[a+4>>2];a+=8;var p=Xb(e,q,l,n,f);if(0>p){var t=-1;break a}b+=p;"undefined"!==typeof f&&(f+=p)}t=b}x[d>>2]=t;return 0}catch(r){if("undefined"==typeof ec||"ErrnoError"!==r.name)throw r;return r.Ce}}},Y=function(){function a(c){Y=c.exports;Y=Se();la=Y.wd;c=la.buffer;h.HEAP8=q=new Int8Array(c);h.HEAP16=oa=new Int16Array(c);h.HEAPU8=v=new Uint8Array(c);h.HEAPU16=pa=new Uint16Array(c);h.HEAP32=w=new Int32Array(c);h.HEAPU32=x=new Uint32Array(c);
h.HEAPF32=y=new Float32Array(c);h.HEAPF64=z=new Float64Array(c);ra.unshift(Y.xd);Aa("wasm-instantiate");return Y}var b={a:of};za("wasm-instantiate");if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return k(`Module.instantiateWasm callback failed with error: ${c}`),!1}Ha(b,function(c){a(c.instance)});return{}}(),D=a=>(D=Y.yd)(a),kf=a=>(kf=Y.zd)(a),pf=h._main=(a,b)=>(pf=h._main=Y.Ad)(a,b),nf=()=>(nf=Y.Bd)(),zd=()=>(zd=Y.Dd)(),Ad=a=>(Ad=Y.Ed)(a),de=a=>(de=Y.Fd)(a);
h.dynCall_ii=(a,b)=>(h.dynCall_ii=Y.Gd)(a,b);h.dynCall_iiiii=(a,b,c,d,e)=>(h.dynCall_iiiii=Y.Hd)(a,b,c,d,e);h.dynCall_iiiiii=(a,b,c,d,e,f)=>(h.dynCall_iiiiii=Y.Id)(a,b,c,d,e,f);var dynCall_vii=h.dynCall_vii=(a,b,c)=>(dynCall_vii=h.dynCall_vii=Y.Jd)(a,b,c);h.dynCall_viiiii=(a,b,c,d,e,f)=>(h.dynCall_viiiii=Y.Kd)(a,b,c,d,e,f);var dynCall_v=h.dynCall_v=a=>(dynCall_v=h.dynCall_v=Y.Ld)(a);h.dynCall_viii=(a,b,c,d)=>(h.dynCall_viii=Y.Md)(a,b,c,d);
var dynCall_vi=h.dynCall_vi=(a,b)=>(dynCall_vi=h.dynCall_vi=Y.Nd)(a,b);h.dynCall_viiii=(a,b,c,d,e)=>(h.dynCall_viiii=Y.Od)(a,b,c,d,e);var dynCall_iii=h.dynCall_iii=(a,b,c)=>(dynCall_iii=h.dynCall_iii=Y.Pd)(a,b,c),V=h.dynCall_iiii=(a,b,c,d)=>(V=h.dynCall_iiii=Y.Qd)(a,b,c,d);h.dynCall_jiji=(a,b,c,d,e)=>(h.dynCall_jiji=Y.Rd)(a,b,c,d,e);h.dynCall_ji=(a,b)=>(h.dynCall_ji=Y.Sd)(a,b);h.dynCall_iiiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_iiiiiiii=Y.Td)(a,b,c,d,e,f,g,l);
h.dynCall_iiiiiiiiii=(a,b,c,d,e,f,g,l,n,p)=>(h.dynCall_iiiiiiiiii=Y.Ud)(a,b,c,d,e,f,g,l,n,p);h.dynCall_iiiiiiiiiiiiiiff=(a,b,c,d,e,f,g,l,n,p,t,r,u,B,N,W)=>(h.dynCall_iiiiiiiiiiiiiiff=Y.Vd)(a,b,c,d,e,f,g,l,n,p,t,r,u,B,N,W);h.dynCall_iiiiiidiiff=(a,b,c,d,e,f,g,l,n,p,t)=>(h.dynCall_iiiiiidiiff=Y.Wd)(a,b,c,d,e,f,g,l,n,p,t);h.dynCall_iiiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_iiiiiiiii=Y.Xd)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiii=(a,b,c,d,e,f,g,l)=>(h.dynCall_viiiiiii=Y.Yd)(a,b,c,d,e,f,g,l);
h.dynCall_viiiiiiiiiii=(a,b,c,d,e,f,g,l,n,p,t,r)=>(h.dynCall_viiiiiiiiiii=Y.Zd)(a,b,c,d,e,f,g,l,n,p,t,r);h.dynCall_i=a=>(h.dynCall_i=Y._d)(a);h.dynCall_vffff=(a,b,c,d,e)=>(h.dynCall_vffff=Y.$d)(a,b,c,d,e);h.dynCall_vf=(a,b)=>(h.dynCall_vf=Y.ae)(a,b);h.dynCall_viiiiiiii=(a,b,c,d,e,f,g,l,n)=>(h.dynCall_viiiiiiii=Y.be)(a,b,c,d,e,f,g,l,n);h.dynCall_viiiiiiiii=(a,b,c,d,e,f,g,l,n,p)=>(h.dynCall_viiiiiiiii=Y.ce)(a,b,c,d,e,f,g,l,n,p);h.dynCall_vff=(a,b,c)=>(h.dynCall_vff=Y.de)(a,b,c);
h.dynCall_vfi=(a,b,c)=>(h.dynCall_vfi=Y.ee)(a,b,c);h.dynCall_viif=(a,b,c,d)=>(h.dynCall_viif=Y.fe)(a,b,c,d);h.dynCall_vif=(a,b,c)=>(h.dynCall_vif=Y.ge)(a,b,c);h.dynCall_viff=(a,b,c,d)=>(h.dynCall_viff=Y.he)(a,b,c,d);h.dynCall_vifff=(a,b,c,d,e)=>(h.dynCall_vifff=Y.ie)(a,b,c,d,e);h.dynCall_viffff=(a,b,c,d,e,f)=>(h.dynCall_viffff=Y.je)(a,b,c,d,e,f);h.dynCall_viiiiii=(a,b,c,d,e,f,g)=>(h.dynCall_viiiiii=Y.ke)(a,b,c,d,e,f,g);h.dynCall_iidiiii=(a,b,c,d,e,f,g)=>(h.dynCall_iidiiii=Y.le)(a,b,c,d,e,f,g);
var hf=a=>(hf=Y.me)(a),We=()=>(We=Y.ne)(),gf=a=>(gf=Y.oe)(a),jf=()=>(jf=Y.pe)();h.addRunDependency=za;h.removeRunDependency=Aa;h.FS_createPath=$b;h.FS_createLazyFile=dc;h.FS_createDevice=bc;h.FS_createPreloadedFile=rb;h.FS_createDataFile=qb;h.FS_unlink=Rb;var qf;ya=function rf(){qf||sf();qf||(ya=rf)};function tf(a=[]){var b=pf;a.unshift(ca);var c=a.length,d=de(4*(c+1)),e=d;a.forEach(g=>{x[e>>2]=ee(g);e+=4});x[e>>2]=0;try{var f=b(c,d);Dc(f,!0)}catch(g){Bc(g)}}
function sf(){var a=ba;function b(){if(!qf&&(qf=!0,h.calledRun=!0,!ma)){h.noFSInit||Zb||(Zb=!0,Yb(),h.stdin=h.stdin,h.stdout=h.stdout,h.stderr=h.stderr,h.stdin?bc("/dev","stdin",h.stdin):Qb("/dev/tty","/dev/stdin"),h.stdout?bc("/dev","stdout",null,h.stdout):Qb("/dev/tty","/dev/stdout"),h.stderr?bc("/dev","stderr",null,h.stderr):Qb("/dev/tty1","/dev/stderr"),Tb("/dev/stdin",0),Tb("/dev/stdout",1),Tb("/dev/stderr",1));zb=!1;Oa(ra);Oa(sa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();uf&&tf(a);
if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ua.unshift(c)}Oa(ua)}}if(!(0<wa)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)va();Oa(qa);0<wa||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var uf=!0;
h.noInitialRun&&(uf=!1);sf();
